### ISSUE TITLE
UI issue when window resolution is minimize

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#102]
Resolution size :- 90%
Steps follow : 
1. zoom in window
2. click on agent profile
3. click on left menu bar 

![screenshot 28](https://user-images.githubusercontent.com/43210406/50647516-c3753a80-0f9e-11e9-996c-229cc8b9f4af.png)

**Comment by shubhwebkul** [comment]
Resolved!
