### ISSUE TITLE
Search bar is hidden back to left menu bar

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#104]
**Resolution size : 100**
**Browser : Google Chrome , Mozilla**

![screenshot 8](https://user-images.githubusercontent.com/43210406/50683725-18658f00-1039-11e9-8208-22e8287320f0.png)

**Resolution size : 67**
**Browser : Google Chrome**

![screenshot 31](https://user-images.githubusercontent.com/43210406/50683911-c7a26600-1039-11e9-8cea-a1d8b1221cbb.png)

**Comment by vaishaliwebkul** [comment]
Not Fixed.. Facing same issue again, Please check

**Comment by kumarSaurabh27** [comment]
Resolved https://github.com/uvdesk/core-framework/pull/139

**Comment by vaishaliwebkul** [comment]
Now side bar menu is hidden for low resolution window.
https://prnt.sc/o6yyoy
