### ISSUE TITLE
All type of files will open to select while User profile image insert (support only PNG/JPG) format

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#105]
User profile (only accept png and jpg formate) when click to attach image then folder should be show only customizable images (i.e; png,jpg formate) not all files and images.

**click to attach image :**  
![screenshot 34](https://user-images.githubusercontent.com/43210406/50689023-0510ee80-104e-11e9-9297-f8454657cfe1.png)

Folder should be fetch which are supported by profile field (jpg and png)
![screenshot 36](https://user-images.githubusercontent.com/43210406/50689084-3b4e6e00-104e-11e9-95ec-07b2e4faf198.png)

**Comment by papnoisanjeev** [comment]
showing only desired format in folder can not be restricted from code end.
