### ISSUE TITLE
Issue during installation of project using composer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#125]
**Framework version -** 0.1.0 DEV

**Install project ->** composer create-project uvdesk/community-skeleton helpdesk-project --stability dev

**Find below attachment to see full description of error :** 
![screenshot](https://user-images.githubusercontent.com/43210406/51527011-a0310300-1e59-11e9-8425-bfa5bcfeeeff.png)

**Comment by shubhwebkul** [comment]
this issue was arrived because of some updation in Symfony dependencies. To resolve this issue we have added default .gitignore file in community-skeleton repository.
Now your could go ahead with the create-project command of UVDesk without getting any error.

**Comment by vaishaliwebkul** [comment]
Ok Thanks for solving this error..
