### ISSUE TITLE
Request Feature: Pre Installation extension description on web installer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#129]
**This feature needs to be added on web installer**

- All the necessary extension and packages (such as imap,mailparse,mysql) are needed to install project should be view in UI also.

 

- Extension that are enabled for configurable system and meet requirement should be marked and if not , then unmarked.

**Comment by shubhwebkul** [comment]
Hi vaishali,
As per your suggestion we have set a UI for showing the details of active and in-active extensions
