### ISSUE TITLE
Website prefix default value not set on command line

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#131]
If the website prefix are already set 
Run command **php bin/console uvdesk:configure-prefix**
Existing prefix value not show.

![screenshot](https://user-images.githubusercontent.com/43210406/51658087-e2c71c80-1fcc-11e9-805e-c061acb084de.png)

**Comment by shubhwebkul** [comment]
resolved

**Comment by vaishaliwebkul** [comment]
Failed to exe **php bin/console uvdesk:configure-prefix**

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul  No need for this command as we have given this option in web Installer and also if Someone want to change later can directly change it  from **UVdesk.yaml** File.
