### ISSUE TITLE
MAMP not working as 127.0.0.1 but works as localhost

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#135]
**Framework version :** 0.1.0 DEV

1. Project Installed Using Zip file
2. Hit URL on setup wizard to add Database configuration
 
 **Issue**
### Server 127.0.0.1 not recognized by Apache but works well with localhost
![screenshot 92](https://user-images.githubusercontent.com/43210406/51903363-fcf46680-23e1-11e9-836c-453898da4d75.png)

**Comment by princewebkul** [comment]
no issue found
