### ISSUE TITLE
If already setup uvdesk , it again redirect us to web installer when open /public directory

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#141]
**Framework Version: 0.1 Dev**

**Test Case:**
Test to check for Re-installation of UVdesk

**Bug:**
If uvdesk is already installed, it gets redirect us to **/setup** wizard instead of serving us to **/en** 

**Requirement:**
Customize the Reinstallation process by selecting checkbox whether admin wants the web installer option or not ?

**Comment by nicholasjonnes** [comment]
I noticed this same issue today which is a pretty big security issue. I installed UV Desk and then if I go to the public folder after the installation has been completed I am taken to the installer page to start again

**Comment by shubhwebkul** [comment]
Hi nicholasjonnes,
you could easily redirect your all requests from web installer to knowledgebase by adding a route as discussed in #153
