### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by eyedocs** [uvdesk/community-skeleton#143]
1: Evaluating System Requirements

The wizard will check whether your system meets the minimum requirements to successfully run the application.

    An unexpected error occurred during the PHP version verification process.
    Hide details
![image](https://user-images.githubusercontent.com/19936673/56304021-cab1f580-6102-11e9-9d7e-5ae62a73fb69.png)

**Comment by papnoisanjeev** [comment]
Hello  eyedocs,
Please check your **php version (7 or higher)** and other dependencies **(mailparse, imap)** which is required to run the project.
check screenshot:
https://user-images.githubusercontent.com/42460055/56337521-54c19300-61c3-11e9-8854-36505bd61479.png

**Comment by davetustin** [comment]
Hi,

We are having exactly the same issue. We have tried PHP 7.1, 7.2 and 7.3. The Imap and Mailparse modules were installed also.

Can someone confirm the list of PHP modules needed? We have installed the following:

 php-mysql php-xml php-xmlrpc php-soap php-gd php-imap php-mailparse

![errors](https://user-images.githubusercontent.com/46324811/56352352-02827100-61c7-11e9-8e05-ae261313c496.png)

Any help would be appreciated.

**Comment by davetustin** [comment]
After a bit more investigation, the problem was due to the httpd.conf.

For /var/www/html the Allow Override needed to be change to All.

![errors](https://user-images.githubusercontent.com/46324811/56355065-4b3d2880-61cd-11e9-84df-9132175882d9.png)

**Comment by eyedocs** [comment]
> 
> 
> Hello eyedocs,
> Please check your **php version which must be (7 or higher)** and other dependencies **(mailparse, imap)** which is required to run the project.
> check screenshot:
> https://user-images.githubusercontent.com/42460055/56337521-54c19300-61c3-11e9-8854-36505bd61479.png

PHP version is 7.2 and downloaded uvdesk for version 7.2 issue remains.

**Comment by eyedocs** [comment]
> 
> 
> After a bit more investigation, the problem was due to the httpd.conf.
> 
> For /var/www/html the Allow Override needed to be change to All.
> 
> ![errors](https://user-images.githubusercontent.com/46324811/56355065-4b3d2880-61cd-11e9-84df-9132175882d9.png)

@davetustin worked great!! Thank you!!

**Comment by bhavingolakiya008** [comment]
@davetustin Hey your code is not working can you please put all the code at once, we edited apache.conf file but then the apache stops working, did you edit any other file also?

**Comment by mailanetworks** [comment]
Hi, same thing here, not working:
 php -v
PHP 7.2.18-1+0~20190503103213.21+stretch~1.gbp101320 (cli) (built: May  3 2019 10:32:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.18-1+0~20190503103213.21+stretch~1.gbp101320, Copyright (c) 1999-2018, by Zend Technologies

php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
json
libxml
mailparse
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by nopsg** [comment]
same issue here.
An unexpected error occurred during the PHP version verification process.

but I was trying to install on nginx, does uvdesk support nginx?

**Comment by vaishaliwebkul** [comment]
**Hello nopsg,**

        An unexpected error occurred during the PHP version verification process
 
If the Allow Override is set to all in apache.conf then also check PHP version inside info.php, should be the same as shown in the CLI mode and don't forget to restart webserver, else could provide us the var/log/dev.log file at step the issue occurred.

       but I was trying to install on nginx, does uvdesk support nginx?

Yes, you can setup uvdesk on Nginx by using composer or zip file

**Comment by DmytroLavryk** [comment]
Hello!

> **Hello nopsg,**
> 
> ```
>     An unexpected error occurred during the PHP version verification process
> ```
> 
> If the Allow Override is set to all in apache.conf then also check PHP version inside info.php, should be the same as shown in the CLI mode and don't forget to restart webserver, else could provide us the var/log/dev.log file at step the issue occurred.
> 
> ```
>    but I was trying to install on nginx, does uvdesk support nginx?
> ```
> 
> Yes, you can setup uvdesk on Nginx by using composer or zip file

can you give an example of nginx config?
I get an error during installation "Unable to locate the path on the server. "
In dev.log:
[2019-12-25 14:08:43] request.INFO: Matched route "base_route". {"route":"base_route","route_parameters":{"_route":"base_route","_controller":"App\\Controller\\BaseController::base"},"request_uri":"https://mysite_url/helpdesk/public/index.php/","method":"GET"} []
[2019-12-25 14:08:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
