### ISSUE TITLE
Permission denied error while Configuration 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#145]
**Apache unable to access .env file** 
Also swiftmailer.yaml, uvdesk_mailbox.yaml, uvdesk.yaml file permission denied

![Screenshot from 2019-04-25 11-00-39](https://user-images.githubusercontent.com/43210406/56711670-64a02080-6749-11e9-90e8-7469f79555c8.png)

**Comment by shubhwebkul** [comment]
Hi Vaishali,
UVDesk needs permission to access some files to save details entered by you.
You need to allow permission to the required files.
for details how you can allow permission to the files refer: -
**https://stackoverflow.com/questions/4917811/file-put-contents-permission-denied**

**Comment by vaishaliwebkul** [comment]
Error shows in console which is sometimes unable to catch,
so request you to show all permission error on the prod mode, so we can easily allow permission.

![Screenshot6](https://user-images.githubusercontent.com/43210406/56959419-f3a6a180-6b6a-11e9-9d80-56bb024e524c.png)

**Comment by kumarSaurabh27** [comment]
resolved https://github.com/uvdesk/community-skeleton/pull/158
