### ISSUE TITLE
Transport needed for smtp server

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#148]
### Add Transport for SMTP sever

![Screenshot5](https://user-images.githubusercontent.com/43210406/56881921-97b31e80-6a7f-11e9-8b5f-c6b4369884f4.png)

**Comment by supportreq** [comment]
is this working? Unable to connect via smtp

**Comment by vaishaliwebkul** [comment]
Hello supportreq,
        Yes, this is working with SMTP, please update and install the latest project.

![Screenshot61](https://user-images.githubusercontent.com/43210406/58700677-5f746800-83be-11e9-861c-9c4dcd797c9d.png)
