### ISSUE TITLE
Cannot save article

### ISSUE THREAD

**Issue by kzsfluxus** [uvdesk/community-skeleton#149]
I.ve downloaded uvdesk php 7.2 version. When i create a new article there is no possibility to choose related categories. And at save, there is an error message: "This field is mandatory". The mandatory Title, Content and Slug fields are not empty.

**Comment by vaishaliwebkul** [comment]
Hi kzsfluxus,

 You will get a related category option, once the article is saved.
 Also there is slug ,title and content field are mandatory to save article.
 When you will save an article it will redirect you automatically to **add for related category.**


Please refer below link for more detail:
https://support.uvdesk.com/en/blog/uvdesk-how-to-add-an-article-inside-a-category

**Comment by kzsfluxus** [comment]
It will be nice, but i cannot save article. At save I've got  "This field is mandatory" message.There are texts in the slug, title and content fields.

**Comment by UVvidu** [comment]
Dear kzsfluxus,
Can you please share the screenshot of the issue you are getting at support@uvdesk.com and if you use Skype then please add me using the ID - lipi.singh412@webkul.com so that I can provide you live assistance and can resolve your concern in no time.

**Comment by kzsfluxus** [comment]
I've changed the default character set to utf-8 and at this moment everything works fine. My other problem: we are a hungarian library, and we use special hungarian characters : éáőóüö, but uvdesk has a validation in category names, so i cannot use these chars. Is there eny solution?

**Comment by akshaywebkul** [comment]
Hello kzsfluxus, there aren't any solutions yet but thanks for pointing out this bug. We'll work on a fix for this issue and we'll update you as soon as it's resolved.

**Comment by kzsfluxus** [comment]
After we creat 4 article this bug came back again. Here's two screenshots.

![knowledgebase_article_2](https://user-images.githubusercontent.com/1884858/56953084-179ebe80-6b3c-11e9-9b5a-c441a29a4841.jpg)
![knowledgebase_article_1](https://user-images.githubusercontent.com/1884858/56953086-179ebe80-6b3c-11e9-9bf1-4387849909d1.jpg)

**Comment by UVvidu** [comment]
Hello kzsfluxus, thanks for notifying us back with the screenshot, we will work to fix this bug and will reply you back as soon once it resolved.

**Comment by kzsfluxus** [comment]
Dear UVVidu, will this bug solve in the near future?

Thanks

**Comment by vaishaliwebkul** [comment]
Hello @kzsfluxus

The issue has been resolved, installed the latest package by executing composer command.
let us know if Hungarian words are accepted or not.

**Comment by kzsfluxus** [comment]
after composer update:

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.code AS code_3, t0.logo AS logo_4, t0.theme_color AS theme_color_5, t0.favicon AS favicon_6, t0.created_at AS created_at_7, t0.updated_at AS updated_at_8, t0.is_active AS is_active_9, t0.timezone AS timezone_10, t0.timeformat AS timeformat_11 FROM uv_website t0 WHERE t0.code = ? LIMIT 1' with params ["knowledgebase"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.timezone' in 'field list'").

**Comment by vaishaliwebkul** [comment]
Hi @kzsfluxus 
 
   The reason behind this error is that the database is not updated with current code changes.
so try to run the following command to update your database.
   **php bin/console uvdesk:configure-helpdesk**

**Comment by kzsfluxus** [comment]
thanks, now it works perfectly
