### ISSUE TITLE
All the ticket's detail can be view by agent(even that ticket not assigned to related agent)

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#15]
**The ticket detail of admin**
![screenshot](https://user-images.githubusercontent.com/43210406/49378531-d7751480-f732-11e8-9e2e-e86a3d9510a9.png)

**Test Case:** login to agent panel
**Bug:**
The agent can also view all the ticket of admin which is not right ,only agent have privileges to access the ticket which was assigned to that agent,not all.

**Comment by papnoisanjeev** [comment]
fixed. Agent will see only assigned ticket to them.
