### ISSUE TITLE
ERROR: There are extensions that haven't been installed or are currently disabled 

### ISSUE THREAD

**Issue by faraimupfuti** [uvdesk/community-skeleton#151]
I am trying to install uvdesk community edition (php 7.2) on xampp server V3.2.3 on Windows 7 Operating system. I created the database on localhost phpmyadmin.

I then activated the **_extension=imap_** on php.ini and also downloaded the **_php_mailparse.dll_** extension and placed it on the **_C:/XAMPP/php/ext folder_** . I also added the **_extension=mailparse_** line on php.ini and restarted the webserver.

when i run the uvdesk installation link **_(localhost/uvdesk/public)_**, the below error pops up:

    

> **There are extensions that haven't been installed or are currently disabled**

How do i solve the problem ??

**_NB: I tried to change the AllowOverride values from "none" to "All" , in the httpd.conf file and still it wont install even after restart._**

**Comment by vaishaliwebkul** [comment]
Hello faraimupfuti, 
 This warning comes when the extensions are not correctly enabled, to double check this, dump of phpinfo() to make sure that IMAP and MAILPARSE are correctly align with your PHP build. 
 Here are some official instruction for php extension https://php.net/manual/en/install.pecl.windows.php#install.pecl.windows.which

you can check your php.ini again and make sure extension=php_mailparse.dll is located below extension=php_mbstring.dll
If still facing common error please share log file.

**Comment by rakesh10933** [comment]
Hello faraimupfuti 

You are going good but have a to do small step while edit php.ini. Just add extension=mailparse after extension=mbstring.
i.e
extension=mbstring
extension=mailparse.

Then save the php.ini and restart your server. your problem will solved.

> I am trying to install uvdesk community edition (php 7.2) on xampp server V3.2.3 on Windows 7 Operating system. I created the database on localhost phpmyadmin.
> 
> I then activated the **_extension=imap_** on php.ini and also downloaded the **_php_mailparse.dll_** extension and placed it on the **_C:/XAMPP/php/ext folder_** . I also added the **_extension=mailparse_** line on php.ini and restarted the webserver.
> 
> when i run the uvdesk installation link **_(localhost/uvdesk/public)_**, the below error pops up:
> 
> > **There are extensions that haven't been installed or are currently disabled**
> 
> How do i solve the problem ??
> 
> **_NB: I tried to change the AllowOverride values from "none" to "All" , in the httpd.conf file and still it wont install even after restart._**


Hello faraimupfuti 

You are going good but have a to do small step while edit php.ini. Just add extension=mailparse after extension=mbstring.
i.e
extension=mbstring
extension=mailparse.

Then save the php.ini and restart your server. your problem will solved.

**Comment by rakesh10933** [comment]
Now Install Composer in my system. And Finally my login issue has been resolved.

**Comment by vaishaliwebkul** [comment]
Hello faraimupfuti,

 Its looks like that your issue has been fixed.
