### ISSUE TITLE
Multiple error message

### ISSUE THREAD

**Issue by avneesh-webkul** [uvdesk/community-skeleton#154]
While performing installation, if the values are incorrect, then it is showing multiple message bar.
http://i.prntscr.com/FOac4UHMSSakZ_AoRjAjUQ.png

Removal of the notification bar depends on only the change of database value, not on others.

**Comment by kumarSaurabh27** [comment]
Resolved  https://github.com/uvdesk/community-skeleton/pull/158

**Comment by vaishaliwebkul** [comment]
Disable warning notification once ready to proceeds again.

**Comment by piyushwebkul** [comment]
Resolved [#180](https://github.com/uvdesk/community-skeleton/pull/180)

**Comment by vaishaliwebkul** [comment]
This issue has been fixed in 0.1, also need to be updated in 1.0
