### ISSUE TITLE
UVdesk Admin Panel Login issue.

### ISSUE THREAD

**Issue by rakesh10933** [uvdesk/community-skeleton#156]
Hello Everyone..

I am getting an error while try to login on UVdesk dmin Pannel.

![image](https://user-images.githubusercontent.com/50945309/58240217-2f96e600-7d68-11e9-9c9c-5444d96f02d8.png)

what is the reason for this

**Comment by akshaywebkul** [comment]
Hello rakesh,
Could you provide us with the composer.json file located within your project root?

**Comment by rakesh10933** [comment]
> Hello Everyone..
> 
> I am getting an error while try to login on UVdesk dmin Pannel.
> 
> ![image](https://user-images.githubusercontent.com/50945309/58240217-2f96e600-7d68-11e9-9c9c-5444d96f02d8.png)
> 
> what is the reason for this

After installation of Composer.exe , my issue has been resolved.
