### ISSUE TITLE
No Route found exception

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#157]
**When visiting customer forget passowrd page  and click to support center to get home page**

![Screenshot62](https://user-images.githubusercontent.com/43210406/58807363-8e484380-8635-11e9-8fb7-f963fd577f0a.png)

### Notify Issue
![Screenshot63](https://user-images.githubusercontent.com/43210406/58807453-b9cb2e00-8635-11e9-929d-a0b391097b5d.png)

**Comment by kumarSaurabh27** [comment]
Resolved. https://github.com/uvdesk/support-center-bundle/pull/51

**Comment by kumarSaurabh27** [comment]
Resolved https://github.com/uvdesk/support-center-bundle/pull/51
