### ISSUE TITLE
Link is not clickable for missing extension

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#159]
**Steps to Reproduce Bug**

Hit working project directory to Url to get setup wizard

1- Click on SETUP UVDESK button
2- move to PROCEED button and click
3- Go back to 1st step, then click on **Show Detail** link to view extensions

**Bug:** 

Show Detail link not get clickable

![Screenshot67](https://user-images.githubusercontent.com/43210406/59015094-ca5ced80-885b-11e9-9fdc-09dcca1445b8.png)

**Comment by kumarSaurabh27** [comment]
Resolved  https://github.com/uvdesk/community-skeleton/pull/158
