### ISSUE TITLE
User get put in CC/BCC mail not added to the ticket reply

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#16]
add user in cc/bcc :
![screenshot 1](https://user-images.githubusercontent.com/43210406/49423406-6fb7db80-f7bd-11e8-8b6d-5948efebbbe2.png)

When submit this reply then user added in cc/bcc not get added.
![download 13](https://user-images.githubusercontent.com/43210406/49423590-02f11100-f7be-11e8-91fb-eadc0f422906.png)

**Comment by papnoisanjeev** [comment]
fixed
