### ISSUE TITLE
Error : Mailbox-refresh command not execute on CentOS 7

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#160]
**Environment Setup**
Php version : **7.0**
OS: **CentOS 7**
Server: **Apache** 

**Imap** and **Mailparse** extension has been successfully enabled and reflected on **info.php** 
###  Issue
Running command from project directory root folder -

**php bin/console uvdesk:refresh mailbox** **demo@example.com**

Error thrown : 
![Screenshot68](https://user-images.githubusercontent.com/43210406/59041722-d2864e80-8896-11e9-8902-a6be47a3dbd3.png)

**Comment by shubhwebkul** [comment]
Hi Vaishali,

Maybe your IMAP extension is not enabled in CLI mode.
You could check your enabled extensions either by running command php -ini or by System Requirements step in web installer of uvdesk (must be in development mode)

Web installer checks all the extensions depending upon how you are running helpdesk-project.
in development mode, it'll check enabled extensions for CLI mode and in production mode, it'll check enabled extensions for the server.

**Comment by vaishaliwebkul** [comment]
Yes, Imap need to be enabled in CLI mode, finally, this issue has been resolved.
