### ISSUE TITLE
Community Edition Installation Issue

### ISSUE THREAD

**Issue by alexanderoitx** [uvdesk/community-skeleton#161]
Hi, 

Been trying to install the community edition on my xampp server but keep getting stuck at step 2/5 (migrating the database). I have tried everything with no solution. Any help would be appreciated. Thanks

<img width="952" alt="Internal server error 500" src="https://user-images.githubusercontent.com/28023890/59136059-7c96d100-8992-11e9-9ca7-9e7eac1399c8.PNG">

**Comment by alexanderoitx** [comment]
<img width="960" alt="Internal server error 500" src="https://user-images.githubusercontent.com/28023890/59136765-a43b6880-8995-11e9-80e1-939b1c587d19.PNG">
Hope this can help shed more light. Thanks again.

**Comment by shubhwebkul** [comment]
Hi alexanderoitx,
Could you please check your _.env_ file.
If the database details you have provided to the web installer are not saved in that file, means this issue is just because of permission.
for reference, you could follow #145

**Comment by alexanderoitx** [comment]
Thanks for the response @shubhwebkul. Can you please guide how to update this file? I followed the reference but it specifies nothing on this. 

I opened up the .env and I see this below:

# In all environments, the following files are loaded if they exist,
# the later taking precedence over the former:
#
#  * .env                contains default values for the environment variables needed by the app
#  * .env.local          uncommitted file with local overrides
#  * .env.$APP_ENV       committed environment-specific defaults
#  * .env.$APP_ENV.local uncommitted environment-specific overrides
#
# Real environment variables win over .env files.
#
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE NOR IN ANY OTHER COMMITTED FILES.
#
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=3c462c42bb5c27a04449ac389bcc0c6b
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS='^localhost|example\.com$'
###< symfony/framework-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data.db"
# Configure your db driver and server_version in config/packages/doctrine.yaml
DATABASE_URL=mysql://helpdesk:password@127.0.0.1/helpdesk
###< doctrine/doctrine-bundle ###

**Comment by alexanderoitx** [comment]
Below is what I found in the .env
------------------------------------
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        options:
            1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

**Comment by shubhwebkul** [comment]
It shows, your database credentials have been saved successfully in _.env_ file.
You are stuck at step 2, that is the migration of the database. It is possible that the migration step is taking longer than 30seconds and the maximum execution time in your settings is 30seconds.

So all you need to do is, increase your maximum execution time.
For that you could take help from [here](https://stackoverflow.com/questions/16171132/how-to-increase-maximum-execution-time-in-php)

**Comment by alexanderoitx** [comment]
You're amazing mate! Finally worked. Thanks @shubhwebkul
