### ISSUE TITLE
Mailbox refresh issue

### ISSUE THREAD

**Issue by rakesh10933** [uvdesk/community-skeleton#162]
![image](https://user-images.githubusercontent.com/50945309/59481923-12939580-8e84-11e9-98fb-76e9b8021b17.png)

I was trying to refresh my UVdesk mailbox gmail emai ld  but it took so much time. And also if try to configure UVdesk mailbox with company email id then getting an error also.

**Comment by shubhwebkul** [comment]
Hi rakesh10933,

- As we have also configured UVDesk mailbox with Gmail but it takes standard time, it'll take time according to the count of emails you're fetching. UVDesk will sure take time if you have a large number of emails.

- Could you please mention what error you're getting while refreshing your mailbox when you're using your company's email id.

**Comment by rakesh10933** [comment]
Brother. i was trying with another email id too. The issue is remain same. I didn't get sent mail as a ticket.

**Comment by rakesh10933** [comment]
Hello support team. Mailbox refresh issue has been resolved finally. thanks for your support and guidance.
