### ISSUE TITLE
Swift mailer and Email settings configuration for outlook not working

### ISSUE THREAD

**Issue by alexanderoitx** [uvdesk/community-skeleton#163]
Hi all,

I am trying to configure the open source version of UV desk to send, receive and also convert mails from office365 to tickets. I feel I got the configuration right but it doesn't seem to accomplish any of the above.

Below are configuration files. Please advise if I entered the correct values. I would any help or insight.

**for swiftmailer.yaml**
swiftmailer:
    mailers:
        Office365:
            transport: smtp
            username: lms@amx.ac.mu
            password: *************
            host: smtp.office365.com
            port: 587
            encryption: tls
            auth_mode: plain
            # sender_address: ~
            # delivery_addresses: ~
            disable_delivery: false

**for uvdesk_mailbox.yaml**
uvdesk_mailbox:
    emails: ~
        # Often Reply emails like from gmail contains extra and redundant previous mail data.
        # This data can be removed by adding delimiter i.e. specific line before each reply. 
        # delimiter: '<-- Please add content above this line -->'
        # enable_delimiter: true
    
    # Configure your mailboxes here
    mailboxes:
        Office365:
            name: IT and AV Support
            enabled: true

            # [SMTP] Outgoing mail server
            # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
            smtp_server: 
                mailer_id: Office365

            # [IMAP] Incoming mail server
            # IMAP configurations to use for fetching emails from mailbox
            imap_server:
                host: '{outlook.office365.com:993/imap/ssl}INBOX'
                username: lms@amx.ac.mu
                password: *****************

**for uvdesk.yaml**
parameters:
    app_locales: en|fr|it
    
    # Default Assets
    assets_default_agent_profile_image_path: 'bundles/uvdeskcore/images/uv-avatar-batman.png'
    assets_default_customer_profile_image_path: 'bundles/uvdeskcore/images/uv-avatar-ironman.png'
    assets_default_helpdesk_profile_image_path: 'bundles/uvdeskcore/images/uv-avatar-uvdesk.png'

    uvdesk_site_path.member_prefix: member
    uvdesk_site_path.knowledgebase_customer_prefix: customer

uvdesk:
    site_url: 'localhost/helpdesk-project/public'
    upload_manager:
        id: Webkul\UVDesk\CoreBundle\FileSystem\UploadManagers\Localhost
    
    support_email:
        id: lms@amx.ac.mu
        name: IT Support
        mailer_id: Office365
    
    # Default resources
    default:
        ticket:
            type: support
            status: open
            priority: low
        templates:
            email: mail.html.twig

**Comment by vaishaliwebkul** [comment]
Hello alexanderoitx,

 You are going great while setup configuration.

**Did you enable the imap access from office365?**
https://prnt.sc/o27b1m

If not, please enable imap access so that our application have access to fetch your emails and try again.

if yes, you could share the error which you are getting while executing refresh-mailbox command.

**Comment by alexanderoitx** [comment]
Hi @vaishaliwebkul, 

Thanks for the response. I'll try this out.

With regards to the refresh mailbox command, I did not get any errors when I ran it. 

Quick question: Does enabling the imao access allow me receive mails when I tickets have been created or responses sent? This also is a problem at the moment

**Comment by vaishaliwebkul** [comment]
Hi alexanderoitx,

  With regards to the refresh mailbox command, I did not get any errors when I ran it.

- **An issue might be with IMAP access is not enabled if an error does not occur and command executed.**


Regarding your question about working of IMAP access:- 

 - **Enabling the IMAP access will allow you to only fetch your emails and convert them into tickets on your support panel. In this scenario, When ticket will be fetched on the support panel, you will receive mail and your customer will also receive a mail by whom the ticket has been created.**

- **When Response sent from the ticket then only your customer will receive an email alert which you can also manage by setting up workflow App in the dashboard.**

This also is a problem at the moment. I am receiving any mail alerts when I for example - create tickets.

**If still having doubt, Please share some snaps from where you create a ticket??**

**Comment by alexanderoitx** [comment]
Hi @vaishaliwebkul,

It still doesn't work after I looked into enabling IMAP. I still can't fetch mails and I do not receive mails when actions are carried out either (i.e. no mail alert when a ticket is created or when an update on the ticket is made). The process of configuration is quite skewed I must say. 

It is also hard to debug as I am not getting any errors. Can I get a straight breakdown on what to do? Or is there some special requirement for outlook servers? As I see your examples only highlight using gmail.

**Comment by shubhwebkul** [comment]
Hi alexanderoitx,
As it's not throwing any exception so it's hard to find the issue for us as well. You need to debug things step by step.

When you run command of refresh-mailbox, it executes code resides in **vendor->uvdesk->mailbox-component->Console->RefreshMailboxCommand.php**

Firstly with the help of function named **refreshMailbox**, all the emails are fetched from details you've provided.

try to print the value of **$emailCollection** that contains the email collection and check if the emails are even fetched or not. PFA

![DumpEmailCollection](https://user-images.githubusercontent.com/41280839/59661956-92459b00-91c9-11e9-89d4-b897cb8666ee.png)

I assume that you'll find your issue here but if not, try to debug on next function called **pushMessage** that is for converting the email into a ticket.

**Comment by alexanderoitx** [comment]
Hi @shubhwebkul, could this be a problem? Please see below:

Fatal error: Class 'Symfony\Component\Console\Command\Command' not found in C:\xampp\htdocs\helpdesk-project\vendor\uvdesk\mailbox-component\Console\RefreshMailboxCommand.php on line 14

**Comment by shubhwebkul** [comment]
Please update your dependencies. This may happen because of your dependencies.

Regarding the conversion issue of emails into tickets, could you please share some details.
try printing the value as defined in the attachment.
![MailIssue](https://user-images.githubusercontent.com/41280839/59677841-84534280-91e8-11e9-9217-004c9460e6e7.png)



FilePath:- vendor->uvdesk->mailbox-component->Services->MailboxService.php-> function processMail

then please share dumped values

**Comment by alexanderoitx** [comment]
Hi @shubhwebkul ,

I decided to try out a gmail account just to see if the poroblem stemmed from my trying to connect to via outlook. This time I got an error. Any ideas would be helpful. Thanks

<img width="659" alt="Capture" src="https://user-images.githubusercontent.com/28023890/59708485-e8d8c680-9215-11e9-8938-04b82f8c1f5c.PNG">

**Comment by vaishaliwebkul** [comment]
Hi @alexanderoitx 

You will be getting this error in case of 3 scenarios, Please check for all

1. please take a look at the Google Help page: https://support.google.com/mail/answer/7126229?hl=en

If you haven't completed step 1 please do so and try again.

2. The error clearly mention invalid authentication, you could check Gmail username and password should be correctly set in a configuration file

3. Imap Incoming server **'{imap.gmail.com:993/imap/ssl}INBOX'** inside uvdesk_mailbox.yaml

**Comment by alexanderoitx** [comment]
Hi @vaishaliwebkul,

Thanks for the message. You were right, my imap was not enabled. This still didn't solve the problem upon enabling it though. I still get the same error as above.

I have also looked into my set credentials and they are okay. When I ran the mailbox refresh command yesterday before enabling imap, I did get a security message fro google stating a Sign-in attempt was blocked and I then went on to authorize it. Even though this didn't solve the issue either, I guess it was proof that my credentials are okay.

Regarding the incoming server details, I have been there over and over, it is exactly  '{imap.gmail.com:993/imap/ssl}INBOX' ... I can't imagine what the issue is anymore :(

**Comment by vaishaliwebkul** [comment]
Hello @alexanderoitx 

Sorry, we could not give you the exact solution at this point as if your configuration is going good, and still mails are not fetching, then might be the issue with Gmail account or encryption port = TLS, as we also check Gmail configuration at our end, it's working fine.

Now you could do so:
Install the latest project and set your Gmail configuration with another test Gmail id and try the last attempt.

if still same,  Raise your support query at support@uvdesk.com

**Comment by vaishaliwebkul** [comment]
Update to **auth_mode=login** in swiftmailer.yaml will help to done configuration with outlook.
