### ISSUE TITLE
Feature to set default timezone

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#164]
### There must be an option available to set own company timezone e.g, currently, no such feature available on support panel.

**Feature** 
Timezone [IST,AST,EDT,GST,GMT]
DateTime Format 

**Hint:**
 It would be better if add this option in the branding section.

**Comment by alexanderoitx** [comment]
Where can this be done internally in the code? Any idea? Cos I was trying to figure it out earlier too

**Comment by kumarSaurabh27** [comment]
Fixed. https://github.com/uvdesk/core-framework/pull/156

**Comment by kumarSaurabh27** [comment]
Hi @alexanderoitx , 
We have added this feature, after merge you need to reinstall the project to get this feature.

**Comment by kumarSaurabh27** [comment]
Fixed. https://github.com/uvdesk/support-center-bundle/pull/52
https://github.com/uvdesk/core-framework/pull/156

**Comment by temiotu** [comment]
After changing the timezone in the branding section, the change in the date/time is not reflected on any tickets (new or old).

**Comment by blckhwk** [comment]
Hi,

I have encountered this issue.

![image](https://user-images.githubusercontent.com/7903090/172110499-5fb6f525-33e1-443f-ad05-18b65e87c149.png)


![uvdesk](https://user-images.githubusercontent.com/7903090/172110541-5a61347f-d438-4674-a53e-2d73cc50230a.png)
![uvdesk1](https://user-images.githubusercontent.com/7903090/172110547-ddd2b98e-55c8-4e71-8ded-da64a12f4b62.png)

**Comment by Komal-sharma-2712** [comment]
@temiotu, @blckhwk 

- If you are changing the **Time zone and Date Time format** option from branding so this will be changed on the admin and customer side. Till the customer or admin did not set the profile changes.

- If the admin or customer changes the **profile** option so time zone and time format option is saved and works only with the profile **Date Time format and Timezone** option. After the profile is saved will not work branding time format or time zone option.

Go to the profile:

![image](https://user-images.githubusercontent.com/63539748/172170559-601fd7fa-f16d-463f-b97e-52ab19737b3a.png)

and change here for the same DateTime and Timezone of your locale area:

![image](https://user-images.githubusercontent.com/63539748/172170643-4e30200b-7353-4245-a786-dc9b7b7e2ea7.png)

Now check ticket view date time and time zone.

If you still have the same issue, let us know.
