### ISSUE TITLE
can't set password for agent

### ISSUE THREAD

**Issue by tzak902** [uvdesk/community-skeleton#168]
Hello,
How to set or generate password for agents I created?

Also how to set password for folders or assign privilege

**Comment by vaishaliwebkul** [comment]
@tzak902,

Please do the following steps to set your agent password.

1. Setup **Swiftmailer** and then **Email Settings**, which enable all outgoing mail from the support system.
2. Then create Agent, who will receive mail to set a password.

 **How to set a password for folders or assign privilege??**

There is no way to set a password for folders, the admin may assign the privileges to agent for creating Knowledgebase to agents.

Here is the below steps to assign privilege
1. Navigate through Dashboard--> Users --> Privilege --> Click to new privilege
2. Make a privilege as you want 
3. Go to Agent then edit agent and assign privilege from permission.
