### ISSUE TITLE
Forgot password will reset the old password immediately

### ISSUE THREAD

**Issue by tzak902** [uvdesk/community-skeleton#169]
Hi,
I'm running uvdesk helpdesk in my localhost with laragon, I tried to reset password for an agent and I didn't receive any email via mail catcher built in with laragon which act as a mail receiver for anything that is Mail based. 
Now I tried for superadmin and reset it and it was resetted to a new password even I didn't receive any email or activate any email.

Expected bahvior: Old password should remain unless I click on a link to change it

**Comment by vaishaliwebkul** [comment]
Hi @tzak902,

Mail catcher will not work until configuration files are not set up inside project which is uvdesk_mailbox.yaml, uvdesk.yaml, swiftmailer.yaml.

sending mail[SMTP] -> setup Swiftmailer then email settings
receiving mail[IMAP]-> setup mailbox configuration with Swiftmailer id 

please go through this guide for mail configuration: 
https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/


Super admin Password can't get changed until email settings and swiftmailer are not setup.
