### ISSUE TITLE
ticket view issue 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#170]
**Composer latest project Install**
Panel: Agent panel
View: Ticket view

![Screenshot84](https://user-images.githubusercontent.com/43210406/59964662-0d3be800-9521-11e9-95f2-60b6902ec6c5.png)

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/core-framework/pull/149

**Comment by vaishaliwebkul** [comment]
Resolved...
