### ISSUE TITLE
Welcome ticket must be there on ticket panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#171]
### Super admin login to support panel then there must be default ticket stored on the ticket panel...

![Screenshot89](https://user-images.githubusercontent.com/43210406/60011304-236bb480-9697-11e9-8148-5db8f236fe4d.png)

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/core-framework/pull/155

**Comment by papnoisanjeev** [comment]
Added a welcome ticket on ticket panel.

**Comment by vaishaliwebkul** [comment]
Initial Ticket is there on the panel, but in the ticket content super admin name is placed with some static value **"community-dev Admin"**

**Comment by papnoisanjeev** [comment]
We have disabled this features currently due to some dependency issue. We will add this feature in upcoming releases.
