### ISSUE TITLE
Ticket type description data fetch in drop down list instead code

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#172]
Ticket type description content showing in ticket type drop-down menu, at all place where exist.
**there should be shown ticket type code**

Update ticket type for all mention below
1. ticket type exist inside ticket detail
2. select ticket will show ticket type option in the header bar
3.  admin create ticket by clicking on + sign,in that form ticket type list also exist

![wkrepo4](https://user-images.githubusercontent.com/43210406/60098048-5767d800-9772-11e9-9e24-18f5939525ef.png)

**Comment by papnoisanjeev** [comment]
fixed.

**Comment by vaishaliwebkul** [comment]
Ticket type assign will change into ticket type description once page reload.

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/core-framework/pull/163
