### ISSUE TITLE
Language Spanish

### ISSUE THREAD

**Issue by georgeemr** [uvdesk/community-skeleton#173]
Is there a way i can have this app in spanish?

**Comment by papnoisanjeev** [comment]
No, currently there is no such option for choosing the language.
but for sure we will implement this feature in next release.

**Comment by papnoisanjeev** [comment]
@georgeemr 

We have added translation for Spanish.
Now you can use this app in Spanish.

Check here:  https://github.com/uvdesk/community-skeleton/issues/247#issuecomment-583220293

We have already add translation file for **spanish(es)**. So you don't need for add new one.
