### ISSUE TITLE
Stuck at step 4/5 while configuration

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#175]
**mysql server: 127.0.0.1**
**Port: 3306**
**Username: admin**
**password: admin**
**Database name: uv_community#**

### Installation stuck at 4/5 step , show error on console

![test](https://user-images.githubusercontent.com/43210406/60485051-44489100-9cb9-11e9-9213-c106833b7cd8.png)

**Comment by papnoisanjeev** [comment]
Database name in **.env** contains # that is not recognized by PHP's parse_url() function as valid.
so remove # from the database url and try.

**Comment by vaishaliwebkul** [comment]
Hello @papnoisanjeev 

 **That's great!! It will work for me** but one should fix it this issue because in general, too many users use # in their database configuration for security reason

It will be nice if DB name and password can be parse

**Comment by papnoisanjeev** [comment]
Hello @vaishaliwebkul 
If u don't want to change your password which contains #.

Encode your password first with this url: https://www.urlencoder.io
Replace your current password with encoded password in **.env** file.
Then open your project directory, go to **config ->packages->doctrine.yaml**

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'

url: '%env(resolve:DATABASE_URL)%'
Remove resolve and make url like as it is below.
url: '%env(DATABASE_URL)%'

Follow these steps and make a try.
