### ISSUE TITLE
An error occured while loading the web debug tool bar

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#190]
Framework version 1.0

**Error while loading the web profiler toolbar in dev and prod environment**

![screenshot1](https://user-images.githubusercontent.com/43210406/62112324-24b08280-b2d0-11e9-95c0-3abac849e03c.png)

**Comment by rNianios** [comment]
Hi, 

I am having the same issue as well. Do you have a workaround?

**Comment by akshaywebkul** [comment]
Hello rNianios, there appears to be some issue with the dependency tree, so presently there are no workarounds. We are currently working on an update to fix this issue and we'll notify you when a fix is available.
