### ISSUE TITLE
.htaccess mod_rewrite "No input file specified."

### ISSUE THREAD

**Issue by VahanPWNS** [uvdesk/community-skeleton#192]
Hello all. I have just installed on my Windows desktop and discovered a minor bug in the .htaccess file. When I browse to the URL for my local server, I get nothing but "No input file specified." however, if I browse to /input.php it correctly redirects to /index.php/en/ and displays the home page.

broken:

![htaccess-bug-1](https://user-images.githubusercontent.com/4217895/62550180-b8022e80-b861-11e9-88ac-0d5d26b3ee1e.PNG)
![htaccess-bug-2](https://user-images.githubusercontent.com/4217895/62550204-bfc1d300-b861-11e9-94f4-d44aa473e294.PNG)

fixed:

![htaccess-bug-fixed](https://user-images.githubusercontent.com/4217895/62550207-c2bcc380-b861-11e9-9a27-2c9aec9b80fc.PNG)

.htaccess file looks like this:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ ./index.php/$1 [QSA,L]
</IfModule>
```

But there is a `?` missing after index.php, it should be like this:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ ./index.php?/$1 [QSA,L]
</IfModule>
```

**Comment by VahanPWNS** [comment]
I have reinstalled Apache, PHP and MySQL - newer versions, 64bit rather than 32bit - and a fresh install of uvdesk doesn't have this issue any more (without the change to .htaccess) so I have to assume this was a problem with my server configuration.

**Comment by lastsamurai26** [comment]
i have the same problem. 

what exactly have you done.

I reinstalled the whole server.
Apache 2.4 (self compiled and also via apt)
php 7.3 (compiled as fcgi)
mariaDB
i use debian
