### ISSUE TITLE
Unable to run via Composer:

### ISSUE THREAD

**Issue by alexsdesign** [uvdesk/community-skeleton#193]

**Comment by alexsdesign** [comment]
When I try to run this in composer via Plesk, I receive the following errors:

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/lib64/plesk-9.0/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
Loading composer repositories with package information
Updating dependencies
PHP Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/lib64/plesk-9.0/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

**Comment by vaishaliwebkul** [comment]
Hello @alexsdesign

 Try to resolve this issue by increasing memory_size = -1 or look into the same issue #167
