### ISSUE TITLE
support guide or documents link on web installer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#195]
### In web installer, Instructions guides link are really needed at each step for better support.

some of the links should be shown at the header 
1. Need Help?
2. forum
3. Installation Guide
4. Developer Guide

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Many update and links added on web installer already.
Also some more checks with progress bar and other updates has been added in master for web installer.
will be available from next release of project.
