### ISSUE TITLE
resetting password for super user update credentials link redirection to home page

### ISSUE THREAD

**Issue by smallBiz** [uvdesk/community-skeleton#196]
I have an issue logging in to a new test UVdesk installation on my local server
firstly the password I copied into my note is not working 
so I worked through the configuration steps to configure swiftmailer and managed to set the system to send the password reset email
when I click on the link it just redirects to the home page, without any error message etc

copy of link sent in  email 
`You recently requested to reset your password for your Landlord Assist account. Click the link to reset it http://192.168.0.42:8001/en/landlord/update-credentials/Ian@sbws.co.uk/pl64MbFUFyeUJWEJxUU19tZJYegBdGPa`

thanks in advance for any assistance 

Ian

**Comment by vaishaliwebkul** [comment]
Hello smallBiz,
 
    
On which Homepage the link was redirected you, please share the attachment and explain more about this issue as I've also done with the same and update super admin credentials successfully.

1. Click on forget password link on member panel
2. received link on my email http://127.0.0.1:8001/en/member/update-credentials/bansalvaish@gmail.com/gJTlMpYfRH9Pkluug74Jo6kVSboOrkCr 
2. open request URL received in an email in the new browser and try to reset password again.

**Comment by smallBiz** [comment]
vaishaliwebkul that is the exact process I carried out 
but the update-credentails path / route goes to what is essentially the home page http://192.168.0.42:8001/en/  which has thetitle HelpDesk Knowledgebase

in detail 
complete the lost password email form http://192.168.0.42:8001/en/landlord/forgot-password
recieve this email 

Hi Laadmin, 

You recently requested to reset your password for your Landlord Assist account. Click the link to reset it http://192.168.0.42:8001/en/landlord/update-credentials/Ian@sbws.co.uk/pl64MbFUFyeUJWEJxUU19tZJYegBdGPa


If you did not request a password reset, please ignore this mail or revert back to let us know.


Thanks and Regards

Landlord Assist

*********
click on the link 
which is routed / redirected to  http://192.168.0.42:8001/en/

this screencast of what happens might help, oyu to see what is going off  [https://youtu.be/nXNmr0HkP2A](url)

**Comment by vaishaliwebkul** [comment]
**Hello smallBiz,**

  You are trying to reset password for customer, this is the panel from where registered customer can reset their password only, but in your case you enter the super admin email id in the customer panel which identifies as a customer and sends mail to super admin, and when super admin trying to update password by link then link redirects you to **knowledgebase** means there is no customer register with this mail id.

If you want to reset the password for super admin, go to the super admin panel first by setting the URL
**http://192.168.0.42:8001/en/member/login** or prefix set for member panel while you have setup your project https://prnt.sc/p50f9b, also if you forgot prefix then check file **uvdesk.yaml** file under your project's **config->packages directory and you will get your member_prefix and knowledgebase_customer_prefix.

Try to forget a password again...
