### ISSUE TITLE
Redis server went away when installing

### ISSUE THREAD

**Issue by KlaasT** [uvdesk/community-skeleton#201]
I tried to setup the community skeleton either by using composer or by downloading the .zip from the website.

When I enter the mysql database credentials and click on "proceed" nothing happens. The symfony profiler tells me "Error 500 - Redis server went away".

**Comment by piyushwebkul** [comment]
I tried with both methods, but did not find any errors. Could tell me more about your system's php environment:

- PHP version
- php extension list
- log files in var/log directory (dev.log or prod.log)

**Comment by KlaasT** [comment]
I got it running by disabling the redis extension in PHP itself. With enabled redis extension (my control panel does that) I'm getting the following inside the log:

> [2019-09-17 06:39:22] request.CRITICAL: Uncaught PHP Exception RedisException: "Redis server went away" at /var/www/vhosts/xxx/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php line 47 {"exception":"[object] (RedisException(code: 0): Redis server went away at /var/www/vhosts/xxx/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:47)"} []

Seems like there is some kind of unwanted dependency?

**Comment by vaishaliwebkul** [comment]
Hello @KlaasT  

     an exception could also occur if Redis is running in backend and use by another service.     

Currently, Redis is not used in this package anywhere as dependency!
