### ISSUE TITLE
No show Page Navigation

### ISSUE THREAD

**Issue by sbonzanni** [uvdesk/community-skeleton#206]
Hi All,

I have the problem in the ticket page. I dont show page navigation.

Many Thanks!

**Comment by vaishaliwebkul** [comment]
Hi sbonzanni,
    
  Ticket page navigation will hit whenever you click on the tabs available at the left side menu bar, in which ticket list show on the basis of ticket status(open, pending, answered, resolved, closed).

![ticket_nav](https://user-images.githubusercontent.com/43210406/65368456-d9c34380-dc5e-11e9-8aaa-f6ee9de26287.png)
