### ISSUE TITLE
User's session out will redirect to 404 error page

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#209]
Framework Version 1.0

**Description**  
Error page show on user's session out

**How to reproduce**  
Login to agent/customer
After clearing, cookies found that error page shows instead of redirect to the login page.

**Possible Solution**  
User should redirect on login page

**Comment by akshaywebkul** [comment]
We need to take into account the different response type as well (html, xml, json). We should create a separate issue for this.
