### ISSUE TITLE
email not receive by clients

### ISSUE THREAD

**Issue by uyo-obong** [uvdesk/community-skeleton#214]
I'm using uvdesk helpdesk symfony open source, when a user click on forget password he/she will not receive forget password email : I follow this articles [https://www.uvdesk.com/en/blog/smtp-imap-open-source-helpdesk-uvdesk/](url) . after everything I get this error `Warning: imap_open(): Couldn't open stream {imap.gmail.com:993/debug/imap/ssl}INBOX` when I try to refresh it...I have open port 993 on the server and still not working.

I'm using gmail for smtp and imap, which I follow the articles to configure it.

**Comment by vaishaliwebkul** [comment]
Hi uyo-obong, 
 
 Try with valid IMAP server: {imap.gmail.com:993/imap/ssl}INBOX

**Comment by vaishaliwebkul** [comment]
Hi @uyo-obong,
  We're extremely waiting for your response, please get back to us if still occurring the same issue.
