### ISSUE TITLE
mysql connection gets failed when deploy with docker

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#227]
**Description**  

I'm trying to deploy helpdesk code with docker but mysqladmin: connect to a server at 'localhost' failed

**How to reproduce**  

1. Install project via
-composer create-project uvdesk/community-skeleton helpdesk-project

2. Follow steps as mention in README.md file

-create image-> $ docker build -t uvdesk-docker .
-deploy using container

If you wish to use a local database within container
$ docker run -dit -p 8003:80 \
    -e MYSQL_USER=uvdesk \
    -e MYSQL_ROOT_PASSWORD=uvdesk \
    -e MYSQL_PASSWORD=uvdesk123 \
    -e MYSQL_DATABASE=uvdesk-demo \
    --name uvdesk uvdesk-docker

3. docker logs

![Screenshot from 2019-11-08 17-22-00](https://user-images.githubusercontent.com/43210406/68474790-6bf1cc00-024c-11ea-8454-d387a286a670.png)

**Comment by piyushwebkul** [comment]
try
```
$ docker run -dit -p 8003：80 
-e MYSQL_USER = uvdesk 
-e MYSQL_ROOT_PASSWORD = uvdesk 
-e MYSQL_PASSWORD = uvdesk123 
-e MYSQL_DATABASE = uvdesk-demo
--host net
--name uvdesk uvdesk-docker
```
