### ISSUE TITLE
Uvdesk container returning Internal Server Error page

### ISSUE THREAD

**Issue by TatendaKwaramba** [uvdesk/community-skeleton#229]
I have followed all the steps required to dockerize uvdesk. However when I ran localhost:MY_PORT_NUM I am getting a page saying:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

Please help

![Screenshot from 2019-11-15 07-39-40](https://user-images.githubusercontent.com/33118227/68919965-7cd69c00-077c-11ea-8418-a979c05ece1b.png)

**Comment by TatendaKwaramba** [comment]
Here is the log file for the uvdesk container 

[logfile.txt](https://github.com/uvdesk/community-skeleton/files/3850096/logfile.txt)

![Screenshot from 2019-11-15 08-38-06](https://user-images.githubusercontent.com/33118227/68922052-536d3e80-0783-11ea-9919-83851ccb7974.png)

**Comment by piyushwebkul** [comment]
Try the following:

- Attach to your docker container using the command below
`docker attach {container_name}`
- Browse to uvdesk diretory 
`cd /var/www/uvdesk`
- Run
`composer install`

**Comment by TatendaKwaramba** [comment]
Thanks, Piyush Goel  it worked, configuring my app now
