### ISSUE TITLE
Unable to run my newly created project and get authentication error

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#23]
**Case 1 :** Install a new project 
**Case 2 :** Run a project on a localhost:8000/setup/

**Exception occur :** 
![screenshot 2](https://user-images.githubusercontent.com/43210406/49632545-17324980-fa1c-11e8-9507-dcfb63faf097.png)

**Resolve this bug by update following file :** 
![screenshot](https://user-images.githubusercontent.com/43210406/49632839-282f8a80-fa1d-11e8-9d6b-7a4e91d67f81.png)

**Comment by akshaywebkul** [comment]
Issue resolved with latest commits to uvdesk/core-framework [[39516b8](https://github.com/uvdesk/core-framework/commit/39516b8f48a734673a86a60f7eacff3dfdb65cd5)] and uvdesk/composer-package-manager [[2a1bf89](https://github.com/uvdesk/composer-package-manager/commit/2a1bf89f9bae36b4bcf438f8df45c727ff9dbeb5), [efeaff4](https://github.com/uvdesk/composer-package-manager/commit/efeaff4d16a64c9df89c7b0a75eca44ca0d2281d)].
