### ISSUE TITLE
Doctrine\ORM\Query\QueryException at multiple classes

### ISSUE THREAD

**Issue by unclego** [uvdesk/community-skeleton#232]
**Description**  
All menus in USERS section not working (Groups, Teams, Agents, Customers, privileges) not working.

**How to reproduce**  

Fresh manual install on Centos 7. php 7.3.12 from 
https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip

Unzip archive into nginx webroot.
Add this lines to webserver config
```
    location / {
	    try_files $uri /public$uri @index;
	}
	location @index {
	    rewrite ^/(.*)$ /index.php?url=$1 last;
	}

    location ~ \.php$ {
		try_files $uri /public$uri =404;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}

```
Naviagte to public folder and configure uvdesc.

Try any menu in in USERS section

**Additional context**  
Erros in log.

request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] ...... 

Error: Class Webkul\UVDesk\CoreFrameworkBundle\Entity\SupportPrivilege has no field or association named url

Error: Class Webkul\UVDesk\CoreFrameworkBundle\Entity\User has no field or association named url

Error: Class Webkul\UVDesk\CoreFrameworkBundle\Entity\SupportGroup has no field or association named url

Error: Class Webkul\UVDesk\CoreFrameworkBundle\Entity\SupportTeam has no field or association named url

etc. etc.

**Comment by vaishaliwebkul** [comment]
Hello unclego,
  Could you please elaborate more steps to reproduce this issue?

**Comment by unclego** [comment]
Well one more thing wich cna probalu help. It's nginx webserver. I have some troubles before i was able to start uvdesk. I cant find exmaple config for ngin in documentation, so i finished with this configuration


`	location / {
	    try_files $uri /public$uri @index;
	}
	location @index {
	    rewrite ^/(.*)$ /index.php?url=$1 last;
	}

    location ~ \.php$ {
		#try_files $uri =404;
		try_files $uri /public$uri =404;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}
`

**Comment by refueledinc** [comment]
I'm having a similar issue, but with Apache.

Page returns `500 error` for XHR.

```
request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Syntax Error] line 0, col 208: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got '/'" at /uvdesk/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 54 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Syntax Error] line 0, col 208: Error: Expected Doctrine\\ORM\\Query\\Lexer::T_IDENTIFIER, got '/' at /uvdesk/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:54, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT COUNT (DISTINCT user.id) FROM UVDeskCoreFrameworkBundle:User user LEFT JOIN user.userInstance userInstance LEFT JOIN userInstance.supportRole supportRole WHERE supportRole.id != :customerRole AND user./en/member/agents/xhr = :/en/member/agents/xhr ORDER BY userInstance.createdAt DESC at /uvdesk/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43)"} []
```

Any ideas as to a fix?

**Comment by papnoisanjeev** [comment]
@refueledinc
Please elaborate more steps to reproduce this issue.

You can also create a support ticket  https://support.uvdesk.com/en/customer/create-ticket/ here for better communication.

**Comment by refueledinc** [comment]
There's not much else I can provide you.

I simple installed the open source version, went to the dashboard and click on any of the links under the `users` sections and I get a loading icon with an XHR error of 500

**Comment by papnoisanjeev** [comment]
@refueledinc

Show your config files and provide us the log  **var->log->dev.log** and **var->log->prod.log** files.

**Comment by papnoisanjeev** [comment]
@unclego  
try this in your config remove url after index.php
    **location @index {
	    rewrite ^/(.*)$ /index.php?$1 last; 
    }**

try using this.

**Comment by imadmoqaddem** [comment]
Hi,
I probably have the same problem as @refueledinc .
After a fresh install today on Debian 10, PHP 7.3.11, Apache2.4.38, via composer, I have several Doctrine errors on users' menus :

```
Doctrine\ORM\Query\QueryException
SELECT COUNT (DISTINCT user.id) FROM UVDeskCoreFrameworkBundle:User user LEFT JOIN user.userInstance userInstance LEFT JOIN userInstance.supportRole supportRole WHERE supportRole.id != :customerRole AND **user./en/member/agents/xhr** = :/en/member/agents/xhr ORDER BY userInstance.createdAt DESC
```

Please find the dev.log file attached.

Thank you for your help

**Comment by unclego** [comment]
@papnoisanjeev 

Now i got a different error

` request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Syntax Error] line 0, col 218: Error: Expected Literal, got 'member'" at .../vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 54 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Syntax Error] line 0, col 218: Error: Expected Literal, got 'member' at .../vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:54, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT COUNT (DISTINCT user.id) FROM UVDeskCoreFrameworkBundle:User user LEFT JOIN user.userInstance userInstance LEFT JOIN userInstance.supportRole supportRole WHERE supportRole.id != :customerRole AND user.public/en/member/agents/xhr = :public/en/member/agents/xhr ORDER BY userInstance.createdAt DESC at .../vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43)"} []
`

**Comment by akshaywebkul** [comment]
The most likely culprit is faulty nginx configuration, that is the request url parameters aren't being resolved correctly.

@unclego , our team is now able to reproduce this new error you're getting so we'll try debug this issue and get back to you shortly.

**Comment by papnoisanjeev** [comment]
@imadmoqaddem  @unclego  @refueledinc @vaishaliwebkul 
Please update your **.htaccess file**.

Open your project, go to **public->.htaccess**
Open **.htaccess** and remove  **?** after **index.php**.

![htaccessNew](https://user-images.githubusercontent.com/42460055/73589296-6aa60780-44fa-11ea-83ab-b13c52afbf27.png)


And finally clear your project cache by:
**php bin/console c:c**

**Comment by unclego** [comment]
@papnoisanjeev 

> Please update your .htaccess file.
> 
> Open your project, go to public->.htaccess
> Open .htaccess and remove ? after index.php.

This doesn't work on nginx if i replace
`rewrite ^/(.*)$ /index.php?$1 last;`
with
`rewrite ^/(.*)$ /index.php$1 last;`
i got this error
` 6376#6376: *29 rewrite or internal redirection cycle while redirect to named location "@index"`

**Comment by papnoisanjeev** [comment]
@unclego 
This fix is basically for **Apache**  we have not tested it for **nginx** but for sure we will test it for nginx too and will let you know.

**Comment by unclego** [comment]
I fixed this using [symfony nginx minimum configuration](https://symfony.com/doc/current/setup/web_server_configuration.html#nginx)

IMHO nginx part of documentation need some work.
