### ISSUE TITLE
Forwarded Email not converted

### ISSUE THREAD

**Issue by Jeebeevee** [uvdesk/community-skeleton#233]
As first, English isn't my first language, so sorry for my bad English.

I'm testing with te use of UVdesk. we make use of outlook (office365) for the mail.
The messages ar send to a distribution group, from there (also) to the mailbox that uvdesk is reading.
When I send a mail direct to the box it is read and converted to a ticket.
When the mail is dropped in the mailbox by the distribution group it is seen by uvdesk, but not converted to a ticket. The output of the command gives no error output.

I think the problem exist in the "strange" way the mailheaders are built with a distribution group.

**Comment by vaishaliwebkul** [comment]
@Jeebeevee 
    we haven't test with the distribution group in office365, because of the limitation of mail server, but we can look into this if you could provide us the complete details of your mail server by raising a ticket to support@uvdesk.com.

**Comment by Jeebeevee** [comment]
I think it hase somethingto do with how the mailheaders ar build. It schould only be for the testing period, after that the mail we be direct in the mailbox, and that is working. 
See this isseu more as a reminder to look in it when time.

**Comment by PeopleInside** [comment]
This issue looks to be old. The issue still persist?

**Comment by papnoisanjeev** [comment]
@Jeebeevee 

This issue is already fixed.
If you are still facing the same you can reply on same thread.
