### ISSUE TITLE
uvdesk won't send mail

### ISSUE THREAD

**Issue by Jeebeevee** [uvdesk/community-skeleton#234]
As first, English isn't my first language, so sorry for my bad English.

**Description**
uvdesk don't send mail, to new agents, agents password reset, reactions on tickets.
as far I know the settings are correct.

config/packages/swiftmailer.yaml
``
swiftmailer:
    default_mailer: ticket@domain.nl
    mailers:
        ticket@domain.nl:
            transport: smtp
            username: ticket@domain.nl
            password: *********
            host: smtp.office365.com
            port: 587
            encryption: tls
            auth_mode: plain
            sender_address: ticket@domain.nl
            delivery_addresses: ['ticket@domain.nl']
            disable_delivery: false
``

config/packages/uvdesk_mailbox.yaml
``
uvdesk_mailbox:
    emails: ~
        # Often Reply emails like from gmail contains extra and redundant previous mail data.
        # This data can be removed by adding delimiter i.e. specific line before each reply.
        # delimiter: '<-- Please add content above this line -->'
        # enable_delimiter: true

    # Configure your mailboxes here
    mailboxes:
        ticket@domain.nl:
            name: ticket@domain.nl
            enabled: true

            # [SMTP] Outgoing mail server
            # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
            smtp_server:
                mailer_id: ticket@domain.nl

            # [IMAP] Incoming mail server
            # IMAP configurations to use for fetching emails from mailbox
            imap_server:
                host: '{outlook.office365.com:993/imap/ssl}INBOX'
                username: ticket@domain.nl
                password: ************
``

config/packages/uvdesk.yaml
``
parameters:
    app_locales: en|fr|it

    # Default Assets
    assets_default_agent_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png'
    assets_default_customer_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png'
    assets_default_helpdesk_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png'

    uvdesk_site_path.member_prefix: member
    uvdesk_site_path.knowledgebase_customer_prefix: customer

    # File uploads constraints
    # @TODO: Set these parameters via compilers
    max_post_size: 8388608
    max_file_uploads: 20
    upload_max_filesize: 2097152

uvdesk:
    site_url: 'ticket.mgmt.domain.nl/uvdesk/public'
    upload_manager:
        id: Webkul\UVDesk\CoreFrameworkBundle\FileSystem\UploadManagers\Localhost

    support_email:
        id: ticket@domain.nl
        name: ICT Helpdesk
        mailer_id: ticket@domain.nl

    # Default resources
    default:
        ticket:
            type: support
            status: open
            priority: low
        templates:
            email: mail.html.twig
``

I don't get errors on screen or in the server log files.

**Comment by vaishaliwebkul** [comment]
Hi @Jeebeevee 

 update  **auth_mode: login**  in config/packages/swiftmailer.yaml
and clear cache **php bin/console c:c**

Now try again to get mails notification.

**Comment by Jeebeevee** [comment]
hmm strange had done that before. On that moment it didn't work. On this moment it works.
thx.
