### ISSUE TITLE
{%global.companyLogo%} not shown inside email

### ISSUE THREAD

**Issue by laurentiu2** [uvdesk/community-skeleton#236]
**Description**  
When agent replies to a ticket, the email sent to customer should display {%global.companyLogo%} as email template is written (Agent Reply To The Customer's ticket)

**How to reproduce**  
upload a png under Branding general settings
reply as agent to a ticket

No error is shown but the email does not display the logo.

**Comment by vaishaliwebkul** [comment]
Hi @laurentiu2 
   This is not the issue, you have to set the permission from the mail account(Gmail, thunderbird, yahoo, outlook or any.) to allow and view the external images and contents inside an email body.
Otherwise, the logo will be shown as a broken image.

**Comment by laurentiu2** [comment]
Thanks. I should have known this :)

**Comment by Nishtha3512** [comment]
@vaishaliwebkul I changed the permission from mail aacount but still getting the broken image. What is the reason?

**Comment by vaishaliwebkul** [comment]
@Nishtha3512 
which email service you are using?

**Comment by Nishtha3512** [comment]
@vaishaliwebkul  Gmail

**Comment by smartysms** [comment]
same issue logo image is not visible in mail.

**Comment by blckhwk** [comment]
I have the same issue on gmail
![image](https://user-images.githubusercontent.com/7903090/149093022-1998ec01-176e-4e3f-8426-15b79be844c7.png)

![image](https://user-images.githubusercontent.com/7903090/149093122-a27f9b19-2a69-42a6-bfd2-213f56bd8194.png)

**Comment by PeopleInside** [comment]
@blckhwk this issue is old (2020).
I use UVdesk latest version 1.0.18 without this issue so be sure to use an updated version and check also maybe your email template in UVdesk. Be sure to use a supported PHP version.
