### ISSUE TITLE
Unhelpful error on installation

### ISSUE THREAD

**Issue by tmertz** [uvdesk/community-skeleton#237]
The below error happens when I try to use the web installer. How do I fix this?

![Screenshot 2019-12-28 at 17 01 56](https://user-images.githubusercontent.com/53013/71546124-e361f300-2993-11ea-8c94-a56160ee5eaa.png)

**Comment by vaishaliwebkul** [comment]
Hello @tmertz 

Webserver unable to override some Apache settings via a . htaccess file.
so update httpd.conf file and set **Allow override** to be **All** in the /var/www/htdocs.
