### ISSUE TITLE
Showing older version in web-installer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#238]
**Description**  
1.0.6 stable version should also be updated over web installer

**How to reproduce**  
Installing fresh uvdesk/community-skeleton v1.0.6 using composer

check the version is still older over the template of web installer

![Screenshot](https://user-images.githubusercontent.com/43210406/71825854-bc599e80-30c2-11ea-9935-594138e4f84d.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
Updated this to latest version(i.e 1.0.7)
