### ISSUE TITLE
ticket created - no email sent

### ISSUE THREAD

**Issue by laurentiu2** [uvdesk/community-skeleton#240]
When a new ticket is created, the email is not sent. All other actions are performed (assign to agent, assign to group, assign type, etc.)
All other emails (like new customer created, agent reply to customer, customer reply to agent) are sent, so the imap and smtp are ok.

I registered yesterday a new issue on github, but was deleted.

Any idea what to do?

**Comment by papnoisanjeev** [comment]
@laurentiu2
The issue that you were created part of a core-framework, so we have transferred that issue
here, https://github.com/uvdesk/core-framework/issues/277
