### ISSUE TITLE
Database migration gets failed if automatically created db in production environment

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#242]
**Description**  
migration failed at the 5th step if while the auto-create database

**Test Environment**

Version: 1.0.7

**How to reproduce**  

step1: download zip for version 1.0.7 
step2: update the environment to production
step3: follow all the step to install the web installer, by selecting auto-create database

**Description and Images**  

![Screenshot](https://user-images.githubusercontent.com/43210406/73587936-00846700-44e8-11ea-8556-5c1a01482b68.png)

**Error Log**
[prod.log](https://github.com/uvdesk/community-skeleton/files/4142208/prod.log)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Please setup your project in **development environment**  as there are some commands running in background  only in  **development** mode.
