### ISSUE TITLE
UVDesk Community - Web Installer hanged on last step

### ISSUE THREAD

**Issue by chazkame** [uvdesk/community-skeleton#245]
**Description**  

I'm trying to install UVDesk Community version in localhost, using Windows machine with Laragon. Currently I'm stuck at the last step of installation, 

> Installation
Please wait while your helpdesk is being installed. This could take up to a few minutes.

This has been running for an hour and not finished yet.
I don't know where the problem is. When I check in phpmyadmin, the database is empty, no tables at all

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by papnoisanjeev** [comment]
@chazkame 

Check below steps and make changes accordingly.

1. Web server might don't have permission to allow overriding of the Apache config on a per-directory basis. Allow Override needs to be set to All for the directory block as mention below:

    <Directory /home/users/var/www/htdocs>
    Options Indexes FollowSymLinks
    **AllowOverride All**
      Require all granted

2. If you database password contain some **spacial character(such as #$%@)** then change your password and make it without spacial character.

3. locate **.env file** in your project and make sure APP_ENV=dev when you are doing your setup.

Restart your server.
And clear your project cache by:
**php bin/console c:c**

Now try to install your project.

If you still face any problem create a support ticket
https://support.uvdesk.com/en/customer/create-ticket/ here or mail us at support@uvdesk.com.

**Comment by papnoisanjeev** [comment]
@chazkame 
Is your issue resolved?

**Comment by IT-njoy** [comment]
@papnoisanjeev 

I am experiencing the same thing as chezkame and have followed all your steps.

I am a not that experienced but i believe the problem is related to the error i always get in the symfony profiler when i click 'begin installation' on step 5/5
![error](https://user-images.githubusercontent.com/60931378/74660735-042a1600-5197-11ea-9ddf-54b954189e04.png)

googling about is has not really gained me anything since i do not know what i am looking at from the beginning.

Any advice?

**Comment by papnoisanjeev** [comment]
@IT-njoy 

Please check : before setup check  https://github.com/uvdesk/community-skeleton/issues/245#issuecomment-582735962 and make changes accordingly.


If you still face any problem create a support ticket
https://support.uvdesk.com/en/customer/create-ticket/ here or mail us at support@uvdesk.com.

**Comment by papnoisanjeev** [comment]
@IT-njoy  @chazkame

Click on 500 error and it will show the error.

Do one  thing allow read write permission for your project by  **chmod 777** 

And also check max execution time if it is 30sec then increase it. **check** [here](https://stackoverflow.com/questions/16171132/how-to-increase-maximum-execution-time-in-php)

Also check this for your reference:  https://github.com/uvdesk/community-skeleton/issues/161
