### ISSUE TITLE
UVDesk hangs trying to create Customer / Agent / Team / Group

### ISSUE THREAD

**Issue by jkjn-tech** [uvdesk/community-skeleton#246]
**Description**  
I have installed uvdesk 1.0.7 successfully. When I try to create Customer / Agent / Team / Group it hangs with 3 blue dots moving up and down

When I click the bottom Symphony error - get error message "[Syntax Error] line 0, col 120: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got '/'"

Please help

**Comment by papnoisanjeev** [comment]
@jkjn-tech 

Remove **?** Just after **index.php** in **.htaccess** file under **public** folder of project.
Check here:  https://github.com/uvdesk/community-skeleton/blob/master/public/.htaccess

**Comment by jkjn-tech** [comment]
Thanks for prompt reply. It is working now.

**Comment by papnoisanjeev** [comment]
@jkjn-tech   
Glad to know that you issue has been resolved.

For any further query or concern you can simply create a support ticket https://support.uvdesk.com/en/customer/create-ticket/ here 
or directly mail us at support@uvdesk.com

**Comment by jafaralshamma** [comment]
@papnoisanjeev 
When I remove ? from .htaccess I get "No input file specified." error. I'm using apache server. Any suggestions?

**Comment by papnoisanjeev** [comment]
@jafaralshamma 

Please let us know your project version.
Check installation [doc](https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-ubuntu-uvdesk/) for more details and apache configuration before setup of project.

Download latest release of UVdesk opensource from [here](https://www.uvdesk.com/en/opensource/).
