### ISSUE TITLE
Translator

### ISSUE THREAD

**Issue by luizbob** [uvdesk/community-skeleton#247]
**Description**  
I want to translate the UvDesk page to Portuguese, but i dont know how to use the symfony translator.
What i need to do to translate the page?

**Comment by papnoisanjeev** [comment]
@luizbob 

You need to add a translation file here for your language.
For Example: We have added **messages.en.yml**  for english here.


![translationfile](https://user-images.githubusercontent.com/42460055/73998947-264ab980-4989-11ea-9e93-16164b802c2a.png)

Now make a entry for your locale here.


![applocale](https://user-images.githubusercontent.com/42460055/73998971-47aba580-4989-11ea-9d77-93349e5101ff.png)



And finally check your if it is working.


![checkTranslation](https://user-images.githubusercontent.com/42460055/73999016-7295f980-4989-11ea-943a-44ed2645780d.png)


If you face any problem you can create a support ticket  https://support.uvdesk.com/en/customer/create-ticket/ here or mail us at support@uvdesk.com

**Comment by papnoisanjeev** [comment]
@luizbob 
Have you done with the translation?

**Comment by luizbob** [comment]
Not yet, but i'm getting close to finishing

**Comment by luizbob** [comment]
Hello, i just finish translating, but some pages still not translated. What i need to do to translate them?

**Comment by papnoisanjeev** [comment]
@luizbob 

You Just need to take words exist in that page and add those words in your translation file.
And let us know In which pages translation not working so we can also add translation for the same.

**Comment by papnoisanjeev** [comment]
@luizbob
 >Hello, i just finish translating, but some pages still not translated. What i need to do to translate them?

We have covered almost all the translations for this project.
Now after adding all words of **Portuguese**  in your translation file(customize file) will reflect into this software.
You can  check out our latest release  [here](https://github.com/uvdesk/community-skeleton/releases).
