### ISSUE TITLE
No feature to select enabled locale in member panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#248]
**Description**  
Add option to select all enabled locale in member panel

**Possible Solution**  

1. Need to implement this feature
- all enabled locale in uvdesk.yaml file should be visualize in front panel so that member can easily translated the provided locale

![Screenshot from 2020-02-14 17-58-14](https://user-images.githubusercontent.com/43210406/74531800-a8bc1600-4f53-11ea-90e3-e878cbd4dc5a.png)

**Comment by devzom** [comment]
+1 to this
