### ISSUE TITLE
Unable to install application

### ISSUE THREAD

**Issue by tmertz** [uvdesk/community-skeleton#249]
**Description**  
Installer hangs on verification of PHP version and PHP extensions. Provides superbly unhelpful error message. 

**How to reproduce**  
Download zip, upload to vhost directory. Attempt to run installer. 

**Additional context**  
![Screenshot 2020-02-18 at 14 25 18](https://user-images.githubusercontent.com/53013/74740220-c098e000-525a-11ea-9d0a-a3ca657dba4d.png)
I've already made sure that AllowOverride is set to All for any Directory setting that touches this application. 

I am running PHP 7.3 and have installed all the dependencies as described on the system requirements page. OS is Ubuntu 18.04 LTS. Using Apache.

**Comment by tmertz** [comment]
And I am running PHP 7.3.

**Comment by vaishaliwebkul** [comment]
@tmertz 
  
Please let us know the community version?

**Comment by tmertz** [comment]
Uh, yes. Sorry. It is the community version downloaded from the website.

**Comment by vaishaliwebkul** [comment]
@tmertz,
 Please try to set up using PHP7.2 Version.

**Comment by tmertz** [comment]
Just did that. Same error when using PHP 7.2.27.

**Comment by vaishaliwebkul** [comment]
@tmertz,
If you are using Ubuntu, share **etc/apache2/apache2.conf** file by raising you support ticket at support@uvdesk.com,
so we can guide you by checking all the configurations.

**Comment by papnoisanjeev** [comment]
@tmertz 
Please again verify your **PHP version** and restart your server  after changing version sometime it does not reflect. 
And check extension enabled  or not  **mailparse** and **Imap**  If not please install these extension first.

**Comment by tmertz** [comment]
I have double and triple checked PHP version, and mailparse and imap extensions are installed for both 7.2 and 7.3.

**Comment by papnoisanjeev** [comment]
@tmertz 

You can try this as well if unable to do so.
https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642
