### ISSUE TITLE
Deleted Tickets Reappearing after uvdesk:referesh

### ISSUE THREAD

**Issue by zaheerabbas1988** [uvdesk/community-skeleton#254]
I have deleted some tickets from the dashboard but upon executing the following it keeps reappearing:

php /var/www/html/uvdesk/bin/console uvdesk:refresh-mailbox zaheer.xyz@gmail.com

I have tried to delete tickets from database as well, but somehow tickets keep reappearing whenever I run the uvdesk:referesh. 

Is it a bug or I am missing something? 

The above mentioned php command is in my cron job and is executing in every 5 minutes.

**Comment by papnoisanjeev** [comment]
@zaheerabbas1988 

If You have deleted the tickets from the Helpdesk (permanently deleted from helpdesk system) and when again refresh command hit (as in your case using cron job) It will check If ticket with same subject or some other info exist with our database If Info not found it will create ticket again.


You don't need to remove ticket from database you can simply delete it from ticket list
these ticket will be in trash and ticket will not create again.

**Comment by zaheerabbas1988** [comment]
Many thanks for the detailed clarification. But what if I want these tickets to be removed from the trash folder as well?
Is there a way to do that? Without getting the same tickets reappearing in ticketing section after referesh command.

**Comment by papnoisanjeev** [comment]
@zaheerabbas1988 
Yes, you can also delete from trash folder as well and all the ticket will remove permanently.
but again ticket will be created as ticket does not exist in your database and you are running cron job.

So here you can do one thing, remove your trash (delete ticket permanently after 2 or more days).
As this command by default check your inbox for last 24 hours.


![trashDescription](https://user-images.githubusercontent.com/42460055/75414392-6aa8f400-594e-11ea-8e8e-a8f2516102d1.png)

**Comment by zaheerabbas1988** [comment]
Thank you, thats definately what I was looking for!

**Comment by ercanyuzuk** [comment]
hi i can't fully understand. iam using cron job for fething mails , if i remove trash , deleted ticket again re-created as a open !

**Comment by papnoisanjeev** [comment]
@ercanyuzuk 

After deleting ticket from your trash that tickets got permanently deleted from your database.
as your cron runs just after sometime it check if email get converted and exist in database.

As you have deleted it permanently so no record found for that email in with database and it again created as a ticket.

And by default once your cron runs it checks for last 24 hours mails only.

So if you want to delete a ticket permanently(delete from trash) then delete after 1 or 2 days.
