### ISSUE TITLE
Unable to install the App (Database Url malformed)

### ISSUE THREAD

**Issue by amhanna86** [uvdesk/community-skeleton#255]
# Bug report
Hallo Everyone,

### Title
Unable to install the app Database Url malformed

### Issue Description
If the username, password, host or database name contain any character considered special in a URI (such as +, @, $, #, /, :, *, !), you must encode them. See RFC 3986 for the full list of reserved characters or use the urlencode function to encode them. In this case you need to remove the resolve: prefix in config/packages/doctrine.yaml to avoid errors: url: '%env(resolve:DATABASE_URL)%'

**Comment by papnoisanjeev** [comment]
@amhanna86 

Thanks for reporting we will update it in our source code for malformed URL  Issue if any spacial character exist in database password.

**Comment by amhanna86** [comment]
Hello, 
I solved it for me now but still waiting to be in your source code for further updates
for the others who had the same issue you have to do the following:

in ConfigureHelpdesk class in updateConfigurationsXHR function change this line:

`'value' => sprintf("mysql://%s:%s@%s/%s", $database_user, $database_pass, $database_host . ($database_port ? ':' . $database_port : ''), $database_name)`

to:

`'value' => sprintf("mysql://%s:%s@%s/%s", $database_user, urlencode($database_pass), $database_host . ($database_port ? ':' . $database_port : ''), $database_name)`


and inside the config->packages->doctrine.yaml change `url: '%env(resolve:DATABASE_URL)%'` to : `url: '%env(DATABASE_URL)%'`

Thanks

**Comment by papnoisanjeev** [comment]
@amhanna86 
Thanks for your efforts.
Definitely we will update it after some test.

You can also contribute for this project.
Whenever you found a issue or add something (some feature) you can create a **pull  request** for the same and after merging your request you will be added as a contributor for this project.
https://github.com/uvdesk/community-skeleton#contributions

You can also create pull request in all dependent bundles of this project.

**Comment by papnoisanjeev** [comment]
@amhanna86 
We have updated these changes in our source code. 
These changes will reflect in next release.

https://github.com/uvdesk/community-skeleton/commit/307b2bd2c56676f678b0b3952b643f78c0a2b950

https://github.com/uvdesk/core-framework/commit/e9315b52160ec7a53a3b1b4a43aa45e19ae6068a
