### ISSUE TITLE
Failed to exec 'php bin/console uvdesk:configure-helpdesk' on Ubuntu PHP 7.4

### ISSUE THREAD

**Issue by adlmr** [uvdesk/community-skeleton#256]
# Bug report

### Issue Description
Failed to exec 'php bin/console uvdesk:configure-helpdesk' on Ubuntu PHP 7.4
Error In ConfigureHelpdesk.php line 243:  Notice: Trying to access array offset on value of type bool

### Preconditions
Ubuntu 18.04.4 LTS
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45)
latest community-skeleton

### Steps to reproduce

    1. composer create-project uvdesk/community-skeleton dfuse-support
    2. nano .env to add DATABASE_URL=
    3. php bin/console uvdesk:configure-helpdesk

### Expected result

Checking if an active super admin account exists should work

### Actual result

```
  Examining helpdesk setup for any configuration issues:

  [-] Establishing a connection with database server
  [v] Successfully established a connection with database uvdesk

  [-] Comparing the uvdesk database schema with the current mapping metadata.
  [v] The current database schema is up-to-date with the current mapping metdata.

  [-] Checking if an active super admin account exists

In ConfigureHelpdesk.php line 243:

  Notice: Trying to access array offset on value of type bool
```

**Comment by vaishaliwebkul** [comment]
@adlmr 
I followed the steps as you mention above, but not getting such type of issue, please check again or try for PHP version 7.2 if it's still not resolved

![Screenshot from 2020-04-10 22-07-46](https://user-images.githubusercontent.com/43210406/79006929-c1bdfd80-7b77-11ea-9297-908ee09c028b.png)

![Screenshot from 2020-04-10 22-04-06](https://user-images.githubusercontent.com/43210406/79006815-91765f00-7b77-11ea-9913-2ef78ec48971.png)

**Comment by papnoisanjeev** [comment]
@adlmr
You don't need to put any database details in **.env** file , after running configure command (php bin/console uvdesk:configure-helpdesk)  It will ask you to put all DB details and automatically create a database  for you with given name.
or
If you are unable to setup with this command you can also try using **Web Installer.**

**Comment by adlmr** [comment]
Still unable to use command line but web installer worked well.
