### ISSUE TITLE
Installation never finish

### ISSUE THREAD

**Issue by 1aigaisa** [uvdesk/community-skeleton#257]
# Bug report

### Title
When installing, in the last step, it is perpetually "please wait while..."

### Issue Description
I get this error:
Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'SATGM2.uv_support_role' doesn't exist" at /var/www/html/uvdesk/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42

### Preconditions
Installed in Oracle VM (3,5Gb, 2 proccesors) Maybe is it short??
The VM has a bridged adaptor so I can access to the website from any other PC in the LAN using IP/uvdesk/public The installation hangs if I try from other computer or from the localhost
PHP 7.3.17
Symphony 4.3.8

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by gonzalomartinrios** [comment]
@1aigaisa have you been able to install it successfully?

**Comment by 1aigaisa** [comment]
Hi finally yes, it was the  max_execution_time , but finally after 1 week installing we will for the SaaS version. Thank you!

**Comment by hoan3108** [comment]
@gonzalomartinrios did you resolved the error 500.please guide to me. I meet same problem

**Comment by vipin-shrivastava** [comment]
@hoan3108 
can you please share screenshots ? so that we can understand well your issues.

**Comment by hoan3108** [comment]
Thank you. My error is Like this

Vào 13:05, T.2, 28 Th6, 2021 Vipin Shrivastava ***@***.***>
đã viết:

**Comment by hoan3108** [comment]
Hi!
I need your support, i install uvdesk on centos 7, i have met the problem
in the step 4/5 of the final installation. The snapshot and the steps are
attached below

Thank you and please support me soon!

Vào Th 2, 28 thg 6, 2021 vào lúc 13:05 Vipin Shrivastava <
***@***.***> đã viết:

**Comment by vipin-shrivastava** [comment]
@hoan3108 
I didn't found your attach snapshot here ?

**Comment by hoan3108** [comment]
I sent again 4 snapshot

Vào Th 3, 29 thg 6, 2021 vào lúc 00:30 Vipin Shrivastava <
***@***.***> đã viết:

**Comment by vipin-shrivastava** [comment]
@hoan3108 
Where are you adding the snapshots? 
Are you reply GitHub through email ?
I didn't get any snapshots .  Please add snapshot in reply also make reply from GitHub web .

**Comment by hoan3108** [comment]
Did you get the picture?

Vào 00:38, T.3, 29 Th6, 2021 Hoan Vu ***@***.***> đã viết:

**Comment by hoan3108** [comment]
I reply your email with attached files
Vào 00:42, T.3, 29 Th6, 2021 Vipin Shrivastava ***@***.***>
đã viết:

**Comment by gdandersson** [comment]
Same error here. Tried changing to 60 seconds, but.. the error happens after 3s, so can't see that being the error.

Attaching screenshot of Symfony Profiler
<img width="1299" alt="Screenshot 2021-12-08 at 15 58 47" src="https://user-images.githubusercontent.com/52959348/145230758-584b4fb3-3526-4290-be1a-1bdea0997388.png">
:
