### ISSUE TITLE
/wizard/xhr/load/super-user error 500

### ISSUE THREAD

**Issue by gonzalomartinrios** [uvdesk/community-skeleton#259]
Hi, I am trying to install uvdesk in ubuntu 18 (mysql 8) and when I get to the last step it gives me the error:
public / wizard / xhr / load / super-user 500
I have followed all the steps and advice of the installation post but I cannot find the error. In the apache log there are no more error data.
Can you guide me?
Thank you.

PD: this error shows me the browser console
An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uvdesk.uv_support_role' doesn't exist

**Comment by gonzalomartinrios** [comment]
is the same problem as #257

**Comment by papnoisanjeev** [comment]
@gonzalomartinrios 

Have you tried this solution https://github.com/uvdesk/community-skeleton/issues/257#issuecomment-617254321

Check this blog for more info: https://www.uvdesk.com/en/blog/installation-open-source-helpdesk-uvdesk/
