### ISSUE TITLE
File directory not found ,when get to download zip files attached with ticket reply 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#26]
When attach a file with reply in any ticket and download that files, than get error : 
![screenshot](https://user-images.githubusercontent.com/43210406/49644153-a9971500-fa3d-11e8-9018-554b848b3ecf.png)

Eroor : Missing directory
![ym](https://user-images.githubusercontent.com/43210406/49644182-c59ab680-fa3d-11e8-936f-96e28f2b5220.png)

**Comment by papnoisanjeev** [comment]
added folder for this. fixed
