### ISSUE TITLE
Cannot create API Access Token

### ISSUE THREAD

**Issue by misterunknown** [uvdesk/community-skeleton#261]
# Bug report

### Title
I cannot create API access tokens.

### Preconditions
Freshly installed uvdesk (stable version 1.0.10)

### Steps to reproduce
Create user and edit profile.

### Expected result
There should be a tab "access tokens" like in the documentation.
![image](https://cdn.uvdesk.com/website/3/kb12.png)
[Link](https://support.uvdesk.com/en/blog/uvdesk-access-token-for-users)

### Actual result
It's not there.

![image](https://user-images.githubusercontent.com/3264829/81411383-96acd680-9142-11ea-89df-428adc7e99a1.png)

**Comment by papnoisanjeev** [comment]
@misterunknown 
You have checking documentation for UVdesk SAAS.
And this project is UVdesk opensource both are different.
If you want to work with UVdesk Opensource API  you need to check this blog: https://www.uvdesk.com/en/blog/api-resource/
