### ISSUE TITLE
composer update caused uvdesk broken

### ISSUE THREAD

**Issue by caww** [uvdesk/community-skeleton#263]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. current
    2. php7.3 +nginx

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. new clean uvdesk installed using composer
    2. run in ssh composer update command
will show this:
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ContextualizedDumper" fr
om namespace "Symfony\Component\VarDumper\Dumper".                                                                                    
Did you forget a "use" statement for another namespace? in /var/www/slavanin/data/www/portal.goaskle.com/helpdesk-project/var/cache/de
v/ContainerBWc3mxA/srcApp_KernelDevDebugContainer.php:4394                                                                            
Stack trace:                                                                                                                          
#0 /var/www/slavanin/data/www/portal.goaskle.com/helpdesk-project/var/cache/dev/ContainerBWc3mxA/srcApp_KernelDevDebugContainer.php(20
69): ContainerBWc3mxA\srcApp_KernelDevDebugContainer->getDebug_DumpListenerService()                                                  
#1 /var/www/slavanin/data/www/portal.goaskle.com/helpdesk-project/vendor/symfony/event-dispatcher/EventDispatcher.php(279): ContainerB
Wc3mxA\srcApp_KernelDevDebugContainer->ContainerBWc3mxA\{closure}()                                                                   
#2 /var/www/slavanin/data/www/portal.goaskle.com/helpdesk-project/vendor/symfony/event-dispatcher/EventDispatcher.php(90): Symfony\Com
ponent\EventDispatcher\EventDispatcher->sortListeners('console.command')                                                              
#3 /var/www/slavanin/da in /var/www/slavanin/data/www/portal.goaskle.com/helpdesk-project/var/cache/dev/ContainerBWc3mxA/srcApp_Kernel
DevDebugContainer.php on line 4394   
3. uvdesk not working anymore

### Expected result
**Tell us what should happen.**

*   

05:54:58 | php | User Deprecated: The "Symfony\Component\Debug\DebugClassLoader" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\DebugClassLoader" instead.Show context    Show trace
-- | -- | --
05:54:58 | php | User Deprecated: The "Symfony\Component\Routing\Loader\ObjectRouteLoader" class is deprecated since Symfony 4.4, use "Symfony\Component\Routing\Loader\ObjectLoader" instead.Show context    Show trace
05:54:58 | php | User Deprecated: The "Symfony\Component\Routing\Loader\DependencyInjection\ServiceRouterLoader" class is deprecated since Symfony 4.4, use "Symfony\Component\Routing\Loader\ContainerLoader" instead.Show context    Show trace
05:54:58 | php | User Deprecated: The "App\Controller\ConfigureHelpdesk" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:54:59 | php | User Deprecated: The "Webkul\UVDesk\CoreFrameworkBundle\Entity\User" class implements "Symfony\Component\Security\Core\User\AdvancedUserInterface" that is deprecated since Symfony 4.1.Show context    Show trace
05:54:59 | php | User Deprecated: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.Show context    Show trace
05:55:00 | php (2 times) | User Deprecated: Checking for the AdvancedUserInterface in "Symfony\Component\Security\Core\Authentication\Token\AbstractToken::hasUserChanged()" is deprecated since Symfony 4.1 and support for it will be removed in 5.0. Implement the Symfony\Component\Security\Core\User\EquatableInterface to check if the user has been changed,Show context    Show trace
05:55:00 | php (2 times) | User Deprecated: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.Show context    Show trace
05:53:44 | n/a | The "App\Controller\ConfigureHelpdesk" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | Configuring an encoder with "bcrypt" as algorithm is deprecated since Symfony 4.3, use "auto" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Account" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\AccountXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Authentication" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Customer" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\CustomerXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Email" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\EmailSettings" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\EmailSettingsXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Group" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\GroupXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Privilege" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\PrivilegeXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\SavedReplies" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\SwiftMailer" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\SwiftMailerXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Team" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\TeamXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Theme" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Thread" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\ThreadXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\SwiftMailer\Event\ConfigurationRemovedEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\CoreFrameworkBundle\SwiftMailer\Event\ConfigurationUpdatedEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.Show context    Show trace
05:53:44 | n/a (6 times) | A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.Show context    Show trace
05:53:44 | n/a (2 times) | The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "uvdesk" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponse" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponseXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\AutomationBundle\Controller\Automations\Workflow" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\AutomationBundle\Event\ActivityEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.Show context    Show trace
05:53:44 | n/a (2 times) | The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "uvdesk_extensions" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\ApiRoutine" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Application" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Dashboard" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\MailboxBundle\Controller\MailboxChannel" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a (2 times) | The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "uvdesk_mailbox" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Article" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Branding" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Category" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Customer" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Folder" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\KnowledgebaseXHR" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Ticket" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | The "Webkul\UVDesk\SupportCenterBundle\Controller\Website" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.Show context    Show trace
05:53:44 | n/a | Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.

### Actual result

>    **Tell us what happens instead.**

* uvdesk broken

**Comment by papnoisanjeev** [comment]
@caww 
>1. new clean uvdesk installed using composer
>2. run in ssh composer update command

Please run **composer create-project** or **composer install** command instead of **composer update** after your first step.

And if you have already run  **composer create-project uvdesk/community-skeleton helpdesk-project**  in your first step then no need to do anything else just setup your project after this using **Web installer** or using **helpdesk configure(php bin/console uvdesk:configure-helpdesk)** command.

**Comment by caww** [comment]
Hi, thanks for answer
But strange how i can update in future? all core parts?

**Comment by papnoisanjeev** [comment]
@caww 

You need to just update depended bundle of this project  - https://prnt.sc/skupu8

**composer update uvdesk/core-framework
composer update uvdesk/support-center-bundle
composer update uvdesk/mailbox-component
composer update uvdesk/automation-bundle
composer update uvdesk/extension-framework**

And by this way you can update in future.

**Comment by caww** [comment]
thanks!
