### ISSUE TITLE
Base table or view not found error.

### ISSUE THREAD

**Issue by PrakashLakhara** [uvdesk/community-skeleton#264]
**We have php extensions installed and it passes the check also**.
While setting up project with composer and configuring the db and after installing the fronted the site is giving error with
**Base table or view not found: 1146 Table 'uv_article' doesn't exist.**

**"**PDOException
PDOException
TableNotFoundException
HTTP 500 Internal Server Error
An exception occurred while executing 'SELECT u0_.id AS id_0, u0_.name AS name_1, u0_.slug AS slug_2, u0_.content AS content_3, u0_.stared AS stared_4 FROM uv_article u0_ WHERE u0_.status = ? ORDER BY u0_.viewed DESC LIMIT 10' with params [1]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb_uvdesk.uv_article' doesn't exist**"**

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Please write all the steps you gone through.
and also send us full error screenshot.

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 
You can try below command to migrate all missing tables as sometime In your first attempt all the table not get migrated due to 
less **max_execution_time** in your **php.ini**

**php bin/console uvdesk:configure-helpdesk**

**Comment by PrakashLakhara** [comment]
@papnoisanjeev 
Steps are:
- create project using
composer create-project uvdesk/community-skeleton helpdesk-project

php version 7.2

- setup using browser added database info and admin user info

- click on install

- all the process is done got message of successfully installation

- admin is working perfectly fine but when accessing frontend got error of artical table not found
**The screenshot is below.**

![error](https://user-images.githubusercontent.com/18083090/82639430-57908200-9c26-11ea-8246-62b00fcbad47.png)

**Comment by PrakashLakhara** [comment]
I also tried the command **php bin/console uvdesk:configure-helpdesk**  after increasing the max execution time from 30 to 1000. So the result of the command was https://prnt.sc/sljepi

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Try to run below commands:

**php bin/console doctrine:migrations:diff**
**php bin/console doctrine:migrations:migrate**

And finally clear your project cache by:
**php bin/console c:c** 

And then make a try.

**Comment by PrakashLakhara** [comment]
Got this error on while running the command **php bin/console doctrine:migrations:migrate** 

> Migration 20200522040716 failed during Execution. Error An exception occurred while executing 'CREATE TABLE uv_article (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, content LONGTEXT NOT NULL, meta_description VARCHAR(255) DEFAULT NULL, keywords VARCHAR(255) DEFAULT NULL, viewed INT DEFAULT NULL, status INT DEFAULT 0, date_added DATETIME NOT NULL, date_updated DATETIME NOT NULL, stared INT DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, INDEX search_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':
> 
> SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Please let us know your MySQL version.

**Comment by vaishaliwebkul** [comment]
Hi @PrakashLakhara 
Could you please mention the UVDesk version.

Thanks

**Comment by PrakashLakhara** [comment]
Hi, Uvdesk version is 4.3.8   and mysql version is 5.6

>  php bin/console -V
> Symfony 4.3.8 (env: dev, debug: true)

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Please upgrade your MySQL version 5.7 or greater.
As you can see it is clearly mentioned [here](https://github.com/uvdesk/community-skeleton#requirements).

Also check this: https://stackoverflow.com/questions/42043205/how-to-fix-mysql-index-column-size-too-large-laravel-migrate

**Comment by PrakashLakhara** [comment]
Ohh, thanks for your help. @papnoisanjeev  and @vaishaliwebkul

**Comment by PrakashLakhara** [comment]
Hi, I have now MySQL 5.7 and php7.2 with all required extensions are installed. But when I started installation it throws the following error:

> An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]:
> 
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uvdesk.uv_support_role' doesn't exist

I am attaching a screenshot.
![Firefox_Screenshot_2020-05-25T09-41-46 236Z](https://user-images.githubusercontent.com/18083090/82800904-17d1d080-9e9a-11ea-91d5-fbcd6580c3cc.png)

And after that I ran the following commands also : 
**php bin/console doctrine:migrations:diff
php bin/console doctrine:migrations:migrate
php bin/console c:c**
The commands were successful with no error. After that I refreshed site in the browser and it is again showing me the installation page of uvdesk.

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Please try to re-setup project with **new database** and before setup check your **max_execution_time** in **php.ini** and **read/write** permission for **config, public folder** and **.env**  file of this project.

**Comment by PrakashLakhara** [comment]
Sorry to say that but I have tried all the things you have mentioned but still nothing happening.
 @papnoisanjeev and @vaishaliwebkul

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Check your database if  only **uv_support_role**  table is missing in your database.
Also count how many tables exist in database currently.
It is only due to migration is not taking place properly.

Again try to run below commands:

Clear doctrine cache by:
**doctrine:cache:clear-metadata**

**php bin/console uvdesk:configure-helpdesk**

or 

**php bin/console doctrine:migrations:diff
php bin/console doctrine:migrations:migrate**

And clear your cache:
php bin/console c:c

If still all does not work please try to import **uv_support_role** table manually in your db.


[uv_support_role.sql.zip](https://github.com/uvdesk/community-skeleton/files/4680998/uv_support_role.sql.zip)

**Comment by papnoisanjeev** [comment]
@PrakashLakhara 

Is your issue resolved ? we are closing issue if still exist you can reopen it.

You can also try this method if unable to do.
https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642
