### ISSUE TITLE
When the setup wizard mode on...

### ISSUE THREAD

**Issue by kad0sh** [uvdesk/community-skeleton#265]
When i try to set the software on my server hosting account i cant make it caouse i havent PHP MAILPARSE EXTENSION and that something that even the hosting support didnt understand how to resolved...

**Comment by papnoisanjeev** [comment]
@kad0sh 
You need to install php mailparase  and imap extension on your server for your php enabled version (php version should be 7.2 or greater).

Check this for ubuntu:  https://support.uvdesk.com/en/blog/prerequisites-ubuntu 
Check this for windows:  https://support.uvdesk.com/en/blog/prerequisites-windows
