### ISSUE TITLE
Variable "user_service" does not exist.

### ISSUE THREAD

**Issue by umwl** [uvdesk/community-skeleton#267]
# Bug report

### Title 
Variable "user_service" does not exist.

### Issue Description
After clean install from composer latest version of uvdesk (1.0.11), 
sucesfully configuration via web,
app crashed.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. php 7.2.31 + apache 2.4.6 (centos)

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. composer create-project uvdesk/community-skeleton helpdesk 

it return error during configuring

  - Configuring uvdesk/core-framework
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Yaml\Yaml::parseFile() in /var/www/html/helpdesk/vendor/uvdesk/composer-plugin/lib/Composer/ComposerPackage.php:125

![image](https://user-images.githubusercontent.com/66734712/84483138-32c58280-ac99-11ea-957d-4e62cfa66f8c.png)

    2. configure by web

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

error: Variable "user_service" does not exist.
![image](https://user-images.githubusercontent.com/66734712/84480160-68b43800-ac94-11ea-9e54-e6e289ee2c0c.png)

* [points....]

**Comment by papnoisanjeev** [comment]
@umwl 
please clear your project cache by below command:

**php bin/console c:c**

and make a try.

**OR**

If above solution does not work download direct Zip file of project then after Unzip just need to setup.
[projectZip](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip)

**Comment by umwl** [comment]
@papnoisanjeev  thans for reply.
php bin/console c:c did not help. 

Instalation from zip working, but with this version from link (1.0.10) i have problem with mail. 
After create ticket or password recovery action mail is not send.
php bin/console swiftmailer:email:send work properly.

composer update return:
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Yaml\Yaml::parseFile() in /var/www/html/helpdesk/vendor/uvdesk/composer-plugin/lib/Composer/ComposerPackage.php:125

and app crash same as with new installation.

**Comment by papnoisanjeev** [comment]
@umwl 

Please don't run **composer update** after setup of project.(as many dependent package are not compatible with latest packages so it will crash this).

After successfully installing the project you need to setup your swift mailer then you will be able to send mails. If not you can see what error cause you are not able to send mails.

Locate the file **vendor->uvdesk->core-framework->Services->EmailService.php.**
Open the **EmailService.php** reach to **sendMail()** function.

and dump() the exception as in [attached link](https://s3-ap-southeast-1.amazonaws.com/cdn.uvdesk.com/website/3/dump.png).

It will show the error you are facing while sending mails.

**Comment by umwl** [comment]
@papnoisanjeev thank you very much. 
Add dump to EmailService helped me and mail work fine now ;-)

**Comment by papnoisanjeev** [comment]
@umwl 
Glad to know that your issue has been resolved.
Stay tuned with  https://github.com/uvdesk/community-skeleton for further release and updates in project.
