### ISSUE TITLE
 Failed to connect to DB if DB port other then 3306

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#269]
# Bug report

### Title
 Failed to connect to DB if DB port other then 3306

### Issue Description
 Failed to connect to DB if DB port other then 3306

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version- master

### Steps to reproduce

    1. step1- setup and migrate with DB port different other than 3306

### Expected result

should be setup successfully without any error.

### Actual result
https://user-images.githubusercontent.com/17231630/84660717-e39c7d80-af36-11ea-860b-17a8c8497642.png

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master [here](https://github.com/uvdesk/community-skeleton/commit/23cca18018dba4e4d5b0d92995427a2c147e160f) you can check.

**Comment by vaishaliwebkul** [comment]
fixed
