### ISSUE TITLE
duplicate key on ../translation/messages.ar.yml file

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#273]
# Bug report

### Title

https://github.com/uvdesk/community-skeleton/blob/master/translations/messages.ar.yml#L46

![Screenshot from 2020-07-09 19-24-50](https://user-images.githubusercontent.com/43210406/87048880-e6c71880-c219-11ea-8af6-07a3d729d15a.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
Fixed in master.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
Thanks it's fixed now
