### ISSUE TITLE
need to add ar translation for the admin login page

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#275]
# Bug report

### Title
need to add ar translation for the admin login page

### Issue Description
need to add ar translation for the admin login page

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- In ar local, admin login page is not translated

### Expected result

Admin login page should be translated

### Actual result

http://localhost/uvdesk_ecomm/community-skeleton/public/ar/agent/login

![Screenshot (16)](https://user-images.githubusercontent.com/43210406/87122330-4bc65100-c2a2-11ea-9d4e-3a8216542df0.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master [here](https://github.com/uvdesk/core-framework/commit/e33bedc4c2dfa75cf78279a086a682871dd757c4).

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/tje9qm
