### ISSUE TITLE
Issues wth swiftmailer password if contains specials characters. Also save password not encrypted seems not good for security.

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#276]
# Bug report

### Title

SwiftMailer doesn't support good strong password with special character.
There is no check on UI so if a special character is inserted in the UI than the system goes in TILT with error and this error show to everyone the email password.

### Issue Description

If you try to add an email address in SwifrtMailer that has special charcater in password and save the system will show error with password cleared showed to everyone also on user side. This is very bad.

For security reason you should support strong password with special charcater, if you can't you should add a verification in the password and give an error to the user in the UI without broken everything. If operator has no FTP access will be not able to resolve the error and the password showed publicy to all on the page.

### Expected result

If you cannot support specil characters in the swiftmailer password filed, do a check in that field and never acepting saving if the password contain this not supported characters.

**Comment by PeopleInside** [comment]
special character is supported for database? Should be.

**Comment by PeopleInside** [comment]
How much secure are store email password in a file that can be easly open by anyone that has FTP access?
In OsTicket password are stored encyped in the database, also email sent from the ticket are encryted, encoded in the source.

If you want have a good security I think is not very safe stored in clear password in a file that also is not suppoting special characters.

FTP access of a server can be given to someone to fix software issues, I'm not happy and safe knowing all password are stored and visible bu accesing FTP. Where is email security?

**Comment by PeopleInside** [comment]
Please encrypt email password stored in yaml file also account password.
Passwords should be not saved in clear in an accessible file by FTP!

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Adding the same for next release.
https://github.com/uvdesk/core-framework/pull/390
