### ISSUE TITLE
Check particular folder for ticket

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#277]
**Description**  

In Osticket when you set an email address where check tickets you can also specify in with folder.
I suggest to add a field pre-compiled inbox as default as you can find is OsTicket and allow user to edit if needs.

For example I may need set a mailbox that check tickets in the ticket Gmail label, currently this is not possibile with Uvdesk.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
kindly let me know if you're asking about this feature https://prnt.sc/tiegru
Ticket create-> if it matched with mailbox -> then label assign to Gmail

**Comment by PeopleInside** [comment]
Umh no, I think.
I mean want to be able to open ticket only for email that come in Gmail label called ticket.

1. create a label in gmail that is called ticket
2. Some email is filtered by Gmail filter and move into ticket Gmail label
3. in UVDesk the Gmail address mailbox has been setup to check for ticket in the ticket label.

When you setup a mail box in UvDesk you may need this string to put on host

{domain.ext:993/imap/ssl/novalidate-cert}INBOX

This is not user friendly, you should have a check box for no validate cert, for SSL settings, email port and folder to scan... in this case INBOX

Hope is more clear now.

**Comment by PeopleInside** [comment]
I'm closing this issue for now. Seems your system support already scan from a folder different from inbox. Maybe if I can have a suggestion is to have separate field or a tip sentence on how to compile the host field
