### ISSUE TITLE
Create ticket from different email boxes with just one cron

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#278]
**Description**  

Setup the cronjob is very hard and is getting errors.

```
Processing uvdesk mailbox configuration.

2. Opening imap stream...
16:01:59 WARNING [php] Warning: imap_open(): Couldn't open stream domain.ext ["exception" => ErrorException { …}]

3. IMAP stream opened.
```

I'm unable to set a CronJob but the issue is about have the possibility to open ticket from email with just one CronJob for all email boxes.

If I have 10 emails that need to be checked because each one has a different department is really impossibile to have 10 cronjob that run every 5 minutes.

**Example**  

In Osticket you have just one cronjob that check email for all.
Need a manager also in Uvdesk.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
> Setup the cronjob is very hard and is getting errors.
16:01:59 WARNING [php] Warning: imap_open(): Couldn't open stream domain.

Imap opening error generally comes when your given credentials are not correct or you have not provided access to fetch your mails. (for gmail:  https://myaccount.google.com/lesssecureapps)

Check the link to set cron job:  https://www.uvdesk.com/en/blog/how-to-refresh-mailbox-using-cron-job-in-uvdesk-opensource/

> If I have 10 emails that need to be checked because each one has a different department is really impossibile to have 10 cronjob that run every 5 minutes.

Currently if you will set 10 mailbox then you need to set cron job for each mailbox.
But we will look for the possibility to refresh all in one shot.

**Comment by PeopleInside** [comment]
@papnoisanjeev thank you. I found the issue and was not related to Gmail (less secure apps).
The issue is the interface has one field host that you need know how to compile.
Is very complicated and I never found a real guide for that.

There is no check box to disable certificate verification, there is no field to insert the port and the folder to scan. User has to use a complex string that i found only after a lot of reasearch.

You should have a software simple to use, please take some trip from Osticket where you configure an email address you don't need a developer but you have all field required simply to compile.

For the cron job I hope you will find a solution to not have 10 or more cron jobs for use different email address.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

You can skip SSl certificate verification by below method.

https://forums.uvdesk.com/topic/1837/i-can-not-send-mail-smtp-issue/2

**Comment by PeopleInside** [comment]
This issue is about one just Cron for all email addresses and is not solved.

**Comment by papnoisanjeev** [comment]
@PeopleInside

We will check for the possibility to refresh all mailbox with a single cron with our system and will try to add this.

**Comment by PeopleInside** [comment]
@papnoisanjeev thanks but how to know when this will be implemented if the issue is closed?

Maybe not a big issue as at the moment I cannot use UvDesk because of opened ticket #23675
also because there is no support on server for encrypted passwords... passwords are visible by FTP in a simple text file yaml file.
If passwords has special character password is showed to all in the public page where the error and password is printed.

I'm asking where security is.
Thanks anyway.

Anyone who use the software can see the issue of unencrypted password in the yaml file also can see the issue of password showed publicly with an error if contain special characters.

**Comment by PeopleInside** [comment]
Maybe this can be already supported.

You can add just more cron adding &&

like this:

`php /project_root_folder_path/bin/console uvdesk:refresh-mailbox your_mailbox_id && php /project_root_folder_path/bin/console uvdesk:refresh-mailbox your_mailbox_id && php /project_root_folder_path/bin/console uvdesk:refresh-mailbox your_mailbox_id`

I'm using this just added to each line `>/dev/null 2>&1` so I have just one cron and no email notification when the cron run:
`
php /project_root_folder_path/bin/console uvdesk:refresh-mailbox your_mailbox_id >/dev/null 2>&1 && php /project_root_folder_path/bin/console uvdesk:refresh-mailbox your_mailbox_id >/dev/null 2>&1 && php /project_root_folder_path/bin/console uvdesk:refresh-mailbox your_mailbox_id >/dev/null 2>&1 `

So maybe you can close this issue and update documentation.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Thanks for update !!
Yes, it can be done by this way also.
