### ISSUE TITLE
Add possibility to delete emails when is added to the ticket

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#279]
**Description**  

Delete an email when ticket is created or reply added.
Add option to be able to delete already processed email.

**Example**  

Email is sent to the support email address
Ticket is created or reply is added
Email should be removed if in the Mailbox the delete box is checked.

Please add the possibility to delete already processed email.

**Comment by PeopleInside** [comment]
Until a delete function will be not implemented I will not use UVdesk.
Osticket work better in this, please add the possibility to delete already processed emails.

**Comment by PeopleInside** [comment]
I use to delete old tickets but in UVdesk issues because as email still exist and is not removed just marked as read, ticket deleted will be soon created again. I hope to see added an option to delete email on ticket creation as for OsTicket.

**Comment by PeopleInside** [comment]
I suggest to implement this as an option where user can decide in the admin side if remove email after be fetched or keep it as read so you are not forcing anyone but you are giving an option that I suggest should be active by default but admin should be able to disable if don't want.

**Comment by papnoisanjeev** [comment]
@PeopleInside  @thoughtspacewebsites

ok we will try to add a option for the same in upcoming release.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

https://github.com/uvdesk/mailbox-component/pull/74  
We are also adding this for next release.

**Comment by PeopleInside** [comment]
This will be great, when will be released need understand how activate.. if is active by default or how to use. Will be amazing, thanks

**Comment by papnoisanjeev** [comment]
@PeopleInside 

By default it will be inactive if anyone need this just need to select a checkbox  for enable it from his mailbox setting.
