### ISSUE TITLE
Ticket list link is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#28]
When click on a ticket bar given below, to get all ticket then got the error : 
![1](https://user-images.githubusercontent.com/43210406/49790143-8927cd00-fd53-11e8-97a9-44323df3a3da.png)

Error comes : 
![imagess](https://user-images.githubusercontent.com/43210406/49789994-351ce880-fd53-11e8-8a81-902da66a0604.png)

**Comment by papnoisanjeev** [comment]
fixed
