### ISSUE TITLE
Issues with email notification and ticket assignment

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#282]
# Bug report

1.
Customer create a ticket by email but no email is sent to the customer with details of created account, even if the workflow is active.

2. 
When ticket is created no email notification is sent to the operator, even if a work flow is created. Seems there is no Unasigned condiction.

In the Osticket admin are notified about created ticket in the system. In UVDesk cannot understand the logic.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
> **Customer create a ticket by email but no email is sent to the customer with details of created account, even if the workflow is active.**

It will definitely work as we have set all basic action in default workflows. 
But for this you need to make sure if your set swift mailer (responsible for sending emails) is working.
There should not any kind of exception while sending mails (permission and other issues)

You can also check this by setting a gmail account email Id.


Locate the file **vendor->uvdesk->core-framework->Services->EmailService.php.**

Open the **EmailService.php** reach to **sendMail()** function.

and **dump()** the exception as in attached image.

It will show the error you are facing while sending mails (if adding an agent, creating a ticket etc).

![image](https://user-images.githubusercontent.com/42460055/87504388-09c35380-c684-11ea-9003-3e258c1e4097.png)

**> When ticket is created no email notification is sent to the operator, even if a work flow is created. Seems there is no Unasigned condiction.**

Everything will work as expected once your swift-mailer will be in running condition.

**Comment by PeopleInside** [comment]
@papnoisanjeev why the ticket message arrive to the customer but not arrive the email creation account?
If the swift mailer not work also the ticket email should not arrive to the customer.

Question:
If customer A send for the first time an email, have you tested customer A recevice two emails? Once with the confirmation of the ticket and other one with account credentials?

From my test only email with ticket recepit is sent to the customer.
Also operators did not get any email notification about the ticket.

It's not clear to me how can be possibile work with UVdesk.
In OsTicket you create department than assign operators and when this is done the operator of the department receive an email notification.

In UvDesk I'm unable to be informed as operator the new ticket as made.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
> If customer A send for the first time an email, have you tested customer A recevice two emails? Once with the confirmation of the ticket and other one with account credentials?

Yes, for the first time customer will receive two emails first for account creation and second one is for to notify him that generated ticket successfully but if already exist as a customer then will only receive second email.

> Also operators did not get any email notification about the ticket.

You need to assign that ticket to some agent based on some condition in workflow.
for example: In case some customer is creating ticket form helpdesk panel then you can assign ticket based on **ticket type** to some agent and apply mail to agent action in workflow then respected agent will receive a email notification for that.

In case when ticket is created through mailbox email and we can't discriminate through ticket type.
then you can create some condition like if subject or message description matches with some string or content then assign ticket to a agent or group or team.

**Comment by PeopleInside** [comment]
> Yes, for the first time customer will receive two emails first for account creation and second one is for to notify him that generated ticket successfully but if already exist as a customer then will only receive second email.

Did you tested this?
From my test this is not working on the opensource, only ticket alert is sent, no account email creating is sent from a new customer that create a ticket by email.

> You need to assign that ticket to some agent based on some condition in workflow.
> for example: In case some customer is creating ticket form helpdesk panel then you can assign ticket based on ticket type to some agent and apply mail to agent action in workflow then respected agent will receive a email notification for that.
> 
> In case when ticket is created through mailbox email and we can't discriminate through ticket type.
> then you can create some condition like if subject or message description matches with some string or content then assign ticket to a agent or group or team.

In my logic should exist department and to this department some agents should be assigned.
Agent assigned to a department should be able to be notified by email when a ticket created by web or email is created in thei department.

This sound more logic to guess how the subject of the ticket will be or try to guess if ticket is created by email or web with a filter.
I tried to insert a workflow where if the ticket was unassigned will be assigned to a single agent but doesn't work or you do not support this kind of filter, however is not login I create a filter to assign ticket's to only one agent.

In OsTicket the logic is there are operator and if they are assigned to a department they are notificated. This has sense or not?
With UVdesk if you do not login on the web side no notification are sent. I was not able to be notified of opening ticket.

Can you improve that?

**Comment by Himaniwebkul** [comment]
@PeopleInside 

please cross check the automated workflow, since all automation work based on workflow. For reference, this workflow should be there - https://prnt.sc/ti6jir if it doesn't exist create the new one. As ticket alert is working in your case then it should also work.
In UVdesk you assign the agent into the Group and team as well. Also, with the workflow you can define the action "mail to group" if you want to notified group members via email.

**Comment by PeopleInside** [comment]
@Himaniwebkul thanks for the answer.
I think workflow is not working very well, as in your screenshot you can see one drop down still have select option also if you select an option ( I tested this) and also if I tried the workflow did not work.

I can maybe try to test better but I think ... the system seems to not work well for me.
The workflow to send an email when user customer account is created was active but never work for ticket generated by email, for example. When I see things did not work i loose the trust in those.
