### ISSUE TITLE
While creating a project, Getting Exception as Class 'Composer\EventDispatcher\ScriptExecutionException' not found

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#29]
Create project by using this command : **composer create-project uvdesk/community-skeleton helpdesk-project --stability dev**

show the error in console 
![save](https://user-images.githubusercontent.com/43210406/49792088-e160ce00-fd57-11e8-915e-f2f6475ce591.png)

**Comment by papnoisanjeev** [comment]
fixed
