### ISSUE TITLE
The cogs keep spinning!

### ISSUE THREAD

**Issue by revsie** [uvdesk/community-skeleton#290]
So I have been looking around, trying all sorts of different things, reading this forum and that but have been unable to resolve my issue.

I have entered in all the details and installation starts but gets to 10 or 11 in the Ajax requests on the symfony toolbar, it then goes a lovely shade of red and gives this error "An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'UVDesk.uv_support_role' doesn't exist"

I have read this post 'https://github.com/uvdesk/community-skeleton/issues/257' and followed it through, but unfortunately this doesn't fix the issue. I have tried following all the tutorials and run through them. Have looked at this 'https://forums.uvdesk.com/topic/511/installation-stuck-at-step-4-need-help' and get this error "In ConfigureHelpdesk.php line 241: Call to a member function fetch() on bool" When running that and also checked composer is installed.

Really lost now so any ideas will be welcome.

**Comment by vaishaliwebkul** [comment]
@revsie 
It seems all the tables in the database are not migrated successfully.
you can go to [.env file](https://github.com/uvdesk/community-skeleton/blob/master/.env#L27)  and add the fresh database credentials here then run **php bin/console configure:helpdesk**

**Comment by papnoisanjeev** [comment]
@revsie 
 
The error generally occurs when your database not migrated properly.

Do below steps to do it manually.

1. open **.env** file of project and put your database detail here.
Do two below steps.

![image](https://user-images.githubusercontent.com/42460055/87955531-82cf0a80-cacb-11ea-9b83-0ae9c32bdbd5.png)

2. Upload a fresh database directly into your database. database size can be large so may be it will not import directly to import it using command.

Please find attached database.

If everything works well then login using below details:

username: **admin@admin.com**
password: **password**

Database Zip:  [4697481.zip](https://github.com/uvdesk/community-skeleton/files/4948629/4697481.zip)


Clear project cache by:
**php bin/console c:c**

**Comment by revsie** [comment]
@papnoisanjeev

You are a gent, it is now working.

As I am testing this is obviously all on a test server and will do a brand new install when we go live, do you have any idea why this would happen? Would be good to get to the bottom of it so that I don't hit the same issue again next time round.

**Comment by papnoisanjeev** [comment]
@revsie 

> Would be good to get to the bottom of it so that I don't hit the same issue again next time round.

It  happens mainly because of less execution time in **php.ini** file.
By default **max_execution_time** is **30 sec** you need to increase it and restart your server.

Also provide write permission for **.env** file in your project.

Then finally try to setup your project.

**Comment by revsie** [comment]
Hi,

Yes I read those and they have been changed. I might spin up another as I am getting errors now when trying to upload a logo, stuck at line 55 mkdir($pathToActiveDirectory, 0777, true); of the file  vendor/uvdesk/core-framework/FileSystem/UploadManagers/Localhost.php. Guessing that is a permissions thing.

**Comment by papnoisanjeev** [comment]
@revsie 

Provide read/write permission for below folders.

For **var** folder -chmod 777 -R path of var folder of UVdesk project
For **config** folder – chmod 777 -R path of config folder of UVdesk project
For **public** folder – chmod 777 -R path of public folder of UVdesk project

**Comment by papnoisanjeev** [comment]
@morevnaproject 

Are you getting any error when you are using web installer to setup the project.

**Comment by morevnaproject** [comment]
@papnoisanjeev Yes, did all that and increased `max_execution_time` too.

**Comment by papnoisanjeev** [comment]
@morevnaproject 

Can you let us know the error you were getting with screenshot.

**Comment by morevnaproject** [comment]
> Can you let us know the error you were getting with screenshot.

![screenshot_001](https://user-images.githubusercontent.com/332868/119844965-14e94000-bf33-11eb-8689-9236cece9cb1.png)

> Also you need to restart your server(apache) to reflect changes like max_execution_time

Yes, I did that.

**Comment by morevnaproject** [comment]
Okay, I did `chmod 777 -R` on all files in "uvdesk" installation dir and after that I was able to pass setup successfully. ^__^

**Comment by papnoisanjeev** [comment]
@morevnaproject 

Glad to know that you have successfully setup to installation part.
Hope we will get more contribution form your end as well as you done recently for [docker](https://github.com/uvdesk/community-skeleton/pull/408) file.

**Comment by morevnaproject** [comment]
My guess is that it was required to add write permissions to some other dirs/files, than `.env`, `var`, `config` and `public`. I haven't had time to investigate that, so I have added permissions to all dirs/files. Of course it would be nice to figure out which exact dirs need write permissions, but I have no time to investigate that further, unfortunately.

Also, I believe it is better to use `chmod -R ugo+rwX` instead of `chmod 777 -R`, as it will avoid making regular files executables.

**Comment by papnoisanjeev** [comment]
@morevnaproject

>I believe it is better to use chmod -R ugo+rwX instead of chmod 777 -R, as it will avoid making regular files executables.

Yes, of course also can use **chmod 775 -R**

**Comment by PeopleInside** [comment]
Hi @ericastillo 
I would be happy to try to help you, just need to see what I can I do from here :)

First question:
Do you need create a new UVdesk install?
If so maybe if you are trying to use the database provided in this issue this is more complicated than create a new empty database.

First of all you need have an empty database and you need creating this in your hosting.
In mine for example I can create a database named uvdesk with username uvdesk and with a strong password.

Than when you run the setup wizard that you have attached in your screenshot,
you will need use the database username uvdesk , database name uvdesk and the strong password than when you click on next you should not have database connection error.

Oh I see you are trying to use and install UVdesk in localhost.
If you still facing issue you can try to reach me in the live chat (when is online) at https://helpdesk.peopleinside.it/it/blog/uv

My time zone is Europe/Rome UTC +2
If the chat is online but I'm unable to reply, please try in another moment.
