### ISSUE TITLE
Error during install: Table 'helpdesk.uv_support_role' doesn't exist

### ISSUE THREAD

**Issue by tuangeek** [uvdesk/community-skeleton#292]
I am getting the following error during install. I am running the latest code from master.

```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'helpdesk.uv_support_role' doesn't exist
```

I get this error when it is sending post to `http://localhost:8080/wizard/xhr/load/super-user`

I've tried https://github.com/uvdesk/community-skeleton/issues/257#issuecomment-617254321 but no success.

**Comment by papnoisanjeev** [comment]
@tuangeek 

Check this:  https://github.com/uvdesk/community-skeleton/issues/290

**Comment by tuangeek** [comment]
@papnoisanjeev 

That solved the problem. Thanks
