### ISSUE TITLE
Sessions table deleted by bin/console uvdesk:configure-helpdesk

### ISSUE THREAD

**Issue by kennu** [uvdesk/community-skeleton#293]
# Bug report

### Title
When user sessions are stored in database, running bin/console uvdesk:configure-helpdesk deletes the sessions table.

### Issue Description
Symfony allows you to store sessions in a database table according to these instructions: https://symfony.com/doc/current/session/database.html

I have done so and created the sessions table manually with CREATE TABLE.

Apparently UVDesk thinks the sessions table is not needed and deletes it when running uvdesk:configure-helpdesk.

### Preconditions

    1. Framework Version 1.0.11

### Steps to reproduce

    1. Install UVDesk and create tables with bin/console uvdesk:configure-helpdesk
    2. Create and configure sessions table manually according to https://symfony.com/doc/current/session/database.html
    3. Login and observe sessions are working
    4. Run bin/console uvdesk:configure-helpdesk again
    5. Reload page and observe error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.sessions' doesn't exist

### Expected result

UVDesk should not delete the sessions table.

### Actual result

UVDesk deletes the sessions table.

**Comment by papnoisanjeev** [comment]
@kennu 

You need to create entity file for session tables as well (https://github.com/uvdesk/core-framework/tree/master/Entity)
Once you run command **php bin/console uvdesk:configure-helpdesk** it migrate all the tables exist in project with entity files.

When you are creating session tables manually.

When you are running command again this command check all entities exist with the project and migrate it into database(As entity file does not exist for your table so it is getting removed from database).

**Comment by kennu** [comment]
Thanks @papnoisanjeev . Is this requirement documented anywhere so others will know they need to create entity files when they use database sessions?

**Comment by papnoisanjeev** [comment]
@kennu 
You can create a entity by command **php bin/console make:entity** and need to define  field which you want to place in table.

Finally migrate your entity to database by below command:
**php bin/console d:s:u --force** 


You can  take help from below link:
https://symfony.com/doc/current/doctrine.html#creating-an-entity-class

https://symfony.com/doc/4.4/session/database.htmlhttps://symfony.com/doc/4.4/session/database.html
