### ISSUE TITLE
Customer Registration

### ISSUE THREAD

**Issue by ryanlupescu** [uvdesk/community-skeleton#294]
Missing customer end registration? I can only find how to register a customer by admin end

**Comment by vaishaliwebkul** [comment]
Hi @ryanlupescu 
Whenever you will raise a ticket from **Contact Us** form https://prnt.sc/tp1ver & send a query to **support Mailbox** then he will get the **"Success!! Account Creation Mail"**.


From the admin end, you can also register the customer from here 
![Screenshot (44)](https://user-images.githubusercontent.com/43210406/88505050-f608dd00-cff3-11ea-82d1-c499d535c1ef.png)

**Comment by ryanlupescu** [comment]
@vaishaliwebkul thank you :) 
If I understand correctly, there is no specific /signup page?

Then in my case, I wanted to avoid making customers able to use different email addresses each time they apply a ticket. Which in my previous experience causes confusing situations. To identify each individual customer correctly, I want to attach each user mail and ID as accuracte as possible even with browser identity. Therefore my own current platform now insert a user straight in UVdesk user database during registration.

**Comment by papnoisanjeev** [comment]
@ryanlupescu 

Customer is identify by his email in UVdesk so if someone create a ticket using different email than the ticket is treated as from different customer(ticket will be generated and a new customer account will be created for the same).
