### ISSUE TITLE
getting error when change the app mode in production

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#296]
# Bug report

### Title

- Install latest community-skeleton

- once all the setup is done

- go to .env file and set APP_ENV=prod

### Issue Description

getting the below issue when deploying on production mode

![Screenshot from 2020-07-30 15-49-18](https://user-images.githubusercontent.com/43210406/88911999-41cdb780-d27c-11ea-8ec5-25b5ae0eccfe.png)

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

You can download project zip from [here](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip). You will not face this issue.

**Comment by bessone** [comment]
Hello,

i have the same problem, is there a reason why the composer installation (indicated on github and in the official documentation) has this problem?

Thanks!

**Comment by papnoisanjeev** [comment]
@bessone 
Yes,  This problem exist for latest release (v1.012 when you will create project using composer)  and will be fixed in next release.

We have fixed it for latest project zip version v1.0.12.
You will not face this problem with project latest zip.

You can download project zip from [here](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip).

**Comment by Muntader** [comment]
Same problem not Fixed even on v1.0.13 
Get 500 Error only on dev mode work

**Comment by papnoisanjeev** [comment]
@Muntader 

No it is fixed with v1.0.13 may be you are facing some different problem.
Please specify steps you have done and when you are getting this so that we can help.

Also share screenshots if any.
