### ISSUE TITLE
Email templates disappear when edited by another user 

### ISSUE THREAD

**Issue by Karlostavitch** [uvdesk/community-skeleton#297]
Any email template created by or edited by another use disappear from the email templates list for anybody else except for that user.  This is the latest build here -> https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip downloaded today.

you can manually browse to the template by manipulating the URL /en/member/template/edit/templateID to the said template but whoever modify's it last appears to be the only person who can see it in the webui.

**Comment by SharePointPro** [comment]
Im facing this same issue. Did you find a solution?

**Comment by Karlostavitch** [comment]
It appears as if when a user is editing or creating an email template the user_id field is set to that userID in the uv_email_templates table. Once set, only that user can view / edit that template, its otherwise filtered out for other agents. manually setting that field back to NULL manually on the table seems to make that template available again.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/69038047/89976419-bc9ac780-dcab-11ea-9328-0162b6c7a122.png)

**Comment by papnoisanjeev** [comment]
@Karlostavitch  @SharePointPro @vaishaliwebkul 

Locate the path in your project:  **vendor->uvdesk->core-framework->Repository/EmailTemplatesRepository.php**

We have fixed it [here](https://github.com/uvdesk/core-framework/commit/9b3fb8eba75271fd1a486eef1508c3b87d8c3eaf#diff-8a5e9146b2a121bff364bb70b1f2d299). 
Now either You can replace the **EmailTemplatesRepository.php** from [here](https://github.com/uvdesk/core-framework/edit/master/Repository/EmailTemplatesRepository.php) or can make changes in existing **EmailTemplatesRepository.php** file of your project as we have done in file [here](https://github.com/uvdesk/core-framework/commit/9b3fb8eba75271fd1a486eef1508c3b87d8c3eaf#diff-8a5e9146b2a121bff364bb70b1f2d299).

We have fixed it in master and will start reflecting from next release.

**Comment by vaishaliwebkul** [comment]
fixed so closing this.
