### ISSUE TITLE
Issue when in refreshing mail n UVdesk

### ISSUE THREAD

**Issue by techbrein** [uvdesk/community-skeleton#298]
When I run the refresh command.
php bin/console uvdesk:refresh-mailbox uvdesk@xxxx.in    

I get

 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

In RefreshMailboxCommand.php line 88:

  Warning: imap_open(): Couldn't open stream localhost

uvdesk:refresh-mailbox [-t|--timestamp TIMESTAMP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<emails>...]

Fatal error: Uncaught ErrorException: Notice: Unknown: Can't open mailbox xxxx.in: no such mailbox (errflg=2) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Unknown: Can't ...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0

**Comment by papnoisanjeev** [comment]
@techbrein 

Please check [here](https://github.com/uvdesk/core-framework/issues/273).

**Comment by papnoisanjeev** [comment]
@techbrein 

 We are closing this issue if you still facing this issue you can reopen it.
