### ISSUE TITLE
it changes Attachment Name

### ISSUE THREAD

**Issue by ercanyuzuk** [uvdesk/community-skeleton#299]
Hi,

When customer create a ticket via web or sending mail , ticket creates but attachment name is different .
if customer send xml file in attachment it also changes the type to txt !
i've tried with , jpeg,png,zip, and rar file , it only change file name .
Version : 1.0.12

Regards,

**Comment by papnoisanjeev** [comment]
@ercanyuzuk 

Locate path in your project:

**vendor->uvdesk->core-framework->FileSystem->UploadManagers->Localhost.php**

Make changes as done in screenshot below:

![FileName](https://user-images.githubusercontent.com/42460055/90402563-420fe480-e0bd-11ea-8ea7-fb2bfdcbcc9f.PNG)


Also if you don't want to see uploaded image in uppercase then:
You need to remove **data-toggle="tooltip"** from below line.

https://github.com/uvdesk/core-framework/blob/master/Resources/views/ticket.html.twig#L769

**Comment by ercanyuzuk** [comment]
thanks, i tried ... it's ok now...
