### ISSUE TITLE
At customer panel some of the icon image are missing

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#30]
uvdesk shows the icon with replies and timestamp at customer panel
![11](https://user-images.githubusercontent.com/43210406/49803719-9c985f80-fd76-11e8-829a-d5a47fef7a79.png)

open source project these icons are missing
![screenshott](https://user-images.githubusercontent.com/43210406/49803792-d5d0cf80-fd76-11e8-95fe-b6c4e63d107b.png)

**Comment by papnoisanjeev** [comment]
fixed. just need to merge code.
