### ISSUE TITLE
Can't install & setup using docker

### ISSUE THREAD

**Issue by codekuu** [uvdesk/community-skeleton#300]
# Bug report

### Issue Description
Fails when trying to setup the docker by following: [https://github.com/uvdesk/community-skeleton/wiki/dockerize-helpdesk-project](https://github.com/uvdesk/community-skeleton/wiki/dockerize-helpdesk-project)
Container won't start when using 7.2 packages for php and php libs.
Removed the version from the packages inside DockerFile, it started but nothing works.
DockerFile to old?

### Steps to reproduce

1.  git clone https://github.com/uvdesk/community-skeleton
2. cd community-skeleton/
3.  docker build -t test-image .
<Successfully built XXXX> (But in reality, alot of packages failed and wget did not end up working due to that.)
4. Run the container with the image built (Using Docker Run with db inside the container)
5. sudo docker logs test-container
(FAILED)

### Screenshots etc:
[https://imgur.com/a/qgpMXdA](https://imgur.com/a/qgpMXdA)

**Comment by papnoisanjeev** [comment]
@codekuu 

As we can see some packages are not there and you are getting exception for the same.
php7.2 Imap, php7.2 mysql

Also you can take help from other closed docker issues.
https://github.com/uvdesk/community-skeleton/issues?q=is%3Aissue+is%3Aclosed+docker

**Comment by codekuu** [comment]
Perfect thank you.
Seems to be occurring issue, should try to make som changes to the wiki page with this information or update DockerFile?

Best Regards
Codekuu

**Comment by papnoisanjeev** [comment]
@codekuu 

Is your issue resolved ?
