### ISSUE TITLE
invalid credentials after fresh install with Composer

### ISSUE THREAD

**Issue by Liel4494** [uvdesk/community-skeleton#303]
i installed uvdesk with composer, i connected to database and create a superuser successfully with this commad:
_sudo php bin/console  uvdesk:configure-helpdesk_
 and when i trying to first login with the super user i created, i get 'invalid credentials'.

the password and the mail i enter is 100% the same as the superuser i created.

please help..
thanks.

**Comment by papnoisanjeev** [comment]
@Liel4494 

If there is any confusion then you can again create a admin by below command:

**php bin/console uvdesk_wizard:defaults:create-user ROLE_ADMIN**

Just fill all the details for the admin and login using new details.

**Comment by Liel4494** [comment]
### still the same error-invalid credentials.

i enter the command:
**php bin/console uvdesk_wizard:defaults:create-user ROLE_ADMIN**

and i asked for Email and Name.
i enter the email and press ENTER, then i enter the Name and press ENTER-
and then everithing is gone.
and stiil cant login.

**Comment by papnoisanjeev** [comment]
@Liel4494 

Please check your console is there any other error you are facing while login?

**Comment by Liel4494** [comment]
this is the only error,
how to fix this?

**Comment by papnoisanjeev** [comment]
@Liel4494 

You can try this way if something is missing with new database details.

https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642
