### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by domeger** [uvdesk/community-skeleton#305]
# Bug report

### Title
When deploying via Docker the apache host still complains about  Request exceeded the limit of 10 internal.

### Issue Description
Installing on a box, with apache 2 and via docker results in the same error when trying to do initial setup.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1.  Spin Up docker image, change version from latest to 18.04
    2.  docker exec -it container_id /bin/bash
    3.  look at apache errors logs.

 Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

### Expected result

Should load the webui setup.

### Actual result
500 Error.

**Comment by papnoisanjeev** [comment]
@domeger 

Please check issues docker related issues and solutions in below link It will help you.
https://github.com/uvdesk/community-skeleton/issues?q=is%3Aissue+is%3Aclosed+docker
