### ISSUE TITLE
Disabling web status displays errors and debug logs for visitors

### ISSUE THREAD

**Issue by toxpal** [uvdesk/community-skeleton#308]
I really like the option to disable "Website Status", so knowledgebase and other stuff is not displayed to users. However, if this option is disabled and some visitor still opens URL, uvdesk displays 404 error page with tons of errors and even debug logs, which is terrible due to obvious security reasons.

This is how website looks when "website status" is disabled and someone opens URL via browser - https://i.postimg.cc/RFvfZwM0/error.png

I think it should display a link to login page for admin or at least an empty page (or some basic message) instead of sensitive logs.

**Comment by papnoisanjeev** [comment]
@toxpal 

As your project environment is **dev** so you are able to see logs or error.
Once you change it to **production** it will not show any error log but instead show just a 404 page.

Make **APP_ENV = prod**     In **.env** file of project.

Use only [latest zip](https://www.uvdesk.com/en/opensource/).

**Comment by toxpal** [comment]
Thank you, wasn't aware of that. And yes, I use the latest zip.
