### ISSUE TITLE
Jquery update necessary but some issue to resolve in branding links page

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#311]
you will need update Jquery asap, now, tomorro, this week but never later.
The only safer version is the latest one https://jquery.com/ 3.5.1

**Comment by papnoisanjeev** [comment]
@PeopleInside 
You can update Jquery and backbone latest version cdn link.

You just need to update it into layout: 

![Js backbone link](https://user-images.githubusercontent.com/42460055/95075710-4ad07e80-072e-11eb-8fdb-0e98ba5a63c7.PNG)

locate path:
**vendor/uvdesk/support-center-bundle/Resources/views/Templates/layout.html.twig**
**vendor/uvdesk/core-framework/Resources/views/Templates/layout.html.twig**

You can Update latest cdn link here.

**Comment by PeopleInside** [comment]
This has resolved all, many thanks !!!!!!!

**Comment by PeopleInside** [comment]
The update seems create an issue
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/95077950-aa219500-0714-11eb-8a3a-9568982c0306.jpg)
right menu blocked.

**Comment by PeopleInside** [comment]
Sorry, resolved the menu issue, was a typo issue on my side.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Please check your console it will show error if something is not correctly loaded.

Also as you will use latest version some functions may be depreciated in latest version which we have used in project may be due to this you are facing this issue.

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> Please check your console it will show error if something is not correctly loaded.
> 
> Also as you will use latest version some functions may be depreciated in latest version which we have used in project may be due to this you are facing this issue.

Was a typo issue on my side. Fixed all works

**Comment by papnoisanjeev** [comment]
@PeopleInside 
>Sorry, resolved the menu issue, was a typo issue on my side.

Glad to know that your issue has been resolved.

**Comment by PeopleInside** [comment]
I'M opening this again because some issue should be fixed:

I created the necessary patch to update but an issue should be resolved in Branding Links that is broken after the updates.
You need to test my patch on your side, the patch is correct but need maybe some update in the branding link page on the theme or other UVdesk file.

**Comment by PeopleInside** [comment]
The issue with my patch update is not only for the **Branding link** page but also **Broadcast Message**

**Comment by PeopleInside** [comment]
Hi, I found another issue that you can test directly in the test instance I created for you and you should know how to reach.
In particular branding custom color button has the wrong color.
![uvdesk bug color](https://user-images.githubusercontent.com/5006150/95663669-7e9e1080-0b41-11eb-9d92-cca955a131d3.jpg)

**Comment by PeopleInside** [comment]
Not true solved

**Comment by PeopleInside** [comment]
Hi, 
I found another issue that you can test directly in the test instance I created for you and you should know how to reach.

In particular in branding custom color button has the wrong color.
This never happen always but with some combinations.

![1](https://user-images.githubusercontent.com/5006150/95665216-8adc9a80-0b4e-11eb-9a48-62807a06f27a.jpg)
![2](https://user-images.githubusercontent.com/5006150/95665218-8b753100-0b4e-11eb-864a-c26955645711.jpg)
![3](https://user-images.githubusercontent.com/5006150/95665219-8c0dc780-0b4e-11eb-81ea-c41c3c46967f.jpg)

you can see also here: https://helpdesk.peopleinside.it/it/usr/create-ticket/
the attachment link is not same as other links. Don't know if this is related but I think yes.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

As we have change our brand color to https://prnt.sc/uxgl98
and it is getting reflected back for buttons in knowledgebase https://prnt.sc/uxguz7

Have you successfully saved the changes or due to jquery update it is not working for you?

**Comment by PeopleInside** [comment]
Hi,
I tested with mine update. For some colour the buttons are correctly changed but for some else color maybe more light on more on the "right of the cube" where you select color, buttons loose the customisation.

You can try on the demo I set for you. You should know how to access as for the Skype support.

Sent from mobile​

Il giorno 12 ott 2020, 06:13, alle ore 06:13, sanjeev <notifications@github.com> ha scritto:

**Comment by PeopleInside** [comment]
I'm also unable to save time zone as the save button did not work with the update.

**Comment by PeopleInside** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/96190188-1c2e8100-0f42-11eb-8cd1-fbb6a6693d18.jpg)

I'm trying to understand where the problem is in branding page where all are broken with the jQuery update but I'm not a programmer. Hope you will be able to find where the issue is just on Branding page, on all Branding tabs.

Once done the update should be done asap for users.

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> Please replace **https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js** this CDN link by old link **https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js**
> 
> Locate path:
> **vendor/uvdesk/support-center-bundle/Resources/views/Templates/layout.html.twig vendor/uvdesk/core-framework/Resources/views/Templates/layout.html.twig**
> 
> You need to update CDN link here.
> 
> As due to you have updated the latest Jquery link many jquery function (due to depreciation) not working. If we update latest link we need to make lots of changes in whole project.

I will not do as this is a strong security issue. You should know what is a security issue and you should not suggest to have a vulnerability.

You will need do a lots of changes in the branding section. Other pages and sections seems work fine.

Do you want leave the project old and with security issue or you are telling me this will just only required time?
I'm confused on your reply.

**Comment by PeopleInside** [comment]
https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-11031/version_id-286394/Jquery-Jquery-2.2.4.html

**Comment by PeopleInside** [comment]
I hope your suggestion means:

if I need change some settings in branding than I can revert back and have the vulnerability for some minutes than after doing the changes I can re apply the patch.

You have a lot of code to change so fix will require some time but you will work on it.
I hope the meaning of your reply is this.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
>I hope your suggestion means:
if I need change some settings in branding than I can revert back and have the vulnerability for some minutes than after doing the changes I can re apply the patch.
You have a lot of code to change so fix will require some time but you will work on it.
I hope the meaning of your reply is this.

Yes, this is what i mean.

**Comment by PeopleInside** [comment]
@papnoisanjeev ok *-*

**Comment by PeopleInside** [comment]
Thank you!
