### ISSUE TITLE
Branding CSS and Javascript code are repeated two times.

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#315]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**

I insert a CSS code and a Javascript code in the branding page: branding/theme/advanced

Than if i go into the ticket system https://helpdesk.peopleinside.it/it/ and look at the page source the CSS and Javascript code are repeated two times.

This create issue with the live chat I inserted.

Please any advice on how to solve this issue?

The inserted CSS code is:

```
img {
  pointer-events: none;
}
```

If you look at the page source here: https://helpdesk.peopleinside.it/it/ than you search with browser, in the source "LHC" you will see CSS and Javascript are inserted twice.

Waiting for a solution please.

![00](https://user-images.githubusercontent.com/5006150/95063423-98cd8e00-06fe-11eb-8267-34145a3c19bb.jpg)

![01](https://user-images.githubusercontent.com/5006150/95063451-9ff49c00-06fe-11eb-8b1a-5fba09433c1e.jpg)

**Comment by PeopleInside** [comment]
Because of this issue I removed the JavaScript code and insert in 
/uvdesk/support-center-bundle/Resources/views/Templates/footer.html.twig

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have fixed this issue check [here](https://github.com/uvdesk/support-center-bundle/commit/3847971a5c1875c0ab60ed123678e8a6a3a78a98).

Locate path in your project.
**vendor->uvdesk->support-center-bundle->Resources->views->Knowledgebase->websiteSettings.html.twig**

Open **websiteSettings.html.twig** and copy and paste code from [here](https://github.com/uvdesk/support-center-bundle/blob/3847971a5c1875c0ab60ed123678e8a6a3a78a98/Resources/views/Knowledgebase/websiteSettings.html.twig) we have removed some duplicate code from here.

**Comment by PeopleInside** [comment]
Works, thank you for fix this fast.
