### ISSUE TITLE
[Feature request] Add use reply to action

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#316]
Situation:

A web application (example live chat) where customer send a message send the message by using the domain email address:
livechatsupport@domain.ext informing customer XXX has leaved a message.

This email insert the customer email address as reply to address.

So I'm in UVDesk workflow.

- I can set an event when ticket is created, will this apply before the ticket is opened? If not need to do an action before the ticket is opened.
- as condition I can set when the email customer is: XX
- as action I don't have use the reply to address

In OsTicket I was able to filter incoming ticket email and if is from XXX email address I can set the action t open the ticket with the reply to address.

Hope you can implement this, will be useful for all web application that cannot send the message from the customer email and if I want create a ticket need to be able to say to the ticket to use the reply to address.

***
The UVDesk seems doing a security check on incoming email and open a ticket only if an email is really authenticated.
Adding the conduiction in workflow to let admin setup a workflow like what is following should be safe and useful:

 Condiction from email is euqal to: application@domain.ext action use reply to address -> create ticket

**Comment by fiftyz** [comment]
Actualy Uvdesk is checking only if the TO email address in raw message is the same as mailbox email and, if it is, the reply-to field is set to that TO address.
The uvdesk/mailbox-component#85 should fix this also.
Also seems related to uvdesk/mailbox-component#89, not working as espected when reply-to is already set before that check.

**Comment by fiftyz** [comment]
This issue should be continued on uvdesk/mailbox-component#101 because this feature should be implemented by [mailbox-component](https://github.com/uvdesk/mailbox-component) not [commuity-skeleton](https://github.com/uvdesk/community-skeleton).

**Comment by PeopleInside** [comment]
This has been not implemented since 2020, we are in 2022 and soon 2023.
I hope UVdesk can implement it soon.

**Comment by PeopleInside** [comment]
With the version 1.1.3 of the UVdesk a workflow has been added but is not working for me.
More details can be found at ticket  #30301

I have a live chat form.
If user leave a message an email from my domain (for example sender support@domain.ext) is sent to support@domain.ext
The workflow should do this:
If sender is support@domain.ext then use the reply to to open a ticket and assign to the live chat department.

Currently from my test no ticket are opened and I don't understand why.
Also why as actions I cannot assign a specific department for that email but I have only actions of use original or reply to as email address?

The fix is not working for me.

**Comment by PeopleInside** [comment]
I was able to see it working, the issue was that I tried to create a ticket from the same helpdesk email and was never working.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside ,

Thanks for updated here. For now we are closing this issue. If you are facing any issue then reply in the same thread.
