### ISSUE TITLE
Email with some special character cannot be used in UVdesk

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#325]
# Bug report

If the email address has special character like ( . - ) I tested this two character like `support-electronic@domain.ext` or `support.dep1@domain.ext` the customer will get only Welcome email. No ticket opened email and no any Agent reply.

So if customer send an email to `support-electronic@domain.ext` that has been setup in UVdesk for monitor email and open tickets, and the email that check tickets has the special character ( - ) the ticket is created but:

- User will not get the email ticket has been opened. If the user are not registered will get the registration email only
- User will not get any Agent reply by email

- Agent will be informed by email (thanks to a custom workflow) of the tickets but when he reply no error, all fine but without he can know, no email is sent to the customer.

****

I was using email with special character without issue in other ticket solution so please, if you can resolve the issue or forbid the use of special character in UVdesk email field just in operator side so when you configure MailBox and Swift email.

I hope you can add support for it as you can need to have some spacial character in an email address. 

**Discover this bug has take a lot of time and stress as I need reconfigure all UVdesk and was not understanding why from my test, customer will miss Agent reply that is something that let me loose trust in UVdesk**

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Are you facing this issue with latest release ?

**Comment by PeopleInside** [comment]
@papnoisanjeev I did not test. If I do will broke my ticket system and risk to expose my email password so I will not test.
You should know if you fixed this issue for email or not.
This is a very intrusive issue.

**Comment by PeopleInside** [comment]
I don't know, I need to create an email address for test this and actually as I use an external antispam system I cannot do the test or have to pay for add an additional email address.

As UVdesk has issue with this I installed different email address without special character.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have tested using dot(example.gvk@gmail.com) and working ok. 
Need to test with hyphen(-) as well. 

Meanwhile if you have such email id you can test it also.

**Comment by PeopleInside** [comment]
At the moment as I use an external antispam that cost I cannot add other email address for testing.
If is working with the fullstop maybe some changes you do fixed the issue, hope also for - if so good job and if you are able to cofirm you can close that. Thank you!

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have checked with dot (.) and working ok.
We were also trying to make a email id with hyphen but gmail not allowing it https://prnt.sc/12kmhnp

**Comment by PeopleInside** [comment]
You can close the ticket, hope email like support-a1@domain.ext will not having issue if have maybe some one can open an issue, thanks.

Closing.

**Comment by PeopleInside** [comment]
Note: I closed this issue without do any test.
I cannot test the issue so I suppose you tested or if the issue will occur again maybe some user will report it.
