### ISSUE TITLE
Issue with translations on visitor and operator side

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#326]
Visitor side: ticket status are not translated.

[x] ticket status on operator but **also on visitor side** (not fully translated)
[x] ticket priority (not translated)
[x] operator confirmation message (not fully translated)
[x] actions on workflow (not fully translated)

For Italian but seems also for fr and other language if visitor see the ticket status the following status are not translated:

**Customer side:**

- answered
- pending
- resolved
- closed

**Operator side:**

Status are not translated
![01](https://user-images.githubusercontent.com/5006150/95448057-037f0380-0963-11eb-9598-ef2f7946e433.png)

![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/95458366-5ca26380-0972-11eb-9f57-39716737a3a4.jpg)
![SharedScreenshot 2](https://user-images.githubusercontent.com/5006150/95458369-5ca26380-0972-11eb-93e6-6a2a4f6f2f85.jpg)
![SharedScreenshot 3](https://user-images.githubusercontent.com/5006150/95458371-5d3afa00-0972-11eb-8a53-8d4a9120ec77.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/95458373-5d3afa00-0972-11eb-942f-c5849ad45598.jpg)

TICKET INFORMATION should be translated too, see screenshot above

Also if agent post a reply green message on right top are not translate as other green message on operator side left.
![02](https://user-images.githubusercontent.com/5006150/95448196-3f19cd80-0963-11eb-8347-f94602fc3595.png)

Translation seems to be present but not used on operator side?
Maybe the translation present is only for customer side as the English message seems to be different from what is showed on operator side.
![00](https://user-images.githubusercontent.com/5006150/95457208-ce79ad80-0970-11eb-9a99-1f2ae57df276.jpg)

Also ticket priority are not translated:
![00](https://user-images.githubusercontent.com/5006150/95457337-03860000-0971-11eb-88f8-4173392be23b.jpg)

Also some action drop down are not translated also if translation is present for Italian
![Immagine](https://user-images.githubusercontent.com/5006150/95457495-49db5f00-0971-11eb-840a-b73576627e5e.png)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have fixed translation for status in admin/agent side and also in customer side.
You can do the same in your project.

https://github.com/uvdesk/core-framework/commit/2d7626d4b84e20b9365a1c8aaf43b19578af67f6
https://github.com/uvdesk/support-center-bundle/commit/afe78de5bc9018b0cceb34893840454d907647a6

We will correct other translations if skip somewhere.

**Comment by PeopleInside** [comment]
Hi, I'm checking.
Ticket created from operator in web side still have confirmation message in English as in English is also the message if the login password is not right.

[x] confirmation message when operator create a ticket
[x] error message if password is wrong on login (tested also issue on customer side)
[X] when user is created and user need to set the password the page is not fully translated
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/95471317-181ec400-0982-11eb-9588-f65ce1274010.jpg)

The fix seems work on admin side, is not working, for me, on visitor side: ticket status still be in English and for you?

**Comment by PeopleInside** [comment]
Need also fix in list ticket of the user but works great for now the fix done in admin and user side, thanks.
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/95473774-b744bb00-0984-11eb-8305-edb3f0b748ef.jpg)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

For **ticket list** at customer panel **status** apply below two patches for translation:

https://github.com/uvdesk/core-framework/commit/d61754005f75d6f85630f5e7286670079fc6a84b
https://github.com/uvdesk/support-center-bundle/commit/d8065390e8c543c4ce1bbe13119b8fc41b884d55

We will update for others as well and also you can report if you find somewhere else.

**Comment by PeopleInside** [comment]
Thanks, I will apply the fix now. Most important done yesterday thanks to you.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have add some other missing translations patch.

https://github.com/uvdesk/community-skeleton/commit/b04127d47eac41f55d5b88e4610e0bd70ce775fa
https://github.com/uvdesk/support-center-bundle/commit/661396c8be9f9b491c8deca4a643f7305d54de50
https://github.com/uvdesk/community-skeleton/commit/0b6484cc3b394f2a509353602387269f4d9816e8

You can directly copy all the files from master branch and add into your project.

**Comment by PeopleInside** [comment]
@papnoisanjeev thanks I will do now 👍🏻

**Comment by PeopleInside** [comment]
@papnoisanjeev  in workflow the ticket priority seems still be in English. Other voice translated, strange.
It's only me?

**Comment by PeopleInside** [comment]
The registration page still be not fully translated (page where user set the password).
Not checked the page where operator set the password and don't know if is the same :D

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We can see on reset page a dot(.)  still exist on your line so may be translation not working for the line.
we have already updated the line https://github.com/uvdesk/support-center-bundle/blob/master/Resources/views/Knowledgebase/resetPassword.html.twig#L14

**Comment by papnoisanjeev** [comment]
@PeopleInside 

For **search ticket** placeholder
do this: https://github.com/uvdesk/support-center-bundle/commit/e0fdea2c2bbf6ba0e07e7d5a3d1092082f2f9668

**Comment by PeopleInside** [comment]
View all category button not translated: https://helpdesk.peopleinside.it/it/

**Comment by PeopleInside** [comment]
I will close this issue for now as I think from my side should be no more corrections about translation.
Feel free to open this again if you still want have the issue open.
If I will find some translation issue I still be reporting or try to fix.

**Comment by PeopleInside** [comment]
Operator side, page workflow. 
Here different issues should be resolved before the issue can be closed.
https://github.com/uvdesk/community-skeleton/issues/326#issuecomment-706179724

Reopen

**Comment by PeopleInside** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/97850414-48911e00-1cf4-11eb-9eef-b843d8281124.jpg)

Search result, string not translated.

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> For **ticket list** at customer panel **status** apply below two patches for translation:
> 
> [uvdesk/core-framework@d617540](https://github.com/uvdesk/core-framework/commit/d61754005f75d6f85630f5e7286670079fc6a84b)
> [uvdesk/support-center-bundle@d806539](https://github.com/uvdesk/support-center-bundle/commit/d8065390e8c543c4ce1bbe13119b8fc41b884d55)
> 
> We will update for others as well and also you can report if you find somewhere else.

This issue persist also if the patch is applied.
Why?

**Comment by PeopleInside** [comment]
If the operator insert wrong credentials the error message is not translated.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Most of the issues has been fixed.
Please generate a new issue for remaining issue.
