### ISSUE TITLE
Verify-database-credentials 500 error on setup

### ISSUE THREAD

**Issue by marjys1234** [uvdesk/community-skeleton#327]
Hello!

I am trying to set up UVdesk, but at the "Database Configuration" setting I type in the correct credentials and the database have all the right permissions, but I get a 500 error and the page does not go further. .env, config and var folder have permission 777.

What should I do?

![image](https://user-images.githubusercontent.com/17552544/95635034-96b35880-0a8b-11eb-9811-2060ff4adba1.png)
![image](https://user-images.githubusercontent.com/17552544/95635097-cd896e80-0a8b-11eb-81b3-1136961dd1f4.png)

**Comment by PeopleInside** [comment]
Hi, please try to use a password for database that not have special characters.
Also for email, special characters in email addresses or password are not supported.
Let me know if you was able to resolve.

**Comment by marjys1234** [comment]
Thank you for the reply!

By standard cPanel adds "_" between the sitename and database, so ex. "Site_Database".

Is it the "_" that mess up the setup? I only have capital letters and numbers in the database password.

**Comment by PeopleInside** [comment]
The issue should be not in the database username and seems to me to understand the database password doesn't have any special characters. What version of MySQL are you using?

Are you sure the password you inserted in the setup is correct? Can you login with that credentials on phpmyadmin?
To the database users has been assigned all database necessary permissions?

In any case I remind you for support you can use the [UVdesk community](https://forums.uvdesk.com/), I think GitHub should be used for bug only.

**Comment by marjys1234** [comment]
I could try to make a new database, but I am able to log into phpMyAdmin with the current username and password.

Current version is 5.7.31 - MySQL Community Server

**Comment by PeopleInside** [comment]
Mysql version seems to be OK.
Maybe the issue is not UVdesk but with your PHP!?

Also if the PHP version in this articles are different from yours seems can be useful (not sure is just a suggestion)
https://stackoverflow.com/questions/47043351/sessionhandlergc-ps-files-cleanup-dir-permission-denied-13
https://community.dreamfactory.com/t/session-start-ps-files-cleanup-dir-opendir-var-lib-php5-failed-permission-denied-13/935

Usually when I get an error I try to look on Google but be careful if you don't know what you are doing.
I'M not part of the UVdesk team and I'm just suggesting things on "user side" as I'm an user like you.

**Comment by PeopleInside** [comment]
Another personal suggestion is to revert folder and file permission from 777 as soon as possible after the install or in any case to not leave it with 777 permission once you end the day.

**Comment by marjys1234** [comment]
I've tried using Google, but I am to afraid to change anything directly with the PHP. I am currently using php 7.2.

I think I am going to reinstall UVdesk, just to check or change to php 7.3

**Comment by PeopleInside** [comment]
You can wait a response from UVdesk team, you can also in the meantime try to reinstall UVdesk.

@papnoisanjeev I suggest to review the [UVdesk guide](https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-ubuntu-uvdesk/) where you suggest to set files or folders permission to 777.

775 may work as well and be [little bit more secure](https://serverfault.com/questions/144194/is-chmod-775-safe-to-use/144195) and also you should suggest to revert permission back to the "normal" and safer settings after the setup.

.env file should be, after the setup, 664 other folders seems to be on 775 also for another app... umh I have to investigate if this is safer or not.

**Comment by marjys1234** [comment]
Thank you for helping me!

I found out that UVdesk is available in the Softaculous Auto Installer, and that worked for some reason.

Closing the issue

**Comment by PeopleInside** [comment]
Great, I'm happy reading the issue was resolved.
Happy week end!

**Comment by papnoisanjeev** [comment]
> You can wait a response from UVdesk team, you can also in the meantime try to reinstall UVdesk.
> 
> @papnoisanjeev I suggest to review the [UVdesk guide](https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-ubuntu-uvdesk/) where you suggest to set files or folders permission to 777.
> 
> 775 may work as well and be [little bit more secure](https://serverfault.com/questions/144194/is-chmod-775-safe-to-use/144195) and also you should suggest to revert permission back to the "normal" and safer settings after the setup.
> 
> .env file should be, after the setup, 664 other folders seems to be on 775 also for another app... umh I have to investigate if this is safer or not.

@PeopleInside 
Thanks for this security patch !!
We will update permission to 775 in our documentation.
