### ISSUE TITLE
Docker use is completely broken

### ISSUE THREAD

**Issue by TaylorDale** [uvdesk/community-skeleton#332]
# Bug report

### Title
Docker installation instructions do not work as the dockerfile produces incorrect results using latest tag. 

### Issue Description
By using the LATEST ubuntu tag, it looks like it is downloading Ubuntu 20 which does not have the dependencies listed in the package (Errors on building, and when run cannot find apache2 and mysql as they are not installed, along with many others). 

I looked at the time of the last commit to the dockerfile and reverted the Ubuntu tag to 18.04 which seemed to make the compile go fine.

Now that it works, I am getting error 500, but I will leave that for another issue. (Request exceeded the limit of 10 internal redirects due to probable configuration error.)

### Preconditions
    1. framework Version. Latest pulled with Composer

### Steps to reproduce
Build the docker image using the dockerfile provided

### Expected result
Should build a working image
### Actual result
Docker image builds but no deps are installed

**Comment by papnoisanjeev** [comment]
@TaylorDale 

Please check issues docker related issues and solutions in below link It will help you.
https://github.com/uvdesk/community-skeleton/issues?q=is%3Aissue+is%3Aclosed+docker

**Comment by TaylorDale** [comment]
Thanks for that, I actually don't need help as I've fixed the issue as you can see in my report, just thought you might like to update the Dockerfile because as-is, if anyone tried to docker build it it will always fail. This exemplifies why the Latest tag shouldn't be used in a Dockerfile, the version should be pinned instead. I can send a pull request if you'd like.

Furthermore, I've looked through the closed docker issues and none actually help with the 500 too-many-internal-redirects problem, some advice there would be great because I've failed on every front to get this one  working!

**Comment by Himaniwebkul** [comment]
@TaylorDale glad to know that you have fixed the issue!!
Yes!! it would be great if you can create a pull request for the same so that we can merge it in our latest release.
Thank you

**Comment by TaylorDale** [comment]
Thanks I've created the pull request. 

This compiles the image (as far as I can tell) successfully but it still does not work, I get LimitInternalRecursion as mention in #305 . Any ideas on that from?

**Comment by vaishaliwebkul** [comment]
Hi @TaylorDale 
try to update the .htaccess file to resolve this.
for more info check this link https://stackoverflow.com/questions/15850845/request-exceeded-the-limit-of-10-internal-redirects-due-to-probable-configuratio

**Comment by schlepper-code** [comment]
I'm new to GitHub so I apologize in advance. I have Docker manifests with 3 containers deployed: Nginx:1.19.3-alpine, Mysql-server:8.0.22-1.1.18 and PHP:7.4-fpm-alpine. It works great!
git clone https://github.com/schlepper-code/uvdesk-docker.git

**Comment by vaishaliwebkul** [comment]
@TaylorDale docker is working as mentioned by @schlepper-code 
So closing this issue.

Feel free to reopen the issue anytime if you still have any issue.

Thanks.
