### ISSUE TITLE
No route found for "GET /wizard/xhr/load/configurations": Method Not Allowed (Allow: POST)

### ISSUE THREAD

**Issue by gstlouisgit** [uvdesk/community-skeleton#334]
# Bug report

### Title
I have tried to install this on centos7 with php7.2+.  after battling all the missing extensions etc I got to the installation screen.  However now it just hangs, in the network console I can see a 500 crash /public/wizard/xhr/load/configurations and if I go to this I have the stack trace shows it halts on $response = $kernel->handle($request); in public/index.php.
The two global vars this looks to accept are $_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']
I then looked at the installation steps that said to change APP_ENV=local to APP_ENV=dev and it is still the same problems

### Issue Description
in the network console I can see a 500 crash /public/wizard/xhr/load/configurations and if I go to this I have the stack trace shows it halts on $response = $kernel->handle($request); in public/index.php.
The two global vars this looks to accept are $_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']
I then looked at the installation steps that said to change APP_ENV=local to APP_ENV=dev and it is still the same problems

There are no error logs when this happens.  I have looked everywhere and nothing is documented on the site or apache.  

### Preconditions
**Please provide as detailed information about your environment as possible.**

this is from the installation site I used the ZIP file because composer didn't install all the files when I ran it
https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-centos-uvdesk/

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

install centos 7 php 7.2

**Comment by PeopleInside** [comment]
Hi, did you see the setup wizard?
After what steps the error occurs?

**Comment by gstlouisgit** [comment]
this happens at the end of the setup wizard, when the gears are turning and is says "Please wait while your helpdesk is being installed. This could take up to a few minutes."

I now managed to see the symphony profiler and had the error .env wasn't writable.  I find strange because I was sure it was, so I changed it back to chmod 777 and now I symphony is giving me this error


Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" at /home/uvdesk/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93

I do not understand, the .env file has the correct user/pass for the DB which IS NOT root it is another user.  In the setup wizard I have also given it the proper user and pass.  Why is it looking to connect via root with no pass?

**Comment by PeopleInside** [comment]
Are you using a local install?
There are special characters on your database password? If yes try to not use special characters as UVdesk seems have issue on manage special characters for now.

Using password NO usually means the system is not requiring database password I think.. 

Seems errors occurs when try to connect to database. You can also Google the error you get

**Comment by gstlouisgit** [comment]
thanks for the reply, but I've spent lots of time searching the errors yesterday and found nothing useful.  now I tried a local macbook and I'm missing php-imap and php-mailparse and it is just a nightmare getting this install with brew for mailparse.  This is costing too much time

**Comment by PeopleInside** [comment]
I'M sorry about this.
I had issues to have mailparse but I use Webuzo control panel and asked to the Softacolous team to add support and they do. Now you can install from Softacolous ijnstaller but if you manage your server and never support the extension of curse you need resolve.

https://docs.uvdesk.com/uvdemo/requirements/requirements-ubuntu.html

**Comment by gstlouisgit** [comment]
this was an install on centos not ubuntu.  On my mac the mailparse is the problem but on the vm on centos I just get the SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) which makes no sense to me as everything is configured properly 

and mysql requiires a password - so it just doesn't seem to be using the user and pass in the .env file or in the install wizard I have given it

[root@stage ~]# mysql -root
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by PeopleInside** [comment]
> this was an install on centos not ubuntu

Sorry fr the Ubuntu link is was for show how maybe PHP extensions can be required.
I never used SSH for install UVdesk as I use a control panel so it's my Panel that let the work to install PHP and PHP extension, etc.

It's a new Centos server or you have already other application?
I'm asking because maybe you can try the Webuzo Panel with a trial premium license of 30 days and install UVdesk from the included Softacolous installer. This should help you but maybe you need a clean server for install a control panel like Webuzo.

I'm asking after the wizard what kind of page error you see and if the database password has special characters.
Username, email has special characters?

**Comment by papnoisanjeev** [comment]
@gstlouisgit 

> this was an install on centos not ubuntu. On my mac the mailparse is the problem but on the vm on centos I just get the SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) which makes no sense to me as everything is configured properly.

You can try this way also:
https://github.com/uvdesk/community-skeleton#using-terminal

Put your database details in **.env** file then run  below command:
 **php bin/console uvdesk:configure-helpdesk**

Also check this link: https://stackoverflow.com/questions/58233866/sqlstatehy000-1045-access-denied-for-user-rootlocalhost-using-password

**Comment by gstlouisgit** [comment]
I have finally managed to get this installed on centos7 fresh install.  It is most likely the other guest had other things installed that create issues.  IT is hard to tell what it was.

On a macbook this was horrible.  getting proper ext installed for php on mac even with brew is sometimes a nightmare.  mailparse was just impossible and I spend more time than I would like to admint

I didn't get to try the CLI config @papnoisanjeev but if I put this on a live machine I might give it a go.

thanks for the responses.

**Comment by PeopleInside** [comment]
@gstlouisgit I'm able to see at the end you resolved.
Have a nice week end!

**Comment by gstlouisgit** [comment]
@PeopleInside sorry

how do I configure an smtp?

I have tried putting this in the .env file but nothing is sent...

MAIL_DRIVER=smtp
MAIL_HOST=domain.ca
MAIL_PORT=587
MAIL_USERNAME=username.user
MAIL_PASSWORD=pass
MAIL_ENCRYPTION=tls

**Comment by PeopleInside** [comment]
SMTP should be set on the interface operator side not in the .env file.
https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/

**Comment by gstlouisgit** [comment]
@PeopleInside 
that link does not work for self signed certificates.  I created another issues https://github.com/uvdesk/community-skeleton/issues/338

I used the zip file download as I do not have composer.

**Comment by PeopleInside** [comment]
Self Signed certificate can create always issue as is not recognized so or you can bypass it or you will have issues.
Maybe you need search on the web how bypass certificate verification.

I don't think the issue is UVdesk
