### ISSUE TITLE
Check the email address with ticket has been created

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#335]
https://forums.uvdesk.com/topic/1856/check-the-email-address-with-ticket-has-been-created

In the ticket operator side should be visible to the operator the email address that has received the ticket.

For example in other ticket system you are able to see in the ticket the to email address so operator can know ticket has been created by email to email address support or privacy, etc.

This is useful also for diagnostic when admin test if is all well with the ticket system and the ticket aperture process

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
   As I can understand with your query, This feature already exists when tickets come to the multiple support mailbox( let's say **Gmail** or **Yahoo**), the operator could verify and filter those tickets from the manage ticket filter section.
![Screenshot_70](https://user-images.githubusercontent.com/43210406/96345639-338f7a80-10b8-11eb-916b-637c9c64a9ae.png)

**Comment by PeopleInside** [comment]
I'm checking and will update in just some minutes.

**Comment by PeopleInside** [comment]
Maybe this solve the issue. Once open the ticket i expect to see here information more than created by email but to how email address? This may be avoided with the filter. Closing the issue for now, thanks.
