### ISSUE TITLE
smtp self signed certificate not working with UVDESK zip download

### ISSUE THREAD

**Issue by gstlouisgit** [uvdesk/community-skeleton#338]
Title
I have setup uvdesk by downloading the .zip file believe it was here https://www.uvdesk.com/en/opensource/.  This seems to have installed an older version of symphony and now I cannot configure smtp with self signed using this example config https://forums.uvdesk.com/topic/1837/i-can-not-send-mail-smtp-issue/2

Issue Description
When I add stream_options and its options it crashes saying There is no extension able to load the configuration for "stream_options"

I do not have composer.  How do we upgrade symphony in UVDESK without composer?  Can we simply replace the swiftmailer and symphony folder in vendor/ ?

Preconditions

Steps to reproduce
download the .zip file and setup uvdesk with that

install centos 7 php 7.2

**Comment by PeopleInside** [comment]
I think you will have always issues with self-signed certificate as is not recognized.
Maybe you need to try to find the settings for ignore certificate validation but this is not good for security.
You may need a valid certificate for have mail works in safe way, today let's Encrypt help a lot.

I don't think the issue is related to UVdesk.

**Comment by gstlouisgit** [comment]
@PeopleInside 
no the self signed certificate is not, but the .zip file I downloaded has an old Symphony and swiftmailer possibly?  because of this stream_options does not work.  If I do not have composer how would someone go about upgrading the symphony and possibly the swiftmailer framework inside of UVDEK?  That would be kind of important if the zip I downloaded from UVDESK is outdated...

**Comment by PeopleInside** [comment]
For that you need wait the UVdesk team here. 🙂

**Comment by papnoisanjeev** [comment]
@gstlouisgit 

 >That would be kind of important if the zip I downloaded from UVDESK is outdated...

UVdesk project zip which you have downloaded is the latest one (v1.0.12).
And **Symfony** version is 4.3 and **Swiftmailer** 3.1 which is not that much older.
**stream_options** should surely work for this.

But still you can share error screenshot it will help us to find the why you are facing such issue while adding stream option.

**Comment by gstlouisgit** [comment]
Hi
thanks for your comment.  Here is the build version in which I have mentioned I can't get smtp self certs to work
 -------------------- ------------------------------------------------------- 
  Symfony                                                                     
 -------------------- ------------------------------------------------------- 
  Version              4.3.8                                                  
  End of maintenance   01/2020 Expired                                        
  End of life          07/2020 Expired                                        
 -------------------- ------------------------------------------------------- 

How can I get you the Swiftmailer version?

**Comment by papnoisanjeev** [comment]
@gstlouisgit 

You can check **composer.json** file in your project.

**Comment by gstlouisgit** [comment]
Thank you @papnoisanjeev 

I see this: "symfony/swiftmailer-bundle": "^3.1",

regardless I still get this error when I try to add to end of file here: 
```
swiftmailer:
    default_mailer: mailer_4123
    mailers:
        mailer_4123:
            transport: gmail
            username: gstlouis@gmail.com
            password: G$tlouis78
            # sender_address: ~
            # delivery_addresses: ~
            disable_delivery: false
stream_options:
    ssl:
         verify_pear: false
         verify_pear_name: false

```

There is no extension able to load the configuration for "stream_options" (in /home/domain/domains/support.domains.ca/public_html/config/packages/swiftmailer.yaml). Looked for namespace "stream_options", found "framework", "doctrine_cache", "doctrine", "doctrine_fixtures", "knp_paginator", "sensio_framework_extra", "doctrine_migrations", "security", "swiftmailer", "uvdesk", "uvdesk_automations", "uvdesk_extensions", "uvdesk_mailbox", "uvdesk_support_center", "twig", "web_profiler", "monolog", "debug", "maker", "web_server" in /home/domain/domains/support.domain.ca/public_html/config/packages/swiftmailer.yaml (which is loaded in resource "/home/domain/domains/support.domain.ca/public_html/config/packages/swiftmailer.yaml").

**Comment by PeopleInside** [comment]
@gstlouisgit is not a good idea show email and password.
The issue is UVdesk never support strong password with special character.
Your password seems have a special character.

https://github.com/uvdesk/community-skeleton/issues/276

**Comment by gstlouisgit** [comment]
that was my mistake about the password thanks I've changed it.

UVDESK not supporting characters for the DB passworrd.  What does this have to do with the smtp password?  I think this would be ridiculous since you want a strong password for most mail systems.
@PeopleInside 

The error does not mention anything about special character it talks about not supporting the"stream_options " string

**Comment by PeopleInside** [comment]
Try with a password that have not special character.
When I start to use UVdesk I discovered also email password was showed to visitor because of the special character. 
This is very bad as is bad password are stored in a yaml file not encrypted so anyone with FTP access can read email passwords.

I hope the team will understand this is not very good and will work to resolve all this potential security issues.
Try to use a password without special characters.

**Comment by papnoisanjeev** [comment]
@gstlouisgit 
Please try to place **stream_options** exactly as we have added and make a try.

As in **yaml** file if you do not place anything (indenting also should be correct) at correct place it will not work for you.
And as we can see you have added stream options not at correct place.

![image](https://user-images.githubusercontent.com/42460055/97316935-524bf900-1890-11eb-89b5-2fb6a68725a5.png)
