### ISSUE TITLE
Ticket confirmation email is not sent to the sender

### ISSUE THREAD

**Issue by glardone** [uvdesk/community-skeleton#342]
The ticket confirmation email is not sent to the sender, but it is sent to itself.

For example, if the address that is polled to open new tickets is support@domain.tld, the reply will be sent to support@domain.tld and not to the address that actually sent the request.

Is there any setting to configure?

Thank you!

**Comment by papnoisanjeev** [comment]
@glardone 

It is the process like if someone generate a ticket by **test@example.com** a mail will send you back to customer email(test@example.com) that ticket generated successfully.

If you want to notify to some agent for this action(ticket generate by customer) you need to set workflow for the same.
and select a agent based on action.

**Comment by glardone** [comment]
@papnoisanjeev 

I probably didn't explain myself well... the process I see is this:
- the ticket is generated by test@example.com sending an email to support@domain.tld
- UVdesk reads the email arrived at support@domain.tld and it opens a ticket.
- the ticket opening confirmation is sent to support@domain.tld and not to the email that requested it (test@example.com).

**Comment by vaishaliwebkul** [comment]
@glardone 
have you created your own custom automated workflow at admin-> workflow .

**Comment by papnoisanjeev** [comment]
@glardone 

You can reopen it if still exist.
