### ISSUE TITLE
Invalid Credentials after fresh install

### ISSUE THREAD

**Issue by patforg** [uvdesk/community-skeleton#343]
# Bug report

### Title
Invalid credentials after fresh install

### Issue Description
create project with : `composer create-project uvdesk/community-skeleton helpdesk-project`
configure uvdesk with: `php bin/console uvdesk:configure-helpdesk`

Install completes, when I try to login I get "Invalid Credentials"

I've tried with a downloaded version.
I've tried using the db mentionned in issue #290 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Using version 1.0.12 (2020-07-27).
    2. Ubuntu 18.04
    3. Nginx server
    4. PHP 7.2
        - max_execution_time: 300
        - max_memory: 128M

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. run `composer create-project uvdesk/community-skeleton helpdesk-project`
    2. go into helpdesk-project folder and run `sudo chmod 777 -R ./var ./config .env ./public/`
    3. run `php bin/console uvdesk:configure-helpdesk`
    4. go you web browser on the uvdesk url http://example.com/en/customer/login
        put in email and password provided at step 3, login fails
    

### Expected result
You should be able to login using the credentials provided during configuration

Here is the entries in var/log/dev.log when I try to login
[log.txt](https://github.com/uvdesk/community-skeleton/files/5691724/log.txt)

 I replaced my domain with example.com in the log

### Actual result

I get invalid credentials error when trying to login.

I've tried this multiple times with a new database and clearing cache serveral times.

**Comment by patforg** [comment]
I've also tried creating a new user as mentionned in issue #303 
```
php bin/console uvdesk_wizard:defaults:create-user ROLE_ADMIN
```

Getting invalid creds for new user as well.

Let me know if I can provide more info to help solve this issue.

**Comment by papnoisanjeev** [comment]
@patforg 

Please mention the URL by which you are trying to login.

**Comment by patforg** [comment]
> @patforg
> 
> Please mention the URL by which you are trying to login.

The url is http://hd.focuslabs.com/

**Comment by papnoisanjeev** [comment]
@patforg 
Which URl you are using to login:

http://hd.focuslabs.com/en/member/login
OR
http://hd.focuslabs.com/en/customer/login

**Comment by patforg** [comment]
@papnoisanjeev 

I was using http://hd.focuslabs.com/en/customer/login

I tried using http://hd.focuslabs.com/en/member/login and it works

I wasn't aware there where 2 different login sections.

Thanks for your help. This fixes it for me.
