### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by hashint** [uvdesk/community-skeleton#345]
# Bug report

### Uncaught PHP Exception ErrorException
Uncaught PHP Exception ErrorException: "Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php74) failed: Permission denied (13)" at /home/bplugins/public_html/helps/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php line 101
{

### Issue Description
Getting error when trying to install uv desk, I am getting this error in the  Database Configuration page, After entering the valid database details when clicking on the proceed button, its not redirecting me next page.  here is a screenshot -> https://prnt.sc/w9r4s1

**Comment by vaishaliwebkul** [comment]
@hashint 
you may refer to this solution https://stackoverflow.com/questions/47043351/sessionhandlergc-ps-files-cleanup-dir-permission-denied-13

**Comment by hashint** [comment]
@vaishaliwebkul 
Thanks, 
It worked !
I got another issue when refreshing the mailbox -> 
Would you please have a look into it ?  #346
