### ISSUE TITLE
 imap_open(): Couldn't open stream

### ISSUE THREAD

**Issue by hashint** [uvdesk/community-skeleton#346]
# Bug report

### imap_open(): Couldn't open stream
I am getting error when trying to refresh mailbox 

Full Screenshot -> https://prnt.sc/wat9o8

[bplugins@54-243-155-197 support.bplugins.com]$ php bin/console uvdesk:refresh-mailbox info@hayat.im

 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

In RefreshMailboxCommand.php line 88:

  Warning: imap_open(): Couldn't open stream mail.hayat.im

uvdesk:refresh-mailbox [-t|--timestamp TIMESTAMP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<emails>...]

Fatal error: Uncaught ErrorException: Notice: Unknown: Can't open mailbox mail.hayat.im: no such mailbox (errflg=2) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Unknown: Can't ...', 'Unknown', 0, NULL)

**Comment by vaishaliwebkul** [comment]
@hashint 
please check this https://github.com/uvdesk/core-framework/issues/273 I hope this would help you.

**Comment by hashint** [comment]
@vaishaliwebkul I have cross checked the id, host, and password but no luck.

**Comment by vaishaliwebkul** [comment]
@hashint 
please specify your mail server provider & also show all the mailbox configuration files [ uvdesk.yaml ,uvdesk_mailbox.yaml, swiftmailer.yaml ]

**Comment by vaishaliwebkul** [comment]
@hashint 
Hope your query has been resolved, we are not getting any activity here from last more than 10 days so closing this right now.

You're free to reopen anytime if the same issue still exists at your end.
