### ISSUE TITLE
Call to a member function fetch() on boolean in ConfigureHelpdesk.php line 241

### ISSUE THREAD

**Issue by LeRouteur** [uvdesk/community-skeleton#347]
![2021-01-12 12_55_10-Window](https://user-images.githubusercontent.com/47207700/104311489-920c9f00-54d5-11eb-99fe-05b50caac865.png)

Ran a fresh install, and while running the `php bin/console uvdesk:configure-helpdesk`, it crashed. Running the web installer hangs on.

Anything I can do to get rid of this problem please? Thanks in advance! :)

**Comment by LeRouteur** [comment]
Running the Web installer with this error gives me:

An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uvdesk_db.uv_support_role' doesn't exist

**Comment by papnoisanjeev** [comment]
@LeRouteur 

It may be due to **less execution time** in your **php.ini**  file.
So all **tables** not migrated properly.

You can try using [this](https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642) also.

**Comment by LeRouteur** [comment]
@papnoisanjeev

It worked like a charm, thank you! But why did it happened?

**Comment by papnoisanjeev** [comment]
@LeRouteur 

**It worked like a charm, thank you! But why did it happened?**

As already mentioned due to this reason it happened.
 >It may be due to less execution time in your php.ini file.
So all tables not migrated properly.
