### ISSUE TITLE
Auto ticket assignment to agent

### ISSUE THREAD

**Issue by eylemozyilmaz** [uvdesk/community-skeleton#349]
Hi, 

We can create assigment rules in Workflow section for new ticket, like assign to specific agent or to a group or to an agent who open the ticket first.

But I need an assigment rule based on round-robin. So far,  this feature is exist in only SmarterTRack.   WE have large support teams 20-30 agents and a lot of tickets and we dont want to track continously if there are open ticket without owned

Is it possible to add this feature on UVDESK ?

**Comment by papnoisanjeev** [comment]
@eylemozyilmaz 

> I need an assignment rule based on round-robin.

It is not possible to **randomly assign** tickets to agents currently in uvdesk.
But yes you can assign a ticket to agent based on certain conditions in workflow (For example based on ticket type, subject or description).


**Moreover** You can do one thing as well create **different groups** of **agent**  deptt. wise.
You can assign to that **group** based on **ticket type, subject or any content** basis from workflow.
And then one **superior** person of that **deptt** can manage and **assign** ticket to other person of his deptt. based on his specialization or availability. 

Hope it will help you !!

**Thanks**
