### ISSUE TITLE
Users avatar not delted from the server

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#350]
I discovered operator or users avatar are removed from the interface but not from the server where randoom image file still exist.
Can you please check the same and made a fix?

If user or operator is deleted or if user remove the avatar, avatar file should be removed from the server also.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
could you please describe how did you remove the user avatar from the interface??

**Comment by PeopleInside** [comment]
Umh, you are right. Is not possibile remove the avatar, currently. If you replace the avatar or if you delete the customer, the avatar still remain in the server, maybe.

I suggest to check and fix the following scenario:

- Add option to remove avatar and be sure this is also removed from the server
- If you delete an operator or a user the relative avatar associated must be removed from the server
- If user or operator change the avatar, the old one must be removed from the server

Currently navigating by FTP I found a folder with many users avatar of user removed from the ticket system.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
Thanks for mentioning these points, this should be implemented indeed.
