### ISSUE TITLE
Issue with Email Settings Page

### ISSUE THREAD

**Issue by WaffleThief123** [uvdesk/community-skeleton#351]
# Bug report

### Title
Issue with Email Settings Page

### Issue Description
When setting up the email accounts, it appears to not accept .cloud as a valid TLD

### Steps to reproduce

    1. Go to SwiftMail Settings
    2. Fill Out Form with a .cloud TLD
    3. hit Save 
    4. recieve error:
    
![image](https://user-images.githubusercontent.com/26676249/105460137-30b89e80-5c40-11eb-8403-c55bffdf3ea4.png)

### Expected result
Accepts settings as valid and tests them

### Actual result

Doesnt save and errors.

**Comment by papnoisanjeev** [comment]
@WaffleThief123 

As on Swiftmailer page a **email pattern** regex check enabled so may be it is not allowing you to add your custom email(.cloud).
We have updated the regex [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/SwiftMailer/manageConfigurations.html.twig#L251) as it is updated in master and will work from next release but you can use it by change this line in your **manageConfigurations.html.twig**(under **vendor/uvdesk/core-framework/Resources/views/SwiftMailer**) and make a try.

If Above solution does not work then you can add any other email from front end and change it from **swiftmailer.yaml** (under **config/packages** of your project).

**Comment by WaffleThief123** [comment]
Awesome, thanks guys gals and nonbinary pals that work on this.  Y'all are rad.  You can close this out as I view the issue as solved.

**Comment by WaffleThief123** [comment]
Asking to reopen due to this only being fixed there, but it also applies to the customer create and agent create fields. I'm gonna update it locally and see if it fixes it to confirm

**Comment by WaffleThief123** [comment]
Confirmed, setting [this line ](https://github.com/uvdesk/core-framework/blob/cf20fba40210ba6d30aff798b1a5d891c121aabf/Resources/views/Agents/createSupportAgent.html.twig#L371) to be identical to line 251 does fix it.

**Comment by papnoisanjeev** [comment]
@WaffleThief123 

Please describe problem you are facing and when.

**Comment by WaffleThief123** [comment]
@papnoisanjeev it was the same problem that i referenced when creating this ticket, except on the Add Agent page. I referenced a fix[ in this comment. ](https://github.com/uvdesk/community-skeleton/issues/351#issuecomment-768093550)
