### ISSUE TITLE
Refresh Mailbox doesn't add any new ticket

### ISSUE THREAD

**Issue by FIndustries** [uvdesk/community-skeleton#352]
# Bug report

### Title
Refresh Mailbox doesn't add any new ticket

### Issue Description
I followed the guides for setting up mailboxes. The refresh-mailbox script completes successfully but no ticket is added. I checked the endpoint and $curlResponse and it returns 200.
The site_url is set correctly. I can't find any log about the issue.

### Preconditions

    1. framework Version: Stable Release v1.0.12
    2. PHP 7.2 / 7.3

### Actual result

<img width="402" alt="Schermata 2021-01-23 alle 11 43 11" src="https://user-images.githubusercontent.com/20090175/105607488-55775800-5d9f-11eb-94ef-6addb9a1057a.png">
<img width="325" alt="Schermata 2021-01-23 alle 17 21 08" src="https://user-images.githubusercontent.com/20090175/105607503-6758fb00-5d9f-11eb-9734-ee9f77a1d6a9.png">
<img width="325" alt="Schermata 2021-01-23 alle 17 21 50" src="https://user-images.githubusercontent.com/20090175/105607554-a5eeb580-5d9f-11eb-8190-6a19db678354.png">
The site_url is correct and with `dump($curlResponse);` it gives me "200".

**Comment by papnoisanjeev** [comment]
@FIndustries 

Most probably it is the problem of **site_url** only.
Please create a support ticket [here](https://support.uvdesk.com/en/customer/create-ticket/) if you do not want to show it publicly.
