### ISSUE TITLE
ROLE_SUPER_ADMIN not created

### ISSUE THREAD

**Issue by wmertens** [uvdesk/community-skeleton#353]
# Bug report

### Issue Description

I'm trying to set up uvdesk. I ran the `uvdesk_wizard:database:migrate` job and it set up the database. Then I created a user via the web-based ConfigureHelpdesk, but it didn't create the (hardcoded) `ROLE_SUPER_ADMIN` role.

I can't find anywhere in the code where this role is created.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. version: 1.0.12 release

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. start with clean db
    2. run migration
    3. add user

### Expected result
**Tell us what should happen.**

*  user should be admin and helpdesk should work
* 
### Actual result

* user has no role and helpdesk just shows install wizard

**Comment by wmertens** [comment]
I see this is due to the doctrine fixtures bundle being dev-only in the 1.0.12 release zip file. I see it is fixed in master, but not sure that the wizard runs it.

**Comment by papnoisanjeev** [comment]
@wmertens 
Have you tried with web installer as well?
Are you still facing any other issue?

**Comment by wmertens** [comment]
The current stable release zip doesn't have fixtures in prod, so the web installer doesn't work.

Is master stable?

**Comment by papnoisanjeev** [comment]
@wmertens 

Current zip 1.0.12 is a stable release but after that there are several updates on master branch as well which will reflect in next release.

You can try this way as well:
https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642
