### ISSUE TITLE
Better password managment. Don't allow week password.

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#356]
**Description**  

"Customer" are able to set week password like 123456789, this should be not allowed.
As Admin I want force only secure password with special characters and numbers and at least one small and one capital letter.

Right now uvdesk never perform security check on password, also is not supporting special characters in password.
This means customer ticket account can easly be violated if the user set a week password.

You should improve to not acept only numerical password without at least one small and one capital letter.
As admin I want require some security on users and operators password!

**Comment by papnoisanjeev** [comment]
**For Agent make changes on given lines in core-framework:**

https://github.com/uvdesk/core-framework/blob/master/Resources/views/Agents/updateSupportAgent.html.twig#L432
https://github.com/uvdesk/core-framework/blob/master/Resources/views/Agents/createSupportAgent.html.twig#L380

Replace https://prnt.sc/xys2ld this one by below code:

**'user_form[password][first]': [{
    required: true,
    msg: '{{ "This field is mandatory"|trans }}'
},{
    pattern:  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
    msg: '{{ "Password must contain at least eight characters one letter, one number and one special character"|trans }}'
}],**


**For customer make changes on given lines in core-framework:**

https://github.com/uvdesk/core-framework/blob/master/Resources/views/Customers/createSupportCustomer.html.twig#L166
https://github.com/uvdesk/core-framework/blob/master/Resources/views/Customers/updateSupportCustomer.html.twig#L169

Replace https://prnt.sc/xysfhy this one by:

**'customer_form[password][first]': [{
    required: true,
    msg: '{{ "This field is mandatory"|trans }}'
},{
    pattern:  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
    msg: '{{ "Password must contain at least eight characters one letter, one number and one special character"|trans }}'
}],**

**On Forget password reset page:**

https://github.com/uvdesk/core-framework/blob/master/Resources/views/resetPassword.html.twig#L83

replace https://prnt.sc/xyso10 this one by:

**'password': [{
        required: true,
        msg: '{{ "This field is mandatory"|trans }}'
    },{
        pattern:  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
        msg: '{{ "Password must contain at least eight characters one letter, one number and one special character"|trans }}'
 }],**

Make and try and let us know if it works for you !!

**Comment by PeopleInside** [comment]
@papnoisanjeev thanks but if I follow your instructions as when I paste your strings I miss aligment I risk to have errors everywhere.

Can you share the file in some patch or share the file with the patch? Or can you upload file as txt here so I replace and avoid to have 500 errors everywhere?

Is really important fix the password weeksness issues.
Thanks.

**Comment by PeopleInside** [comment]
@vaishaliwebkul will user profile and operator profile support special character?
You know if special character as used in some email Uvdesk goes in error so once you will increase the password security don't forget to test if user or operator are able to turn uvdesk into errors just because of using of some characters in the password.

I will wait a fix. Thanks
PS: I'm unable to test and apply the correction suggested because I miss the right aligment of rows.

**Comment by vaishaliwebkul** [comment]
Hi @PeopleInside 
I am verifying the fixed mention here by @papnoisanjeev , then will let you know.

**Comment by PeopleInside** [comment]
> 
> 
> Hi @PeopleInside
> I am verifying the fixed mention here by @papnoisanjeev , then will let you know.

Thank you, test well using for user and operator special character to be sure the new edits doesn't allow user or operator to have uvdesk offline in error. Thanks :D

**Comment by PeopleInside** [comment]
An additional check will be nice to add is: password should not contain the part before the @ in the email address.

For example customer or operator with email address: mariorossi@domain.ext should not able to use mariorossi in the password.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Will try add password which will be of 8 character max and should contain mix up of spacial character, alphabet and numbers etc so by this way nobody can use address before @ in password may be it is enough for a strong password.

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> Will try add password which will be of 8 character max and should contain mix up of spacial character, alphabet and numbers etc so by this way nobody can use address before @ in password may be it is enough for a strong password.

That's will be enough.
I'm scared of use special characters in uvdesk since ticket email did not support this in uvdesk and I was exposed to security issue when I setup emails with special characters as my password was publicly showed in the error page... and uvdesk went down, unusable.

For that reason I'm avoid any special character password in uvdesk... but I hope one day you will be able to fix this everywhere.
I reduced my email security because your system doesn't support special characters... and now I feel not safe even using special characters for operators or user profiles.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have added strong password on all the places from where user set or update a password.
check this: https://prnt.sc/10dowqb

From next release this validation will work.

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> We have added strong password on all the places from where user set or update a password.
> check this: https://prnt.sc/10dowqb
> 
> From next release this validation will work.

Great, thank you!

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
I have verified these changes done by @papnoisanjeev , everything is working fine at operator and customer end

Closing this right now.

Thanks for your suggestion!

**Comment by PeopleInside** [comment]
Umh so for have I need the new version. Will wait, thanks
