### ISSUE TITLE
Resetting Superadmin Password without Mail working

### ISSUE THREAD

**Issue by webbrosdigital** [uvdesk/community-skeleton#360]
Im in a predicament,

I'm still in setup, I need to set up my Zoho email account with UVdesk following this https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/

The problem is I can't log in to do any of that because it's not accepting the password i set as super admin during setup.

So I clicked Forgot my Password so it's generated a random password and couldn't send it anywhere.

How does one reset the admin password? Or setup the email integration with Zoho without being able to log into UVdesk?

Have tried searching docs but haven't found anything for this situation.

**Comment by papnoisanjeev** [comment]
@webbrosdigital 

Probably you have not setup your **Swift mailer** (responsible for sending email in helpdesk) so you are not receiving any emails when applying **forget password.**

But still you can create a new one by below command:

**`php bin/console uvdesk_wizard:defaults:create-user ROLE_ADMIN`**

Just fill all the details for the admin and login using new details.

Thanks

**Comment by webbrosdigital** [comment]
Awesome thanks @papnoisanjeev that worked great. It also made me realise I was logging in as a customer not a member. What a dingus!

**Comment by Komal-sharma-2712** [comment]
@Draecal 

You can create a new one by below command:

**php bin/console uvdesk_wizard:defaults:create-user ROLE_ADMIN**

or also used a **super admin role**:

**php bin/console uvdesk_wizard:defaults:create-user ROLE_SUPER_ADMIN**

After that run this command you will show the email, name, and password details on the console.

If you giving an error after run this command so please share your **composer.json** and **composer.lock** file.
