### ISSUE TITLE
User Profile and Branding pic has // in the url

### ISSUE THREAD

**Issue by iSparkyZA77** [uvdesk/community-skeleton#361]
After uploading images for the user/agent profile or branding the url points to the url.

http://domain.com//assets/profile/zcadmONo03RADmUd.png

Not sure where to replace the // with / in the code though...

**Comment by vaishaliwebkul** [comment]
@iSparkyZA77 
the same issue is reported here https://github.com/uvdesk/core-framework/issues/308, follow this for better communication.
