### ISSUE TITLE
Support Tickets

### ISSUE THREAD

**Issue by iSparkyZA77** [uvdesk/community-skeleton#362]
All the support tickets are delivered to the agent not the client. I don't see any issues with how emails have been setup - seems pretty straight forward.

**Comment by vaishaliwebkul** [comment]
@iSparkyZA77 
have you followed this guide to setup Mailbox https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/

**Comment by PeopleInside** [comment]
Hi @iSparkyZA77 , please check well workflow.
Usually is the workflow that send emails to customer and operator.

If emails are delivered to operators I suppose outgoing email is working.
Check the workflow.

**Comment by vaishaliwebkul** [comment]
@iSparkyZA77 I hope the suggestion provided by @PeopleInside resolved your issue.

We haven't face this type of issue anymore so now closing this right now.

Feel free to ask any further query!
