### ISSUE TITLE
Docker image not start

### ISSUE THREAD

**Issue by cheesgno** [uvdesk/community-skeleton#363]
Hi
I tried to run a docker image of uvdesk following your guide.
I was able to create the image but when I try to run it I cannot setting the database configuration and  I see the following error:

uvdesk_1  | mysqladmin: connect to server at 'localhost' failed
uvdesk_1  | error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
uvdesk_1  | Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
uvdesk_1  | Error: Failed to establish a connection with mysql server (localhost)
uvdesk_1 exited with code 1

I've also configured the environment variable for docker and database configuration in the .env file
Can you help me?

**Comment by vaishaliwebkul** [comment]
@cheesgno 
Use "127.0.0.1", instead of "localhost"

**Comment by vaishaliwebkul** [comment]
@cheesgno 
not getting any response so closing this issue.
