### ISSUE TITLE
Can not connect to database although credentials are correct

### ISSUE THREAD

**Issue by Turab** [uvdesk/community-skeleton#364]
Downloaded the latest version right now, extracted it to a www directory in a Centos LAMP. Setup script passes prerequisite test and comes to database screen; although the information is correct, it still cannot connect to database by saying:

Details are incorrect ! Connection not established.

**Comment by vaishaliwebkul** [comment]
@Turab 
once verify your host server and port of database then check again.

**Comment by Turab** [comment]
@vaishaliwebkul Thank you for taking time to respond, but as I said, credentials and information are already correct as with exact same data I can connect to DB and do CRUD operations. For testing I put a simple PHP file into the Uvdesk directory, with the same server information and a piece of code like:

```
$conn = mysqli_connect('localhost', user, password, database_name); // No port provided as it is default already
mysqli_query($conn, "CREATE TABLE...");
```

And without an error it created the table.

**Comment by Turab** [comment]
I debugged the issue by dumping the thrown exception and saw that Uvdesk is trying to connect to a Redis server for a reason I don't understand. The exeption said "connection refused" which is perfectly normal because Redis is not installed on this server. I disabled PHP Redis plugin and installation process could continue. There is also a discussion in community about this. I believe this is a valid bug.

**Comment by papnoisanjeev** [comment]
@Turab 
> which is perfectly normal because Redis is not installed on this server. I disabled PHP Redis plugin and installation process could continue. There is also a discussion in community about this. I believe this is a valid bug.

Please mention where you have made changes with detail explanation so that it will help to others to do the same.

**Comment by Turab** [comment]
@papnoisanjeev as I said, I just disabled Redis extension of PHP by commenting out "extension=redis" line in php.ini. Another approch can be editing the file `/uvdesk/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php` and commenting out this whole block:

`        if (extension_loaded('redis')) {
            $redis = new \Redis();
            $redis->connect('127.0.0.1');

            $cache = new \Doctrine\Common\Cache\RedisCache();
            $cache->setRedis($redis);

            return $cache;
        }`

**Comment by xAurai** [comment]
I also encountered this issue during setup. I tested credentials in MySQL Workbench and successfully connected.

I am using Plesk and disabling the Redis PHP extension I was also able to continue to the next part of the setup.

**Comment by papnoisanjeev** [comment]
@Turab @xAurai 

Thanks !!

**Comment by jxs714** [comment]
> @papnoisanjeev as I said, I just disabled Redis extension of PHP by commenting out "extension=redis" line in **php.ini**. Another approach can be editing the file `/uvdesk/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php` and commenting out this whole block:
> 
> ```
>         if (extension_loaded('redis')) {
>             $redis = new \Redis();
>             $redis->connect('127.0.0.1');
> 
>             $cache = new \Doctrine\Common\Cache\RedisCache();
>             $cache->setRedis($redis);
> 
>             return $cache;
>         }
> ```

Thank you so much for this. This fixed the issue!

**Comment by BlackDahlia313** [comment]
I am having this issue, but redis is not installed.

**Comment by Turab** [comment]
Then try removing Redis check from the setup file. I gave the instructions above.
