### ISSUE TITLE
[Feature request] Show Uvdesk version in the admin side

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#365]
The application should show his version on admin side so admins can compare the last version and update.
Currently you never show any info about the app.
I suggest to add a section in admin side for admin to see maybe PHP, version of Uvdesk, and if the version is updated or not (will be nice)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We are adding project version and it will show in footer of dashboard from next release.

![version](https://user-images.githubusercontent.com/42460055/109805832-ee747b00-7c49-11eb-8543-7d00d914e35c.png)

**Comment by PeopleInside** [comment]
Great!
