### ISSUE TITLE
strong password is not accepting as per the validation

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#366]
# Bug report

### Title
enter password  'uvdesk@123' and still, it's not accepting

![Screenshot_321](https://user-images.githubusercontent.com/43210406/109984357-b2184c00-7d29-11eb-8b94-0c5e3aa675c0.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated in master please check now.

**Comment by vaishaliwebkul** [comment]
I have checked and verified the strong password update for the customer, agent, and web installer which works fine, so closing this.
