### ISSUE TITLE
At the part of Website Configuration, add some restrictions when add Prefix value for member/customer panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#37]
if member prefix : //mm
customer prefix : //cm
it will get accepted but the suggestion is double or triple /// not allowed in URL 
![screenshot 3](https://user-images.githubusercontent.com/43210406/49933210-0b99c380-fef1-11e8-8531-1925a34915ac.png)
![screenshot 2](https://user-images.githubusercontent.com/43210406/49933304-469bf700-fef1-11e8-83e1-e2f9b7810ffc.png)

**Comment by shubhwebkul** [comment]
resolved
