### ISSUE TITLE
API request failed on api/v1/tickets

### ISSUE THREAD

**Issue by dotupNET** [uvdesk/community-skeleton#370]
# Bug report

### Issue Description
When trying to fetch a list of tickets the api reponse with "No such user"

### Preconditions

I followed this installation guide:
https://docs.uvdesk.com/uvdemo/installation/installation-ubuntu.html

and this api guide:
https://www.uvdesk.com/en/blog/api-resource/

and I changed php to 7.3 and composer to 1.10.20
PHP 7.3.27-9+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:10:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-9+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

Make a call with insomnia to:
your.domain/api/v1/tickets

with header "Authorization: Basic" and value with YOUR_API_KEY

![2021-03-15 15_16_01-Insomnia – uvdesk](https://user-images.githubusercontent.com/7642282/111167525-82770880-85a1-11eb-830d-93b2a1d0deba.png)

### Expected result

Should return a list of tickets.

### Actual result

{
  "status": false,
  "message": "No such user found",
  "error_code": "CC-001"
}

**Comment by papnoisanjeev** [comment]
@dotupNET

As we can see your header request is not correct.

Please check below screenshot.

![image](https://user-images.githubusercontent.com/42460055/111283906-997f2e80-8665-11eb-9fa1-841444518fe6.png)

**Comment by papnoisanjeev** [comment]
@dotupNET 

As no response from your side and we have provided you solution for this..
Still if you face any problem you can reopen it.
