### ISSUE TITLE
Agent not receiving emails when customer replies

### ISSUE THREAD

**Issue by slawn** [uvdesk/community-skeleton#371]
With default workflows - there is a workflow that should send an email to assigned agent once customer replies. This doesn't work - no email is sent to agent.

Installed using composer today - so assuming latest version. PHP 7.2.

SwiftMailer is configured correctly - emails are sent back to customer, welcome emails are received, password resets for agents work as well - so mail is working.

I tried different options and change the settings on the workflow to send an email to assigned agent, to response performing agent - and basically all other agents - nobody is getting notification when customer replies. Please see settings here:

![image](https://user-images.githubusercontent.com/17828022/111482971-49b76a80-872c-11eb-867b-db98b6196f92.png)

Also to check if the event works - on customer reply - I change the status of the ticket to opened - and this works - so only the email part doesn't. I also tried changing email templates - this didn't helped either.

How can I troubleshoot this? I cannot see any errors or issues in logs - not sure how I can track the issue. Like I said emails overall are working - so it's not the SwiftMailer issue? Any suggestions?

**Comment by papnoisanjeev** [comment]
@slawn 

According to this workflow If agent is assigned on that ticket and customer reply on ticket then agent should receive email for the same.

If agent not receiving the email then please do a change in your file and make a try.

Locate path in your project:
**vendor/uvdesk/core-framework/Services/EmailService.php**

Open **EmailService.php** and reach to **sendMail(**) https://prnt.sc/10b0koq .

Add these line https://prnt.sc/10agjxs in your code from here.

**Comment by slawn** [comment]
yup - I can confirm that fixed it! Thanks
