### ISSUE TITLE
Option to remove emails from mailbox after they are fetched

### ISSUE THREAD

**Issue by slawn** [uvdesk/community-skeleton#372]
It would be handy if there would be an option that once email is retrieved by uvdesk - that it is removed from the inbox. Right now I cannot see any option that would help with that - and with big number of tickets the mailbox grows in size.

Also what I noticed that when emails are deleted from ticketing system and then removed from trash permanently - old emails are being picked up as new tickets as they are still on the mail server.

**Comment by PeopleInside** [comment]
https://github.com/uvdesk/community-skeleton/issues/279

**Comment by PeopleInside** [comment]
I suggest to implement this as an option where user can decide in the admin side if remove email after be fetched or keep it as read so you are not forcing anyone but you are giving an option that I suggest should be active by default but admin should be able to disable if don't want.
