### ISSUE TITLE
Add one more column to ticket list view - last updated

### ISSUE THREAD

**Issue by slawn** [uvdesk/community-skeleton#373]
Right now on the ticket list view there is a column called Timestamp - which shows when the ticket was created. It would be great if it would be possible to add another column with Last Updated date / time. I can see this info is easily accessible in the DB - in the columns called updated_at.

It would be very handy to see when customer replied by quickly looking at the list - it's already possible to sort the list by last replied so that info is there already - just not displayed.

**Comment by papnoisanjeev** [comment]
@slawn

Yes we will try to add this in next release we will add this.

**Comment by papnoisanjeev** [comment]
@slawn 

We have added last reply field in ticket list and update in master branch and will reflect from next release.
Meanwhile you can add this to your project by below method:

Locate path in your project and replace your file code:

1.  **vendor/uvdesk/core-framework/Resources/views/ticketList.html.twig**

open **ticketList.html.twig** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/ticketList.html.twig).

2.  **vendor/uvdesk/core-framework/blob/master/Services/TicketService.php**

open **TicketService.php** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Services/TicketService.php).

Now it should work for you !!

**Comment by slawn** [comment]
> @slawn
> 
> We have added last reply field in ticket list and update in master branch and will reflect from next release.
> Meanwhile you can add this to your project by below method:
> 
> Locate path in your project and replace your file code:
> 
> 1. **vendor/uvdesk/core-framework/Resources/views/ticketList.html.twig**
> 
> open **ticketList.html.twig** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/ticketList.html.twig).
> 
> 1. **vendor/uvdesk/core-framework/blob/master/Services/TicketService.php**
> 
> open **TicketService.php** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Services/TicketService.php).
> 
> Now it should work for you !!

Works now! Just one thing - twig cache needs to be cleared for this to start working. thanks
