### ISSUE TITLE
No pagination on Tags List - only 15 displayed

### ISSUE THREAD

**Issue by slawn** [uvdesk/community-skeleton#374]
When you go Productivity > Tags to view the tags list only 15 tags are displayed and there is no pagination or any easy way to browse through tags. I've checked the manual and it doesn't mention that there is such limitation - that's why raising this as a bug. You can search through tags - but there is no easy way to browse through them.

Using latest version of uvdesk installed with composer and using PHP 7.2, but also tried online demo from your website to double check and there is the same behaviour.

When I check the console (xhr request to list tags) it looks like the pagination should be there - or at least page count and other items are visible, but no matter how many tags you have there is only 1 page. In my case I have close to 700 tags and it's not easy to find them

Thanks

![image](https://user-images.githubusercontent.com/17828022/111507745-e2f17b80-8742-11eb-8c69-587b465cda94.png)

**Comment by papnoisanjeev** [comment]
@slawn 

Ok we will test and let you update for this.

**Comment by vaishaliwebkul** [comment]
@slawn 
Thanks for reporting this, we have verified this and found a bug, will soon fix it.

**Comment by papnoisanjeev** [comment]
@slawn 

It is fixed now in master branch [here](https://github.com/uvdesk/core-framework/commit/aca02cf62ef279354388f3f6576e879bfc1219ce).

Locate path in your project:
**vendor/uvdesk/core-framework/Services/TicketService.php**

Open **TicketService.php** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Services/TicketService.php).

It will fix for you !!

**Comment by slawn** [comment]
> @slawn
> 
> It is fixed now in master branch [here](https://github.com/uvdesk/core-framework/commit/aca02cf62ef279354388f3f6576e879bfc1219ce).
> 
> Locate path in your project:
> **vendor/uvdesk/core-framework/Services/TicketService.php**
> 
> Open **TicketService.php** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Services/TicketService.php).
> 
> It will fix for you !!

Confirmed it's fixed now. Thank you!
