### ISSUE TITLE
[Feature request] support extensions

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#375]
**Description**  

Support extension also in the community edition.
I want to have the possibility to know user (customer) feedback when a ticket is closed.

Right now this is only supported in Uvdesk hosted by you, not in the self-hosted version.
You can consider to add some paid add-on to the open source like pay once and get extension.

If not introduce support to extension please add ticket feedback once ticket is closed to see the user happiness or not.

**Comment by Himaniwebkul** [comment]
Hello @PeopleInside 
Are you referring to the **Kudos** customer feedback feature - https://prnt.sc/10oz3fj available in the cloud-hosted variant?
Thank you!!

**Comment by PeopleInside** [comment]
Yes correct. I really want to see on the self hosted version but I don't have and don't see any support.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have added [kudos ](https://support.uvdesk.com/fr/blog/uvdesk-what-is-kudos) feature for self hosted version and will show you in upcoming release.

**Comment by PeopleInside** [comment]
Great, I will try to have as soon will be available. Thanks

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> We have added [kudos ](https://support.uvdesk.com/fr/blog/uvdesk-what-is-kudos) feature for self hosted version and will show you in upcoming release.

I'm unable to find Kudos in the new version.
A lot of old bugs has been reintroduced in this new version, means you never fixed in the correct branch and miss months of fix.

I will wait your support.
https://github.com/uvdesk/community-skeleton/commit/368ac8020fb5edae0e679fc02b64d999434688f1#commitcomment-55254502
