### ISSUE TITLE
Need support for PHP 7.4

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#377]
**Description**  

Is a little bit late for asking support for PHP 7.4 as this version has been released on 28 November 2019 and will be supported until 28 November 2022

so we have 12 months of support but maybe before this 12 months I will switch to PHP 8.0 as soon other application end the support of this PHP 8 release.

Consider PHP 7.1 and PHP 7.2 that you are supporting has ended is life so should be no more supported.
At the moment seems the only good version you support is PHP 7.3 that will soon be deprecated before 12 mounts.

You asked me to downgrade PHP and also Composer: I cannot downgrade my server, I try my best to keep secure and updated.

Please add support for PHP 7.4 asap.
Issue that can be connected to this: https://github.com/uvdesk/core-framework/issues/352

jQuery need to be updated but the PHP code seems old and doesn't support the jQuery update and PHP 7.4

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
please clarify if you are facing any issues while using UVdesk on PHP version 7.4 only and composer version series 1.
As I also always use 7.4 while testing UVdesk, I didn't get any issue, the only issue I found just because of composer version 2 which currently uvdesk doesn't support.

**Comment by PeopleInside** [comment]
> please clarify if you are facing any issues while using UVdesk on PHP version 7.4

At the moment I'm running UVdesk on PHP 7.4 without strong issues but I cannot update jQuery
https://github.com/uvdesk/core-framework/issues/352
In your forum you asked to downgrade PHP and not use PHP 7.4, I can't use an inferior PHP version https://forums.uvdesk.com/topic/1840/add-google-recaptcha/42

so I'm asking to support PHP 7.4

You made a patch for ReCaptcha but is not working and the reply is to downgrade PHP so this is why I ask to support PHP 7.4

Also checking the doc PHP 7.4 is not mentioned:
https://docs.uvdesk.com/uvdemo/requirements/requirements-ubuntu.html

**Comment by vaishaliwebkul** [comment]
@PeopleInside 

- You don't need to downgrade the PHP version( supported 7.2, 7.3, 7.4) but restricted to PHP 8.
- Don't use composer version 2, only use Composer 1 series.
- README is already updated regarding the PHP version https://github.com/uvdesk/community-skeleton/blob/master/README.md
- we will update doc soon https://github.com/uvdesk/uvdesk.github.io/issues/29

**Comment by PeopleInside** [comment]
Why you are asking to use PHP 7.3 in the forum?
https://forums.uvdesk.com/topic/1840/add-google-recaptcha/42

Your patch never work on my server with PHP 7.4 and I cannot test with PHP 7.3

If PHP 7.4 is supported than this issue may be closed and I will as soon I understand why you send to me an update that doesn't work on my server and also you are asking to downgrade PHP.

I cannot downgrade composer to version 1 so simply I will be unable to use everything you asking for composer 1

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
If you don't want to downgrade the composer that kindly waits until the composer 2 version supports uvdesk, and follow this issue for further update https://github.com/uvdesk/community-skeleton/issues/355

You may close this issue for now.

**Comment by PeopleInside** [comment]
@vaishaliwebkul I will close but still scared of not being able to update UVdesk if you send an update or the patch you give in the forum never work for me, no way to update my instance. Will see if I will get replies there. Thanks for the help.
