### ISSUE TITLE
Password managment issue

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#378]
This issue is about the new developed version of UVdesk that need in future be released.
You made change on password requirement as for the issue https://github.com/uvdesk/community-skeleton/issues/356 but I think you create new issues.

Now is really hard get password accepted.
![password bad experience](https://user-images.githubusercontent.com/5006150/111923821-54159380-8aa1-11eb-82fd-472b406f256b.jpg)

Why password must have at max 8 characters?
8 should be the minimum not the max value for password.

I tried password that has 8 characters, one capital and one not capital letter, a number and a special characters but your system never accepted the password.

For more information you can check the ticket ticket: #25126 that is currently opened and reports issues with the new UVdesk version that should be released in the not to long future.

In the ticket I also suggest to implement a password indicator that will help the user to understand what is wrong in the password, for example like there: https://www.my1login.com/resources/password-strength-test/

I don't wanna stress you just help to not do a patch that maybe increase the password security but create very big stress to users.
L imitating password to 8 characters is not good on my point of view.

8 should me the minimum characters for a good password not the max limit.
If 8 is the max characters for password how much is the minimum, 3/ 4? Very week password with less than 8 characters.
You can also decide to not develop something like https://www.my1login.com/resources/password-strength-test/ is just a suggestion. Maybe you can resolve by allowing more characters and require minimum 8 characters.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have updated validation for minimum 8 characters.
Also we have testing different pattern and its working.

**Comment by PeopleInside** [comment]
@papnoisanjeev thank you.
Now I'm just unable to update seems because incompatibility with composer.
In the ticket you told me I need place recaptcha but I don't see any recaptcha in vendor folder.

I'm unable to update UVdesk as seems is needed composer... and you don't support composer 2
No way to have updated UVdesk without composer?
The zip file you give to me in the community never work.
