### ISSUE TITLE
missing strings translation in polish language

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#381]
# Bug report

### Title
Here are almost all the links attached that needs to be translated into the polish language

### Preconditions

    1. framework Version- master

### Actual result

https://prnt.sc/10t6idk category translation is missing
https://prnt.sc/10t6j35 folder translation is missing
https://prnt.sc/10t6jx3 folder translation is missing
https://prnt.sc/10t6q2l explore apps not converted
https://prnt.sc/10t6qrj under explore apps
https://prnt.sc/10t6ro7 articles issues
https://prnt.sc/10t6s8l new article
https://prnt.sc/10t6sws category issue
https://prnt.sc/10t6tyl folder issue
https://prnt.sc/10t6ur6 Dashbaord issue
https://prnt.sc/10t6veu Dashboard Issue
https://prnt.sc/10t6w4f Agent
https://prnt.sc/10t6wpv Customers
Rest all are not converted

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

 Updated the PL translation file [here ](https://github.com/uvdesk/community-skeleton/commit/8afd6ac2df386cc4bbb632d2ccad484ea77e9129). Please verify if still something is missing.

**Comment by vaishaliwebkul** [comment]
fixed now https://prnt.sc/10wt5dr
