### ISSUE TITLE
Improve new user experience: install and setup

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#382]
There are two big issue (on my point of view) for new users to install and setup UVdesk.
This two issue that I'm to illustrate are showed here #369

## **1. Suggestion: Wizard should set correctly site_url without user have to edit the server file**

When user run the Wizard the setup process should take care of compile correctly the domain in /uvdesk/config/packages/**uvdesk.yaml**

I mean can you compile in some way site_url: during the install wizard process without the user has to guess where put hands and the correct strings to put here?

This is the fist suggestion I give.

## 2. Changing email settings should not need an SSH command

The second one is an issue that will be better and nice if you can resolve.
If user try to change, in email settings the address support@localhost this is not changed. User need SSH command php bin/console c:c

You should avoid this and find a solution to make working the operator interface without need to do an SSH command to save correctly a settings. If this is not saved correctly user will probably get Mailbox for email not found while try to fetching tickets.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Now when saving email setting it will automatically set **site_url**
