### ISSUE TITLE
Upcoming version should be updated on web installer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#385]
# Bug report

### Title
Upcoming version should be updated on web installer

### Preconditions

    1. framework Version- master

### Expected result

when update with the master branch, getting old version in web installer

### Actual result

![Screenshot_330](https://user-images.githubusercontent.com/43210406/112724710-a5f36900-8f3a-11eb-8512-ff8f5c957053.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated on [latest release](https://github.com/uvdesk/community-skeleton/releases/tag/v1.0.13
) **(1.0.13)** you can verify.
