### ISSUE TITLE
Cannot statically assign Agent's Password

### ISSUE THREAD

**Issue by aconite33** [uvdesk/community-skeleton#386]
# Bug report

### Cannot statically assign Agent's Password

When creating a new Agent, an Admin is unable to set the initial password

### Issue Description

When standing up a new instance of UVDesk, an admin account can create an Agent, assign the agent's name, email, icon, etc, but cannot set an initial password for the agent user.

### Preconditions

I am using release 1.0.12, using the docker instance found here: https://github.com/schlepper-code/uvdesk-docker

### Steps to reproduce

1) Setup a new instance of UVDesk
2) Log in with the initial Admin User
3) Create an Agent User
4) Verify you cannot set the initial password of the Agent

Creating a new Agent

![image](https://user-images.githubusercontent.com/3675886/112984873-7062a180-912d-11eb-851a-2bc074f0e00e.png)

Modifying an existing Agent

![image](https://user-images.githubusercontent.com/3675886/112985018-a142d680-912d-11eb-8ba4-a66b2f21429f.png)

### Expected result

Should be able to set the password of an Agent when first creating the user

### Actual result

Agent user is created, but unable to set a password.

**Comment by papnoisanjeev** [comment]
@aconite33 

You need to setup your **Swift mailer** (responsible for sending email) first.
Once your email sending work start working then you should add a **agent**.
Hope [this ](https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/) blog will help.


Here when you will add a **agent** into UVdesk then agent will receive an email for the same with **password setup link**.
Once agent done with password setup using that link will be able to login into uvdesk.

**Comment by papnoisanjeev** [comment]
@aconite33 

You can achieve this by simply doing some changes on your project.
Normally option is not provided to **admin** to setup password to other users.

 

**For enabling option to update or add password for Agents by Admin:**

Locate path in your project:

**vendor/uvdesk/core-framework/Resources/views/Agent/updateSupportAgent.html.twig**

Open this file reach to [this ](https://github.com/uvdesk/core-framework/blob/master/Resources/views/Agents/updateSupportAgent.html.twig#L142-L160) section and **updateSupportAgent.html.twig** make changes in this file.

And replace:

{% if userDetails and userDetails.isVerified %}

BY

{% if user_service.isAccessAuthorized('ROLE_ADMIN') %}

 


**For enabling option to update or add password for Customer by Admin:**

locate path in your project:

**vendor/uvdesk/core-framework/Resources/views/Customers/updateSupportCustomer.html.twig**

 

Open [this ](https://github.com/uvdesk/core-framework/blob/master/Resources/views/Customers/updateSupportCustomer.html.twig#L82-L100 ) file reach to this section.
**updateSupportCustomer.html.twig** make changes in this file.

And replace :

{% if userDetails and userDetails.isVerified %}

BY

{% if user_service.isAccessAuthorized('ROLE_ADMIN') %}

**Comment by papnoisanjeev** [comment]
@aconite33 

Hope you made it working using given solution above.
We are closing it for now you can reopen it again if you are unable to do so .
