### ISSUE TITLE
Sentence correction on installation

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#387]
# Bug report
![Screenshot_342](https://user-images.githubusercontent.com/43210406/113293728-c1cc8580-9313-11eb-854c-fac11f28300a.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here](https://github.com/uvdesk/community-skeleton/commit/4b5b67f77d6e2115c5191cee4a5ce34eed17484c).
