### ISSUE TITLE
Error on line 88 in RefreshMailboxCommand.php (Warning: imap_open(): Couldn't open stream) fixed by making changes to RefreshMailboxCommand.php

### ISSUE THREAD

**Issue by AlldoGroup** [uvdesk/community-skeleton#390]
I'm trying the latest version installed with composer on a system with PHP 7.4.16.
Everything seems to be working except one thing.

No matter what I try, I always getting:

```
Warning: imap_open(): Couldn't open stream

PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: Can't open mailbox my.mailServerExample.com:143: no such mailbox (errflg=2) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError()
#1 {main}
thrown in Unknown on line 0
```

The solution was to "hard code" the imap mail server information directly into RefreshMailboxCommand.php and comment out line 88, like in the following image, and voila, everything works!!

![uvd](https://user-images.githubusercontent.com/57530884/115527741-a1984280-a291-11eb-8dd2-176bb3060f05.jpg)

**Comment by papnoisanjeev** [comment]
@AlldoGroup 

Have you checked all input coming there like  **$server_host**, **$server_username**, **$server_password**

You can print each input by like:
dump($server_host); die;

**Comment by AlldoGroup** [comment]
Thanks for your reply,

When adding `dump($server_host); die;` to the function `refreshMailbox()`, this is what is shown on the screen (the host name only):

![uvdesk](https://user-images.githubusercontent.com/57530884/115722578-6c6a1e00-a37f-11eb-85ac-b80153aee13e.jpg)

**Comment by papnoisanjeev** [comment]
@AlldoGroup 

If all inputs are correct then it should work as same as you have passed by hard code.

**Comment by papnoisanjeev** [comment]
@AlldoGroup 

We are closing this issue.
If you still facing the the same issue you can reply us on same thread.
