### ISSUE TITLE
Broadcast Message: issues

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#393]
If the message is long get error 500
Cannot also insert a button or a link. I need inform the ticket is not working due to a server issue than want provide a link with more info. I can't because HTML are not supported and if the text is long get error 500 and there is no possibility to add a button that open a link.

- Please fix the error 500 for Broadcast Message if is long text
- Add the possibility to insert a more info button with a link or allow html

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/115974375-93317b80-a55c-11eb-89ae-8e6e538dbf87.jpg)

Stable Release v1.0.13

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Make [these ](https://github.com/uvdesk/support-center-bundle/commit/adcd4a7df5914f15c221837f90c4d037a96359b0) changes in respective files.

Run below command after:
**php bin/console d:s:u --force**

And make a test again.

**Comment by PeopleInside** [comment]
@papnoisanjeev thank you!
I tested with the following message after following your instructions:

Prova di un messaggio abbastanza lungo che avvisa in caso di anomalie di sistema. Test about a long message than can alert in case of any service issue. This is just a test. Si tratta solo di un test!

This message is OK, never generate errors.
If I wrote some more long text I still get error 500.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/116067275-4c8d6f80-a689-11eb-9f31-3753d81b3182.jpg)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have changes the **field type** and it is sufficient for broadcast we will add a limitation for max charter length for broadcast message.

**Comment by PeopleInside** [comment]
OK, you should avoid the 500 error.

In those days I had a server issue, openssl certificate expired so all PHP email by SMTP was broken.
My intent was to insert a broadcast message in Italian, English and a link to the relative article in Knowledgebase but due to characters limitation get error 500 and maybe in the future will get max characters error because long like take space.

Don't know if in the future the broadcast message can have a more info button with a link field that never take characters space from the broadcast message. 

Actually seems is not possible link more info in the broadcast message.
Thank you!

**Comment by papnoisanjeev** [comment]
@PeopleInside 

>My intent was to insert a broadcast message in Italian, English and a link to the relative article in Knowledgebase but due to characters limitation get error 500 and maybe in the future will get max characters error because long like take space.
Don't know if in the future the broadcast message can have a more info button with a link field that never take characters space from the broadcast message.

Also for your concern we are adding a new feature which is **marketing announcement**  which will show your announcement to your customer based on customer ticket group.

https://tinyurl.com/yf8zx2xy
https://prnt.sc/1239xpy

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> > My intent was to insert a broadcast message in Italian, English and a link to the relative article in Knowledgebase but due to characters limitation get error 500 and maybe in the future will get max characters error because long like take space.
> > Don't know if in the future the broadcast message can have a more info button with a link field that never take characters space from the broadcast message.
> 
> Also for your concern we are adding a new feature which is **marketing announcement** which will show your announcement to your customer based on customer ticket group.
> 
> https://tinyurl.com/yf8zx2xy
> https://prnt.sc/1239xpy

Umh at the moment I don't know how this work.. I'm not into business so maybe is a function that will be not useful for me but looks good in other cases. Don't know if this will allow to set a banner for anyone on the front help desk for inform about maybe a server issue for example or something important with a button and a link opened.

Thank you anyway, feel free to close this issue when you think is resolved.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Added validation of 350 for broadcast as well [here](https://github.com/uvdesk/support-center-bundle/commit/79440b4048ea75b6d30441138192883fc6f64b13).

**Comment by PeopleInside** [comment]
Test if works, because I still get 500 error.
Thanks anyway

**Comment by PeopleInside** [comment]
@papnoisanjeev your fix is wrong, I cannot propose edit on the file you edited because I have no access on that brunch.
I do the correction that works here: https://github.com/uvdesk/support-center-bundle/pull/129

**Comment by papnoisanjeev** [comment]
@PeopleInside 
As it was ok from our side.
But still update it [here ](https://github.com/uvdesk/support-center-bundle/commit/4bdf5d75f1b0614f91af6cc65094f4c5f1433000)it is working for you !!
