### ISSUE TITLE
@revsie

### ISSUE THREAD

**Issue by pepisito** [uvdesk/community-skeleton#396]
@revsie 
 
The error generally occurs when your database not migrated properly.

Do below steps to do it manually.

1. open **.env** file of project and put your database detail here.

![image](https://user-images.githubusercontent.com/42460055/87955531-82cf0a80-cacb-11ea-9b83-0ae9c32bdbd5.png)

2. Upload a fresh database directly into your database. database size can be large so may be it will not import directly to import it using command.

Please find database zip below.

If everything works well then login using below details:

Login URl:   **your_domain/en/member/login**   (Default URl)

username:  **admin@admin.com**
password:  **password**

Database Zip:  [4697481.zip](https://github.com/uvdesk/community-skeleton/files/4948629/4697481.zip)

Clear project cache by:
**php bin/console c:c**

_Originally posted by @papnoisanjeev in https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642_

**Comment by pepisito** [comment]
With the manual install, I still have to go through web installation and notice that I see that password requires one alternate character and number.  But, the seed db encoded with the default  "password".

Neverthless, it finally finished installation and when I trying to login, It throws recaptcha exception.  see below.

how to get around this?

HTTP 500 Internal Server Error
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id AS id_1, t0.site_key AS site_key_2, t0.secret_key AS secret_key_3, t0.is_active AS is_active_4 FROM recaptcha t0 WHERE t0.id = ? LIMIT 1' with params [1]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uvdesk.recaptcha' doesn't exist").

**Comment by pepisito** [comment]
![recaptcha_error_Screenshot from 2021-04-29 17-50-16](https://user-images.githubusercontent.com/63040151/116635867-bbcac400-a914-11eb-87df-d8ad9558545e.png)

**Comment by pepisito** [comment]
It looks like every link on the initial page generates an exception; "contact us", "sign in".

**Comment by pepisito** [comment]
![init_Screenshot from 2021-04-29 18-05-07](https://user-images.githubusercontent.com/63040151/116636278-c89be780-a915-11eb-82fd-8840257b63c3.png)

**Comment by papnoisanjeev** [comment]
@pepisito 

Run below command as database is not up-to-date in comment.
Navigate to your project directory from your CMD and run below command:

**php bin/console d:s:u --force**

**Comment by papnoisanjeev** [comment]
@pepisito 

We have updated database zip also in the same comment.

we are closing this issue for now if you are still facing the issue then you can reply us back on the same thread.
