### ISSUE TITLE
Redirect users to login page after email validation

### ISSUE THREAD

**Issue by akhileshkcoder** [uvdesk/community-skeleton#405]
In UVdesk when an agent is created, an email is sent to the agent's email account with a link where he can create his password. Now after the password is submitted the user is redirected to the front end website of UVdesk. But I want the user to be redirected to the login page after setting his password. Is it possible to achieve this? Please help.

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

As the link is common for both (agent and customer) by for setting up the password but you can edit the email template for the both and can add information for login URL in Email Template.

Check this: https://tinyurl.com/yk2q68ex

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

I hope above solution will help you !
Closing this issue if you are not able to do so you can reply on same thread.

**Comment by akhileshkcoder** [comment]
@papnoisanjeev Thank you for the help. I was able to do it with the help of .htaccess file.

`RewriteEngine On
 RewriteRule ^en/$ /tickets/en/member/login [R,L]`

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

It is not the **correct URl** don't know how is it working for you !
Also always keep in mind for customer login page that should should also working after any change.

**Comment by akhileshkcoder** [comment]
@papnoisanjeev  Yes. I am using it along with Laravel. So I have changed the URI a bit.
