### ISSUE TITLE
Is there a way I could hid the menu links and dashboard links.

### ISSUE THREAD

**Issue by akhileshkcoder** [uvdesk/community-skeleton#406]
I know we can set the privileges for the Agent and hide the items for the Agent role. But I want the items to be hidden for the Administrator role as well. Is there a way I could do it through the code? I want to hide the Apps menu link.

![image](https://user-images.githubusercontent.com/62323833/118448629-dd4aee80-b70f-11eb-9966-5fa791b3e089.png)

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

No, Admin and super admin can see everything in helpdesk.
You can not currently restrict only apps part for this as admin and for this many part of project flow need to update.

**Comment by akhileshkcoder** [comment]
Okay. Thank you. I just edited the core files uvdesk-community\vendor\uvdesk\core-framework\Dashboard\Dashboard.php and  uvdesk-community\vendor\uvdesk\core-framework\Dashboard\NavigationTemplate.php and removed the links from menu and dashboard.

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 
Ok, But you will not able to see from super admin or some other agents if you will remove links from there.

**Comment by ricoarliyanto** [comment]
> Okay. Thank you. I just edited the core files uvdesk-community\vendor\uvdesk\core-framework\Dashboard\Dashboard.php and uvdesk-community\vendor\uvdesk\core-framework\Dashboard\NavigationTemplate.php and removed the links from menu and dashboard.

can you give me the source code of the files that you edited?
or give me advice abaout it sir

**Comment by adversinc** [comment]
For everyone who get here to remove Apps (and Workflows):

1. Open vendor/uvdesk/extension-framework/UIComponents/Dashboard/Homepage/Items/ExploreApps.php
2. Add the following method to the class:

```
    public static function getRoles() : array
    {
        return ['ROLE_SUPER_ADMIN'];
    }
```
