### ISSUE TITLE
Ticket forwarding option forward the entire thread

### ISSUE THREAD

**Issue by akhileshkcoder** [uvdesk/community-skeleton#407]
Currently, UVdesk has the option to forward a reply to an agent. Now it's sending only what is written in the reply box. But my requirement is to send the entire thread along with the reply to an agent. How can I achieve this? Is it possible to do it by editing the core files?

![image](https://user-images.githubusercontent.com/62323833/118759290-583a1380-b88e-11eb-859c-d768aafa23d8.png)

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

Nothing is impossible you can do updates for the same in core files until or unless it is not affecting any other functionality, If it is your requirement then you can try to collect all threads of that ticket and collect under Forward tab And can proceed.

**Comment by akhileshkcoder** [comment]
@papnoisanjeev Okay. Thank you.
