### ISSUE TITLE
Emails not retrieving

### ISSUE THREAD

**Issue by iLoveSarabear** [uvdesk/community-skeleton#409]
Hi, I'm having an issue converting emails into tickets see below:
![image](https://user-images.githubusercontent.com/9739139/120077944-2a14ba80-c06a-11eb-9ab1-5dd3a9af1fe6.png)

Running: `php bin/console uvdesk:refresh-mailbox email@email.com`
Ubuntu 20.04
UVdesk | V -1.0.13

**Comment by papnoisanjeev** [comment]
@iLoveSarabear 

Please check if **php_curl** extension enabled in your system or not.
Hope it will help: [Check here](https://www.geeksforgeeks.org/how-to-enable-curl-in-php/).

**Comment by iLoveSarabear** [comment]
Hi, you were correct. I needed the php_curl extension installed. However, it's not parsing the emails into tickets.

It's showing as success, but we're not seeing any actual updates to tickets, nor are we seeing any new tickets created.

![image](https://user-images.githubusercontent.com/9739139/120420526-bc92b380-c321-11eb-91b2-5c4d1ad9fc85.png)
