### ISSUE TITLE
vulnerability issue at tags fields

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#41]
please check all the input fields as i have store the script in tag of the article section
which cause the issue
![screenshot 9](https://user-images.githubusercontent.com/43210406/50085352-cb538180-021f-11e9-8e33-78ac133c64e2.png)

**Comment by papnoisanjeev** [comment]
Fixed.

**Comment by vaishaliwebkul** [comment]
as i checked again, found the same stored xss script is run
![screenshot from 2018-12-18 14-05-35](https://user-images.githubusercontent.com/43210406/50141689-2479ee80-02ce-11e9-9dc7-86058fd327d8.png)

**Comment by papnoisanjeev** [comment]
Please check after clearing composer cache.
