### ISSUE TITLE
Unable to create super user during installation

### ISSUE THREAD

**Issue by Raveendiran-RR** [uvdesk/community-skeleton#410]
# Bug report

### Title
Unable to create super user during installation

### Issue Description
Unable to create super user during installation

### Preconditions
Docker container image and container created as per the instructions provided in the repo

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**
Error while installation
Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.description AS description_3 FROM uv_support_role t0 WHERE t0.code = ? LIMIT 1' with params ["ROLE_SUPER_ADMIN"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticketdb.uv_support_role' doesn't exist" at /var/www/uvdesk/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 61
--

![image](https://user-images.githubusercontent.com/46484439/120100269-8b698600-c15d-11eb-90ac-0909ff032417.png)

### Actual result
The wizard works fine until the super admin user creation. During installation, it fails before completing the 3rd phas

**Comment by Raveendiran-RR** [comment]
Steps to reproduce
1. Create docker image and run the it as mentioned in the documentation
2. Tried with available port as 80 and 3306 separately
3. Browse http://localhost:{port#}
4. The check list gave error that the max_execution_timeout needs to be increased to 300
5. To do so, login to terminal of the container
6. type the command add-apt-repo multiverse
7. type command apt update
8. install vim by typing the command apt-get install vim
9. Using vim open the file /etc/php/7.2/apache2/php.ini
10. Edit line # 380 max_execution-timeout = 300
11. restart the container
12. Now it let's you proceed to the next step Click on Proceed- DB details (provide them as mentioned in the run command while creating the container
13. Check the checkbox Create new container if not present
14. Click on proceed
15. Provide details for super admin
16. click proceed.

That's when the above error shows up

**Comment by vaishaliwebkul** [comment]
Hi @Raveendiran-RR 
Thanks for notifying this, we will check with all the steps followed by you and get back to you.
Meanwhile, if you got any issues then you may also [contribute](https://github.com/uvdesk/community-skeleton#contributions) on UVDesk to help community.

**Comment by vipin-shrivastava** [comment]
@Raveendiran-RR 

As I checked, I didn't found any issue creating a superuser when installing UVDesk.

Please check it again, If you still get this issue please let me know.

**Comment by papnoisanjeev** [comment]
@Raveendiran-RR 

We have not get any reply from your side we are closing this as we have not found this issue.
you can still reply on same thread.
