### ISSUE TITLE
i have installed uvdesk open source and i have configured mailbox, email settings and swift mailer but the customer is not able to receive a mail when replied to a ticket ?

### ISSUE THREAD

**Issue by vineetha1089** [uvdesk/community-skeleton#412]

**Comment by vaishaliwebkul** [comment]
@vineetha1089 

- [ ] From which source you reply to the customer using email or support panel??
- [ ] Let me know if account creation mail or forgot password mail are received by the customer?

**Comment by vineetha1089** [comment]
@vaishaliwebkul mam.
1. I reply to customer by clicking on the ticket raised,type the content and select reply. So I guess it is by email.
2.Customer did not receive any creation or forgot password mail .

**Comment by papnoisanjeev** [comment]
@vineetha1089 

 Have you setup your **swiftmailer** (responsible for sending emails in uvdesk) ?

**Comment by papnoisanjeev** [comment]
@vineetha1089 

You have not correctly setup swiftmailer for gmail.

Please edit your **swiftmailer** setting and select **transport** type **gmail**.

Check this: https://tinyurl.com/yywwgh2o

And save it and then make a try.

**Comment by papnoisanjeev** [comment]
@vineetha1089 

You have not correctly setup swiftmailer for gmail.

Please edit your **swiftmailer** setting and select **transport** type **gmail**.

Check this: https://tinyurl.com/yywwgh2o

And save it and then make a try.

**Comment by vineetha1089** [comment]
@papnoisanjeev  ji. after changing to gmail also mail is not delivered.
swiftmailer:
    default_mailer: mailer_5807
    mailers:
        mailer_5807:
            transport: gmail
            username: uvdesk.icf@gmail.com
            password: uvdesk123
            # sender_address: ~
            # delivery_addresses: ~
            disable_delivery: false

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

As I checked with this credential, it is working fine. customer is getting mail when admin or agent reply on ticket.
**username**: uvdesk.icf@gmail.com
**password:** uvdesk123

![Screenshot_9](https://user-images.githubusercontent.com/58874186/120456763-89990000-c3b3-11eb-878f-76a31c1323b5.png)
![Screenshot_8](https://user-images.githubusercontent.com/58874186/120456838-99184900-c3b3-11eb-964c-671d391f0a34.png)

**Comment by vineetha1089** [comment]
@vipin-shrivastava ji. sorry to ask am bit new. where should i check if the mail is delivered to the customer ( in gmail account ?right) .

**Comment by vipin-shrivastava** [comment]
@vineetha1089

Yes ! you can check it into customer gmail account.

**Comment by vineetha1089** [comment]
@vipin . i have not received any mail . when i click on the ticket and when submit button is clicked.

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

I already check & setup with your gmail credentials & It is working fine.
you can run "php bin/console c:c" to clear the cache.

**Comment by vineetha1089** [comment]
@vipin how to i run this command in windows

**Comment by vineetha1089** [comment]
![image](https://user-images.githubusercontent.com/84970726/120473030-37140f80-c3c4-11eb-884a-d0c46f36ca33.png)

**Comment by vineetha1089** [comment]
@vipin . this the where i type  content and reply. fromhere it does not send any mail to customer ?. kindy help.
![uvdesk](https://user-images.githubusercontent.com/84970726/120474106-670fe280-c3c5-11eb-95af-bb161f9144c9.png)

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

after reply it will automatically send a mail to a customer.
If you still facing issue create a ticket with "servicewebkul@gmail.com".

**Comment by papnoisanjeev** [comment]
@vineetha1089 

Is this fixed for you !!
We are closing the issue if issue still exist you can reply on same thread.

**Comment by vineetha1089** [comment]
My issue is not rectified yet sir. I facing the same issue .

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

Can you please create a ticket with "servicewebkul@gmail.com" email so that we can check .

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

Please set your **site_url** in **uvdesk.yaml** file correctly .
site_url: **_'localhost:8000\uvdesk\public'_**.
site_url: **'localhost\uvdesk\public'**.

**Comment by vineetha1089** [comment]
@vipin-shrivastava . After changing the site_url also customer not able to receive mail 

parameters:
    app_locales: en|fr|it
    
    # Default Assets
    assets_default_agent_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png'
    assets_default_customer_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png'
    assets_default_helpdesk_profile_image_path: 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png'

    uvdesk_site_path.member_prefix: member
    uvdesk_site_path.knowledgebase_customer_prefix: customer
    
    # File uploads constraints
    # @TODO: Set these parameters via compilers
    max_post_size: 8388608
    max_file_uploads: 20
    upload_max_filesize: 2097152

uvdesk:
    site_url: 'localhost\uvdesk\public'
    upload_manager:
        id: Webkul\UVDesk\CoreFrameworkBundle\FileSystem\UploadManagers\Localhost
    
    support_email:
        id: uvdesk.icf@gmail.com
        name: UVDesk Community
        mailer_id: mailer_5807
    
    # Default resources
    default:
        ticket:
            type: support
            status: open
            priority: low
        templates:
            email: mail.html.twig

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

After changing the Site_url . had you runed the **SSH command "PHP bin/console c:c**" & also **refresh** the browser .

If not please do that, sometimes after update the **site_url** or ** updates in code** is not **reflected** because of **cache**.

**Comment by vineetha1089** [comment]
%{global.companyLogo}% image is not displayed in the mail sent to customer. ?

**Comment by vipin-shrivastava** [comment]
@vineetha1089 
Is UVdesk installed on your localhost server?

**Comment by vineetha1089** [comment]
@vipin-shrivastava . Yes sir I have installed the uvdesk open source

**Comment by vipin-shrivastava** [comment]
@vineetha1089 

The link of the image which attached in the email of your localhost server =>"localhost/xyz/src/raw.jpg" . 
it's your localhost server how your email server know that which email are you requesting ?

**Comment by vineetha1089** [comment]
Ticket creation email

**Comment by vineetha1089** [comment]
Can I manage the ticket status submit (I need only 1st tw
Three options like open , pending and close)option when I click on the repy button.  Can I manage in code?

**Comment by papnoisanjeev** [comment]
@vineetha1089 

Yes, Obviously you can hide or comment other options if don't need for other option.
