### ISSUE TITLE
remove debugger from the installation wizard 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#415]
# Bug report

https://github.com/uvdesk/community-skeleton/blob/master/public/scripts/wizard.js#L779

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Removed it from [here](https://github.com/uvdesk/community-skeleton/commit/bd843c36655e0e66288ffdd4f6f0e03a07d3b43e).
