### ISSUE TITLE
Potential Security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [uvdesk/community-skeleton#417]
Hi, @akshaywebkul @papnoisanjeev  @piyushwebkul @shubhwebkul 

Few security vulnerability has been submitted through huntr .
Plz validate them 
https://huntr.dev/bounties/1-uvdesk/community-skeleton/
https://huntr.dev/bounties/2-uvdesk/community-skeleton/
https://huntr.dev/bounties/3-uvdesk/community-skeleton/
https://huntr.dev/bounties/4-uvdesk/community-skeleton/
https://huntr.dev/bounties/5-uvdesk/community-skeleton/
https://huntr.dev/bounties/6-uvdesk/community-skeleton/
Report is only visible to repo maintainer and reporter .

**Comment by PeopleInside** [comment]
Thank you for report this, I really hope the UVdesk team can fix asap with emergency priority and give immediately instruction to fix and update UVdesk.

Is nice to see someone care about security of the product, thanks again!

**Comment by papnoisanjeev** [comment]
@PeopleInside 

The issue reported here is not open and asking for our account access if we are checking it which is not acceptable for us to provide account access to them.

@ranjit-git  can report all issue @  support@uvdesk.com if do not want to public security issues here.

**Comment by ranjit-git** [comment]
@papnoisanjeev  
Report details  can be seen by only repo-maintainer for  security reason . If you are the maintainer then login to huntr with your GitHub account and you can see details and validate them.
Other user cant see report  details if he is not a repo-maintainer

**Comment by ranjit-git** [comment]
If you are not interested to signup there then I can send you all report over above security mail.
Pls let me know what you prefer

**Comment by papnoisanjeev** [comment]
@ranjit-git 
>Report details can be seen by only repo-maintainer for security reason.

Yes, I do have maintainer access for the project but can't provide account access.

Please send security mail on support@uvdesk.com we will check.

**Comment by ranjit-git** [comment]
@papnoisanjeev 
i just sent all report to support@uvdesk.com .

**Comment by PeopleInside** [comment]
Thank you @ranjit-git
@papnoisanjeev I will monitor the progression of the fix in this week, I hope to be able to fix security issues asap  😉

**Comment by ranjit-git** [comment]
Hi @PeopleInside @papnoisanjeev , there are still 3 bug need to fix

**Comment by PeopleInside** [comment]
@ranjit-git I know and I wrote to the UVdesk team in private some days or week ago.

Seems they are busy with some other work and I try to explain that a security vulnerability should be at the first position of the priority because this mean every self-hosted server install can be vulnerable and make server vulnerable.

I really hope this security issue will never stay opened for months.

**Comment by jitendra-webkul** [comment]
@papnoisanjeev please fix this issue as soon as possible.

**Comment by papnoisanjeev** [comment]
@PeopleInside @ranjit-git 

We have fixed 3 issues out of 6 here and working on other.
@Sanjaybhattwebkul working on security issues and will update once done.

**Comment by Sanjaybhattwebkul** [comment]
Bug  :  unprivileges user can see all ticket details

Huntr report
===========
https://huntr.dev/bounties/3-uvdesk/community-skeleton/
Fixed :: https://github.com/uvdesk/core-framework/commit/198077e0ea93e2221a6e070cca78fcc4881917e4

2 . Bug : unprivileges user can see all ticket details
      => Hunter report 
      -> https://huntr.dev/bounties/3-uvdesk/community-skeleton/?token=dab8c53273ad48a1e375fa640c30ca88df111d19d964b6e707bc06a23a6a7f64fc6663b9d9b06ea628a2aee1125f8c0dc2e9c8d6f9b1e0da8c8960a4f21e738d264d5667624ff06d55100842837b4006951d8a128d8f8781a0a4d1944837f4b61988a78974867685174ed8626c62d6fbd35509362295f04379fb102490676a492b292ba0c0
  => Fixed ::  already fixed

3 . Bug : Stored xss 
      =>Hunter Report  :  https://huntr.dev/bounties/6-uvdesk/community-skeleton/
      =>Fixed ::  
                https://github.com/uvdesk/support-center-bundle/blob/master/Controller/Article.php#L213-L217
4. Bug : Store xss
        => Hunter Report :  https://huntr.dev/bounties/6-uvdesk/community-skeleton/?token=dab8c53273ad48a1e375fa640c30ca88df111d19d964b6e707bc06a23a6a7f64fc6663b9d9b06ea628a2aee1125f8c0dc2e9c8d6f9b1e0da8c8960a4f21e738d264d5667624ff06d55100842837b4006951d8a128d8f8781a0a4d1944837f4b61988a78974867685174ed8626c62d6fbd35509362295f04379fb102490676a492b292ba0c0
        => Fixed :: already fixed

**Comment by ranjit-git** [comment]
@Sanjaybhattwebkul  
can you plz remove the magick link from your last comment , Those are private link
https://huntr.dev/bounties/3-uvdesk/community-skeleton/?token=dab8c53273ad48a1e375fa640c30ca88df111d19d964b6e707bc06a23a6a7f64fc6663b9d9b06ea628a2aee1125f8c0dc2e9c8d6f9b1e0da8c8960a4f21e738d264d5667624ff06d55100842837b4006951d8a128d8f8781a0a4d1944837f4b61988a78974867685174ed8626c62d6fbd35509362295f04379fb102490676a492b292ba0c0
https://huntr.dev/bounties/6-uvdesk/community-skeleton/?token=dab8c53273ad48a1e375fa640c30ca88df111d19d964b6e707bc06a23a6a7f64fc6663b9d9b06ea628a2aee1125f8c0dc2e9c8d6f9b1e0da8c8960a4f21e738d264d5667624ff06d55100842837b4006951d8a128d8f8781a0a4d1944837f4b61988a78974867685174ed8626c62d6fbd35509362295f04379fb102490676a492b292ba0c0

**Comment by Sanjaybhattwebkul** [comment]
**3 . Bug : privilege escalation bug to pin a threads** 

Fixed [here](https://github.com/uvdesk/core-framework/commit/1591db934af9e36f830834c0acddbc8d8528750e).

**4 . Bug : privilege escalation bug to update customer details**

Fixed [here](https://github.com/uvdesk/core-framework/commit/818754a4c48e658ebaeb7807b6e4c5bef36d4412).

**Comment by Sanjaybhattwebkul** [comment]
**1. Bug : privilege escalation bug to add collaborator to ticket**
  Fixed [hare](https://github.com/uvdesk/core-framework/commit/df69b3d7ca9a08a99c4ff65a3009240a135180a2).

**Comment by ranjit-git** [comment]
Hello, @Sanjaybhattwebkul  
If you having problem to reproduce any bug then pls comment into the provided report-link and I will assist you
Thanks

**Comment by ranjit-git** [comment]
@Sanjaybhattwebkul 
As 8 report is fixed ,can you plz mark them valid by going corresponding report url (magick link received in mail)?

**Comment by Sanjaybhattwebkul** [comment]
Hello , @ranjit-git  
 I marked all 8 report valid by  corresponding report url (magick link received in mail)

**Comment by ranjit-git** [comment]
@Sanjaybhattwebkul  thanks 
But you mistakenly mark this report invalid https://huntr.dev/bounties/3e695d80-b710-47aa-a66a-5affeb56abef

**Comment by Sanjaybhattwebkul** [comment]
@ranjit-git 
 I will update it as valid   soon

**Comment by Sanjaybhattwebkul** [comment]
@ranjit-git 
 i have mark  [this](https://huntr.dev/bounties/3e695d80-b710-47aa-a66a-5affeb56abef)  report as valid

**Comment by ranjit-git** [comment]
@Sanjaybhattwebkul   @papnoisanjeev 
Few other security vulnerability has been submitted to your other repo https://github.com/uvdesk/core-framework 
can you plz validate them?

**Comment by Sanjaybhattwebkul** [comment]
@ranjit-git 
Can you please tell me,  which security vulnerability you have been submitted in this [repo](https://github.com/uvdesk/core-framework).

**Comment by ranjit-git** [comment]
@Sanjaybhattwebkul 
https://huntr.dev/bounties/4bae2d4d-98ae-446d-aac8-44dcd3980b78/

**Comment by Sanjaybhattwebkul** [comment]
@ranjit-git  
 please provide me the open link .

**Comment by ranjit-git** [comment]
Email address where open link will be send?

**Comment by Sanjaybhattwebkul** [comment]
sanjay.bhatt371@webkul.com

**Comment by papnoisanjeev** [comment]
@ranjit-git 
We are closing this issue as all of the security issues mentioned here has been fixed.
If can open a new issue if found some more issues.
