### ISSUE TITLE
Stable Release v1.0.14, never show new version

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#418]
@papnoisanjeev I see you released today [version v1.0.14](https://github.com/uvdesk/community-skeleton/releases/tag/v1.0.14)

I updated with 

```
composer update uvdesk/core-framework

composer update uvdesk/support-center-bundle

composer update uvdesk/mailbox-component

composer update uvdesk/automation-bundle

composer update uvdesk/extension-framework
```

than i replaced the following file from my backup:

swiftmailer.yaml, uvdesk_mailbox.yaml, uvdesk.yaml translation.yaml (You will find these files under config->packages of your project).

services.yaml under config

I can see the new Marketing annuncment not trasnlated yet in Italian but the version showed on the footer is still be V -1.0.13

Can you please check if you forget to update that, if I can just fix with an edit or why I see the old version printed on footer?

Please when you are ready create an announcement on forum or I can do for you if you authorize.

**Comment by PeopleInside** [comment]
https://github.com/uvdesk/community-skeleton/issues/419

**Comment by papnoisanjeev** [comment]
@PeopleInside 
>I can see the new Marketing announcement not translated yet in Italian but the version showed on the footer is still be V -1.0.13

You can add words in Italian file if something is not translating for **Marketing announcement** we will also check it.

For version we skipped to update footer of dashboard to **v1.0.14** we will update it on project zip.
Also user can see latest release version from [changelog.md](https://github.com/uvdesk/community-skeleton/tree/v1.0.14) file.

**Comment by PeopleInside** [comment]
@papnoisanjeev I tried to run composer update and get fatal error.
I made screenshot but I have already deleted without report to you.

**Comment by PeopleInside** [comment]
`For version we skipped to update footer of dashboard to v1.0.14 we will update it on project zip.`

I need to see this fixed also on GitHub where composer take the update.

**Comment by vaishaliwebkul** [comment]
@PeopleInside @papnoisanjeev 
getting the same issue while updating older version to new version
![Screenshot_407](https://user-images.githubusercontent.com/43210406/122896543-c9c22180-d366-11eb-8f2c-23147ff6bf4f.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

What commands you have applied?
Run only "**composer update"** and it should work.

If still the same problem then remove vendor folder and again run   "**composer update"**.

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Also we have updated many packages version in this update and also added 1-2 more packages in [composer.json](https://github.com/uvdesk/community-skeleton/blob/master/composer.json) file to compatible with **composer 2** as well.

So first copy the [require ](https://github.com/uvdesk/community-skeleton/blob/master/composer.json#L6) section only from new composer.json file and replace with your old composer.json file require section.

Finally run **composer update**.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
can you update your composer.json with all updated [require](https://github.com/uvdesk/community-skeleton/blob/master/composer.json#L6) packages then just run the `composer update`, this will solve my issue.

**Comment by PeopleInside** [comment]
@vaishaliwebkul thanks, I was able to upgrade by doing the manual command at the top of this discussion, very fist message... however I resumed my backup due to some issue with the new version.

I'm waiting issue get fixed especially security issue present maybe not only on the new version but the previous too.
Once the security will be fixed and also the version showed in the footer, I will try to update again to the most recent version. 

This issue can be closed once I can see the fix in GitHub about how to fix wrong version on the footer.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

You can update version from [here](https://github.com/uvdesk/core-framework/blob/v1.0.14/Resources/views/dashboard.html.twig#L217)  we have updated this in [project official zip](https://www.uvdesk.com/en/opensource/).

**Comment by PeopleInside** [comment]
I still get error trying to update with composer update

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!   // Clearing the cache for the prod environment with debug
!!   // false
!!
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!
!!    The service "security.context_listener.0" has a dependency on a non-existen
!!    t service "Webkul\UVDesk\ApiBundle\Providers\ApiCredentials".
!!
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by papnoisanjeev** [comment]
@PeopleInside 

This issue was with version v1.0.12 with production.
Please delete your [composer.lock](https://github.com/uvdesk/community-skeleton/blob/master/composer.lock) file.

Now run **composer update** and make a try.

**Comment by PeopleInside** [comment]
```
Symfony operations: 1 recipe (11255ae1bdf29ad1424c61a5b768e88d)
  - Configuring phpunit/phpunit (>=9.3): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!   // Clearing the cache for the prod environment with debug
!!   // false
!!
!!  PHP Fatal error:  Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator) and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available in /home/piadm/public_html/helpdesk.peopleinside.it/uvdesk/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 33
!!  14:08:04 CRITICAL  [php] Fatal Compile Error: Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator) and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available ["exception" => Symfony\Component\Debug\Exception\FatalErrorException^ { …}]
!!
!!  In LazyLoadingValueHolderGenerator.php line 33:
!!
!!    Compile Error: Could not check compatibility between Symfony\Bridge\ProxyMa
!!    nager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(Reflect
!!    ionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator
!!    ) and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate
!!    (ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $cla
!!    ssGenerator), because class Zend\Code\Generator\ClassGenerator is not avail
!!    able
!!
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by PeopleInside** [comment]
@papnoisanjeev I will not use composer update, I will use every command on top of this post.
composer update never work for me - stop -

**Comment by papnoisanjeev** [comment]
@PeopleInside 

As you always updated the project with command on top of this post.
so your **composer.lock** and **composer.json** file never updated.

You just need to do two things before running composer update.
1. Remove **composer.lock** file from your project.(it will again generate with updated dependencies when you will **composer update** command).
2. Copy the [require ](https://github.com/uvdesk/community-skeleton/blob/master/composer.json#L6) section only from new composer.json file and replace with your old composer.json file require section and also remove [this line](https://github.com/uvdesk/community-skeleton/blob/v1.0.12/composer.json#L49) from **composer.json** (As it was in v1.0.12).

Finally run **composer update** and it should work.
and from next release also you just need to run composer update only without need to change anything.

**Comment by papnoisanjeev** [comment]
> I tried, doesn't work for me. Also the composer.json present on GitHub is set by dev as default when I suppose should be prod
> 
> ```
>   [Seld\JsonLint\ParsingException]
>   "./composer.json" does not contain valid JSON
>   Parse error on line 48:
>   ...ndle": "4.3.*",    },    "config": {
>   ---------------------^
>   Expected: 'STRING' - It appears you have an extra trailing comma
> ```

You have done mistake in syntax while copy paste.

>Also the composer.json present on GitHub is set by dev 

You are checking master branch and released branch tag.

Just copy whole content from [here](https://github.com/uvdesk/community-skeleton/blob/v1.0.14/composer.json) and replace with your project composer.json file.

**Comment by PeopleInside** [comment]
Hi @papnoisanjeev today I imported my existent UVdesk to Softacolous panel but Softacolous panel is show I'm using version 1.0.13 when I'm using version 1.0.14 so where I can fix this? I suppose somewhere in my install the version was not updated but I'm on 1.0.1
