### ISSUE TITLE
Unable to delete customer Stable Release v1.0.14

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#419]
When I try to delete a customer an error occur:
Error : Something went wrong, please try again later 

Stable Release v1.0.14
Apache
PHP 7.4

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Please check your console if there is some other issue on your server.

As we have checked we are able to do it so.

![CustomerList](https://user-images.githubusercontent.com/42460055/122662222-def45000-d1ae-11eb-867e-4cac25938d59.jpeg)

![AfterDelete](https://user-images.githubusercontent.com/42460055/122662224-e0be1380-d1ae-11eb-9735-59647c73e03a.jpeg)

**Comment by PeopleInside** [comment]
I removed the latest UVdesk version for now.
I opened a ticket by email, customer created than tried to delete customer and get error.

**Comment by PeopleInside** [comment]
The issue seems to be present only for customer created by an email ticket!

**Comment by PeopleInside** [comment]
I never tested but a fix has been released
https://github.com/uvdesk/core-framework/commit/442590fa5ba4e03c7b804a69cef361607e222406

Closing this.

**Comment by PeopleInside** [comment]
@papnoisanjeev this issue is not resolved. Have you tested the fix you done?

The edit you do has been done in a commented part of the code, how can this work?
I still get error when try to delete a customer that has been created from a ticket.

Please help me to resolve this.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Fix is currently in master branch not in release you need to add it manually in core-framework.

or

Delete your core-framework under **vender/uvdesk** and **clone** again using below command at the same place:

**git clone https://github.com/uvdesk/core-framework**

also other issues fixed in master branch will come into your project.

Finally run command:
**php bin/console d:s:u --force**

And everything should work as expected.

**Comment by PeopleInside** [comment]
Sorry but you told me what edit and I edited but the fix is not working. How can manually fix this without loose the customisation I done this afternoon after update to the latest stable version?

The following fix never work for me
https://github.com/uvdesk/core-framework/commit/442590fa5ba4e03c7b804a69cef361607e222406

Maybe because I need run the SSH command you given?

**Comment by PeopleInside** [comment]
Resolved with

**php bin/console d:s:u --force**

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Yes, Whenever there is any **update in entity file** or **adding a new entity** then it needs to push to database with below command:

**php bin/console d:s:u --force**
