### ISSUE TITLE
How will member login to their panel, if they are at knowledgebase??

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#42]
**Can a member login to the panel, from knowledgebase :** 
![screenshot 11](https://user-images.githubusercontent.com/43210406/50139119-b847bc80-02c6-11e9-826e-638d90057b84.png)

**Comment by papnoisanjeev** [comment]
No need to add a link for customer to login as agent from customer panel.

**Comment by akshaywebkul** [comment]
By design.
