### ISSUE TITLE
1.0.14 download issue.

### ISSUE THREAD

**Issue by GaneshKandu** [uvdesk/community-skeleton#421]
Hi,

I am trying to download latest stable version (1.0.14) but getting old version (1.0.13)
when downloading from [https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip)

**Comment by papnoisanjeev** [comment]
@GaneshKandu 

We have not updated zip on our [official site ](https://www.uvdesk.com/en/opensource/) till now we are working on it.
We will soon update zip there and will let you know here.

**Comment by papnoisanjeev** [comment]
@GaneshKandu 

We have update project zip now you can download using [link ]( https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip) or from our[ official site](https://www.uvdesk.com/en/opensource/).

**Comment by GaneshKandu** [comment]
> We have updated project zip now you can download using [link ](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip) or from our[ official site](https://www.uvdesk.com/en/opensource/).

Thanks !
