### ISSUE TITLE
Bad reCaptcha error in version Stable Release v1.0.14. How to reverse back?

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#424]
I upgraded UVdesk from v1.0.13 to v1.0.14

Now on ticket creation if the recaptcha is not well compiled an errors showed on top of the page instead near the filed captcha.
I really don't like this error because is not clear for who can have issue on understanding the language, where the issue is in the form.

Please how I can revert back to the old recaptcha error message showed under the recaptcha filed that was much more clear than now?

### **IS not an improvement** remove red error near field that are not compiled correctly in the ticket creation or in any form.

I don't understand about code but seems you edited the file support-center-bundle/Resources/views/Knowledgebase/ticket.html.twig 

https://github.com/uvdesk/support-center-bundle/commit/62519db4ffef482f307daddaa53117c5b8358bf3

From the code seems you add custom field check and if custom field is present you decide to show a different "bad" error on top instead of show an error near the field who is not correctly compiled.

This edit is not good if you never show in the page where the issue is.
Imagine a ticket creation that never show in red field email if email is not well compiled... will be a form more difficult to compile or will be more difficult for someone that are trying to open a ticket but his language is not supported or selected...

You removed the red error message that was near the ReCaptcha field so was more easy to understand why the ticket is not created and you moved this error on top of the page. If the user is not understanding the error or doesn't know what ReCaptcha mean, user will be not able to open ticket and will report ticket system are broken.

What other custom field will show error on top instead the better way to show error near the field that has errors?

I really need to remove this error from top and move again near the recaptcha, lease tell me how to do.
I looked in commits done but cannot understand nothing as there is no description of the changes.

Is much better have the recaptcha error like that:
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/123216836-3efa3780-d4ca-11eb-8f2b-42be17fc773e.jpg)

How can I return back to this in the latest stable version?
I suggest also to make this standard, i don't think is good show a different generic error on top just for custom field or for recpatcha. Custom field and recaptcha should show error near the field that has the issue, this is much more easy to understand instead of blocking the ticket creation with a generic error on top where if you cannot understand what the error message say, you will be not able to create a ticket.

**Comment by PeopleInside** [comment]
The bad message error on top made also user loose his attachments.
I really don't like this update about moving the recaptcha error on top, I think is a really wrong update.

I not only want revert back but really suggest you to revert back in the official project... was better before: more understandable and without loosing of attachment,

**Comment by vipin-shrivastava** [comment]
@PeopleInside 
Please take clone of **support-center-bundel** from [https://github.com/uvdesk/support-center-bundle](here) & then after run `php bin/console c:c`. 
Now, your mentioned issue should be resolved. if you found any issue please let me know.

**Comment by PeopleInside** [comment]
Done i cloned the support-center-bundle
`https://github.com/uvdesk/support-center-bundle`

on the uvdesk main root done the `php bin/console c:c`

reload page https://helpdesk.peopleinside.it/it/usr/create-ticket/

but still see the captcha error on top.

Issue not resolved.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/123297167-9d013c00-d517-11eb-8522-11e284de022d.jpg)

![SharedScreenshot2](https://user-images.githubusercontent.com/5006150/123297274-b99d7400-d517-11eb-8c6d-5b47f3554c99.jpg)

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

Please follow the below steps :

Update your support-center-bundel->controller->ticket.php file from here.
Update your support-center-bundle->Resources->views->Knowledgebase->ticket.html.twig file from here.
After successfully update these two files. Please run php bin/console c:c .
Now, your mention issue should resolve.
If you still facing this issue or any issue please let me know.

**Comment by PeopleInside** [comment]
Thanks, seems work now.
Will this be integrated in UVdesk or I have to patch every time?

This resolve also other issue https://github.com/uvdesk/community-skeleton/issues/420

Thank you!

**Comment by PeopleInside** [comment]
@vaishaliwebkul thank you very much for your precious help!
I'm happy thanks to the fix now... I was waiting for this, thank you!

**Comment by vipin-shrivastava** [comment]
@PeopleInside 
we have merged these patches in the master branch. Please check.

**Comment by PeopleInside** [comment]
Thank you @vipin-shrivastava :)
Can you help me to find the commits?

I'm looking for it but I cannot find
https://github.com/uvdesk/community-skeleton/commits/master

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

below are the commits link : 
https://github.com/uvdesk/support-center-bundle/commit/15e0291a677e1593297fe4834df8c77a1759964f
https://github.com/uvdesk/support-center-bundle/commit/818e3189c73cb10795a8c3d1ecd1e3023de94dbb

If you want any help . Please let me know .
