### ISSUE TITLE
"New" Tickets going to a customer for some reason

### ISSUE THREAD

**Issue by iLoveSarabear** [uvdesk/community-skeleton#425]
V -1.0.13

I don't know why UV Desk has "This" customer picked out, but every time a new ticket is created it sends a notification to this one specific customer.

- It's not labeled as an agent
- It's not assigned to any of these tickets
- **It's just notified** that a new ticket has been created.

I think it has something to do with WorkFlows. And that it doesn't know what agent to assign this to. (I don't want it assigned to any agent). 

![image](https://user-images.githubusercontent.com/9739139/123262765-7ad6d200-d4b5-11eb-932f-08209caca7ef.png)

**Comment by papnoisanjeev** [comment]
@iLoveSarabear 

If you don't want to send notification to customer about his ticket creation you can remove first action **"Mail to customer"**
Form here.

Also if you are as a admin or agent  creating a ticket on behalf of a customer from admin panel then you are "Response performing agent" that time and according to above action ticket will assign to you and you will receive notification for the same.

You can add or remove any actions from workflow and then things will work accordingly.

**Comment by iLoveSarabear** [comment]
That's not what's happening here.

- The customer is receiving his notification.
- A **random customer is receiving the agent notification**.

This is the problem.

**Comment by papnoisanjeev** [comment]
@iLoveSarabear 

Please check your workflow if you have made any changes for the same.

Also share screenshots for the same so that we can reproduce the same.

**Comment by iLoveSarabear** [comment]
I have made no changes to the workflow. There doesn't appear to be anyway that the application is referencing this one specific user. But it keeps notifying this one user about new tickets, and that's unacceptable.

### This is the email it's sending to this user:
![image](https://user-images.githubusercontent.com/9739139/123526966-c1d0ed00-d698-11eb-9147-2a0ada71ee8c.png)

### These are the settings for that email template:
![image](https://user-images.githubusercontent.com/9739139/123526979-d319f980-d698-11eb-87d2-4dbcb90f8c80.png)

### **This is the customer** it's sending the email above to:
![image](https://user-images.githubusercontent.com/9739139/123526992-f5137c00-d698-11eb-808b-6e9d353c24f9.png)

### This is the actual email that user receives: (He's not an agent)
![image](https://user-images.githubusercontent.com/9739139/123527032-47ed3380-d699-11eb-86fe-0ae23fc7ccfd.png)

### This is the workflow:
![image](https://user-images.githubusercontent.com/9739139/123527046-5f2c2100-d699-11eb-9c3f-00e913c0d133.png)

Who knows why it's treating this customer as an agent or if it's treating other customers as agents. Yikes!

**Comment by papnoisanjeev** [comment]
@iLoveSarabear 

As you can see working.

Most probably you are doing this sequence.

1. Creating ticket from admin panel on behalf of a customer.

2.  You can see second action in working   **Assign to agent => Response performing agent**, response performing means at that time who is performing that action.

3. Now in 3rd action you can see action **Mail to Agent => check select dropdown and you will see assigned agent** (means this time ticket will assign to someone who is generating the ticket and from 3rd action he will be able to receive email notification for the same).

You can select any other agent there of simply remove this action and agent will not able to receive notification for the same.

**Comment by papnoisanjeev** [comment]
@iLoveSarabear 

Hope your issue has been resolved.
If not please let us know.
We are closing this if still issue exist you can reply on same thread.
