### ISSUE TITLE
Using UVdesk v1.0.14 but there stands in my dashboard v1.0.13

### ISSUE THREAD

**Issue by ItsJustMyron** [uvdesk/community-skeleton#426]
Hey, I downloaded v1.0.14 but when i fully installed it there stands v1.0.13

And i have 1 question, when do you think custom fields is added in the community version

**Comment by Himaniwebkul** [comment]
@ItsJustMyron 
**Our bad :( We forgot to add a version in the footer. ==>** Hey, I downloaded v1.0.14 but when i fully installed it there stands v1.0.13

**We have just made the addon live on our store** - **https://store.webkul.com/uvdesk-open-source-custom-fields-app.html =>** And i have 1 question, when do you think custom fields is added in the community version

**Comment by ItsJustMyron** [comment]
Oi it is 99.00 i tought it will be a free addon

**Comment by papnoisanjeev** [comment]
@ItsJustMyron 

Apps part will be paid only.

All common features of helpdesk is absolutely free and we will add some more as well in upcoming release.
