### ISSUE TITLE
Customer: contact number is invalid

### ISSUE THREAD

**Issue by reeyon** [uvdesk/community-skeleton#427]
Hi There, 

When adding new customer, but unable to save changes due to Contact Number is invalid error. Please see screenshot below, is this known issue or how can I fix this?

![image](https://user-images.githubusercontent.com/3666089/124545525-c9904e80-de5b-11eb-9f5d-65d32b4c35c2.png)

**Comment by papnoisanjeev** [comment]
@reeyon 

Please enter 10 digit.

**Comment by vipin-shrivastava** [comment]
@reeyon 

It is showing the invalid contact because you entered only  8 digits number.
Solution :
Either you enter the ten digits contact number or else you can leave as empty.

**Comment by reeyon** [comment]
Thanks, input 10 digits worked.
