### ISSUE TITLE
Attachment and Logo Issue - Web Installer Public Folder Issue 

### ISSUE THREAD

**Issue by dungeonist** [uvdesk/community-skeleton#428]
# Bug report

### Title: 
Attachment and Logo Issue - Web Installer Public Folder Issue 

### Issue Description
Recently I started to use UVDesk and found a bug related with attachments and logo when it is installed using the web installer under certain circunstances. Any file uploaded in a ticket or even the logo uploaded in the branding appear in the website like if their links are broken.

The origin of the issue seems to be related about the default public directory used by UVDesk. In my case I am running UVdesk in a cpanel account where the public folder is named as "public_html", the website is running fine, but uploaded files are being uploaded to the default "public". This is what is causing the broken link for all files.

### Preconditions

    1. framework version 1.0.14

### Steps to reproduce

    1. Install uvdesk using the web installer in a server that use a different folder as their public folder, in my case I am using it in a cpanel account where the public directory is "public_html"
    2. Create a ticket and try to upload a file, the file will be uploaded, but after submitted the file will appear as a broken image/link.

### Expected result

*   Images should be displayed as images and not as broken link images.

### Actual result

>    Images are being displayed as broken link images.

**Comment by papnoisanjeev** [comment]
@dungeonist 

Please share screenshots for the same as currently there is no such issue.
Also mention steps you have done.

**Comment by dungeonist** [comment]
@papnoisanjeev 

Here is a screenshot:

![f2dd2b61-d649-4b92-93fc-2b950de77394](https://user-images.githubusercontent.com/5342341/125081596-925cb000-e09c-11eb-82fa-a944980efb86.png)

The same occur with for logo:

![63365680-3f26-4782-a726-d7595ea7ee05](https://user-images.githubusercontent.com/5342341/125081710-b0c2ab80-e09c-11eb-9956-f1c11058e1ab.png)

What is occuring is that uploaded file are being uploaded to "public" folder but the uvdesk was installed and is running in the "public_html".

As steps:
1. Uploaded UVDesk to my server using FTP;
2. Moved the content of folder "public" to "public_html"
3. All other folder from UVDesk (config, vendor and others) are above the server public folder;
4. Installed UVDesk using the web installer;
5. Any uploaded file are not being created inside the "public_html", but still being uploaded to "public"

**Comment by dungeonist** [comment]
@papnoisanjeev 

I made a new test and the same problem occurs. I created a new account in cpanel and uploaded all files to this account, as before I moved all files from public to public_html folder.

After the installation using the browser, all files uploaded in a ticket still being uploaded to the default "public" folder instead of my "public_html".

**Comment by vipin-shrivastava** [comment]
@dungeonist 

Can you please tell me ? Why are you Changing the folder name 'public' to 'public_html'?

**Comment by dungeonist** [comment]
> Can you please tell me ? Why are you Changing the folder name 'public' to 'public_html'?

Because public_html is the public folder from whm/cpanel server. WHM/CPANEL doesnt allow to change their public folder name since this cause several problems with their internal settings. All files accessible to the world must be in the "public_html", so this is why I moved the uvdesk public files from "public" to "public_html".

**Comment by vipin-shrivastava** [comment]
@dungeonist 

This issue which you faced is because of PUBLIC_HTML. All the images and bundles are accessing from the public folder. If it is not able to be found then it will create an issue. 

Solution :
0

If you can access the server in SSH, you can use the cp command to copy your directory files to public_html or rename the folder as you suggested.

Be sure to stop the Apache service first.


If you still facing the same issue Please let me know.

**Comment by papnoisanjeev** [comment]
@dungeonist 

Hope your issue has been resolved if not you can reply us back here !!
