### ISSUE TITLE
Invalid type for path "uvdesk_mailbox.mailboxes.Support.imap_server.password". Expected scalar, but got object.

### ISSUE THREAD

**Issue by dungeonist** [uvdesk/community-skeleton#429]
# Bug report

### Issue Description
While trying to setup a mailbox in my server, I started to receive this message. The last thing that I did was to update the password of the mailbox and now this message started to being displayed when I try to access the mailbox or swift mailer. This seems to be related some

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework version 1.0.14

### Steps to reproduce

I am not sure what triggered this issue. I tried to find where in the installation I can find the mailbox information to delete it and create a new one, but couldnt find. 

### Expected result

I should be able to visit the mailbox page and swift mailer page to manage the information of mail. 

>    **Tell us what happens instead.**]

I started to receive the following message when I visit the mailbox or swifter mailer page in the backend: Invalid type for path "uvdesk_mailbox.mailboxes.Support.imap_server.password". Expected scalar, but got object.

**Comment by vipin-shrivastava** [comment]
@dungeonist 

Can you please share the screenshots ? So that we can understand the issue better .

**Comment by dungeonist** [comment]
I solved yesterday after some attempts, seems that if your password has a comma (,) as the last character it will break the website.

**Comment by papnoisanjeev** [comment]
@dungeonist 

Which password database or web login?

**Comment by dungeonist** [comment]
The mailbox password. Seems that when creating a mailbox if the last character of the e-mail password is a comma (,) the website will break.

**Comment by vipin-shrivastava** [comment]
@dungeonist 

I think this is not the correct reason behind this issue. As I tried to set up mailbox & swift-mailer with a Password `xxxx#09,` . It is perfectly working fine & then after I also able to create a new mailbox or swift-mailer. I also attached screenshots here.

![Screenshot_20](https://user-images.githubusercontent.com/58874186/125091106-bf857e80-e0ed-11eb-92d3-46eba5ab7445.png)
![Screenshot_21](https://user-images.githubusercontent.com/58874186/125091134-c613f600-e0ed-11eb-83a7-ad5989e5f26c.png)
![Screenshot_23](https://user-images.githubusercontent.com/58874186/125091170-cdd39a80-e0ed-11eb-9915-79d7458ab88d.png)

**Comment by dungeonist** [comment]
@vipin-shrivastava 

I did a test again with the same password that caused the problem previously and the error appeared again. Here is a screenshot:

![6366804a-bcba-4db3-98ef-2e315d794e11](https://user-images.githubusercontent.com/5342341/125093971-406e5700-e0a9-11eb-9935-ed3c0ec1ef39.png)

The password in question was (I changed it after): !8+L)n6r?LP,

**Comment by vipin-shrivastava** [comment]
@dungeonist 

As I found the issue, this is because you use ! (exclamation mark) at the start of the password.

we will fix this issue in master.

If you found any issues, Please let me know.

**Comment by papnoisanjeev** [comment]
@dungeonist 

Password encryption has been added with above pull request hope it will resolve your issue.
You can check.
