### ISSUE TITLE
Email should be deleted from mailbox after fetch

### ISSUE THREAD

**Issue by thoughtspacewebsites** [uvdesk/community-skeleton#433]
**Description**  
There needs to be an option to delete emails from the inbox after the first fetch. Not deleting emails causes a host of problems with having to re-sync the entire list every time the cron job is run. As the support email grows in size, fetches take longer and longer. Beyond this, if a ticket is fully deleted, it will be re-fetched. IMO, this is a bug and really needs addressed in order for the email client to be effective at all.

**Example**  
Continue to fetch emails as you use the portal. Over time, the amount of emails that needs to be processed grows astronomically and slows down the fetch process.

**Comment by thoughtspacewebsites** [comment]
Just found this thread that requested this also with sadly no interaction from devs:
https://github.com/uvdesk/community-skeleton/issues/279
What's going on with this? I'd say this is a very crucial feature for a helpdesk. I recently submitted a pull request for updated english translations for you too and would gladly help spread the word and work on minor things here and there as long as I see vital features like this aren't being left and forgotten about. Any updates?

**Comment by vipin-shrivastava** [comment]
@thoughtspacewebsites

ok, we will try to add an option for the same in an upcoming release.

**Comment by thoughtspacewebsites** [comment]
Thank you very much! Will keep an eye out and start my personal migration once this is available :)

**Comment by thoughtspacewebsites** [comment]
I just ran composer update, but I'm not seeing this checkbox anywhere. Where is it exactly? Do I need to specify the mailbox component when running composer update or something?

**Comment by papnoisanjeev** [comment]
@thoughtspacewebsites 

All updates are currently in master branch when a new release will come after that when you will run composer update then you will get updates.
