### ISSUE TITLE
Newer TLDs are considered invalid.

### ISSUE THREAD

**Issue by kp3nguinz** [uvdesk/community-skeleton#435]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**
Email validation on setup does not support abnormal TLDs (in my case, .group)

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**
My email is showing as not valid (which ends with a .group), but my throw away does (.com TLD)

### Preconditions
**Please provide as detailed information about your environment as possible.**
Using the latest build in docker as of today (I built from your main branch).
    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   .group emails should be considered valid

### Actual result

>    .group emails are not considered valid.

**Comment by papnoisanjeev** [comment]
@kp3nguinz 

As there are some frontend validation to validate a email id before adding it.
We will update regex for the same so that it will support  **.group** emails.

**Comment by vipin-shrivastava** [comment]
@kp3nguinz 

As I tested with Test@test.com.group, It is working fine.
can you send us a screenshot. so that it is easy to understand where you get the issue.

![Screenshot_59](https://user-images.githubusercontent.com/58874186/128651237-7373aad5-8cf1-47b0-b6f5-a0b4d3d24755.png)

**Comment by papnoisanjeev** [comment]
@kp3nguinz 

As we have tested the current release of project it is supporting such emails !!
Please let us know if you getting this error for current release.

We are closing this if you are still facing the issue please reply here on same thread or can generate a new issue !!

**Comment by sarahessex** [comment]
The new TLDs do not seem to be validated in the Helpdesk Configuration wizard. I am on release 1.0.16.

When I created a super admin account as prompted within the installation wizard, my email address (which ends in .agency) was not accepted. I tried .group too and that wasn't either. "Invalid email" error message.

**Workaround**
I used @example.com just to get passed the step and complete with installation wizard, then once the Helpdesk was installed, went to edit my profile and changed my address to .agency which was then accepted.

So my assumption is, custom TLDs are accepted under Edit Profile, but I think there is still a bug with the installation wizard.

**Comment by vipin-shrivastava** [comment]
@sarahessex 

As we check we found that regex is not able to accept new email TLDs to be validated in the Helpdesk Configuration wizard.
we will update the regex in master.

If you found any error or any issue, please let us know
