### ISSUE TITLE
Unable to finish installation - Error during load/superuser

### ISSUE THREAD

**Issue by lemtargatwing** [uvdesk/community-skeleton#438]
# Bug report

### Title
Unable to finish installation - Error during load/superuser

### Issue Description
Unable to finish new installation - Error during load/superuser

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Ubuntu 20.04 LTS
    2. PHP 7.3
    3. External MySQL database

### Steps to reproduce

    1. Proceed through web based installation
    2. Error during setup

Attempt 2:

1. Followed CLI installation steps - ran php bin/console uvdesk:configure-helpdesk
2. Database migration failed

### Expected result
Installation should succeed

### Actual result

>    Installation fails
Web installation:
![image](https://user-images.githubusercontent.com/19838881/128614478-cd69cb1e-e303-4d5b-b28d-988a8a1aa6a6.png)

CLI Installation:

![image](https://user-images.githubusercontent.com/19838881/128614501-3afdbc3b-ecc9-4907-803d-f96d0e64c3b0.png)

Database after failed install:
![image](https://user-images.githubusercontent.com/19838881/128614520-e81229f8-97cc-4865-aa88-2a503109a9a9.png)

**Comment by papnoisanjeev** [comment]
@lemtargatwing 

Please try using web installer.

Or 

You can try [manual ](https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642) installation as well.

**Comment by papnoisanjeev** [comment]
@lemtargatwing 

Is you issue resolved or still you need help !!
we are closing this issue if still facing the issue you can reply on same thread or can generate a new one.
