### ISSUE TITLE
Update jQuery and Underscore.js

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#439]
# Bug report

### Title

Next version of UVdesk should have updated jQuery and other components, actually Underscore.js need also be updated.

### Issue Description

Actual version of:

- jQuery 3.5.1
- Underscore.js 1.12.0

Should be updated to:

- jQuery 3.6.0
- Underscore.js 1.13.1

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

We will try to add jQuery 3.6.0 & Underscore.js 1.13.1 in our upcoming release.
