### ISSUE TITLE
Not PHP 8 compatible

### ISSUE THREAD

**Issue by MainTobias** [uvdesk/community-skeleton#440]
PHP 8.0.6 (cli) (built: Aug  2 2021 08:41:40) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies

When running php -S 127.0.0.1:8080 -t ., symfony says: 
FatalErrorException
Compile Error: Array and string offset access syntax with curly braces is no longer supported

in HTMLFilter.php line 351

This is not unexpected as php does mention it:
https://www.php.net/manual/en/migration80.incompatible.php

**Comment by vipin-shrivastava** [comment]
@MainTobias 
We are working on compatibility with PHP 8. If we found everything good then we will provide support with PHP 8 from the next release.

**Comment by MainTobias** [comment]
Okay thanks just didn't know if you were aware of this problem
