### ISSUE TITLE
Error translation V 1.0.15 status ticket not translated. The fix made is not working

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#443]
Issue not resolved in V 1.0.15
https://github.com/uvdesk/community-skeleton/issues/423

I upgraded and issue persist

Also time stamp is wrong, date should be DD MM YYYY so is showed not correctly.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/130367649-02d7d568-6cee-4196-9b49-d7e165cfbbf9.jpg)

**Comment by PeopleInside** [comment]
I'm restoring the old version using the backup as seems something is wrong with the upgrade.
Waiting your replies on the forum and here on many issues.

I loosed a lot of time by upgrading and try to fix issues than put again customization... you should have a better upgrade procedure and made an announcement with detailed steps or you made me loose a lot of time and doing a lot of not useful work. Now I will lost everything I done in this last hours and resume the old version.

**Comment by PeopleInside** [comment]
Updating with:

```
composer update uvdesk/core-framework
composer update uvdesk/support-center-bundle
composer update uvdesk/mailbox-component
composer update uvdesk/automation-bundle
composer update uvdesk/extension-framework
```

than:
```
php bin/console d:s:u --force
php bin/console assets:install
```
resolve the issue.

The problem was with composer update or missed update information from you.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

There is some issue with merge request with the current release please wait we are again creating a new one then you will get all updates and fixes and most probably we will again make a new release today itself.

**Comment by PeopleInside** [comment]
@papnoisanjeev OK, if you can fix two important things:

https://github.com/uvdesk/community-skeleton/issues/446
https://github.com/uvdesk/community-skeleton/issues/447 (important)

and check this:
https://github.com/uvdesk/community-skeleton/issues/444

other issues resolved with manual update was closed by me some minutes ago.
Thank you.
