### ISSUE TITLE
On your website the zip file is at aversion 0.1.13, very old! Need keep update link or remote this download button.

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#445]
At the page https://www.uvdesk.com/it/opensource/

If user download the zip file from the download button get the version 0.1.13
This is really not updated so you should keep this always updated or I suggest to remove the download link.

Issues are not only in your website, I run composer update and get an updated version of UVdesk 1.0.15 that resumed a lot of old bugs and I cannot see any one new future added.

Something is wrong, you should make more attention and give more care about the release and update process.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have created a new release **[v1.0.16](https://github.com/uvdesk/community-skeleton/releases/tag/v1.0.16)** (as v1.0.15 missed with some merge issue) and also updated zip https://www.uvdesk.com/it/opensource/ here.

**Comment by PeopleInside** [comment]
Great, thanks
