### ISSUE TITLE
error deleting ticket permanently

### ISSUE THREAD

**Issue by Pekerche** [uvdesk/community-skeleton#452]
When time permanently deletes a ticket, the same error always appears. can you help me?

follow image; 
![error](https://user-images.githubusercontent.com/85793019/131175754-6a176db2-5060-45cc-b491-2aa1e287d3bc.png)

**Comment by vipin-shrivastava** [comment]
@Pekerche 
Which version of UVdesk are you using?

**Comment by Pekerche** [comment]
V -1.0.13

**Comment by vipin-shrivastava** [comment]
@Pekerche 
Okay, Update your Uvdesk from the below steps :

1. Download project zip from [here](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip).
2. After download the project zip extract it.
3. Now, Copy **uvdesk folder** from  **` uvdesk-community-v1.0.16->vendor->uvdesk`**  file location.
4.  First, Delete the Uvdesk folder from your project **` your_project_name->vendor->uvdesk`** location.
5. Now, Paste the copied Uvdesk folder.
 
Share screenshot for your reference .

![Screenshot_5](https://user-images.githubusercontent.com/58874186/131331101-fcf514b4-447e-46e7-ad94-0da85a841e67.png)


Now, run the PHP bin/console c:c

if you still getting the same error . Please let me know.

**Comment by Pekerche** [comment]
![image](https://user-images.githubusercontent.com/85793019/131334298-45deb601-9b81-40a6-accd-a08ccaa8796c.png)


continue the error

**Comment by Pekerche** [comment]
continue the error

![error2](https://user-images.githubusercontent.com/85793019/131334510-78059058-7c5a-45e5-9db3-b1ed5de0a725.png)

![verson](https://user-images.githubusercontent.com/85793019/131334523-8a67a294-376a-4c59-8605-678d3c17eedd.png)

**Comment by vipin-shrivastava** [comment]
@Pekerche 
I think your project table did not update because of the doctrine cache

Run the following command in the given sequence order

```
php bin/console d:c:clear-metadata
php bin/console d:s:u --force --dump-sql --complete
php bin/console c:c  
php bin/console c:c --env prod
```

Hope this will resolve your issue. If not please let me know

**Comment by vipin-shrivastava** [comment]
@Pekerche 
are you still facing the same issue?

**Comment by Pekerche** [comment]
Good morning. Thanks to you it worked, thank you very much!
