### ISSUE TITLE
Can not install UVdesk after install of Composer 2.x

### ISSUE THREAD

**Issue by mjfortega** [uvdesk/community-skeleton#454]
I am trying to install UVDesk on an Ubuntu machine,
After installing Composer 1.x I needed to upgrade before I could go on.
I upgraded to Composer v2.x.

No when I execute: `composer create-project uvdesk/community-skeleton helpdesk-project` 

I get the following error and I am stuck:

 **[InvalidArgumentException]                                                  
  Could not find package uvdesk/community-skeleton with stability stable in   
  a version installable using your PHP version, PHP extensions and Composer   
  version.**

**Comment by vipin-shrivastava** [comment]
@mjfortega 
What PHP version are you using?

**Comment by vipin-shrivastava** [comment]
@mjfortega 
I think you are using PHP8 that's why it is giving you a warning.
Downgrade your PHP version to 7.4 then you can easily download the project using `composer create-project uvdesk/community-skeleton helpdesk-project` command.

we are also working on PHP8, soon you will see the support with PHP8 in UVDesk.

Hope  now your issue will resolve. If not please let us know

**Comment by mjfortega** [comment]
Yes, the command I used to install PHP seems to have installed all PHP versions, version 8 (v8.0.9) included.
Although version 8 has been disabled, and PHP v7.4 has been enabled, the UDesk composer install probably detects PHP v.8.x.

After uninstalling PHP 8.x using the following lines:
`sudo apt-get purge php8.*`
`sudo apt-get autoclean`
`sudo apt-get autoremove`

After de above, was able to continue with the UVDesk installation using "composer".
However I do not know if some this uninstall will have any adverse effects later.

**Comment by vipin-shrivastava** [comment]
@mjfortega 
As per my knowledge, it will not affect anything but if some other projects want PHP8 then will occur some issues.
But as I know if some projects support PHP8 then it will also be perfectly fine working with PHP7.4.

**Comment by vipin-shrivastava** [comment]
@mjfortega 
Any updates? Are you still facing the issue?

**Comment by PeopleInside** [comment]
Hi @mjfortega ,
I use UVdesk with PHP 7.4 and I don't see or know any issue with composer 2.

You can try to install UVdesk by using the method 4 (FTP) see:
https://forums.uvdesk.com/topic/1833/how-to-upgrade-uvdesk

**Comment by Komal-sharma-2712** [comment]
Here, your side is nothing updates so we are closed this issue and after that If you are getting same issue so please let we know
