### ISSUE TITLE
Move the HelpDesk string to the custom field

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#455]
UVDesk branding show two customizable field where user can decide the page title of the HelpDesk and of the Knowledgebase.
In my case I set both filed to be: HelpDesk website name
but when I load my main help desk page https://helpdesk.domain.ext the page title is: HelpDesk Helpdesk website name.

Seems UVdesk add the world HelpDesk before the custom title the user choice so my suggestion is to include this in the custom field name means when user will try to customize the branding name will find as default the HelpDesk title in the custom field but if user decide to delete or change this, when the main HelpDesk page is loaded https://helpdesk.domain.ext this should not show HelpDesk before the custom name.

https://forums.uvdesk.com/topic/1986/site-title

![1](https://user-images.githubusercontent.com/5006150/132121620-fed61b9d-84b8-4814-9b33-15152697ca1f.jpg)

This is the UVdesk demo picture.
My suggestion is to add in the custom filed HelpDesk before the word Knowledgebase and remove in the code the fact HelpDesk is added before the Knowledgebase title also if this is not present in the custom field.

![2](https://user-images.githubusercontent.com/5006150/132121650-6d08e5ba-b523-4614-8d2b-b7b7ff51369b.jpg)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

https://forums.uvdesk.com/topic/1986/site-title/5

**Comment by PeopleInside** [comment]
Great but I suggest to improve the code: is better move the static HelpDesk "label" to the original translation / string inside the default name field where user can decide.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Removed static Helpdesk and added with default entry [here](https://github.com/uvdesk/support-center-bundle/commit/f577b4a207d9aa8d926fa603fd0315b1dfdd8c9a).

**Comment by PeopleInside** [comment]
Great thank you. Please check the forum discussion linked above as the user asking how to clean cache without SSH. You may consider in the future to add a button on the admin side to help users without SSH access. Closing this
