### ISSUE TITLE
Disable cloudflare CDN for static contents

### ISSUE THREAD

**Issue by llmuculusll** [uvdesk/community-skeleton#459]
**Description**  
We want to use uvdesk in our private network that is has not access to internet. So some of the static contents from cloudflare does not load(Such as backbone-min.js). I suppose a configuration that disables cloudflare CDN for static contents and serves them from local assets.

**Comment by vipin-shrivastava** [comment]
@llmuculusll 

As I understand your problem, I can suggest to you some steps that will help you:
1. Open the **layout.html.twig** in **core-framework** & **support-center-bundle** from the following path in your project
     => `your_project_name/vendor/uvdesk/core-framework/Resources/views/Templates/layout.html.twig`
     => `your_project_name/vendor/uvdesk/support-center-bundle/Resources/views/Templates/layout.html.twig`
2. After opening both files find the CDN links from here & download all the CDN link data, save them in a file & save them with the same file name in the given CDN.
3. After saving all the CDN, Please remember **core-framework** CDN files put into 
     => `your_project_name\public\bundles\uvdeskcoreframework\js`
     => `your_project_name\public\bundles\uvdeskcoreframework\css`
4. After saving all the CDN, Please remember **support-center-bundle** CDN files put into 
     =>`your_project_name\public\bundles\uvdesksupportcenter\js`
     =>`your_project_name\public\bundles\uvdesksupportcenter\css`
5. Now, replace all the CDN links with the static files CDN 
   `<link href="{{ asset('bundles/**uvdeskcoreframework or uvdesksupportcenter**/**css or js**/file_name') }}" type="text/css or text/javascript"  media="all" />`

I hope this will help you, If you still facing any issue please let us know

**Comment by llmuculusll** [comment]
thanks
