### ISSUE TITLE
Mails are not received by customer by any reply is added to their ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#46]
Test scenario :- 
1. Customer create ticket by using mail id
2. Agent receive ticket at their dashboard
3. When agent add reply to that ticket , customer will not get any mail

Bug :- customer is not receiving mails on their mail id
![screenshot 15](https://user-images.githubusercontent.com/43210406/50152903-edfe9c80-02ea-11e9-9480-3478143e4e2f.png)

**Comment by shubhwebkul** [comment]
resolved
