### ISSUE TITLE
Loading issue of Tickets which have more  Text messages  

### ISSUE THREAD

**Issue by IwataNeo** [uvdesk/community-skeleton#466]
Hello everyboy,
I spottet an loading issue if i want to open a Ticket which Containes more Textmessages.
I click on a Ticket, then i can see the data behind the overlay, but the overlay with the 3 loading dots never disappear.
I hope someone can assist me to find out the reason for that.
![Screenshot_20210909-170247_Samsung Internet.jpg](https://user-images.githubusercontent.com/70383926/132800647-23eaceeb-4541-40b8-8ea4-28424bc1bd6f.jpg)![Screenshot_20210909-170253_Samsung Internet.jpg](https://user-images.githubusercontent.com/70383926/132800657-56066499-9a71-4626-a618-8e10e4b4e562.jpg)

**Comment by vipin-shrivastava** [comment]
@IwataNeo 

Please share the screen shot

**Comment by IwataNeo** [comment]
This is what symfonie displays when this happens. Is this a help??

**Comment by vipin-shrivastava** [comment]
@IwataNeo 
which version of UVdesk are you using?

In my case it is working fine
![Screenshot_59](https://user-images.githubusercontent.com/58874186/132801203-8b51a586-4c4c-4edd-ac67-9b461823c6e5.png)

**Comment by IwataNeo** [comment]
In my changelog i can see entries for version 1.0.14.

**Comment by vipin-shrivastava** [comment]
@IwataNeo 

AS I am using the latest Helpdesk version 1.0.16, update your helpdesk to the latest version.

**Comment by IwataNeo** [comment]
How can i perform an update?
ist it still changing all the files on the server?

**Comment by vipin-shrivastava** [comment]
@IwataNeo 

Are facing the same issue on any other tickets?

**Comment by IwataNeo** [comment]
@vipin-shrivastava 
yes. I am facing this issue on all Tickets which contains more than one reply as i know now.

**Comment by vipin-shrivastava** [comment]
@IwataNeo 

Please check in console while opening the tickets, any error is occurring there or not,
Have you done any changes to the code?

**Comment by PeopleInside** [comment]
> can you give me a little information on how to perform the update and then i will try this first.

https://forums.uvdesk.com/topic/1833/how-to-upgrade-uvdesk
First of all take a full folder and backup before do any upgrading actions.

You cannot use the method 1 because your UVdesk "is old" and doesn't yet support composer update.
You can follow method 2, 3 or 4

**Comment by IwataNeo** [comment]
@PeopleInside i updated sucessfully to the latest version but the problem still exists. I am not sure on how i can start a console to see what is happening. Is there an explanation for that anywhere too?

**Comment by vipin-shrivastava** [comment]
@IwataNeo 
Open the console of your browser & then refresh the page, you will see the error

**Comment by PeopleInside** [comment]
> @PeopleInside i updated sucessfully to the latest version but the problem still exists. I am not sure on how i can start a console to see what is happening. Is there an explanation for that anywhere too?
> 
> I am using php Version 7.4 on my Webserver.

I'm sorry to read the issue persist.
Please see if this article can help you: https://balsamiq.com/support/faqs/browserconsole/

At time of Europe/Rome you can find me also on live chat on my personal website (see GitHub page).
I'm not part of the UVdesk team, just a passionate user but if I can help in some way to resolve your issue will be happy to do.

**Comment by IwataNeo** [comment]
@vipin-shrivastava @PeopleInside 
the Console just showing some warnings but no errors as you can see in the Screenshot

![screenshot](https://user-images.githubusercontent.com/70383926/133196189-2ad03edd-92a5-443c-900a-2887ece38426.PNG)

**Comment by vipin-shrivastava** [comment]
@IwataNeo 

See the below screenshot here you can see the error

![Screenshot_62](https://user-images.githubusercontent.com/58874186/133196882-1b85c79f-70db-4134-83a8-30fb0b85005b.png)

**Comment by IwataNeo** [comment]
@vipin-shrivastava 
yes. that is what i have done at my very first post.

that is the output.

![screenshot](https://user-images.githubusercontent.com/70383926/133197263-862deb40-19ef-4c98-9a15-6e981826a10b.PNG)
![screenshot1](https://user-images.githubusercontent.com/70383926/133197267-b4f30fec-79eb-4c9b-a5a4-05b11698b204.PNG)

**Comment by PeopleInside** [comment]
@IwataNeo do you find any error on UVdesk main root folder var/log ?
Have you also checked server error logs?

**Comment by vipin-shrivastava** [comment]
@IwataNeo 

Share your helpdesk URL with admin credentials on support@uvdesk.com, our team will check & update you.

**Comment by IwataNeo** [comment]
@PeopleInside 
I checked both log files but can't find any hint of the source of this issue.

**Comment by IwataNeo** [comment]
@vipin-shrivastava 
Will write this mail right now.

**Comment by PeopleInside** [comment]
What the issue was?

**Comment by IwataNeo** [comment]
@PeopleInside 
The issue was that the Agent and the Customer had the exact same E-Mail Adress within one Ticket.
This is possible if an Agent creates a Ticket and uses his Agent Data. Then the System creates a customer with these Data without checking if the Email already exists. This was happened during testing, but shouldn't happen in normal use i guess. 

Sorry for making all of this trouble ;-)

**Comment by PeopleInside** [comment]
I believe UVdesk team need solve this as this should not happen.

**Comment by vipin-shrivastava** [comment]
@IwataNeo @PeopleInside 
wait, I have created a ticket  & assigned it to the same email agent & when I  open that ticket & reply from admin, customer & agent it works fine. There is no loading issue occurs

@IwataNeo Please create a new ticket from the same email of the agent & customer then check, If you found this issue please let us know
