### ISSUE TITLE
Feature request: Options to set default language

### ISSUE THREAD

**Issue by devzom** [uvdesk/community-skeleton#470]
**Description**  

Option to pick from available languages from **translations folder** and set the default language.

**Example**  

Admin user can access **settings page** and set the default language for the supportCenter

**Comment by Komal-sharma-2712** [comment]
We have **added this feature** to the **admin panel** in the **branding section** in the Latest Release v1.1.1. You can check the below screenshot:

![image](https://user-images.githubusercontent.com/63539748/197149410-9fa7db05-0812-408a-a7dc-fcd444bc5c2e.png)

The admin can also change the language on the customer end. Once the language is updated, it will display at the customer end.
