### ISSUE TITLE
Login Button backend shows no reaktion

### ISSUE THREAD

**Issue by IwataNeo** [uvdesk/community-skeleton#472]
Hi Community,
my Login button to the Backend shows no reaction anymore.
is there an opportunity to force a new installation like automatically done after an Update? 

The Console show this Error message after hitting the login button.

recaptcha__de.js:50 Uncaught Error: No reCAPTCHA clients exist.
    at Array.<anonymous> (recaptcha__de.js:50)
    at recaptcha__de.js:33
    at r.fn (login:416)
    at Object.fn (backbone-validation-min.js:8)
    at nr (underscore-min.js:6)
    at Object.<anonymous> (underscore-min.js:6)
    at Object.fn (underscore-min.js:6)
    at backbone-validation-min.js:8
    at r (underscore-min.js:6)
    at Function.<anonymous> (underscore-min.js:6)

**Comment by PeopleInside** [comment]
Hi @IwataNeo,
I hope you are fine!

I think for support you should use the UVdesk forum https://forums.uvdesk.com
as GitHub is more for bug reports.

For this time let's continue here but next time maybe questions I think is better ask on the forum.

> my Login button to the Backend shows no reaction anymore

Have you tried with different browser and on incognito mode?
The issue still persist also with this try?

Can be maybe useful looks if there is any log of error, the following article should help you to diagnosticate better the issue: 
https://forums.uvdesk.com/topic/1988/how-to-debug-errors

Try maybe also to clean cache with the SSH command: **php bin/console c:c**

**Comment by IwataNeo** [comment]
@PeopleInside 
Oh i see.....
Sorry for that. I'll keep that in mind for the future.
I guess there is an Problem with the ReCaptcha option.

**Comment by IwataNeo** [comment]
@PeopleInside 
Thanks for the hint and sorry for bothering you again.
Changing the Captcha value to 0 in the Database solved this problem.
i am able to login to the Backend again.
Thanks a lot.
I am starting to slowly understand UVdesk.

**Comment by PeopleInside** [comment]
> Thanks for the hint and sorry for bothering you again.
> Changing the Captcha value to 0 in the Database solved this problem.

No problem, I'm happy reading you can now login.
Be sure ReCaptcha options are correct than try again to activate Captcha, you need a valid code from Google.
