### ISSUE TITLE
Error when downloading attachment from customer side

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#475]
# Bug report
### Title

Error when try to download an attachment from the customer page.
I get 500 error

![0 SharedScreenshot](https://user-images.githubusercontent.com/5006150/134516849-1e0fc4f6-f92f-4283-bafe-d3b7e81d540a.jpg)

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/134516862-2a446218-8657-4558-837e-028bfdaeba2f.jpg)

So I generated a ticket from https://marcoborla.com/uvdesk/public/en/customer/create-ticket/
than I registered by following the customer link and when try to download the attachment as customer I get 500 error.

UVdesk  v1.0.16

Issue reported by a customer here: https://forums.uvdesk.com/topic/1991/download-attachment-issue-on-customer-s-page

**Comment by PeopleInside** [comment]
More error details can be found here:
https://forums.uvdesk.com/topic/1991/download-attachment-issue-on-customer-s-page

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

We have already fixed this in master, if you want you can take clone of core-framework & support-center-bundle packages 

After update both the packages, run php bin/console c:c 

Hope this will resolve your issue, if not please let us know

**Comment by PeopleInside** [comment]
Sorry, can you share the edit I need to do without have to replace full core-framework & support-center-bundle packages where I have customization?

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

Is this still occurs?

**Comment by PeopleInside** [comment]
resolved. I updated the customer on the forum also.
Thanks... hem.. always some bug that i don't know and if some one not report here or in the forum I still have bugs also on my helpdesk. Fortunately I'm following forum and here and some user report issues.

**Comment by PeopleInside** [comment]
@vipin-shrivastava you make me loose my time :)

I followed what you told to do so I downloaded from master, on GitHub core-framework & support-center-bundle packages
The download of attachments has been resolved but

- now in Dashboard I see I'm using version V -1.0.13 and not v1.0.16
- I see again an [old issue](https://github.com/uvdesk/community-skeleton/issues/357) that I may re-open at this point

**Comment by vipin-shrivastava-webkul** [comment]
@PeopleInside 

No, you had to take the clone from the master branch itself. you have done it right.
As we updated the version in the released package but forget to update it in the master branch of GitHub.
Also, UVDesk GitHub master branch has the latest & updated code, here we fixed all the issue which comes in current & previous release.

**Comment by PeopleInside** [comment]
> As we updated the version in the released package but forget to update it in the master branch of GitHub

How this is possible?
You fix things in released package but keep GitHub not updated?
Where is the released package that you updated?

I mean if you fix things in your zip file but keep GitHub not updated, next update will resume bugs because GitHub is not updated so every edit future you do on GitHub will be not updated.

You are also suggesting a fix that is not what I think to be.

> you have done it right

I done right but the code i replaced now is not updated so?

> UVDesk GitHub master branch has the latest & updated code

You told you forget to update GitHub so the code cannot be updated.

> here we fixed all the issue which comes in current & previous release.

Here where?
I downloaded the packages from master and looks to be not updated as show in two different place that I'm running version V -1.0.13 that is old.

I'm now also see again an [old issue](https://github.com/uvdesk/community-skeleton/issues/357) maybe was never fixed?

**Comment by vipin-shrivastava-webkul** [comment]
> > As we updated the version in the released package but forget to update it in the master branch of GitHub
> 
> **How this is possible?**
> **You fix things in the released package but keep GitHub not updated?**
   we have updated the version in the master branch as well.
**> Where is the released package that you updated?**
 When you run the "Composer update" in your project. it will default download the released packages. But as you know there are some bugs are there so we recommended you to take clone for [ core-framework master](https://github.com/uvdesk/core-framework) branch.
> **I mean if you fix things in your zip file but keep GitHub not updated, the next update will resume bugs because GitHub is not updated so every edit future you do on GitHub will be not updated.**
> Sorry, but the only versions is not updated on GitHub (master branch).
> **I done right but the code i replaced now is not updated so?**
> As I told you, only versions are not updated, but now we will remember to update the version on GitHub packages as well
> > **UVDesk GitHub master branch has the latest & updated code**

> > here we fixed all the issue which comes in current & previous release.
> 
> **I'm now also see again an [old issue](https://github.com/uvdesk/community-skeleton/issues/357) maybe was never fixed?**
  Can you Please tell me the steps, how did you get this issue again?

**Comment by PeopleInside** [comment]
> Can you Please tell me the steps, how did you get this issue again?

There is no steps.
I noticed this issue after done the replacement you told me to do,
I don't know if this is related or not and seems i resumed an old code that is giving again this issue.

Strange was only the version of UVdesk to be not updated on GitHub.

I don't know why your system allow some spam users with a not valid email to registering... consider that as admin I have no admin control means there are no logs, no indication of when the account has been created, no date no time and no IP.
This is bad, an admin should have this information in the UVdesk backend panel.

Why this account with invalid email address and who result active (Why a fake account with no mail should result active?) is created, I don't know, I'm asking to you.

I have no custom page just my default ticket creation page protected also by the ReCaptcha https://helpdesk.peopleinside.it/it/usr/create-ticket/

I have no idea of what kind of bug UVdesk code has to allow this.

**Comment by vipin-shrivastava-webkul** [comment]
@PeopleInside 

For this [old issue](https://github.com/uvdesk/community-skeleton/issues/357), we will check again & update you back
