### ISSUE TITLE
 Email replies cause new ticket thread #397 

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#478]
The following issue still be unresolved so please don't close an issue before it get resolved.
https://github.com/uvdesk/community-skeleton/issues/397

If you see an issue is not resolved you should reopen it because when you close an issue we cannot open anymore.

**Comment by PeopleInside** [comment]
Maybe with the new fix the duplicate ticket is happening if mac.com user reply to the ticket creation email.
Seems never happen now if an operator reply is sent to the customer and customer reply to that email.

Maybe you fixed 50 % of the issue?

So if mac.com address create a ticket, receive the ticket creation message than reply to this a new duplicate ticket will be created. Reply not added to the existent ticket. This need a fix.

If the operator reply to the ticket and customer mac.com reply to the operator email, reply are now correctly added to the right existing ticket. This looks has been fixed.

All auto email model email that can be created from workflow should add replies to the existing ticket.
This need to be fixed.

**Comment by vipin-shrivastava-webkul** [comment]
@PeopleInside 

As you know we don't have any **@mac.com** account & **Stephen** is not replying frequently also it is hard to resolve an issue with this minimal **email raw content** but we are giving our best & trying to resolve this issue as soon as possible.

**Comment by PeopleInside** [comment]
@vipin-shrivastava I appreciate your help and work but soon I think I will be out on helping on this and I'm scared when I will decide to stop helping you on this, the issue will be also kept unresolved.

Today my test UVdesk instance is no more working. I cannot see any auth email issue just don't know why, all email that should be delivered to customers email address are delivered to my admin email address and not to the customers.

You told to me this is my server or email issue but how can be?
If I have a server and email issue I should never get any email and the web interface should show a warning about SwiftMailer error, this is not happening. No error showed.

Now as I don't know how to resolve this new issue in the UVdesk test instance if you also don't know why this happen... Will be the time for me to erase the test install and leave the issue as unresolved.

I was think.. I create a test UVdesk instance, the user create a ticket, create a reply and we will have two emails headers and two tickets that should be one. The UVdesk team will so have all information necessary... but was not.

***
I don't know how UVdesk associate an email to an existing ticket.
Maybe other help desk ticket system do this with the ticket ID present in the email subject or somewhere else.
I'm not understanding why there is this error just on mac.com email address in UVdesk.

So now my UVdesk test looks to be broken.
I can erase it and leave the try to diagnosticate and resolve the issue?

I'm thinking to erase all.

**Comment by vipin-shrivastava-webkul** [comment]
@PeopleInside 

No, need to erase it is working fine, It is sending a notification email on every creation or reply or forward a maill, I already test with your helpdesk.

**Comment by NikuyaJS** [comment]
@PeopleInside any way to get the version you're using?

This is pretty make or break for us

**Comment by PeopleInside** [comment]
No problem, you can run another test however the issue I see with you happen also with mac.com domain so I suppose the issue faced will be the same.

**Comment by NikuyaJS** [comment]
I work very closely with my mail provider if I cold be told by @vipin-shrivastava what uvdesk looks for to determine a successful reply in the mail headers we might be able to make amendments mail server side

**Comment by NikuyaJS** [comment]
@vipin-shrivastava can you give an example of what the reference ID in the headers looks like?

Have you had any luck with testing?

**Comment by PeopleInside** [comment]
@NikuyaJS duplicate ticket are created also when you reply to UVdesk support tickets?
I hope this duplicate ticket issue will be resolved.

I'm asking if UVdesk team is still searching where the issue can be or they know about it.
I imagine this is a big issue for who are facing this issue.

**Comment by PeopleInside** [comment]
How long this issue will keep open and unresolved?
I hope in a solution also because I also hope to resolve the issue I'm facing with the latest version 1.0.18 that doesn't work for me.. so seeing how long this issue, that is strong, is keep opened let me think sometime I don't know when will be resolved and when I will be able to update to the latest UVdesk version.

**Comment by Komal-sharma-2712** [comment]
We are already working on this issue, once we fix this issue will update you soon

**Comment by vipin-shrivastava** [comment]
@NikuyaJS 


> @vipin-shrivastava can you give an example of what the reference ID in the headers looks like?
> References: - as the In-Reply-To: field, this field is used when the message for which you're viewing the email header is a reply to another message. The References: field contains the Message-IDs of all the replies in the thread.
>  I have attached a screenshot here :
![Screenshot](https://user-images.githubusercontent.com/58874186/140717891-b5180a0d-6b38-44d5-bcd5-9d6ba3cb74ae.png)

> Have you had any luck with testing?
> NO,  As I found reference IDs are disabled in your email header. This is the reason for gernating new ticket on a reply by email.

**Comment by NikuyaJS** [comment]
@vipin-shrivastava 

Are there any plans to move away from using reference IDs? Without being able to reply to tickets we will have to move to another platform

**Comment by NikuyaJS** [comment]
Any update to this? it's not only my mail provider that has this issue...

**Comment by NikuyaJS** [comment]
Still nothing?

**Comment by PeopleInside** [comment]
@NikuyaJS  I think this issue will stay unresolved for a lot of time, I see no progression on this, personally and this is a strong issue, o my point of view.

It's sad because I think UVdesk is a really amazing Help Desk.

@NikuyaJS  a question: have you emailed the UVdesk support?
If you email they on they help desk do you have the same double ticket issue that happen in the open source?

I'm asking that because I suppose if a customer send 10 emails to UVdesk team and they get 10 different ticket opened without be able to have a single ticket conversation, then how this issue is big will be maybe more clear.

At the moment you can ask to customers that have email with this issue to not reply to emails but use the web interface for update tickets.

Maybe if some providers delete some fundamental headers, UVdesk should check also something in the Subject email or use an additional tracking in body message etc.

I think actually UVdesk is the best Open Source Help Desk solution so I really hope this issue will be solved, we don't wanna loose UVdesk users, we wanna increase it.

**Comment by PeopleInside** [comment]
IM sure that UVdesk team is looking for a better solution to apply for fix this keeping focused on the security so this may take sometime.

**Comment by vipin-shrivastava** [comment]
@NikuyaJS 

Our team again tried to login into your email service but they are unable to log in.

**Comment by NikuyaJS** [comment]
Hi Vipin,

I have refreshed the details and replied to the ticket with them

**Comment by papnoisanjeev** [comment]
@NikuyaJS  @PeopleInside 

We have made added some fixes for this case.
Please make below updates on your project and check it if working fine for you !

Locate path in your project.
**vendor/uvdesk** under uvdesk folder you will see some folder.

Delete **core-framework** and **mailbox-component** folder.

Then again **clone** both using below command at same place (under **vendor/uvdesk** folder).

**git clone https://github.com/uvdesk/core-framework**
**git clone https://github.com/uvdesk/mailbox-component**

Finally clear your cache and make a try !!

**Comment by PeopleInside** [comment]
@papnoisanjeev thank you, I will test and let you know as soon I have the results.

**Comment by PeopleInside** [comment]
@NikuyaJS my helpdesk has the patch but I cannot test if the user with the mac.com address never reply to my ticket.
If you are waiting to know if works or not you can open a test ticket in my help desk, I will reply to you so we can see if the issue persist.

I don't have anymore a test ticket instance so you can open the ticket sending an email to helpdesk@peopleinside.it

**Comment by PeopleInside** [comment]
I'm closing this issue until someone report that issue still be present. I cannot test the fix without help of the reporters.

**Comment by NikuyaJS** [comment]
please re open this, i have sent a test email to your helpdesk @PeopleInside

**Comment by NikuyaJS** [comment]
@PeopleInside on checking i got a NDR 

550 5.7.23 SPF validation failed.

**Comment by PeopleInside** [comment]
@NikuyaJS for be able to deliver an email to my email system you have to have a correctly configured email with a valid SPF record or email will be refused by the email system as spam.

https://support.google.com/a/answer/33786?hl=en

You may need test your spam score and improve your email configuration.
You have three free test every 24 hours visiting the external tools (at your risk) https://www.mail-tester.com/

How it works?
When you have set correctly an SPF record than you can try to resend an email to my email address.

If you want monitor how bad or how good your email are configured for the delivery open the https://www.mail-tester.com/ website than send an email that has some text (randoom text or a text from Wikipedia) to the temp email address showed from the page.

Than press the button and check your score.

If your email is not delivered to my help desk email system is because your email is not well configured.
Again you need fix the SPF record on your email.

Once done please write back here or if you will open successfully a test ticket on my system I will see and I will reply to you.
I will re-open this issue once I have evidence that the issue is not fixed.

**Comment by PeopleInside** [comment]
Great, I received the email reply from Stephen, mac.com address and this time all works great!
The fix work, thank you very much UVdesk team!

**Comment by steveb85** [comment]
@PeopleInside et al, i’ve found since this update, that my workflows aren’t working, is this another bug based on the way i upgraded? as with having to remove mailboxes and re-enter the password?

**Comment by PeopleInside** [comment]
Hi @steveb85, happy new year!
I hope you are fine.

> I’ve found since this update, that my workflows aren’t working

I never experienced this, what kind of workflow are not working?
How to reproduce this issue?

> as with having to remove mailboxes and re-enter the password?
This was for security improvement and was not really a bug but maybe an issue if users are not informed in the upgrade procedure.

What kind of workflow is not working?
When I create a ticket from the web interface or by email the ticket is created, assigned and notified by email so this is show that workflow are working for me.

**Comment by steveb85** [comment]
thanks @PeopleInside 

Those tickets are working fine. I found the problem when i tried adding a new agent, no email sent to them, then same with "forgot password" workflow, then i tested this version and i'm not getting the notifications email to agents after a ticket has been created. the tickets, and their responses are going to customers perfectly. 

I thought it was perhaps related, because after updating this, i had to re-enter the email passwords, and thought perhaps another part of the applicaiton is trying to access those for this workflow function?

best
steve

**Comment by PeopleInside** [comment]
Hi @steveb85,
maybe the issue can be related to the email address that help desk use to send notifications. 

How many email address have you configured on UVdesk MailBox and on SwiftMailer?
If you go on UVdesk email settings you can see what email address is used for send password reset email and other kind of notification, if you put wrong password or settings in UVdesk MailBox and on SwiftMailer than you won't receive any email.

Remember that currently UVdesk as a bad issue that is: no checks are made when you save email settings if email settings are wrong or correct: https://github.com/uvdesk/community-skeleton/issues/313

Maybe so the cause is UVdesk are unable to send email with password or host you inserted in UVdesk.
Be sure to update again credentials and be very slow on digit credentials as if you put that wrong, UVdesk will never alert you. Just you will get no email.

Check and hope this will help to resolve your issue.

**Comment by steveb85** [comment]
@PeopleInside i only have one mailbox and swiftmailer set up, and use them for everything
this was working before i did the update to v1.0.18 so i believe it’s something in either the update method used, or with that version. i’ve re-entered the swiftmailer details and checked them, however that same swiftmailer is working for sending out ticket replies just not these workflows

**Comment by PeopleInside** [comment]
In my install V 1.0.18 operator, customer password reset works, I also get emails when a ticket is assigned.
I don't know what can be, you can try to change the prod mode to dev and test than switch again on prod mode.

Each time you change the env file you need clear cache.
https://forums.uvdesk.com/topic/1988/how-to-debug-errors

If your issue persist you may need update here so we can try to ask to developers what you can maybe do for understand what is wrong.

**Comment by steveb85** [comment]
ok thanks! I’ll look at this tomorrow morning, and do a debug. hopefully it’s a minor thing to clear out. best steve

**Comment by steveb85** [comment]
@PeopleInside i re-installed the v1.0.18 as above, re did the mailbox and swiftmailer and re cleared cache, and it seems that things are working. I think we’re good, thanks for your support as always.

**Comment by PeopleInside** [comment]
@steveb85 I'm glad to read all is working fine now, I'm sorry to read that for resolve you need do a new installation.

**Comment by papnoisanjeev** [comment]
@steveb85  @PeopleInside 

Glad to know now all working fine now after re-install still any issue related to this please report us back here.
