### ISSUE TITLE
Vulnerability found in all email type input fields

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#48]
Found Vulnerability in the following page :
**Script used : "<script>alert(1)</script>"@gmail.com** 

1. ticket create from admin panel :- email field
2. customer profile update :- email field
3. Agent Profile :- email field
4. update customer information from ticket list :- email field do not have any validation

![screenshot from 2018-12-19 11-02-13](https://user-images.githubusercontent.com/43210406/50201426-0a004d80-0380-11e9-972d-e5eb34dc7fcd.png)

**Comment by shubhwebkul** [comment]
resolved
