### ISSUE TITLE
No puedo enviar ni recibir correos

### ISSUE THREAD

**Issue by ericastillo** [uvdesk/community-skeleton#484]
Por favor me podrian ayudar no puedo enviar ni recibir correos desde uvdesk.

Gracias.

**Comment by PeopleInside** [comment]
Actually, on my opinion, UVdesk miss a button in the admin interface that allow admin to clean cache without need to have access to SSH.

**php bin/console c:c** is to run in SSH where you run composer command.
I don't know where you do on docker composer.

You need be on the UVdesk root folder on SSH and run that command.
After that when you refresh the email settings page you should see the correct email address.

For me sound to be a bug: when user save email settings clearing of cache should be performed and a refresh of the page also with correct email info but this is not happening, you need run the provided SSH command to clean cache.
