### ISSUE TITLE
Version 1.0.18 not usabe, fatal server errors

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#495]
Thanks, for me the new version still generate a fatal error if the error page 404 is showed.
After I click on a link in the 404 page my server give an error and helpdesk turn down.

I do this:
After following all updating instruction given by you I try to load an inexistent URL like https://helpdesk.peopleinside.it/it/dtrtrt
than I click on one of the links in the new 404 page and server get down with a fatal error.

![uvdesk new error](https://user-images.githubusercontent.com/5006150/139229476-029798b5-ecdb-4ac4-a6c4-ccdbce020ba7.gif)

https://github.com/uvdesk/community-skeleton/discussions/493

**Comment by PeopleInside** [comment]
I'm closing this issue for now also if **is not resolved**.

The reason why I do this is because I will diagnose with Webuzo team as the error seems to be from Webuzo and here seems I'm not getting useful info on why I'm facing this.

**Comment by PeopleInside** [comment]
The Webuzo team tested the new version of Uvdesk and told me they get the same issue on Cpanel so they suggest to report the issue to you.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 
I have tested with prod mode but here are not showing this type of issue or errors on the 404 page not found. 

You can see here:
https://www.loom.com/share/4b99694d96e34770be54388b8bb67f1f

**Comment by PeopleInside** [comment]
@Komal-sharma-2712 thank you but what I can do now?

I forwarded this issue to the Webuzo team, they said the issue if from UVdesk and they was able to reproduce the issue also on CPanel.

Webuzo say is UVdesk, you show me no issue in UVdesk so what I should do, not upgrade and still run an old version?

UVdesk tested in localhost by you with what version of PHP?
Under Apache?

In any case I need run on a servernot on localhost.
I'm not new in UVdesk so I'm just reporting I'm unable to upgrade, even new instalation from Softaculous installer give error, see UVdesk ticket N #26712

I need a solution.

**Comment by PeopleInside** [comment]
I'm running PHP 7.4.24
Now the issue can be from PHP or from UVdesk.

I need understand this and how I can resolve.
Unfortunately Webuzo doesn't yet allow me to install PHP 8.0 so I cannot test with a different supported PHP version.

The error server log say:
[proxy_fcgi:error] [pid 20263] (104)Connection reset by peer: AH01075: Error dispatching request to : 
[proxy_fcgi:error] [pid 20263] [client ****:56025] AH01067: Failed to read FastCGI header

**Comment by PeopleInside** [comment]
There is a particular new Apache, PHP requirements for UVdesk 1.0.18 that was not necessary in UVdesk 1.0.16?
I still be in touch with the Webuzo team that I understand continue to think the issue is in UVdesk.

Is a real strange issue, all works on my server except UVdesk 1.0.18
The error seems to be a Webuzo 50 X error but they said also on CPanel there is a 503 server error.

You show no issue on localhost but I don't know what version of PHP are you using.
In any case I need help to resolve the issue to be able to upgrade to the latest UVdesk version.

**Comment by Komal-sharma-2712** [comment]
I used PHP version 7.4.22 and apache version: Apache/2.4.41

**Comment by PeopleInside** [comment]
Hum maybe is possible to test with PHP 7.4.24?

But also if in that case all works I still need help because I need upgrade UVdesk and due to the 50 X error on Webuzo I'm unable to do.

So actually webuzo team say the issue is UVdesk and UVdesk say all is fine.
Results.. I'm unable to use latest version of UVdesk.

I need find help and solution to this.

**Comment by PeopleInside** [comment]
I hope in some help from you or I need find an alternative version in the future if I still be not able to resolve this.
Also... I'm not reeving no more, since weeks, email notifications when you reply to the ticket #26712 so you should have some issue in email configuration or in spam score.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 
our team working on that issue and ticket and we will resolve it as soon as possible. 

our team will reply you soon.

**Comment by PeopleInside** [comment]
@Komal-sharma-2712 ok thanks. Unfortunately seems when you reply to that ticket I get no email so your outgoing email has spam issue or something is broken. I tested the reset password on your ticket system and I get the email. I will monitor the ticket online :) Thanks.

For now if you where not able to reproduce the issue I reported here, you cannot resolve. This is my worry but I hope you will understand and fix what is wrong. Thanks again.

**Comment by PeopleInside** [comment]
Just for information, in dev mode on V 1.0.18 I'm unable to get 50 X error.
In prod mode I'm able to get always this error even navigating the operator panel... just clik some link and get server error while in dev mode not.

**Comment by PeopleInside** [comment]
![uvdesk18 bugged prod](https://user-images.githubusercontent.com/5006150/140233161-802fe8e8-15d7-4106-946c-e8cca0c04854.gif)

**Comment by PeopleInside** [comment]
The issue seems to be from Webuzo side as UVdesk team has showed all works fine on locale and on the server.
Sorry... I will write again to the Webuzo team where seems hard to get support for this issue.

**Comment by PeopleInside** [comment]
This issue seems to be caused by PHP 7.4.24 used by Webuzo.
I suppose Webuzo team need upgrade PHP to the latest PHP 7.4.25

In my test with PHP 7.3 that I cannot run because is no more supported by other app I use, UVdesk 1.0.18 seems to work fine

**Comment by PeopleInside** [comment]
Webuzo team tested with PHP 7.4.25 also on CPanel and they say the error persist so the issue seems to be in UVdesk. Also is curios to see that on dev mode the issue are not present.

**Comment by PeopleInside** [comment]
Seems this issue as other issue will be not resolved or maybe will require a long time for be resolved.

A strong issue is regarding duplicate ticket, issue not resolved. Another important issue is that delete email are forever and are not moved to trash, this is another issue opened and another important issue is that there is no way to have sent email from UVdesk to be avaiable in the sent folder.

How about this issue to be unable for almost a month to update to the latest version of UVdesk?

Now, I'm using the Webuzo control panel and not only mi install of UVdesk 1.0.18 is not working but also creating a new install from Softacolous panel, it give the same exact issue confirmed also from the Webuzo team panel staff.

If I'm not wrong, if I never missunderstood, the Webuzo team are able to reproduce the issue also on the CPanel so not only in Webuzo Control panel.

This let me think the issue is of UVdesk also because I have no issue in the old installation 1.0.16 where all works fine so how can be an issue of my server?

In the other hands maybe I tested UVdesk 1.0.18 with PHP 7.3 (that is old and should not be used) and the error seems is not present, also if I turn UVdesk into dev mode, the error is not present. This let me think the issue can be the PHP version on the first case and on the second let me think something is wrong in UVdesk that work on dev but not on prod.

As you can understand I cannot give full VPS access to diagnose this issue so, as I don't see any solution, any light I suppose this will be the end of the story: I need find another software solution for manage my ticket. 

Really sad.
Instead of asking full access to my server, you need to consider to give remote support, this will allow you to see the issue on the customer, user PC without getting full access to the server where you also are taking a big responsability in the case you do any damage when admin cannot check what you are doing on his server.

I'm really sad to see this issue and other issues ... issue that are most important, still be frozen.
UVdesk is nice but strong issues should be resolved and not after too many months or to be kept unresolved.

**Comment by PeopleInside** [comment]
Resolved with your support and PHP 8.0
