### ISSUE TITLE
Improve error / confirmation messages

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#497]
**Description**  

Today while I was doing some ticket test I discover an issue:

during a ticket test generated from the web, once submitted the email error red message was showed but has hidden really quickly that was impossible to read.

Can you add settings in branding where admin can decide how many time show the error and confirmation message?
Can you also add a check box for disallow timing and let user close the message with the x near the message?

If you can also tell me where edit the code to fix this asap will be nice.

***
Actually if an error sending email occur the error message is showed for a very short time, almost impossible to read.
I set a long message and the timing where this is showed is very insufficient.

I want maybe to be able in the future to customize that timing because you can set more time but maybe can be not enough for me.

**Where I can edit and fix for now? I want edit the time where confirm, warning message are showed. Too shorter time right now**
In the future maybe a settings in branding section will help the admin to customize this on his needs.

**Comment by PeopleInside** [comment]
Currently email error is unreadable in my case as is showed for a very short time. I must change this, my Italian message is more long.

The error swift email error is not understandable from users, the error message should be more friendly like: an error occurred while sending email notification, please inform admins.

**Comment by PeopleInside** [comment]
https://github.com/symfony/symfony/discussions/44324

**Comment by PeopleInside** [comment]
Can be an idea to use https://php-flasher.github.io/ for have more control on notifications?

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We can manage it from our side please locate path in your project.
**public/bundles/uvdeskcoreframework/js/_common.js** 
open **_common.js** and reach to  function name **renderResponseAlert** (line no **258**).

Now you can increase time as per your requirement.
![image](https://user-images.githubusercontent.com/42460055/144002898-aa02964d-3d86-4ed6-8fbf-65e5735eb1c9.png)

You can replace **fade out** and **timeout** values here.
For example make **fadeout** current value 500 to 1000 or any greater number and timeout value 5000 to 10000 or any greater number. How much time you want to increase.

And make a try !!

**Comment by PeopleInside** [comment]
Thanks I will try
