### ISSUE TITLE
If the attachments is big, a wrong email error is showed on ticket submission

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#498]
# Bug report

### Title
If the attachments is big, a wrong email error is showed on ticket submission

### Issue Description

Following the forum guide: [How I can increase attachment size?](https://forums.uvdesk.com/topic/1872/how-i-can-increase-attachment-size) I increased attachments to 1 GB than I try to submit a ticket from the web interface.

Results: Ticket is created, email has been sent but a red message is showed for a too short time that alert some error occured during email sending... this is not true.

### Preconditions

UVdesk 1.0.16

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Set attachments to be 1 GB in uvdesk.yaml
    2. Clear cache
    3. Submit a ticket online in the web interface attaching something of 59 MB or more

### Expected result

Ticket should be created with just sucesful message

### Actual result

Ticket is created, all email are sent but a red message inform the user an error occurred while sending email.

PS: I'm evaluating to move to another help desk solution doing too many issue that still be unresolved.

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

Actually, that error comes from email sending. They are not allowed to send that many big files. It is not a ticket-creating error. It is an error of a big file attaching in that email.

If I am not wrong Gmail Attachment size up to **25 MB** in attachments.

**Comment by PeopleInside** [comment]
Umh... I understand so the issue is generated because when user create an online ticket the attachment is attached to the email.. in this case is correct the alert is showed and in fact I cannot find ticket creation email confirmation message sent to the user.

OK so no much here we can do... in this case.
Maybe I can decide to not attach attachment or if the attachment is bigger more than 25 MB should be good not attach to the email and add in the email an alert text that invite the customer to download the big attachment online, in the web interface.

This will avoid error showed in UI and avoid also ticket email confirmation to be not delivered.
