### ISSUE TITLE
Mails aren't fetch as ticket at admin end after configure a mailbox

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#50]
Steps which i follow to configure mailbox: -
Configure mailbox:
**Swiftmailer.yaml -->** 
swiftmailer:
    # url: '%env(MAILER_URL)%'
    # spool: { type: 'memory' }
     mailers:
          textkumar:
              transport: gmail
               username: test123@gmail.com
               password: *****

**uvdesk.yaml--->**
  # Configure your mailboxes here
    mailboxes: 
        textkumar:
            name: Sample Mailbox
            email: test123@gmail.com
            enabled: true
        
            # [SMTP] Outgoing mail server
            # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
            smtp_server:
                mailer_id: textkumar
        
            # [IMAP] Incoming mail server
            # IMAP configurations to use for fetching emails from mailbox
            imap_server:
                host: '{imap.gmail.com:993/imap/ssl}INBOX' 
                username: test123@gmail.com
                password: *****

   **Run command:** 
$ php bin/console uvdesk:refresh-mailbox test123@gmail.com

**BUG:** no ticket found

**Comment by shubhwebkul** [comment]
resolved
