### ISSUE TITLE
Profile picture or attachments not removed on ticket or profile deletion

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#506]
# Bug report
### Issue Description

If a customer set a profile picture, create ticket with attachments and if the profile of the user are deleted from an admin operator with all tickets, profile picture and ticket attachments still be exist on public/assets/

**profile**

and

**threads**

folders.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 1.0.18
    2. don't know

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create a ticket from UI that generate also a new customer
    2. On the account creation email create a password for the user profile (customer)
    3. Upload a custom profile picture
    4. Add attachments to the existing opened ticket

1. Now on the operator side delete the customer profile and be sure all customer tickets has been deleted.

### Expected result

Customer has been deleted with also all tickets so surfing on public/assets/ and than the two folders profile and threads should not show the user profile picture and the ticket user folder with the attachments

### Actual result

On public/assets/ profile and threads you will find user deleted picture and relative folder with the attachments.

I never tested if for operator the picture is not deleted when an operator is deleted.

Please fix.
When a customer is deleted with all his ticket or a ticket is deleted, profile picture and attachments should not stay on the server, taking space!

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Thanks for reporting !!
We will check and fix it as well.

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/support-center-bundle/pull/155

**Comment by PeopleInside** [comment]
Great, if profile delete is fixed should be fixed also ticket attachments that are not deleted if customer is deleted with all ticket.
don't know if is deleted if the single ticket is deleted, I never test this.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Yes, for single ticket permanent delete action it is working please check if not please let us know.

We are fixing for customer all ticket attachments from physical path if we delete customer.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 
This issue is now resolved in the latest release of UVdesk v1.1.0 for the customer and also the admin side:

- If we delete a customer so delete the profile and attachments on this path: **public/assets/profile** and **public/assets/threads**
- If we delete an agent so delete the profile on this path: **public/assets/profile**
