### ISSUE TITLE
Tried building a docker file

### ISSUE THREAD

**Issue by Palmer-Hub** [uvdesk/community-skeleton#507]
I tried building a `Dockerfile` (and Podman), as instructed by, https://docs.uvdesk.com/uvdemo/default/docker.html and it wont build

```shell
$ podman build -t=uvdesk .
STEP 1/14: FROM ubuntu:18.04
STEP 2/14: LABEL maintainer="akshay.kumar758@webkul.com"
--> Using cache efcd7022f9140dff15dd17e2b58162d623506e2fcb935a28bac62a776c1a3aa8
--> efcd7022f91
STEP 3/14: ENV GOSU_VERSION 1.11
--> Using cache e723041eeba4e83625c6e7b450e17a9d6c89aa118aa6b1435794f480c6efc4a0
--> e723041eeba
STEP 4/14: RUN adduser uvdesk -q --disabled-password --gecos ""
chfn: PAM: System error
adduser: `/usr/bin/chfn -f  uvdesk' returned error code 1. Exiting.
Error: error building at STEP "RUN adduser uvdesk -q --disabled-password --gecos """: error while running runtime: exit status 1
```

```shell
$ uname -a
Linux localhost 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Steps to recreate

1:  `Clone repo`
2.  `podman build -t=uvdesk`

Outcome Desired:

A built docker image.

**Comment by Komal-sharma-2712** [comment]
@Palmer-Hub 

Please try once the docker command you are using podman
you clone it latest docker file from here: https://github.com/uvdesk/community-skeleton/blob/master/Dockerfile

**Comment by vipin-shrivastava** [comment]
@Palmer-Hub 

Any update?

**Comment by vipin-shrivastava** [comment]
@Palmer-Hub 

Still not getting any update from you. we are closing this issue as we take this issue has fixed. 
If you still facing the issue you can re-open this.
