### ISSUE TITLE
Operator Ticket creation issues V1.0.18

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#510]
# Bug report

### Title

1. Operator seems have no option to create a ticket for existing customer, need insert all data manually.
2. When operator create a ticket for the customer seems text email formatting are not respecting spaces or sentences in a new row: all is showed as plain text very hard to read, see bug details bellow for see example of the issue. 

### Issue Description

1. When operator are logged and click on his profile on top right than create new ticket, a drop down or an easy solution to create ticket for an existing customer without have to remember name, and email address, should exist.
2. When the ticket is created the text reported in the email should respect text formatting. The editor is missed from operator creating ticket interface but if after a sentence I go in a new row, email should also show the sentence in a new row not all text unify in a unique row.

### Preconditions
**Please provide as detailed information about your environment as possible.**

UVdesk 1.0.18

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

Issue 1

    1. Login as operator in the Dashboard
    2. Be sure to have an existent customer
    3. On right top click to create a new ticket: you have to insert name and email manually if no ticket exist for this user. There is no way to auto-fill name and email field.

Issue 2

Create a text with some sentence in new row so a text with some spaces between rows.
When the ticket will be created and sent to the customer, as I have in the template (customer ticket creation email) to report the content of the ticket.

**The issue was fixed if the text is a reply in the ticket but not if the ticket is created from an operator in the Dashboard interface!**

![1](https://user-images.githubusercontent.com/5006150/145020078-0ab2ffbc-de37-433e-854f-643fb169c63b.jpg)
![2](https://user-images.githubusercontent.com/5006150/145020079-446a0442-856d-459d-a127-08dc2699fb79.jpg)
![3](https://user-images.githubusercontent.com/5006150/145020083-8895f0a7-5ffb-48a8-9afa-c128d2174af6.jpg)

### Actual result

Te text not respect spaces and new rows.

**Comment by PeopleInside** [comment]
Currently also, if the ticket is created from the Dashboard no operator signature is attached.
Will be maybe nice add the text editor and attach the operator signature as is now working for ticket replies.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 
On the operator side we if we create a ticket on behalf of a customer then it is just a text field option given and does not contain more information(exact space given, or text bold, etc) like an editor.

So for further conversation, once the ticket is created client and operator both have an editor option for making
replies for discussing issues in detail and with a text editor option.

**Comment by PeopleInside** [comment]
@Komal-sharma-2712 
If an operator create a ticket for the customer the text written by the operator should be clear and not confused.

The fact to sending all text as attached row that has no spaces and not respect new row make the ticket very hard to understand for the customer. I seen this by email and it's terrible.

I tested today because need inform an user to check the UVdesk new ticket duplicate issue and get by email a terrible text very bad to read... so what I should do, create a duplicate message as reply in the ticket because UVdesk never support a good ticket text field when operator create a ticket?

Sound to have no much sense.

On the point of view you are describing I need to remember that no important text should be written in Dashboard ticket creation because this will generate a very bad and unprofessional email. An email from the ticket system that seems a game not a real professional ticket email where text is understandable.

On your point of view, where you told that text if well formatted in reply, I need always send two email message to the customer, one with just a "we are creating ticket" and the other one with the ticket content... this sound to be not good.

Will be nice if you can improve this and add the editor and the text formatting also on Dashboard on new ticket creation.
Will be also useful have a drop down menu or an option to create a ticket using existing customer details.

Now I have the doubt, the wrong text formatting will be the same if ticket is created from customer by using the web form on ticket where editor is not present? If yes, also in this case you need improve.

**Comment by PeopleInside** [comment]
Consider also that in my screenshot the text is short because is a test,
on the real ticket I created today "for the customer" the text was more long: many rows.

The result is terrible!
I loosed my time to wrote all this text to have a very bad email sent to the customer.

Using ticket system should improve the user experience not devastating it with email sent from the website interface that is without spaces and text formatting. I'm sure this has sense (my point) and the way the system is working now is not good.

Improve this should be not a too much big request and work, I hope.

**Comment by PeopleInside** [comment]
Due to this BUG I need now remove the tag that add ticket message in the creation template because as is now is UNUSABLE.
I hope this issue will be resolved.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

We have added added editor now you can check.

Locate path in your project.
**vendor/uvdesk** under **uvdesk** folder you will see **core-framework** and **support-center-bundle** folders.

Delete **core-framework** and **support-center-bundle** folder.

Then again clone both using below command at same place (under **vendor/uvdesk** folder).

**git clone https://github.com/uvdesk/core-framework
git clone https://github.com/uvdesk/support-center-bundle**

Finally clear your cache  using below command or from web interface.
**php bin/console c:c**

**Comment by PeopleInside** [comment]
Great improvement, thanks.

Just maybe add again the resize window if possible.

![Immagine 2021-12-08 113528](https://user-images.githubusercontent.com/5006150/145194016-f9352da7-b7e2-4803-bb95-b29b54fb0d27.jpg)

Text box should be resizeable.

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

We have added the resize option to the editor.

Locate a path in your project.
vendor/uvdesk under uvdesk folder you will see core-framework and support-center-bundle folders.

Delete core-framework and support-center-bundle folder.

Then again clone both using the below command at the same place (under vendor/uvdesk folder).

git clone https://github.com/uvdesk/core-framework
git clone https://github.com/uvdesk/support-center-bundle

Finally, clear your cache using the below command or from the web interface.
`PHP bin/console c:c`

**Comment by PeopleInside** [comment]
@vipin-shrivastava I don't remember if I miss your last message here where you told you added the resize option to the editor.
For mee seems is not working... I never updated again today but when I load https://helpdesk.peopleinside.it/it/usr/create-ticket/ I see for a very short time the option to resize but is immediately hidden.

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

Thanks for informing us. We will check it & update you soon.
