### ISSUE TITLE
In the ticked assigned email template the tag to include the ticket message is not working

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#511]
UVdesk 1.0.18

Steps to reproduce:

1. Login in the operator Dashboard
2. Open email templates
3. Edit Ticket Assign adding the tag: {%ticket.message%}
4. Try to open a ticket that is assigned to you and check if the ticket message is reported in the email

The email will not have any ticket message reported.

Should not work the tag  {%ticket.message%} even in the ticket assign template?
Maybe operator want to have a preview of the ticket content by email.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 

For ticket assignment, the email template already contains placeholder {%ticket.message%} and working fine.

When ticket assign email template:
![image](https://user-images.githubusercontent.com/63539748/145196211-d56e6a1a-e4c9-4521-bd47-f455c3443087.png)


When after assigning the agent and going to agent mail:
![image](https://user-images.githubusercontent.com/63539748/145196385-9838b992-fefc-43ce-964a-8710d85ec3d1.png)


Please let me know where you are facing the issue.

**Comment by PeopleInside** [comment]
Hum I have a workflow where ticket is assigned to the group.
For me message is not showed.

![1](https://user-images.githubusercontent.com/5006150/145198746-32ee30e7-5e49-4abf-95a5-3ccb13d202ee.jpg)
![2](https://user-images.githubusercontent.com/5006150/145198763-685e2992-aa0d-4b00-b61d-f9dcceeaf666.jpg)

**Comment by PeopleInside** [comment]
In my help desk a ticket is not assigned to a single agent but a group.
Also in this case message should be reported by the email that groups operators receive.

Non assegnato = not assigned to any operator but is assigned to the group that are informed by email

![3](https://user-images.githubusercontent.com/5006150/145199419-0b16228a-dd08-43bb-a5ae-dbd03c4fc9b2.jpg)

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 

Please use {%ticket.threadMessage%} and again make a try.

**Comment by PeopleInside** [comment]
`{%ticket.threadMessage%} `

This is working.
It's so just a wrong tag used by me?

Should close this issue?

**Comment by Komal-sharma-2712** [comment]
Yes
