### ISSUE TITLE
Cannot add Third link on footer

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#512]
V 1.0.18
PHP 8.0

I need add a third link in the footer.
The system never let me add the third link as I cannot save the page, nothing happen.

How can I increase this limit?

![Immagine 2021-12-08 142127](https://user-images.githubusercontent.com/5006150/145215570-46102367-667d-4451-ada5-9000a23c640f.jpg)

This is what I need save but with three link in the footer the system never let me save.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 
We used four link in the footer and also in the header and working fine.

![image](https://user-images.githubusercontent.com/63539748/145217134-38ccc733-1cf8-40f1-a840-05d44562e294.png)

On Customer dashboard:
![image](https://user-images.githubusercontent.com/63539748/145217447-5fc0601d-a351-46a2-a2cb-a0034df163cc.png)

**Comment by PeopleInside** [comment]
@vikhyat-webkul , @papnoisanjeev 
any idea on how can I diagnose why I cannot add the third link?

Clicking saving is not saving and link is not added.
Can be a database issue or where I can look?

Thanks.

**Comment by PeopleInside** [comment]
Issue seems has get resolved I don't know why.
Better.
