### ISSUE TITLE
Disabling Frontend-Website has no effect

### ISSUE THREAD

**Issue by Gill-Bates** [uvdesk/community-skeleton#514]
When I disable the frontend website, I would expect, that the Page is not longer shown:

![image](https://user-images.githubusercontent.com/25774289/145730344-ad20fabf-e992-4ea6-9b98-be3165b65f20.png)

Result: Website still visible

![image](https://user-images.githubusercontent.com/25774289/145730381-1d278eba-da6c-467a-a2c1-aa3b32016fff.png)

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

As we checked we didn't find this issue in Uvdesk Opensource v1.0.18. 
https://www.loom.com/share/f478ea114e9e4f8a92c47eed81cfbfcc

Please tell us. What steps did you follow to disable the knowledgeBase?
Which version of uvdesk are you using?

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

Any update?

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

we closed this issue, If you still face this issue reopen it again,

**Comment by Gill-Bates** [comment]
Before you close the ticket it might be good to clarify where the two database entries come from. I did not create them.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

I asked you, what steps you have done after installing uvdesk which creates the two entities?

I have set up two fresh installations & set up branding also try to disable the website multiple times,  but have not found this issue. 
In my case, Only one entry is there.

**Comment by Gill-Bates** [comment]
I‘ve reinstalled uvdesk. The issue was not reproducable. Looks for me for a broken installation. Closing this case seems to be ok.
