### ISSUE TITLE
LimitInternalRecursion Error on Installation UVDesk

### ISSUE THREAD

**Issue by umutgur** [uvdesk/community-skeleton#525]
# Installation Error

### Instalation Error: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

After Completing installation steps, UVDesk app getting internal server error called by "Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace."

### Issue Description
After completing installation steps, I got the error which I wrote above. It's about many redirection and I guess there is a infinite loop because of .htaccess. So I created a index.php file in public folder, index.php file opened

### Preconditions

1. Digital Ocean Droplet with Ubuntu 20.04 (LTS) x64
2. Apache/2.4.41 (Ubuntu)
3. Running PHP version: PHP 8.0-fpm

.htaccess file:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ ./index.php/$1 [QSA,L]
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>
```

**Comment by vipin-shrivastava** [comment]
@umutgur The .htaccess file in webroot should look like:

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ ./index.php/$1 [QSA,L]
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>

instead of this:

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ ./index.php/$1 [QSA,L]
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>

Please make a try with this.

**Comment by Komal-sharma-2712** [comment]
@umutgur 
For now, I am closing this issue as we didn't get any response from your side.

Reopen this issue any time, If you still facing the same issue.
