### ISSUE TITLE
Sort Order in Categories (knowledge base) is overridden by updating an article

### ISSUE THREAD

**Issue by steveb85** [uvdesk/community-skeleton#526]
# Bug report

### Title
when you update a category, it goes to the bottom of list on front end, regardless of the sort order. IE the most recent is at the bottom and sort order is ignored. 

### Preconditions

v -1.0.18 

### Steps to reproduce
edit a category. 
order is ignored. to fix you ahve to open and save each article in the order you want the categories displayed within the folder.

**Comment by Komal-sharma-2712** [comment]
@steveb85 
Now this time sort order working on the admin side in the sort order filter option. You can check [here](https://prnt.sc/26w7s3f).
The front end(customer side) does not show the sort order of categories because here sort order is ignored but we will try it in the next release.

Thanks

**Comment by Komal-sharma-2712** [comment]
This issue is now resolved in the latest release so we are closing this issue. If you are getting the same issue so reply on the same thread.
