### ISSUE TITLE
Getting set up with the helpdesk

### ISSUE THREAD

**Issue by Nawta1** [uvdesk/community-skeleton#529]
Can anyone confirm if there are any up to date guides on how to install the help desk on Windows 10?

I've followed the guide on the website, and the steps are not detailed enough to follow for me. 

I've installed and set up composer, downloaded the ZIP file, extracted it into C:\Bitnami\wampstack-8.1.2-0\apache2\htdocs\localhost 

When I open a browser and type localhost/local host I see the folder structure, however when I click public (I assume public, as on the website installation guide the text looks like it's been clicked on due to being a different colour), the webpage doesn't load and runs into an issue.

I watched a YouTube video produced by uvdesk and followed their steps, though for me it doesn't work.

Any help appreciated.

**Comment by vipin-shrivastava** [comment]
@Nawta1 
Sorry to know that you are facing hard to understand the uvdesk user guide. we will update the guide soon.

For now, Follow the below steps:
1. First, extract the downloaded uvdesk zip & put that inside htdocs folder (eg: C:\Bitnami\wampstack-8.1.2-0\apache2\htdocs\)
2. Now open your browser & enter localhost/your_helpdesk_folder_name)/public.
3. It will open the setup wizard on your browser.
![image](https://user-images.githubusercontent.com/58874186/154623141-0714bb5e-a7c1-48f8-9eb8-9dc440ee04db.png)
4. Now, you can follow our user guide to setup uvdesk from [here](https://docs.uvdesk.com/uvdemo/installation/installation-windows.html).
5. Skip step 1 & step 2, Follow step 3 directly.

Hope, This will help you. If you still have any confusion or issue regarding uvdesk. Please let us know.

**Comment by vipin-shrivastava** [comment]
@Nawta1 
For now, I am closing this issue as we didn't get any response from your side.

Reopen this issue any time, If you still facing the same issue.
