### ISSUE TITLE
Email notifications issues V 1.0.18

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#530]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

Customer open a ticket by using the web contact form using an email that is not a real email but a forward means email@domain.ext will not receive any email, will just forward it to another email account for example Gmail.

Customer so submit the ticket using email address email@domain.ext
all email notification (ticket creation, ticket account creation and tickets replies) will be received by anotheraddressexample@gmail.com

Now customer will reply to the ticket creation email with the Gmail account.
Reply are added correctly to the existing ticket, another user account will be created for Gmail address.

**Issue 1: operator emails sent to the customer:**

The new reply operator alert is sent to the operator but also to the customer at email Gmail.
Customer that added to an existing ticket that was generated from email@domain.ext but has replied with Gmail account so reply has been added to the existent ticket, Gmail should not receive operator alert that a new reply has been added and login to the ticket for manage it.

I tested also a reply to the ticket from the operator side so made a reply as operator to the ticket.
**Issue 2: The reply to the ticket was added to the ticket but without any email notification to the operator.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: V 1.0.18
    2. Commit id. Don't know.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create an email that has no inbox but is a forward email to another email address. Example test@domain.ext forward email to a Gmail email address 
    2. Create a ticket as customer from the web interface inserting the forward email test@domain.ext
    3. Submit the ticket.
    4. You will receive all email notification on the Gmail account, try to reply to the ticket creation email and the reply should be added correctly to the ticket and will be notified to the operator but the same operator email notification template is sent also to the user and this is a error. The email received by the customer say a customer has replied to the ticket to login in the operator control panel console.
    5. Try to made a reply as operator to the ticket
    6. Once you get the email in Gmail try to reply to the operator email: no notification about this reply will be sent to the operator.
- 

### Expected result

**Issue 1: operator emails sent to the customer:**

This should not happen

**Issue 2: The reply to the ticket was added to the ticket but without any email notification to the operator.**

All ticket replies should be notified to the operator.

*   [Screenshots, logs or description]

### Actual result

**Issue 1: operator emails sent to the customer:**
The customer Gmail account will receive the same operator email that inform that a customer with email test@domain.ext has replied to the ticket so to login in the operator console to manage the ticket. This should be not happen.

The original email address that opened the ticket is test@domain.ext but customer replied to the ticket from Gmail email address.
The reply was correctly added to the ticket, a Gmail customer account has also been created and not notified to the Gmail email address, this is maybe fine but the Gmail email address should not get email as operator. It's a customer!

**Issue 2: The reply to the ticket was added to the ticket but without any email notification to the operator.**

The situation of the ticket is:

test@domain.ext created the ticket
All ticket notification arrived to a Gmail email address
the customer replied to the ticket creation email from Gmail so the reply has been added correctly but from a different account that has been added to the ticket help desk system. Seems is added as operator not as customer as the reply generate an email to operator and to customer.. when only the operator should get new response email.

When the operator made a reply to the ticket and customer reply from the Gmail account, the reply is added to the ticket but no more notified by email to operators.

* [points....]

**Comment by PeopleInside** [comment]
I tested again in the same existing ticket a second operator reply.
The operator reply has been sent.

All customer replies was added to the ticket but no email notification about those replies was sent to operators.

This is a strong issue and should be resolved.
Issue 1 and Issue 2

**Comment by PeopleInside** [comment]
Seems workflow stop to work in this particular case where user reply to a ticket with a different email address.
Not only no email alert is sent to the operator but also workflow to reopen ticket if the ticket is closed and a reply is added stops to work. The reply are added to the ticket but no notification to operator and the ticket status is not changed.

This is a strong bug that let me miss ticket replies.

**Comment by PeopleInside** [comment]
![img](https://user-images.githubusercontent.com/5006150/155232339-4b046c44-9193-4fd7-87ac-6a87f19a8ac7.png)

Look at the screenshot.

1. **Customer A with email forward** test@domain.ext has a message in the ticket.
2. The operator reply to the ticket **(operator)** in the screenshot
3. The reply is sent to test@domain.ext that has no inbox so email is forwarded to the Gmail address
4. Customer A receive the ticket reply to the Gmail email address
5. Customer A reply to the ticket email operator reply
6. The reply is added to the ticket as showed in the screenshot **Customer A Email 2 (Gmail)** but is not notified to the operator 
7. Even if the ticket is closed and a workflow is set to open a ticket in a case of a reply, the ticket status is not changed

Seems the reply from a different email address is added to the ticket but this will broke the ticket workflow for everything will happen after.

If Customer A make reply from his Gmail email address the operator are no more informed and ticket status are no more updated.

My Workflow:

![Immagine 2022-02-22 235254](https://user-images.githubusercontent.com/5006150/155233145-ee208125-7e3a-4fa8-b7bc-fd269484c4a7.png)

If ticket have a customer reply and the ticket status is not pending, reopen the ticket.

I think the bug is: the Gmail account is added to the ticket but is not the original email address that opened the ticket so.. reply from Gmail is added but Gmail address is not considered a customer this seems is the reason why no reply is notified to the operator and ticket never change status... workflow give false and not true.

Still be in doubt why I get an email the initially informed the customer with the operator email template that a reply has been added. I suppose this happen because the Gmail 2 address in the ticket is not added as customer. Something broken even if a customer profile is created.

**Comment by Komal-sharma-2712** [comment]
@PeopleInside 
We will check it and update you very soon.

**Comment by PeopleInside** [comment]
Thank you!



Il giorno 23 feb 2022, 14:45, alle ore 14:45, Komal Sharma ***@***.***> ha scritto:
***@***.*** 
>We will check it and update you very soon.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/uvdesk/community-skeleton/issues/530#issuecomment-1048797297
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by PeopleInside** [comment]
I hope UVdesk will be keept updated, seems no update since some month, no improvment and no issues fix: no issue has been closed recently. I hope also this issue will be not opened for long time because this scenario made operators miss tickets.
Thank you ! Loving UVdesk.

**Comment by PeopleInside** [comment]
@Komal-sharma-2712 now I can say your words to hear you very soon about this issue are not true.

**Comment by Nitz992** [comment]
I am also facing similar issue as mentioned above. 

Operator A forwarded email to operator B from admin panel and its not notifying to customer through email or in conversation of user panel.(this is the right flow) but operator B replying from email on that forwarded email it's notifying the customer to as new reply added and as well it is appearing in conversation history of customer panel. 2nd operator reply should not be visible to customer or customer shouldn't receive email for that. For me it's very critical issue because internal email will popup to customer directly.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

If in your case it was an issue.
we have added some more checks in email service in case message Id missing.
https://github.com/uvdesk/core-framework/commit/3b28bb1dd94be7436b0e9661b68012ee7f61e8fe

Hope issue will resolved by this.
