### ISSUE TITLE
Publish pre-built docker images

### ISSUE THREAD

**Issue by stavros-k** [uvdesk/community-skeleton#533]
**Description**  

It would be great to have pre-built images readily available in ghcr or docker hub or where ever!
That would make it even easier for people to spin it up, eliminating the need of build it.

Also would make it easier for people to build "easy installs" in various systems, like Unraid, Synology, TrueNAS SCALE.

I know it's easy to build an image and also keep it up to date with the releases using a CI etc. 
But I'd prefer having an official one. 

**Example**

**Comment by papnoisanjeev** [comment]
@stavros-k 

We would love to accept contribution from your side.
Please raise a Pull request for the same and we will add it with project after review.

**Comment by stavros-k** [comment]
> @stavros-k
> 
> We would love to accept contribution from your side. Please raise a Pull request for the same and we will add it with project after review.

I'd love to, but I don't have that much time right now. 
I'm maintaining an app catalog for TrueNAS Scale, and a user asked if we could add this to the catalog.

I didn't see any prebuilt image, so I asked if that was possible!

Maybe once I have some more time, I do a PR. But no guarantees here.

**Comment by Komal-sharma-2712** [comment]
@stavros-k ,

We have published our **official docker image on docker hub**. Please can check the below link:
https://hub.docker.com/r/webkul/uvdesk

Now we are closing this issue or suggestion. 

Thanks and Regards,
Uvdesk Team
