### ISSUE TITLE
Script cache:clear returned with error code 255

### ISSUE THREAD

**Issue by rajasuresh2** [uvdesk/community-skeleton#534]
Not able to open console using php script, i am getting below error when running the command "php console"

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Declaration of ContainerSNGxBdg\srcApp_KernelDevDebugContainer::getParameter(string $name) must be compatible with Symfony\Component\DependencyInjection\Container::getParameter($name) in /var/www/uvdesk/var/cache/dev/ContainerSNGxBdg/srcApp_KernelDevDebugContainer.php on line 17
!!  PHP Stack trace:

**Comment by Komal-sharma-2712** [comment]
@rajasuresh2 
Which version of UVdesk are you using and also which version of PHP are you using?

**Comment by rajasuresh2** [comment]
Hi Komal,  I could able to install the product with the help of Akshay.  Right now i am working on validation of the product.  Thanks

**Comment by steveb85** [comment]
I am having this exact same issue, what was the solution?

**Comment by steveb85** [comment]
i seem to have fixed it.
