### ISSUE TITLE
When using wamp server showing an error in uvdesk installation

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/community-skeleton#537]
# Bug report
Uvdesk installation when using wamp server

### Issue Description:

- Install wamp server
- Download zip file or use command of UVdesk project
- Now run the project on the browser showing an error:
**This site can't be reached**

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

As we have tested with xampp7.4 , It is working fine.
