### ISSUE TITLE
Cannot access /member priveleges,teams,groups & customer

### ISSUE THREAD

**Issue by cagrisungur** [uvdesk/community-skeleton#541]
URL: en/member/teams/xhr

`[Semantical Error] line 0, col 120 near 'q = :q AND userInstance.supportRole': Error: Class Webkul\UVDesk\CoreFrameworkBundle\Entity\User has no field or association named q`

What is the problem?

**Comment by Komal-sharma-2712** [comment]
@cagrisungur 
Please let us know which version of UVdesk opensource and PHP version you are using?

**Comment by cagrisungur** [comment]
> @cagrisungur Please let us know which version of UVdesk opensource and PHP version you are using?

sorry. I've solved my problem. My problem was about nginx conf :)
