### ISSUE TITLE
Address in mailbox given [email] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by Stefan-CPlanet** [uvdesk/community-skeleton#542]
Hello,
After submitting a ticket there is a 500 error, even though a ticket is created and an email is sent, just instead of redirection to the proper page it's redirecting to the 500 error page.

enabling debug mode shows error: **Address in mailbox given [email] does not comply with RFC 2822, 3.6.2.**

Ubuntu: 20.04
Php- Latest 7.4.3
UVDesk- Latest

Thanks

**Comment by vipin-shrivastava-webkul** [comment]
@Stefan-CPlanet 

We have fixed this [#512](https://github.com/uvdesk/core-framework/pull/512 ), Changes will reflect in the upcoming release.
