### ISSUE TITLE
Custom fields for Agents and Customer

### ISSUE THREAD

**Issue by rajasuresh2** [uvdesk/community-skeleton#544]
Hi,

Please can you guide me to create custom fields for agents and customers?

Thanks
Suresh

**Comment by Himaniwebkul** [comment]
Hello @rajasuresh2 
You can get the custom field separate addon for uvdesk community helpdesk from here - https://store.webkul.com/uvdesk-open-source-custom-fields-app.html
Thank You!!

**Comment by rajasuresh2** [comment]
Hi Himaniwebkul,

Thanks for link, i have already installed opensource uvdesk, I need only custom fields APP.  But the link is not allowing me to buy only custom fields for 19.80$.  Please help me in getting only custom fields.

Best Regards
rajasuresh2
