### ISSUE TITLE
v1.1.0 broken clear cache button and wrong version showed on Dashboard

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#548]
# Bug report

**Error 1:** 
On version v1.1.0 seems you forget that you introduced a clean cache button in the Dashboard so now seems is no more working also if a green confirmation message is showed, cache are not cleaned.

**Error 2:**
The footer Dashboard showing version 1.0.18: this is wrong, version showed should be 1.1.0

**Comment by PeopleInside** [comment]
I see the version showed on the Dashboard should be correct V. 1.1.0 maybe in my install cache was not cleared yet?
I fixed in the code the version so don't know why installing on localhost give me the old version in the Dashboard. Be sure this is not a bug present.

For the clean cache button in the Dashboard, is not working even show a green message.
How I know? I edited some code and use this button to see edits, never work, need clean cache by SSH so changes are applied and showed.

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

We have made a fix for the cache-clear button, Please follow the below steps to update your project.
1. Open **Authentication.php** in your project from the below path.
**Path:** your_project_name/vendor/uvdesk/core-framework/Controller/Authentication.php
2. After that open the update **Authentication.php** file from [here](https://github.com/uvdesk/core-framework/blob/2ab61c148e1cc6377437a09889cde2043f5f9dcc/Controller/Authentication.php).
3. Now, Copy the updated **Authentication.php** file & paste it into your project **Authentication.php** file.

After making all the changes now try & let us know, If it is working fine or not.

**Comment by PeopleInside** [comment]
Seems still not working

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

Okay, we will check & update you soon

**Comment by PeopleInside** [comment]
Getting errors about that file when clean cache so check.
I have also the issue (maybe I will open a new issue) that on Plesk, since you released the version 1.1.0 now every php command never work anymore. Before I was able to use for example the command: 

php bin/console c:c

now I need use 

/opt/plesk/php/8.1/bin/php bin/console c:c

so I need update all cronjobs also...

I suppose because you may introduced limitations for PHP 7.4 that is still the default system PHP in Plesk

**Comment by PeopleInside** [comment]
I still get errors. I will send errors on ticket.

**Comment by PeopleInside** [comment]
Seems fixed: https://github.com/vipin-shrivastava/core-framework/commit/cbb777119a6fa705dff947ac27a12db8190604dd

**Comment by PeopleInside** [comment]
Seems fixed: https://github.com/uvdesk/core-framework/blob/7aa1edba144daf1e5fd0ff0c9018cfb264514dd5/Controller/Authentication.php
