### ISSUE TITLE
v1.1.0 Custom favicon is not working

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#549]
In branding of my UVdesk the logo is set but the custom favicon is not showed, the standard UVdesk icon is showed.
I mean in the browser tab the UVdesk icon is showed not my logo icon.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

You can replace your **favicon.ico** under public folder ([favicon](https://raw.githubusercontent.com/uvdesk/community-skeleton/master/public/favicon.ico))  of your project by new one (with your icon by same name).

**Comment by PeopleInside** [comment]
But if I'm not wrong,
in the code I can see there is a check that should work that set favicon if a help desk logo is set.

This is not working.
Hope you can fix in future, will be useful have an option in the UI to set the custom fav icon or set as logo.
Updates can broke the favicon.ico replacement.

**Comment by vipin-shrivastava** [comment]
@PeopleInside 
   
Can you check that **custom favicon** present inside the **public/assest/website** or not?

**Comment by PeopleInside** [comment]
Favicon on UVdesk will be need always to be replaced or placed by FTP.
No way to set in the UI interface.
Closing this as is possibile have a custom favicon by replace the original one, that is not the maximum but it's possible.
