### ISSUE TITLE
v1.1.0 On error page the logo should not point to the operator login but to customer login.

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#551]
# Bug report

On v1.1.0 error pages, if the logo of the help desk is clicked they redirect to the operator login not to the customer login page.

**Comment by PeopleInside** [comment]
https://github.com/uvdesk/community-skeleton/pull/552

**Comment by Komal-sharma-2712** [comment]
Now this issue has been resolved now on the customer panel on website logo point to the customer login panel instead of admin panel in uvdesk latest release **v-1.1.3** version, so we are closing this issue.
