### ISSUE TITLE
Form builder can be used to add more reports?

### ISSUE THREAD

**Issue by rajasuresh2** [uvdesk/community-skeleton#553]
Form builder can be used to add more reports? also Form builder includes custom fields functionality? Thanks

**Comment by Himaniwebkul** [comment]
@rajasuresh2 
**Form builder can be used to add more reports?**
>> Can you please elaborate on how you would like to add additional report with form builder?

**also Form builder includes custom fields functionality?** 
>> Yes!! the addon will come with custom fields functionality.

Thank You!!

**Comment by rajasuresh2** [comment]
Hi,

Can you please elaborate on how you would like to add additional report with form builder?

Customer report, Agent report, ticket status report.... other reports.

also Form builder includes custom fields functionality?

Yes!! the addon will come with custom fields functionality.

Thanks for the confirmation.
Thank You!!

**Comment by Himaniwebkul** [comment]
@rajasuresh2 
Customer report, Agent report, ticket status report.... other reports.
> Currently, the reporting feature is not available in the open source community helpdesk.
Thank You
