### ISSUE TITLE
New customer not receive account activation mail when customer created

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#56]
**customer not receiving welcome mail for uvdesk and account is activate and password setup information
even workflow is setup there :** 
![screenshot 25](https://user-images.githubusercontent.com/43210406/50230903-97b95880-03d3-11e9-9670-18594329328f.png)

**Comment by shubhwebkul** [comment]
resolved

**Comment by vaishaliwebkul** [comment]
Customer receiving welcome mail only when customer added by admin.
Rest of the other cases mails not received ; 
1. When customer create ticket from knowledgebase than account activation mail is not received.
2. When customer create ticket by mail id then also mail not received.
