### ISSUE TITLE
Index.php missing in public folder

### ISSUE THREAD

**Issue by jxs714** [uvdesk/community-skeleton#560]
Hey guys,

For some reason the public folder is missing the index.php. Am I missing something?

**Comment by Komal-sharma-2712** [comment]
@jxs714 

Which version of UVdesk and where are you installing this project.

Please install the latest version of the project from here: **https://github.com/uvdesk/community-skeleton**

**Comment by jxs714** [comment]
@Komal-sharma-2712 - hello, yes the same and latest version here. There is no index.php in the public folder. Also, when I downloaded the zip version on the website through the ubuntu tutorial, that one had a index.php, but I could not get passed the database credentials. I kept getting an error saying that the credentials are wrong no matter what I did. 

Please advise

**Comment by papnoisanjeev** [comment]
@jxs714 

> I kept getting an error saying that the credentials are wrong no matter what I did.

For database credentials wrong issue you can check [here](https://github.com/uvdesk/community-skeleton/issues/364#issuecomment-780486976).

**Comment by jxs714** [comment]
> @jxs714
> 
> > I kept getting an error saying that the credentials are wrong no matter what I did.
> 
> For database wrong credentials issue you can check [here](https://github.com/uvdesk/community-skeleton/issues/364#issuecomment-780486976) hope it will help.

Thank you so much for this. This fixed the issue. Great job guys
