### ISSUE TITLE
Mandatory Ticket Fields

### ISSUE THREAD

**Issue by Ivan-mst** [uvdesk/community-skeleton#561]
I'm trying to understand what's the code behind the ticket validation,
Trying to figure out how i can let a user create a ticket before i know the customer email adress or how i can validate it differently and maybe use a phone number instead.

i did try to change for example the "required" option to false editing ticket.php inside vendor\uvdesk\support-center-bundle\Form and reloading the page but i assume i either got something wrong or there's a validation executed somewhere else.

Any hints?

**Comment by papnoisanjeev** [comment]
@Ivan-mst 

You can check ticket create page for customers [here](https://github.com/uvdesk/support-center-bundle/blob/master/Resources/views/Knowledgebase/ticket.html.twig#L253-L290).

Hope it will help you !!

**Comment by Ivan-mst** [comment]
It does indeed! and it works!
Just wondering aswell where is the control for staff ticket creation xD

Thank you!

**Comment by papnoisanjeev** [comment]
@Ivan-mst 
> Just wondering as well where is the control for staff ticket creation

You can check [here](https://github.com/uvdesk/core-framework/blob/master/Resources/views/Snippets/createMemberTicket.html.twig).

**Comment by Ivan-mst** [comment]
I actually found it myself just a minute ago but it gives an error in another file cause getemail() doesn't tolerate an empty value..
will need to check a few things here and there i guess.
i was editing my answer to let you know but wasn't fast enough. thank you!
