### ISSUE TITLE
installing uvdesk on windows

### ISSUE THREAD

**Issue by wcutler123** [uvdesk/community-skeleton#562]
trying to install uvdesk on a windows machine.  
using this guide - https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-windows-uvdesk/
have installed xampp 8.1.5-0 and composer on the pc
ran the composer create-project uvdesk/community-skeleton helpdesk-project which installed the "helpdesk-project" folder in the htdocs folder.
I can get to the localhost/helpdesk-project in the edge browser but when I go to public it "cant reach this page"

**Comment by wcutler123** [comment]
anyone?

**Comment by vipin-shrivastava** [comment]
@wcutler123 

Share the screenshot of the error, Also check whether the **index.php** file is present inside the public folder or not.

**Comment by wcutler123** [comment]
[uvdesk setup.docx](https://github.com/uvdesk/community-skeleton/files/8556640/uvdesk.setup.docx)

install latest xampp for windows and composer
composer create-project uvdesk/community-skeleton helpdesk-project

**Comment by vipin-shrivastava** [comment]
@wcutler123 

Try to download latest zip from [here](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip) & try again.

Extract the zip  & placed the folder inside the server (xampp/htdocs).

**Comment by Komal-sharma-2712** [comment]
@wcutler123 

Have you checked the vendor folder in your helpdesk directory?

**Comment by wcutler123** [comment]
“composer update” in the uvdesk folder and then restart apache and mysql finally made it work.
then I couldnt get to the admin panel.  a reboot of the pc fixed that.
luckily i created ticket as user help sucks...

**Comment by vipin-shrivastava** [comment]
@wcutler123 

Did you set up the swift mailer? If not, First set up a swift mailer then email settings. After that try again to create a ticket.

**Comment by wcutler123** [comment]
Email integration with office365 or exchange is critical for us

Plus swiftmailer is abandoned

***@***.***

***@***.***


Wayne

**Comment by vipin-shrivastava** [comment]
@wcutler123 

Follow the below guide to set up a swift mailer with office365.
https://www.uvdesk.com/en/blog/outlook-mailbox-configuration-in-uvdesk-open-source-helpdesk/

>Plus swift mailer is abandoned.
We will try to update it soon in the upcoming versions. For now, it will not affect your helpdesk system.

**Comment by Komal-sharma-2712** [comment]
@wcutler123 

For the log file follow this path:
**your_helpdesk_project/var/log**

**Comment by Komal-sharma-2712** [comment]
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.
