### ISSUE TITLE
Company Setting features for UVdesk opensource

### ISSUE THREAD

**Issue by blckhwk** [uvdesk/community-skeleton#564]
Hi, 

I saw this feature on the uvdesk website https://www.uvdesk.com/en/features/company-setting/ but not in the uvdesk opensource. 

![image](https://user-images.githubusercontent.com/7903090/165875975-a1be200d-006d-44e6-85bb-b6c7ef4faa54.png)

![image](https://user-images.githubusercontent.com/7903090/165875996-9a07d61c-043a-46cd-a450-4385b26e7bca.png)

![image](https://user-images.githubusercontent.com/7903090/165876023-6d4bee26-e59a-4f93-817a-04289c1c0c50.png)

![image](https://user-images.githubusercontent.com/7903090/165876031-43195b62-17de-4911-bb36-b9ec31db1554.png)

![image](https://user-images.githubusercontent.com/7903090/165876055-a1a8ed93-bae2-40c2-a2af-cd6f807a07af.png)

It is nice to have in the opensource version of UVdesk. In my current UVdesk opensource implementation, I haven't seen this feature yet.
If this is not possible, could someone please point me in the direction of where I can find the codes for these features so that I can customize them on my own?

**Comment by papnoisanjeev** [comment]
@blckhwk 

UVdesk available with **two variant** and both are different and there is no connection between them.

-  **UVdesk SAAS** **(Paid and subscription based** and hosted on our server) **Pro** plan and **Enterprise** plan available.
   Sign Up URL:  https://uvdesk.com/en/member/signup

-  **UVdesk Opensource** (Free or opensource and user will be able to host it on his own server).
   Git hub Repository: https://github.com/uvdesk/community-skeleton

AS UVdesk SAAS created to work based on company (start with company registration) and everything is distinguish based on company (Like tickets, teams groups etc).

**Uvdesk opensource** structure is different and not made to use based on company simply user can host it for own and can use it.
