### ISSUE TITLE
Stuck loading the first step - Ubuntu

### ISSUE THREAD

**Issue by Mkdantas** [uvdesk/community-skeleton#565]
Hi everyone, 

I was able to run my application on ubuntu, however, i am still stuck in the web installation process.
![image](https://user-images.githubusercontent.com/50972667/166312236-766f272e-0b4a-4f95-a3dc-910c6e56b3cb.png)

it doesn't go past step one, it doesn't give me any errors also.

I have also tried to configure through the terminal, however when i try to do $php bin/console  server:run it says that the command doesn't exist.

Can someone help?

**Comment by vipin-shrivastava** [comment]
@Mkdantas 

Is your Helpdesk-project folder have read/write permission?

**Comment by Komal-sharma-2712** [comment]
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.
