### ISSUE TITLE
UVDESK Helpdesk Version 1.1.0 Hanging at step 4/5 

### ISSUE THREAD

**Issue by Silasdaniel13** [uvdesk/community-skeleton#566]
# Bug report

Hi, 
I have been trying to install UVDesk helpdesk version 1.1.0 on Debian 10 with php7.4. 
I have downloaded the project and built it with php composer. 
I have launched the installation through the web browser and at the step 4/5 I got an error message: 
"Something went wrong, Please try again". 

Then I restarted the process with the web developer toolkit on.
I got the an error on the query: POSThttp://helpdesk.local/wizard/xhr/load/super-user

"

And I really don't know how to get it solved. 

Is anybody able to help? 

 

![image](https://user-images.githubusercontent.com/50920787/168515624-405189f0-730f-4b11-9ac4-e33aab0beeb7.png)

![uvdesk_error](https://user-images.githubusercontent.com/50920787/168515383-660f159c-1773-4849-a0d0-b6dfdc51514b.png)

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by Komal-sharma-2712** [comment]
@Silasdaniel13 

Update your **composer.json**  file by the below code:

```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": "^7.2.5 || ^8.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.6",
        "doctrine/doctrine-fixtures-bundle": "3.4.1",
        "doctrine/doctrine-migrations-bundle": "^2.2",
        "doctrine/orm": "^2.12",
        "google/recaptcha": "^1.2",
        "knplabs/knp-paginator-bundle": "^5.8",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.2",
        "sensio/framework-extra-bundle": "^6.1",
        "symfony/asset": "^5.4",
        "symfony/console": "^5.4",
        "symfony/dotenv": "^5.4",
        "symfony/expression-language": "^5.4",
        "symfony/flex": "^1.17|^2",
        "symfony/form": "^5.4",
        "symfony/framework-bundle": "^5.4",
        "symfony/http-client": "^5.4",
        "symfony/intl": "^5.4",
        "symfony/mailer": "^5.4",
        "symfony/mime": "^5.4",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "^5.4",
        "symfony/process": "^5.4",
        "symfony/property-access": "^5.4",
        "symfony/property-info": "^5.4",
        "symfony/proxy-manager-bridge": "^5.4",
        "symfony/runtime": "^5.4",
        "symfony/security-bundle": "^5.4",
        "symfony/serializer": "^5.4",
        "symfony/string": "^5.4",
        "symfony/swiftmailer-bundle": "^3.5",
        "symfony/translation": "^5.4",
        "symfony/twig-bundle": "^5.4",
        "symfony/validator": "^5.4",
        "symfony/web-link": "^5.4",
        "symfony/yaml": "^5.4",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0",
        "uvdesk/automation-bundle": "^1.1",
        "uvdesk/composer-plugin": "^1.1",
        "uvdesk/core-framework": "^1.1",
        "uvdesk/extension-framework": "^1.1",
        "uvdesk/mailbox-component": "^1.1",
        "uvdesk/support-center-bundle": "^1.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "^5.4",
        "symfony/css-selector": "^5.4",
        "symfony/debug-bundle": "^5.4",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^6.0",
        "symfony/stopwatch": "^5.4",
        "symfony/web-profiler-bundle": "^5.4"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true,
            "uvdesk/composer-plugin": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^5.4"
        }
    }
}
```

Finally, run the below command:
**composer update**

And setup again.

**Comment by vipin-shrivastava** [comment]
@Silasdaniel13 

The latest version of "doctrine/doctrine-fixtures-bundle" is not compatible with uvdesk. As this release came in the last week. 

You can fixed this issue by changing the version in composer.json in uvdesk:

        "doctrine/doctrine-fixtures-bundle": "^3.4",
         **TO**
        "doctrine/doctrine-fixtures-bundle": "3.4.1",

After Updating the changes in composer.json. Simply, run the **composer update** command in your project root directory.

I Hope, This will resolve your issue.

**Comment by Silasdaniel13** [comment]
@Komal-sharma-2712 Thank you for your answer. However,  have tried it but I am still getting the same error

**Comment by Komal-sharma-2712** [comment]
@Silasdaniel13 


Please let me know what steps have you followed?

Share the screenshot what is the error showing?

Make a try once download the zip file from [here](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip) of the latest stable release.

If you have still facing the error let us know.

**Comment by Silasdaniel13** [comment]
@Komal-sharma-2712 

As you have suggested, 
1- I have downloaded the latest stable release following the link you provided
2- I proceeded to unzip it and edit the composer.json file as you suggested earlier
3- I have executed the command: "composer update"
4- I have tried the installation through the web browser again and I got the same error

**Comment by Komal-sharma-2712** [comment]
@Silasdaniel13 

**Using Zip:**
If install using a zip file you don't need to update the **composer.json** file and don't need to run the **composer update** command.
You directly unzip and go to the browser and set up the project.

**Using Command:**
If install using command so you will changed only the version in **composer.json** file in uvdesk:

    "doctrine/doctrine-fixtures-bundle": "^3.4",
     TO
    "doctrine/doctrine-fixtures-bundle": "3.4.1",

After Updating the changes in **composer.json**. Simply, run the **composer update** command in your project root directory.

In the last refresh your page on the web browser and set up again of project.


If still facing the error please share the screenshots of the error.

**Comment by Silasdaniel13** [comment]
@Komal-sharma-2712 
After following your steps, this is the error I got

![image](https://user-images.githubusercontent.com/50920787/168605992-351de7b5-8627-48d8-bdba-cecc54d72746.png)

**Comment by Komal-sharma-2712** [comment]
@Silasdaniel13 

Clear the cache of project using this command:
**php bin/console c:c**  in your project root directory. 
Now try setup again of UVdesk.


**Using Manual Setup:**
Make a try once manual setup of UVdesk. 
Check the below link for manual setup from [here](https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642)


**Note: Once you clear the cache of your browser and project cache.**

If still facing the error please let us know.

**Comment by Komal-sharma-2712** [comment]
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.
