### ISSUE TITLE
Script doesn't fetch replies from email

### ISSUE THREAD

**Issue by EgyptianM** [uvdesk/community-skeleton#567]
# Bug report

### Title
Script doesn't fetch replies from email

### Issue Description
I configured Swift Mailer and Mailbox , When I reply to customer he receives an email but when he replies to this email his reply doesn't show in the ticket.
I do receive the replies on the email but they doesn't show in the ticket.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    V -1.1.0
    PHP 7.4

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create a ticket and let an agent reply to it.
    2. Goto customer email and reply to the ticket from there.

### Expected result
Customer reply shows in the ticket.

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**
It doesn't show.
* [points....]

**Comment by Komal-sharma-2712** [comment]
@EgyptianM 

After the mail reply, you have run this command on the console in the project root directory:

**php bin/console uvdesk:refresh-mailbox your_mailbox_id**

Now check your ticket on the dashboard here mail replies are added in the same ticket number.


If still the same issue shares your screenshot of the mailbox setting.

**Comment by Komal-sharma-2712** [comment]
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.
