### ISSUE TITLE
Installation - Bug in password box

### ISSUE THREAD

**Issue by kubik256** [uvdesk/community-skeleton#568]
### Issue Description
Password box doesn't allow **underscore** as special char, or doesn't accept it as special char.

### Preconditions
Possible every install, my setup was: UVDesk-community-v1.1.0, PHP v 8.1.5, Apache2, Debian 11 headless

### Steps to reproduce
While install on Admin Details page - password box.

### Expected result
Allow password with underscore char "_" or describe allowed chars in password box.
It would save a lot of time...

### Actual result
Only error hint with a list what must be in a password - but in my world undescore is relevant special char ;-)

**Comment by papnoisanjeev** [comment]
Updated the regix for allowing _ in password.
will be added in next release.
https://github.com/uvdesk/community-skeleton/commit/835add3e01e4217d104f2cb5c537ba72dc9e409c
