### ISSUE TITLE
Website configuration details get saved without installing database tables

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#57]
When re setup existing project by changing website configuration details but not install the migrated tables again , still website configuration details saved in files by new values and unable to login to dashboard using old values. 
Getting error:
![screenshot from 2018-12-20 10-37-03](https://user-images.githubusercontent.com/43210406/50264981-4648b200-0443-11e9-936c-28e46e803e86.png)

**Comment by shubhwebkul** [comment]
resolved
