### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by newerit** [uvdesk/community-skeleton#570]
**Description**  

**Example**  

It's possible integrate with Whatsapp Chat , Telegram Chat, Librenms API (for open a ticket and list the equipament monitoring list)?

**Comment by Aanchal542** [comment]
@newerit 
This is here to inform you that this integration is not available as of now with the UVdesk helpdesk ticketing system. But we can make this done via customization which would be paid service.
To move with the custom work you can mail us at support@uvdesk.com

**Comment by Komal-sharma-2712** [comment]
We are closing this issue because it is not an issue it's an additional requirement. 

If you want any integration then you can reach us at [support@uvdesk.com](mailto:support@uvdesk.com)
