### ISSUE TITLE
Authentication Problem when changing .env to prod

### ISSUE THREAD

**Issue by ricardolca** [uvdesk/community-skeleton#571]
Hello. First of all, thank you for the great system you made, it is really awesome.

I am changing the .env file to prod, clearing the cache (php bin/console c:c) and restarting the Apache.

However, when we try to log in again, I get the following message:

![image](https://user-images.githubusercontent.com/93027912/172220194-fb5ae0ca-26b0-4d0c-b5d6-0febcc47d772.png)

So I am not able to log in production mode.

If I change back to dev mode, everything works again.

Is there any step I am missing while changing to prod mode?

By the way, when I clear the cache in production mode, I get several notices on deprecation...including some for authentication. Is this anything known already?

Thank you,

**Comment by Komal-sharma-2712** [comment]
@ricardolca 
 
Let us know, where have you downloaded the project?

**Comment by ricardolca** [comment]
Hi Komal,

I followed the instructions on GitHub UVDesk Page.

1- Installed Composer
2 - Created a folder /var/www/html/helpdesk-tm
3 - I ran composer create-project uvdesk/community-skeleton helpdesk-tm
4 - I had some problem on installation, so I followed this link (https://forums.uvdesk.com/topic/2085/installation-problem/2) and updated composed.yaml 
5 - Everything is working fine in dev mode, no problem at all.

However, once I change the env. file to prod. I clear the cache using (php bin/console c:c), I get these messages below on the attached file.
[Symfony Deprecation Messages.txt](https://github.com/uvdesk/community-skeleton/files/8855919/Symfony.Deprecation.Messages.txt)

The application loads fine in the browser, however, if I try to log in I get the message mentioned about aythentication that I mentioned on the initial question. If I switch back to dev mode, everything works fine in this mode, but problem arises again once I am back to production mode,

Thank you for your help, it is really appreciated.

**Comment by vipin-shrivastava** [comment]
@ricardolca  Are you still facing issue or have you resolved the issue?

**Comment by vipin-shrivastava** [comment]
> Hi Komal,
> 
> I followed the instructions on GitHub UVDesk Page.
> 
> 1- Installed Composer 2 - Created a folder /var/www/html/helpdesk-tm 3 - I ran composer create-project uvdesk/community-skeleton helpdesk-tm 4 - I had some problem on installation, so I followed this link (https://forums.uvdesk.com/topic/2085/installation-problem/2) and updated composer.yaml as recommended. 5 - Everything is working fine in dev mode, no problem at all.
> 
> However, once I change the env. file to prod. I clear the cache using (php bin/console c:c), I get these messages below on the attached file. [Symfony Deprecation Messages.txt](https://github.com/uvdesk/community-skeleton/files/8855919/Symfony.Deprecation.Messages.txt)
> 
> The application loads fine in the browser, however, if I try to log in I get the message mentioned about aythentication that I mentioned on the initial question. If I switch back to dev mode, everything works fine in this mode, but problem arises again once I am back to production mode,
> 
> Thank you for your help, it is really appreciated.

The latest version of "doctrine/doctrine-fixtures-bundle" is not compatible with uvdesk. As this release came in the last week.

You can fixed this issue by changing the version in composer.json in uvdesk:

    "doctrine/doctrine-fixtures-bundle": "^3.4",
     **TO**
    "doctrine/doctrine-fixtures-bundle": "3.4.1",
After Updating the changes in composer.json. Simply, run the composer update command in your project root directory.

I Hope, This will resolve your issue.

**Comment by ricardolca** [comment]
Hi Vipin,

I am still having the issue. My composer.json file was already set to use the version 3.4.1.

Thank you,

**Comment by vipin-shrivastava** [comment]
@ricardolca 

Mail us at support@uvdesk.com with your query.

**Comment by Komal-sharma-2712** [comment]
We are closing this issue.
If you still facing the same issue you can reply to us on the same thread.
