### ISSUE TITLE
Unable to access UVdesk page

### ISSUE THREAD

**Issue by blckhwk** [uvdesk/community-skeleton#572]
Hi, 

Does anyone have this issue or have a solution?

![image](https://user-images.githubusercontent.com/7903090/172523169-fc3bbdc5-de5c-4966-91d5-a9ca5bc44d5d.png)

![image](https://user-images.githubusercontent.com/7903090/172523190-af1f7d86-8f2f-49a3-8073-18b8ff8cc141.png)

I was unable to debug the issue because currently the.env file is configured to "prod". If I changed it to "dev", the composer sends out an error.

![image](https://user-images.githubusercontent.com/7903090/172523376-fc234e10-6e0a-41cd-b19c-880e63cfa586.png)
![image](https://user-images.githubusercontent.com/7903090/172523424-84fb75a5-8cdc-467e-9ad8-bd97a6173dea.png)
![image](https://user-images.githubusercontent.com/7903090/172523467-63762c69-7ff2-471c-be33-1530a9564858.png)

I don't know if this composer errors are related to my issue

![image](https://user-images.githubusercontent.com/7903090/172523488-e215d77f-927c-4497-a342-c8b5468ed38a.png)

**Comment by Komal-sharma-2712** [comment]
@blckhwk 

Which UVDesk version, composer & PHP version are you using?

**Comment by blckhwk** [comment]
I'm using UVdesk version 1.1, Composer version 2.3.4 and PHP version 7.4.3

**Comment by blckhwk** [comment]
You may closed this issue I just re-installed the UVdesk
