### ISSUE TITLE
Excel Attachment Corrupted

### ISSUE THREAD

**Issue by Nitz992** [uvdesk/community-skeleton#573]
# Bug report

From the admin panel when agent downloading the excel files, its downloading corrupted file.  

### Issue Description
We are using gsuite for mail server. When user is attaching any excel files into ticket then from agent side its downloading corrupted file in admin panel but the same file we can download from Gmail web interface or we can download the attachment from outlook. 

**Tell us what should happen.**
Actual file should be downloaded from Admin panel.

*   [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/97659510/172634871-159535d5-2afc-4c9f-be5d-bafbf1b97f81.png)
![image](https://user-images.githubusercontent.com/97659510/172635065-de2f5647-a166-4197-a08f-f2ed73bc8f0e.png)

### Actual result
Excel file unable to download from agent side panel. The same file can be opened from mail interface. problem I found that is only with excel..

**Comment by Komal-sharma-2712** [comment]
@Nitz992 

We are closing this issue. As we have discussed on ticket number: **[#27805](https://support.uvdesk.com/en/customer/ticket/view/27805)**. 
If you still have any issue so you can reply on the same ticket.
