### ISSUE TITLE
Email are not sent

### ISSUE THREAD

**Issue by Ethereumx** [uvdesk/community-skeleton#578]
We are facing a problem that Uvdesk is no more sending emails when creating customers or requesting a new password (forget pwd).
We have tried different options (yahoo, Google, smtp/Iamp, ..) but nothing seems to work.
For outlook we followed the official guide (with 2f activation) https://www.uvdesk.com/en/blog/outlook-mailbox-configuration-in-uvdesk-open-source-helpdesk/
The fetch seems to work
![image](https://user-images.githubusercontent.com/25054471/179929896-ef537c74-8ec0-4801-8ac5-29d670e6fd68.png)
Any leads?

**Comment by Ethereumx** [comment]
Maybe this happens because all mail providers no longer accept less secure app login

![image](https://user-images.githubusercontent.com/25054471/179944886-f2be0ee4-20da-4219-8bd4-065f6dfce78f.png)

**Comment by Ethereumx** [comment]
Is there any why to debug the issue. uvdesk log doesn't seem to report anything related to emailing

**Comment by Komal-sharma-2712** [comment]
You can also check this by setting a Gmail account email Id.

Locate the file **vendor->uvdesk->core-framework->Services->EmailService.php.**

Open the **EmailService.php** reach to **sendMail()** function.

and dump() the exception as in the attached image.

It will show the error you are facing while sending mails (if adding an agent, creating a ticket etc).

![image](https://user-images.githubusercontent.com/63539748/179960649-78b56d0b-a572-4a5e-8abf-d5152d3fb0a8.png)

**Comment by Ethereumx** [comment]
Thanks!
