### ISSUE TITLE
Public url in emails

### ISSUE THREAD

**Issue by Ethereumx** [uvdesk/community-skeleton#579]
I am looking for how to configure uvDesk to use the public url instead the local IP. When users receive emails they get

`You recently requested to reset your password for your Test Support Center account. Click the link to reset it http://192.168.1.1:8000/en/update-credentials/abc@gmail.com/utjmV6jOzVMgKVwKmvuekXpsisnl4fKL
`

Although I change the 
![image](https://user-images.githubusercontent.com/25054471/179969528-6a3cbdae-60ec-493a-9f77-54583a8304e8.png)
to point to the public url but it doesn't work IT keeps using the local IP

**Comment by akshaywebkul** [comment]
Hello Ethereumx,

This seems like an unusual behavior. Is your application in production environment? And if so, did you clear your cache following the changes made?

**Comment by Ethereumx** [comment]
I have cleared the cache and switched to dev and prod but the issue remains. I've fixed the issue by changing the code to construct the correct url.

**Comment by Komal-sharma-2712** [comment]
If you have further any other queries so reply in the same thread.
Now we are closing this issue.
