### ISSUE TITLE
When customer reply to their previous ticket using mail then ticket isn't open at admin panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#58]
**customer reply to existing ticket using mail id and attachment** 
![screenshot 27](https://user-images.githubusercontent.com/43210406/50269100-3cc74600-0453-11e9-838d-6e3d660772fa.png)

**At admin end : ticket is not open**
![screenshot from 2018-12-20 12-32-29](https://user-images.githubusercontent.com/43210406/50269127-56688d80-0453-11e9-8e2e-4a5afa14630c.png)

**Comment by shubhwebkul** [comment]
resolved
