### ISSUE TITLE
Wizard does not advance

### ISSUE THREAD

**Issue by JoseLuisHD** [uvdesk/community-skeleton#590]
# Bug report

### Title
Wizard does not advance

### Preconditions
**Please provide as detailed information about your environment as possible.**

    Current version

### Steps to reproduce

    1. Follow the installation steps in the web interface.

### Expected result
Installation does not proceed from step 1, console errors

*   [Screenshots, logs or description]
* 
![image](https://user-images.githubusercontent.com/74986278/182963472-4a2c3578-3d89-4357-b7e3-caa5df6c4abe.png)
![image](https://user-images.githubusercontent.com/74986278/182963514-f4b76d07-eacc-4300-83a0-1b8a26a88b6e.png)

https://github.com/uvdesk/community-skeleton/blob/master/public/scripts/wizard.js#L91

**Comment by tarasis** [comment]
exact same issue, and same location. Curious why this was marked as completed.
