### ISSUE TITLE
Tickets which are deleted not move into trashed

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#61]
** delete one ticket which is in **answer status** currently :**
![screenshot 30](https://user-images.githubusercontent.com/43210406/50270171-b6146800-0456-11e9-93f2-327d5fde95be.png)

Now it should be move in to trashed : 
![screenshot 31](https://user-images.githubusercontent.com/43210406/50270256-f83da980-0456-11e9-9eac-d5c230cfb6ec.png)

**Comment by shubhwebkul** [comment]
resolved
