### ISSUE TITLE
Swiftmailer not working

### ISSUE THREAD

**Issue by blckhwk** [uvdesk/community-skeleton#616]
Hi, 

How do I resolve this issue?

![image](https://user-images.githubusercontent.com/7903090/196612752-d08378ff-1bf6-4ff6-9b46-9b3e5b6cbf89.png)

**Comment by Komal-sharma-2712** [comment]
Let us know which email service you are using [Gmail](https://www.uvdesk.com/en/blog/setup-gmail-mailbox-uvdesk-open-source-helpdesk/ ), [Yahoo](https://www.uvdesk.com/en/yahoo-configuration-in-uvdesk-open-source-helpdesk/), [Outlook](https://www.uvdesk.com/en/blog/outlook-mailbox-configuration-in-uvdesk-open-source-helpdesk/ ), or using [IMAP](https://www.uvdesk.com/en/blog/smtp-imap-open-source-helpdesk-uvdesk/).
Once you check again your Swift mailer settings with the correct app password.

**=> Also, check this:**

Locate the file **vendor->uvdesk->core-framework->Services->EmailService.php**

Open the **EmailService.php** reach to **sendMail()** function.

and **dump()** the exception as in the attached image.

![image](https://user-images.githubusercontent.com/63539748/196615638-76ad8e3f-de96-4173-b474-ca562a4579be.png)


Once done then you just need to reply to the ticket accordingly the error will be reflected.

It will show the error you are facing while sending emails (if adding an agent, creating a ticket, etc).


**Another helpful link:**

https://forums.uvdesk.com/post/2083

**Comment by blckhwk** [comment]
Hi,

Swiftmailer - Gmail free account
mailbox - Gmail free account - IMAP

![image](https://user-images.githubusercontent.com/7903090/196934280-530c6d4d-9eb8-4dc9-9eca-e9c39fecbb77.png)

I don't think we sent out 500 emails per day

I might use another email account to workaround this issue.

**Comment by mateusvtoledo** [comment]
@Komal-sharma-2712 For me it doesn't work at all... And worse than in my case the error doesn't even show... it saves everything correctly.

Important: Your forum is out due to expired SSL.

**Comment by Komal-sharma-2712** [comment]
@mateusvtoledo 

Create a ticket from [here](https://support.uvdesk.com/en/customer/create-ticket/) with your query and screenshots of the errors.
Our team will assist you.

**Comment by nitinarora39** [comment]
> @Komal-sharma-2712 For me it doesn't work at all... And worse than in my case the error doesn't even show... it saves everything correctly.
> 
> Important: Your forum is out due to expired SSL.

same issue

**Comment by nitinarora39** [comment]
``
![image](https://user-images.githubusercontent.com/88287704/203957885-7d52e7b4-35cc-4758-bf28-8547adfcf43b.png)

**Comment by Komal-sharma-2712** [comment]
@nitinarora39 

Once you try with the below steps:

Open the **swiftmailer.php** file under **config->packages** in your project.

Disable **SSL verification on the server** by using this option and make a try.

 

```
stream_options:
    ssl:
        verify_peer: false
        verify_peer_name: false
        allow_self_signed: true

```

![image](https://user-images.githubusercontent.com/63539748/204202578-0317cf4b-8572-4363-99fa-42280ea6acc5.png)


After that, you will **clear the cache of your project** run the below command in your **project root directory**:

**_$ php bin/console c:c_**

 

Now you can reply to tickets and check swift mailer is working or not.


**Useful link:**

[https://stackoverflow.com/questions/36454920/swiftmailer-php-how-to-disable-ssl-certificate-validation](https://stackoverflow.com/questions/36454920/swiftmailer-php-how-to-disable-ssl-certificate-validation)

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue. We have checked your ticket is created on our support tickets system.
If you are facing the same error then reply on the same ticket id: [28955](https://support.uvdesk.com/en/customer/ticket/view/28955)
