### ISSUE TITLE
If customer has more than one ticket ,still with ticket detail it's showing that customer has only 0 more ticket 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#62]
### **Bug** 
**customer more ticket link shows wrong no of tickets :** 
![screenshot 33](https://user-images.githubusercontent.com/43210406/50271652-5e2c3000-045b-11e9-94a1-c8e205b86e1f.png)

**When click on the link get this customer has 2 ticket :** 
![screenshot 32](https://user-images.githubusercontent.com/43210406/50271497-e8c05f80-045a-11e9-9a81-c1ae70e81e39.png)

**Comment by papnoisanjeev** [comment]
fixed
