### ISSUE TITLE
生产环境下修改完邮箱配置，不清除缓存会导致程序无法读取到最新配置

### ISSUE THREAD

**Issue by yjqphp** [uvdesk/community-skeleton#623]
# Bug report

### Title
**生产环境下修改配置不生效，不清除缓存会导致程序无法读取到配置.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**生产环境（APP_ENV=prod）时修改邮箱配置，修改完成后uvdesk.yaml中文件有正常更改，程序通过$this->getParameter('uvdesk.support_email.id')获取到的还是旧的配置.**

    1. v.1
### Steps to reproduce

    1. 更改环境环境变量APP_ENV=prod
    2.  登录管理后台修改邮箱设置。
    3. 
    

### Expected result

*   1. 刷新浏览器页面，展示的还是上一次的修改。但是查看邮箱设置保存文件：uvdesk.yaml  support_email。查看和修改的预期一致。
    2. 创建一个tickts,邮箱发送还是用的上一次的配置

### Actual result

>    **Tell us what happens instead.**

* prod环境下修改配置后，若不清除缓存，配置不生效

**Comment by Komal-sharma-2712** [comment]
@yjqphp 

Thanks for reporting. We have already noticed this issue. If we do the setup in prod mode of the mailbox and email settings so these settings need to clear the cache of the project for the configuration shown in the settings.
We will try to fix it in the future.
