### ISSUE TITLE
 Additional form processing

### ISSUE THREAD

**Issue by Evgl1** [uvdesk/community-skeleton#626]
When the user is logged in. I need to do the following: for a certain type of request, check the attached files for errors, if there are no errors, allow the creation of the request, if there are errors, report it and prevent the creation of the request.

Please tell me how should I do this? Can you please point me to similar examples?

**Comment by Komal-sharma-2712** [comment]
Thanks for sharing this requirement. we will try to add this requirement in a future release.

**Comment by Komal-sharma-2712** [comment]
@Evgl1 

You can change in this file follow the below path:
**your-project/vendor/uvdesk/core-framework/Resources/views/Templates/attachment.html.twig**

**Comment by Komal-sharma-2712** [comment]
We are closing this issue, If you are still facing the same error then reply in the same thread.
