### ISSUE TITLE
maximum size of attached files

### ISSUE THREAD

**Issue by Evgl1** [uvdesk/community-skeleton#631]
Hello. Please tell me how to increase the size of the uploaded file and files in total?

**Comment by Komal-sharma-2712** [comment]
@Evgl1 

Increase the **upload_max_filesize** in **uvdesk.yaml** file and also **increase the upload size** from your **php.ini** file and make try:

![image](https://user-images.githubusercontent.com/63539748/208352261-acb6e8a2-1add-4fff-aa28-d48cd92b9dd6.png)

Finally, restart your server and try.

**Comment by Komal-sharma-2712** [comment]
We are closing this issue, If you are still facing the same error then reply in the same thread.
