### ISSUE TITLE
How to add mail server

### ISSUE THREAD

**Issue by senthil-kms** [uvdesk/community-skeleton#633]
how to add our mail in UVDESK and access the mail function

**Comment by Komal-sharma-2712** [comment]
@senthil-kms 

> how to add our mail in UVDESK and access the mail function

Let us know, if you are talking about mail sent from the uvdesk helpdesk. 
If yes then **you will setup of the swift mailer and email settings option** for sends mail on the customer mail when a ticket is created on Uvdesk. 

Please follow this blog: 
https://www.uvdesk.com/en/blog/setup-gmail-mailbox-uvdesk-open-source-helpdesk/

**Comment by senthil-kms** [comment]
@Komal-sharma-2712 

I have created **swift mailer and the email setting option** but the mail is not receiving to customer and to the admin.
I got an error message :+1: 
         Warning ! Swiftmailer not working. An error has occurred while sending emails!

Whether there is any other possible to generate mail

**Comment by senthil-kms** [comment]
@Komal-sharma-2712

**Comment by Komal-sharma-2712** [comment]
@senthil-kms 

Open the **swiftmailer.php** file under **config->packages** in your project and add these lines.

Disable SSL verification on the server by using this option and make a try.

```
stream_options:
ssl:
verify_peer: false
verify_peer_name: false
allow_self_signed: true
```

![image](https://user-images.githubusercontent.com/63539748/208902505-3ed1dfa1-a8f9-47bd-a02f-d6cb5fe83075.png)


After that, you will **clear the cache of your project** run the below command in your project root directory:

**_$ php bin/console c:c_**


Now you can reply to tickets and check swift mailer is working or not.

**Useful link:**

https://stackoverflow.com/questions/36454920/swiftmailer-php-how-to-disable-ssl-certificate-validation

 
If the error is not an SSL certificate regarding so share your screenshot of the error.

I hope this solution works for you, if you have still the same problem let us know.

**Comment by senthil-kms** [comment]
@Komal-sharma-2712 

When i change the swiftmailer file i didn't able to load the shop page  below error i have displayed
![Screenshot from 2022-12-21 17-56-58](https://user-images.githubusercontent.com/121149153/208905367-d0bed778-944c-42d0-b79a-7a7d9aed5a01.png)

**Comment by senthil-kms** [comment]
@Komal-sharma-2712 
I swiftmailer which mail id i should add whether the customer mail id or admin mail id

**Comment by senthil-kms** [comment]
![Screenshot from 2022-12-21 18-02-52](https://user-images.githubusercontent.com/121149153/208906121-dff0501b-97fa-4f86-9572-d57c6b199f57.png)
This message only displaying

**Comment by Komal-sharma-2712** [comment]
> @Komal-sharma-2712 I swiftmailer which mail id i should add whether the customer mail id or admin mail id

In swiftmailer email id should be different from the customer and the admin email.

Share your screenshots of the swiftmailer.yaml file.

**Comment by senthil-kms** [comment]
![123](https://user-images.githubusercontent.com/121149153/208907411-0461691c-cb80-46da-9a75-f310796e103b.png)

**Comment by senthil-kms** [comment]
when we are creating the port forwarding in gmail where the confirmation mail will be shown whether the mail will be displayed as a ticket in uvdesk

**Comment by senthil-kms** [comment]
when we create ticket from customer the ticket is displayed in uvdesk member page but the mail is not receiving for both the customer and the admin

**Comment by senthil-kms** [comment]
> Check once again with changes in the code for debug the error.
> 
> Locate the file **vendor->uvdesk->core-framework->Services->EmailService.php.**
> 
> Open the **EmailService.php** and reach to **sendMail()** function.
> 
> and add the below line as in the attached images:
> 
> `$this->session->getFlashBag()->add('warning', $e->getMessage());`
> 
> ![image](https://user-images.githubusercontent.com/63539748/208912635-bf96104f-d770-4a75-8645-fcec39b9dda3.png)
> 
![Screenshot from 2022-12-21 18-46-06](https://user-images.githubusercontent.com/121149153/208914435-7ec4c8e3-8cce-4765-81be-28102028624c.png)

> Once done then you just need to reply to the ticket accordingly the error will be reflected.
> 
> It will show the error you are facing while sending emails (if adding an agent, creating a ticket, etc) and share the screenshots of the error.

When i changed the file different error is displaying

**Comment by senthil-kms** [comment]
Now i have displayed this error now what i have to do for the swiftmailer error

**Comment by Komal-sharma-2712** [comment]
> 
> 
>
> ![Screenshot from 2022-12-21 18-46-06](https://user-images.githubusercontent.com/121149153/208914435-7ec4c8e3-8cce-4765-81be-28102028624c.png)
> 
> > Once done then you just need to reply to the ticket accordingly the error will be reflected.
> > It will show the error you are facing while sending emails (if adding an agent, creating a ticket, etc) and share the screenshots of the error.
> 
> When i changed the file different error is displaying


Let us know, this is the same error on the admin dashboard. If the admin creates a ticket from the admin dashboard.

**Comment by senthil-kms** [comment]
Yes This error is from admin dashboard when admin reply to the ticket this error is displaying

**Comment by senthil-kms** [comment]
Both customer and admin receives the same error while sending mail

**Comment by akshaywebkul** [comment]
Hello @senthil-kms,

Could you please verify whether demo123@uvdesk.com is the customer email address in this case and not the email address you used to setup your mailer settings as you've shared in previous replies. It seems that the system is trying to deliver emails from demo123@uvdesk.com through the gmail smtp server, which obviously won't work. I would request you to please share the screenshot of your uvdesk_mailbox.yaml & swiftmailer.yaml configuration files to cross-verify these details. In order to avoid leaking any sensitive information, i would suggest you to either blur the sensitive content in your screenshots, or raise a support request by reaching out to us at https://support.uvdesk.com/en

**Comment by senthil-kms** [comment]
![Screenshot from 2022-12-21 19-28-28](https://user-images.githubusercontent.com/121149153/208923075-004d4924-359e-4700-9c6f-ef2495afd931.png)
![123](https://user-images.githubusercontent.com/121149153/208923128-b4b92727-c01f-4b35-ae84-49e4dd3863da.png)
this is the config file

**Comment by senthil-kms** [comment]
![123](https://user-images.githubusercontent.com/121149153/208923304-6b072687-7f2a-45cb-975d-73f5ac908647.png)
![456](https://user-images.githubusercontent.com/121149153/208923420-08eda569-fc0f-47e0-973b-ce39365202af.png)


this is the config file

**Comment by senthil-kms** [comment]
![Screenshot from 2022-12-21 19-28-28](https://user-images.githubusercontent.com/121149153/208923725-abc0b1f2-231f-4aa6-a4bf-ff8ceaaa3a73.png)
this is config file

**Comment by senthil-kms** [comment]
hello if there is any solution to solve this

**Comment by Komal-sharma-2712** [comment]
@senthil-kms 

Please create a ticket on our support dashboard from [here](https://support.uvdesk.com/en/customer/create-ticket/) with all **screenshots files of the swift mailer, mailbox, and email settings**. Also, **share the server details of your project** so that we will check the error.

**Comment by senthil-kms** [comment]
@Komal-sharma-2712 
I have created the ticket with this details

> @senthil-kms
> 
> Please create a ticket on our support dashboard from [here](https://support.uvdesk.com/en/customer/create-ticket/) with all **screenshots files of the swift mailer, mailbox, and email settings**. Also, **share the server details of your project** so that we will check the error.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Hope your issue will be resolved, if you are still facing the same issue then **feel free to reopen** this issue.
