### ISSUE TITLE
Repeatitive email template for different purposes

### ISSUE THREAD

**Issue by mashahabi15** [uvdesk/community-skeleton#634]
Hello everyone, I hope you're doing well.
I enabled mail server on uvdesk and I'm using that. I changed some of uvdesk email templates for customization. But I found a bug. When superuser replies to customer ticket, uvdesk sends an email and when customer replies to a ticket an email is sent. But these templates are the same, although the names in "Email Template" section of uvdesk are different. How can I say uvdesk to send email on an special action? Because even when you want to add a new template there is no option for assigning the template to action.
What can I do?
Thank you for any help you can offer.

**Comment by Komal-sharma-2712** [comment]
@mashahabi15 

>when you want to add a new template there is no option for assigning the template to action.
If you are added a new email template after that you will add this email template to workflow actions. You follow the below steps:

Step 1: **Create a new email template:**

![image](https://user-images.githubusercontent.com/63539748/209514485-1d62dac7-2ba4-4e84-a8e0-c83c8db0d31d.png)


Step 2: **Now you want to add this newly created email template in sends mail so you will add this email template in the workflow option, so go to the workflow option:**

![image](https://user-images.githubusercontent.com/63539748/209515692-01690f37-6b42-43c8-829b-6b203c171b05.png)

Click on the customer replied on the ticket workflow, here you will add a new email template in the mail to agent actions and then save: 
![image](https://user-images.githubusercontent.com/63539748/209514529-8436a665-33f1-43e8-a4c2-e3dfdc9bd569.png)

Step 3: Now reply from the customer side and check the email templates send is a new or old template on the agent email.

=> **For going to the customer going the new email template:**

![image](https://user-images.githubusercontent.com/63539748/209517739-a6ab0f32-08c3-430b-8d89-e6e8413e622c.png)

**Edit the Agent replied on the ticket workflow:**

![image](https://user-images.githubusercontent.com/63539748/209517796-e1f3282e-12ba-416b-925e-e442a05c39cc.png)


**Once you check these cases and let us know you are still facing the same issue.**

**Comment by kamraniwork** [comment]
> @mashahabi15
> 
> > when you want to add a new template there is no option for assigning the template to action.
> > If you are added a new email template after that you will add this email template to workflow actions. You follow the below steps:
> 
> Step 1: **Create a new email template:**
> 
> ![image](https://user-images.githubusercontent.com/63539748/209514485-1d62dac7-2ba4-4e84-a8e0-c83c8db0d31d.png)
> 
> Step 2: **Now you want to add this newly created email template in sends mail so you will add this email template in the workflow option, so go to the workflow option:**
> 
> ![image](https://user-images.githubusercontent.com/63539748/209515692-01690f37-6b42-43c8-829b-6b203c171b05.png)
> 
> Click on the customer replied on the ticket workflow, here you will add a new email template in the mail to agent actions and then save: ![image](https://user-images.githubusercontent.com/63539748/209514529-8436a665-33f1-43e8-a4c2-e3dfdc9bd569.png)
> 
> Step 3: Now reply from the customer side and check the email templates send is a new or old template on the agent email.
> 
> => **For going to the customer going the new email template:**
> 
> ![image](https://user-images.githubusercontent.com/63539748/209517739-a6ab0f32-08c3-430b-8d89-e6e8413e622c.png)
> 
> **Edit the Agent replied on the ticket workflow:**
> 
> ![image](https://user-images.githubusercontent.com/63539748/209517796-e1f3282e-12ba-416b-925e-e442a05c39cc.png)
> 
> **Once you check these cases and let us know you are still facing the same issue.**

Hello,
I did these things, but when I reply with the customer user, the agent reply section is executed in the work flow section, while I also activated the customer reply section in the other section, and what I expect is that the customer reply section is executed.

**Comment by Komal-sharma-2712** [comment]
> Hello, I did these things, but when I reply with the customer user, the agent reply section is executed in the work flow section, while I also activated the customer reply section in the other section, and what I expect is that the customer reply section is executed.

@kamraniwork 
Can you please share your screenshot of the workflow in which you are executing workflow for the customer and agent replied workflow?
Also, let us know you are using multiple workflows for customer replies in tickets.
We are clearing that if you are using this workflow: 
**Customer replied on the ticket workflow** so **this workflow will work for the agent mail** because here action performs to mail to the agent end.
**Agent Replied on Ticket workflow** so **this workflow will work for the customer mail** because here action performs to mail to the customer end.

**Comment by Komal-sharma-2712** [comment]
We are closing this issue, if you are facing the same issue then create a ticket on our support panel from [here](https://support.uvdesk.com/en/customer/create-ticket/).
