### ISSUE TITLE
Cannot access tickets from the application

### ISSUE THREAD

**Issue by boudig** [uvdesk/community-skeleton#635]
Hello, 
1 year ago I installed uvdesk on a local ubuntu server (20.04 LTS). 
Recently this server has been updated to 22.04 LTS and suddenly all tickets are not being shown inside the applications. 
![image](https://user-images.githubusercontent.com/32864471/209672531-f7d613c7-3971-436c-b03c-8e61b3d77951.png)

is there anything that i should check? 
Thank you!

**Comment by Komal-sharma-2712** [comment]
@boudig 
Please check once these two cases:

1. Check your database here tickets are shown or not in the **uv_ticket table**:
 
![image](https://user-images.githubusercontent.com/63539748/209797312-3e12b54a-a3df-4ffc-8196-b4d7649a8549.png)


2. Check your console error, click on the ticket list page **open the console using press F12** or right-click on a web **page,** and **click on inspect option** after shown like this, and the page refresh again:

![image](https://user-images.githubusercontent.com/63539748/209796247-66d0da79-1884-443d-b603-d1f54971052c.png)

If showing any error in the console sends a screenshot of the error.

**Comment by Komal-sharma-2712** [comment]
We are closing this issue from your side not revert on this issue. If you are facing the same error then reply on the same thread.
