### ISSUE TITLE
301 Moved Permanently Error

### ISSUE THREAD

**Issue by bigzolly** [uvdesk/community-skeleton#641]
Hi hello everybody! 

I would like to get help from you if that is possible as I cannot narrow it down anywhere now. 
The error itself comes up, when I try to convert emails to tickets. Everything seems fine, it opens the imap stream reads the email, recognizes that it is new and tries to convert it, but whenever it does it threws at the end a 301 Error - Moved permanently. 

Here is the full cycle: 

<i>1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

 3. IMAP stream opened.

 4. Fetching Email collection since 19 January 2023.

 5. Total fetched email -> 1

 6. Starting to convert Emails into Tickets ->
=============================================
=============================================

  Converting email 1 out of 1.

  Error -> 301 Moved Permanently</i>

It just happened from one day to another without changing anything. 

What I have already tried: 
 - Tried to reinstall the whole app. Deleted from the webserver folder, then re-download and reinstall happened without touching the db.
 - I cheked the .htaccess files if there is any redirection what shouldn't be there, but nothing
 - Tried to hit the ~/public/mailbox/listener which I can access and threws out a message "200" on it's body, but basically nothing else

Does any1 of you has any idea, what I am missing, or why did it just stopped working? 
Thanks for your time/effort in advance!
bigzolly

**Comment by Komal-sharma-2712** [comment]
Can you please share your screenshots of the **swiftmailer, mailbox, and email settings** option. Also, **let us know which version of uvdesk you are using**.

**Comment by bigzolly** [comment]
Hi hello! Sorry for the late reply.

First of all, it's UVDesk 1.1.0

I attached what you requested, I have removed the whole pack, with it's db dropped, everything cleared, even I purged anything that is connected to php and reconfigured completely with 8.1, but still not working. I'm out of any ideas. Completely.

The support from their ticketing sent me a code: composer require uvdesk/mailbox-component

Well.. that was not working at all. Threw out a whole bunch of error messages, that some of the items requiring php7.4 and other stuff, so I tried to do a

composer update

That was successfull, and now the whole email module has changed, however now I am facing with an another issue... which you can see on 6.png.


I tried to narrow it down where might be in the issue in the code, but I was not able to find it.

I am kinda curious if you guys have any idea, what's going on, as now it seems it is a code problem (huge amount of deprecation messages next to it)

![1](https://user-images.githubusercontent.com/114352439/214915792-479b9c8f-4bc7-4e8a-8d86-5e44d0b3682a.png)
![2](https://user-images.githubusercontent.com/114352439/214915799-bde4eba2-de9b-4aab-bc11-b86209daa061.png)
![3](https://user-images.githubusercontent.com/114352439/214915804-d6bb25ec-3de1-4afa-9c98-c7e659575a77.png)
![4](https://user-images.githubusercontent.com/114352439/214915806-1e4c5f2d-e4f3-42ce-8327-f2b76138953c.png)
![5](https://user-images.githubusercontent.com/114352439/214915807-a60aee26-b871-44ac-b473-104fb6f1a213.png)
![6](https://user-images.githubusercontent.com/114352439/214915810-32682885-3d89-4fc4-a6e2-a4200d46229c.png)

**Comment by Komal-sharma-2712** [comment]
@bigzolly

I would suggest you to re-setup the helpdesk project using the latest development release (v1.2.x-dev) using the following command:

`$ composer create-project uvdesk/community-skeleton:dev-master;`

The new development release has moved away from the swiftmailer package, and has centralised the mailbox configurations all in one place making it much more convenient to manage your settings. So you shouldn't be encountering this issue anymore after moving to the latest development release.

We have checked your ticket is craeted on our support tickets system.

Now, we are closing this issue if you are facing the same error then reply on the same ticket id: [29279](https://support.uvdesk.com/en/customer/ticket/view/29279)
