### ISSUE TITLE
Error on receiving email on creating agent

### ISSUE THREAD

**Issue by mashahabi15** [uvdesk/community-skeleton#643]
# Bug report

### Title
**Error on receiving email on creating agent**

### Issue Description
I deployed uvdesk 1.0.0 on the server on the production mode and configured mailbox. When I call uvdesk APIs(like creating new ticket, reply a ticket, etc) emails are successfully sent to both agent and customer. But when I try to create new agent or new customer within the uvesk panel, I don't receive emails for setting password, etc.  And when I refresh the mailbox with 
`php bin/console uvdesk:refresh-mailbox example@example.com`
I get the following error:
`09:58:15 WARNING   [php] Warning: Use of undefined constant CURLOPT_NOBODY - assumed 'CURLOPT_NOBODY' (this will throw an Error in a future version of PHP) ["exception" => ErrorException { …}]
09:58:15 WARNING   [php] Warning: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' (this will throw an Error in a future version of PHP) ["exception" => ErrorException { …}]
{"message":"Warning: Use of undefined constant CURLOPT_NOBODY - assumed 'CURLOPT_NOBODY' (this will throw an Error in a future version of PHP)","context":{"exception":{"class":"ErrorException","message":"Warning: Use of undefined constant CURLOPT_NOBODY - assumed 'CURLOPT_NOBODY' (this will throw an Error in a future version of PHP)","code":0,"file":"/var/www/uvdesk/vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php:163"}},"level":300,"level_name":"WARNING","channel":"php","datetime":"2023-01-24T09:58:15.427855+00:00","extra":{}}
{"message":"Warning: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' (this will throw an Error in a future version of PHP)","context":{"exception":{"class":"ErrorException","message":"Warning: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' (this will throw an Error in a future version of PHP)","code":0,"file":"/var/www/uvdesk/vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php:163"}},"level":300,"level_name":"WARNING","channel":"php","datetime":"2023-01-24T09:58:15.472458+00:00","extra":{}}
{"message":"Error thrown while running command \"uvdesk:refresh-mailbox 'example@example.com'\". Message: \"Call to undefined function Webkul\\UVDesk\\MailboxBundle\\Console\\curl_init()\"","context":{"exception":{"class":"Error","message":"Call to undefined function Webkul\\UVDesk\\MailboxBundle\\Console\\curl_init()","code":0,"file":"/var/www/uvdesk/vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php:164"},"command":"uvdesk:refresh-mailbox 'example@example.com'","message":"Call to undefined function Webkul\\UVDesk\\MailboxBundle\\Console\\curl_init()"},"level":500,"level_name":"CRITICAL","channel":"console","datetime":"2023-01-24T09:58:15.679022+00:00","extra":{}}
09:58:15 CRITICAL  [console] Error thrown while running command "uvdesk:refresh-mailbox 'example@example.com'". Message: "Call to undefined function Webkul\UVDesk\MailboxBundle\Console\curl_init()" ["exception" => Error { …},"command" => "uvdesk:refresh-mailbox 'example@example.com'","message" => "Call to undefined function Webkul\UVDesk\MailboxBundle\Console\curl_init()"]
{"message":"Command \"uvdesk:refresh-mailbox 'example@example.com'\" exited with code \"1\"","context":{"command":"uvdesk:refresh-mailbox 'example@example.com'","code":1},"level":100,"level_name":"DEBUG","channel":"console","datetime":"2023-01-24T09:58:15.706152+00:00","extra":{}}
{"message":"Uncaught Error: Call to undefined function Webkul\\UVDesk\\MailboxBundle\\Console\\curl_init()","context":{"exception":{"class":"Error","message":"Call to undefined function Webkul\\UVDesk\\MailboxBundle\\Console\\curl_init()","code":0,"file":"/var/www/uvdesk/vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php:164"}},"level":500,"level_name":"CRITICAL","channel":"php","datetime":"2023-01-24T09:58:15.708100+00:00","extra":{}}`

What should I do?
Thank you very much for your consideration.

**Comment by Komal-sharma-2712** [comment]
@mashahabi15 

Can you please check **curl extension** is installed or not in **php.ini** file . If curl extension is missing so you will need to **add a curl extension in php.ini** file.

**Comment by mashahabi15** [comment]
> @mashahabi15
> 
> Can you please check **curl extension** is installed or not in **php.ini** file . If curl extension is missing so you will need to **add a curl extension in php.ini** file.

Hi. Excuse me, I couldn't find this file. Where should I look for that?

**Comment by Komal-sharma-2712** [comment]
You can check in also php.info() file. First you will check the curl extension is added or not. 
Please follow the below command:

`$ php -m`

![Screenshot from 2023-01-25 19-01-00](https://user-images.githubusercontent.com/63539748/214576344-0070718f-3126-4f15-a396-62448a9b2f15.png)

**If not showing the curl extension in your php file so you will need to add this extension:**

`$ sudo apt-get install php7.4-curl`             [sudo apt-get install php-version-curl]

**After that restart your apache:**

`$ sudo /etc/init.d/apache2 restart`


**For references follow the below link:**

https://www.geeksforgeeks.org/how-to-enable-curl-in-php/

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you still facing the same issue you can reply to us on the same issue thread.
