### ISSUE TITLE
imap with outlook no longer working  => ErrorException { …}]

### ISSUE THREAD

**Issue by steveb85** [uvdesk/community-skeleton#645]
Processing uvdesk mailbox configuration.

 2. Opening imap stream... 
17:06:00 WARNING   [php] Warning: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}INBOX ["exception" => ErrorException { …}]

 3. IMAP stream opened.

**Comment by steveb85** [comment]
i noticed my cron wasn't working (it previously had been) and when i ran the uvdesk:refresh-mailbox manually in CLI i found this issue which is super tough

**Comment by steveb85** [comment]
I'm wondering if it is because outlook office 365 has depreciated basic auth? If that's the case then it renders uvdesk useless to anyone using office365 as an email server

**Comment by steveb85** [comment]
i have just tested with a dummy gmail account, and it seems that it works. so the issue is outlook, if @PeopleInside  or @vipin-shrivastava  have any update on how to use with outlook that would be great. I've been using an app password but it's not working still. something is not correct

**Comment by steveb85** [comment]
new errors 
 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream... 

 3. IMAP stream opened.

 4. Fetching Email collection since 09 February 2023.

 5. Total fetched email -> 7

 6. Starting to convert Emails into Tickets -> 
=============================================
=============================================


  Converting email 1 out of 7.

  Converting email 2 out of 7.

  Converting email 3 out of 7.

  Converting email 4 out of 7.

  Converting email 5 out of 7.

  Converting email 6 out of 7.

  Error -> Attention Required! | Cloudflare

**Comment by Komal-sharma-2712** [comment]
Can you please share the log file of your project. Follow the belo path for log file: 
**your-project/var/log/dev.log file**

![dev log-file](https://user-images.githubusercontent.com/63539748/218430531-d18ee0bd-b89a-493e-a592-0f9d1b7b32b9.png)

Please share the files on our support center from [here](https://support.uvdesk.com/en/customer/create-ticket/)

Also, you can try with the new version v-1.1.2 of mailbox components bundle. You can change the mailbox bundle using the belwo command:

`$ composer require uvdesk/mailbox-component`


After that again setup of mailbox and cleared the cache of project using the below command:

`$ php bin/console c:c`

**Comment by steveb85** [comment]
thanks, i sent the log files. 

I added the mailbox-component and cleared cache, no change. I'm wondering if this is a microsoft issue, looking for other ways to test that

**Comment by steveb85** [comment]
thanks @Komal-sharma-2712

**Comment by steveb85** [comment]
i'm not getting outgoing smtp connection eitehr, not sure if there is a way to test that via CLI.

**Comment by steveb85** [comment]
Current Print from refresh mailbox
  - Establishing connection with mailbox
  - Failed to establish connection with mailbox

  Warning: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}INBOX

  0: Retrying PLAIN authentication after AUTHENTICATE failed.
  1: Retrying PLAIN authentication after AUTHENTICATE failed.
  2: Can not authenticate to IMAP server: AUTHENTICATE failed.

obviously it's about authentication. i ahve tried inboxes with basic auth, and some with a office365 app password

**Comment by steveb85** [comment]
IT seems that microsoft won't support this auth in any way moving forward, we will need an oauth option ot use a microsoft IMAP connection. SMTP is possible to send emails, but this makes the UV desk somewhat redundant until this can be updated. https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

**Comment by steveb85** [comment]
work around was to forward my office 365  mail -> gmail account, and read that. it's horrible work around but surviving until uvdesk can implement better auth processes
