### ISSUE TITLE
UNABLE TO SEND LARGE ATTACHMENT ON UVDESK

### ISSUE THREAD

**Issue by AshMO49** [uvdesk/community-skeleton#647]
We use GitHub issues only to discuss about uvdesk bugs and new features. For customizations and extended support:

- Contact us at support@uvdesk.com
- Visit official support website (https://support.uvdesk.com/en/)
- Visit our community forums (https://forums.uvdesk.com)

Hello There,
I am here to ask you that, how can send large files to raise a ticket in UVDESK. because due to this i have missed several replays from the customer side. Please let me know about the solution 

Thanks!

**Comment by Komal-sharma-2712** [comment]
> I am here to ask you that, how can send large files to raise a ticket in UVDESK

@AshMO49 

Please **increase upload_max_filesize** in **uvdesk.yaml** file and also **increase the upload size** from your **php.ini** file and make a try.

Check the screenshot below:

![image](https://user-images.githubusercontent.com/63539748/219379635-7a443264-4321-47ea-bdb7-a09122eeeef5.png)


Finally, **restart your server** and also **cleared cache of the project** using the below command:

`$ php bin/console c:c`

**Comment by Komal-sharma-2712** [comment]
@AshMO49 
Can you please share screenshots of **uvdesk.yaml** file and also share your **php.ini** upload file size.

**Comment by AshMO49** [comment]
@Komal-sharma-2712 , i set the memory_limit = 512M and upload_max_filesize = 50M and max_file_uploads = 20. but still it is giving same problem.

**Comment by Komal-sharma-2712** [comment]
@AshMO49 
We will check and updated you with the correct solution. Thank you for your time and patience.

**Comment by AshMO49** [comment]
Hii @Komal-sharma-2712 , 
I am having problem to open the tickets as it is showing "Access Denied" as the internal server error 500. 
But i have given all the permission to the whole UVDESK Folder. Do you have any idea how to resolve this one.

i shall remain grateful to you.

**Comment by Komal-sharma-2712** [comment]
Can you please share your **log file**  of your project. Please follow the below path for the log file:

**_your-project-folder/var/log/dev.log file_**

![image](https://user-images.githubusercontent.com/63539748/220098041-d05e235d-5ad7-40c0-bbf9-3856471fa48a.png)

**Comment by AshMO49** [comment]
![image](https://user-images.githubusercontent.com/125567457/223424707-98789e70-2b03-4031-8eaf-da95fcba09d8.png)


Hii Komal. this time, i got a new issue regarding to the uvdesk. there are certain mails to whom i am not able to reply. kidnly reach out asap and please do help me out from this problem.

regards 
Ashutosh

**Comment by Komal-sharma-2712** [comment]
@AshMO49 

> I got a new issue regarding to the uvdesk. there are certain mails to whom i am not able to reply

Let us know, you are facing this error shown only on mails tickets or also with website tickets when you have replied on ticket. 
Can you please confirm it, this error facing while replied time or after reply added on ticket.

Also, let us know, you have added any condition in workflow and you have replied on the ticket with large attachments.

**Comment by AshMO49** [comment]
Hello,
thank you for the responding this quick.

i am not able to reply  certain tickets at all. and i am also not able to tag them as well.
Please provide me a permanent solution on this because since the setup uvdesk is giving problems after problems. as it is in the production server. I am not able to reply or tag via our uvdesk website. please do help me out from this....

**Comment by Komal-sharma-2712** [comment]
> Is this related to TinyMCE.. if so, can you tell me how to prevent these issues

Can you please share your screenshot of the console error. Also, share a screenshot of the ticket where you have added a reply or adding a tag in the ticket.

**Comment by AshMO49** [comment]
I have resolved that issue, regarding to that particular thing. but a new problem has been arised, it is related to mysql. it somehow failing to start. and this is been happening since yesterday. sometimes it's working and it's failing. please give a permanent solution regarding to this uvdesk 
my mysql  Ver is 8.0.32.

**Comment by Komal-sharma-2712** [comment]
> A new problem has been arised, it is related to mysql. it somehow failing to start. and this is been happening since yesterday.

Can you please share a error of screenshot which error you are facing regarding mysql.

**Comment by AshMO49** [comment]
[-bash: fork: Cannot allocate memory](https://stackoverflow.com/questions/43652021/bash-fork-cannot-allocate-memory)

sometimes it's showing like this. I cannot give the screenshot as it's not giving any issues. but sometimes the server slows down even with the 15% occupation of the disk.

**Comment by Komal-sharma-2712** [comment]
> [-bash: fork: Cannot allocate memory](https://stackoverflow.com/questions/43652021/bash-fork-cannot-allocate-memory)
> 
> sometimes it's showing like this. I cannot give the screenshot as it's not giving any issues. but sometimes the server slows down even with the 15% occupation of the disk.

Alright, but this is not an uvdesk error. So now we are closing this issue if you are facing any other issue regarding uvdesk then reply in the same thread.
