### ISSUE TITLE
Do we have any plans to use symfony/mailer instead of swiftmailer/swiftmailer?

### ISSUE THREAD

**Issue by yjqphp** [uvdesk/community-skeleton#648]
Package swiftmailer/swiftmailer is abandoned，Do we have any plans to replace it with symfony/mailer?

**Comment by Komal-sharma-2712** [comment]
> Package swiftmailer/swiftmailer is abandoned，Do we have any plans to replace it with symfony/mailer?

**This package is not added in the latest release. We have already added this package in our uvdesk opensource. But it will reflect in the future release.**
