### ISSUE TITLE
The mailbox cannot be used in the production environment

### ISSUE THREAD

**Issue by yjqphp** [uvdesk/community-skeleton#649]
Recirculation step
 
1、shell execute
composer install --no-dev --optimize-autoloader

2、shell exceute
php bin/console uvdesk:refresh-mailbox -emails support@uvdesk.com

Repair:

1、composer require symfony/dom-crawler symfony/css-selector

**Comment by Komal-sharma-2712** [comment]
Thanks for reporting. We will review and check the issue. Thanks for your time and patience!!!

**Comment by Komal-sharma-2712** [comment]
We have checked and you have some changes in project, please follow the below steps:

1. First we have run this command in our project root directory in dev mode:

`composer install --no-dev --optimize-autoloader`

Here showing an error like this:

`Uncaught Error: Class 'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle' not found`

2. Now we will **uncommment** some classes from **bundles.php** file under **config/bundles.php** file in your project:
```
// Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
// Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
// Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
```

3. Now we will **delete some files also**, please follow the below files path:

a. **web_profiler.yaml** file under the **config/routes/web_profiler.yaml** 
b. **web_profiler.yaml** file under the **config/packages/**web_profiler.yaml** 
c. **debug.yaml** under the **config/packages/debug.yaml** 

4. Now you will run the below command:

**composer run-script post-install-cmd**

5. Now checked run the mailbox refresh command and here refreshed successfully.

If you are facing any issue then let us know.

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you have still facing any issue, you can reply to us with screenshots on the same issue thread.
