### ISSUE TITLE
Customer not receive any attachment on their mail id when agent reply from admin panel by attaching documents

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#65]
**Description of Bug :** 

Customer not find attachment files on mail which were added to reply done from agent end.
![screenshot 35](https://user-images.githubusercontent.com/43210406/50276916-288e4380-0469-11e9-9747-f3d7a6a56510.png)

workflow is setup for the same
![download](https://user-images.githubusercontent.com/43210406/50276829-ebc24c80-0468-11e9-9169-21b60306f6a5.png)

**Comment by papnoisanjeev** [comment]
Resolved.
