### ISSUE TITLE
Admin Login not allowed after installation

### ISSUE THREAD

**Issue by operations-ics** [uvdesk/community-skeleton#652]
Dear All,
completing installation I attempeed to login as SUPER_ADMIN, but received a credential error.
Following the information in this platform, I have reloaded (into the directory where is installed the application):
sudo bin/console uvdesk_wizard:defaults:create-user ROLE_SUPER_ADMIN [Antonio [myMail [MyPassword]]]
in the console prompt I receive only the request to insert my mail and my name, but no the password..
I think this may be a Symfony problem related some deprecated routine, but I don't understand what I need to modify.
The installation is on ububtu, the last version, apache2, php8.2, mysql 8.0, Composer 2.5.4.
I have also verified in the database and my user and password (hashed)  is present,
I haven't an smtp configuration available on the application to provvide a new password in this way.
Waiting for Your help
Antonio

**Comment by Komal-sharma-2712** [comment]
Can you please share your **log file** from your project. Please follow the below path for the log file:

`your-project-folder-name/var/log/dev.log`

![image](https://user-images.githubusercontent.com/63539748/225877387-58a11500-af60-4252-9397-0fb6dc2a37da.png)

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you still facing the same issue you can reply to us on the same issue thread.
