### ISSUE TITLE
Overriding the event listener

### ISSUE THREAD

**Issue by ghada-charef** [uvdesk/community-skeleton#653]
Hi, I'm going to add some changes to the sendCcBccMail method, I thought of overriding the MailCustomer class or with inheritance using the WorkflowListener event listener
But in any case I don't know why the override doesn't work for me.

Any Idea Please!

**Comment by Komal-sharma-2712** [comment]
> I'm going to add some changes to the sendCcBccMail method, I thought of overriding the MailCustomer class or with inheritance using the WorkflowListener event listener.

You can added or update changes follow the below path:
https://github.com/uvdesk/core-framework/tree/master/Workflow/Actions/Ticket 

Here you can updates files or create a new file with the same format.

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you still any query then you can reply to us on the same thread.
