### ISSUE TITLE
"Forgot Password" feature not working

### ISSUE THREAD

**Issue by Oxymoron290** [uvdesk/community-skeleton#654]
# Bug report

### Title
"Forgot Password" feature not working, throws exception.

### Issue Description

When a member goes to log into the administrator portal and uses the "Forgot Password" link, they are able to put in their email address. However after submitting their email a Symfony Exception occurs with an HTTP 500 error with the message

> Attempted to call an undefined method named "setPassword" of class "Swift_Transport_NullTransport".

It is then followed by a stack tract starting at line 520 of `vendor/uvdesk/core-framework/Services/EmailService.php`. I noticed that in the last several months this section of the core-framework [has been modified](https://github.com/uvdesk/core-framework/commit/d76972eee469183dbecca6d87be5f1d3359ece65#diff-a9bed08253c8fcfda549726a57b07ee993c3ccc8757aec2d151450611486f91dL519).

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. v1.1.1 downloaded from [the CDN](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip) as `latest` at 12pm CST on 3/20/2023

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Click Forgot Password
    2. Enter Email Address
    3. Press Enter
    4. Experience exception

### Expected result

The user should receive an email

### Actual result

User experiences a symfony exception

**Comment by Komal-sharma-2712** [comment]
> However after submitting their email a Symfony Exception occurs with an HTTP 500 error with the message
Attempted to call an undefined method named "setPassword" of class "Swift_Transport_NullTransport".

Let us know, your **swiftmailer and email settings** option is enabled or not.

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you still facing the same issue you can reply to us on the same issue thread.
