### ISSUE TITLE
Swift mailer gmail not working

### ISSUE THREAD

**Issue by nepidaps** [uvdesk/community-skeleton#657]
i created agent but can't send email to agent's email address

**Comment by Komal-sharma-2712** [comment]
@nepidaps 


Let us know, you show any error while you have created an agent.
Also, let us know you have configured your swiftmailer and mailbox settings.

If not please follow the below blog:
https://www.uvdesk.com/en/blog/setup-gmail-mailbox-uvdesk-open-source-helpdesk/

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you still facing the same issue you can reply to us on the same issue thread.
