### ISSUE TITLE
Warning: imap_open(): Couldn't open stream outlook.office365.com:993/imap/ssl}INBOX

### ISSUE THREAD

**Issue by Kamekshakumar** [uvdesk/community-skeleton#664]
### Discussed in https://github.com/uvdesk/community-skeleton/discussions/663

<div type='discussions-op-text'>

<sup>Originally posted by **Kamekshakumar** May 22, 2023</sup>
Hi Guys,

I am facing below issue while configuring office 365 support email in uvdesk.

Can anyone help?

![uvdesk error](https://github.com/uvdesk/community-skeleton/assets/15952829/8d1fac79-fa8c-43ff-ae63-925dd2e4e0d0)
</div>

**Comment by Komal-sharma-2712** [comment]
If you are using **microsoft office 365 modern auth** email, then stable release V-1.1 is not working with microsoft auth. We have changes for the modern auth email, so this feature will be added with our **next release in V-1.2.0** or most renamed V-2.0 till this version is in development mode.

So, you will be install new project with the dev master command and setup microsoft apps with modern auth outook.

Please, You can try out the newest available version using the following command:

`$ composer create-project uvdesk/community-skeleton:dev-master;`

We would request you try the new updates and let us know if you come across any notable issues which we can address right away during our testing phase.

**Comment by Komal-sharma-2712** [comment]
Now, we are closing this issue.
If you have still facing the same issue, you can reply to us on the same issue thread.
