### ISSUE TITLE
Error Base table or view not found: 1146 Table 'uvdesk_prod_com.microsoft_app' doesn't exist after upgrade

### ISSUE THREAD

**Issue by serjsv87** [uvdesk/community-skeleton#669]
# Bug report

### Title
**Error Base table or view not found: 1146 Table 'uvdesk_prod_com.microsoft_app' doesn't exist after upgrade**

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. git clone https://github.com/uvdesk/community-skeleton.git .
    2. git checkout 1.2
    3. replace .env from old project
    4. clear cache
    5. add new mail configuration(/en/member/settings/microsoft-apps/xhr#trace-box-1) or go to en/member/settings/microsoft-apps

### Expected result

* Everything should work without error

### Actual result

Base table or view not found: 1146 Table 'uvdesk_prod_com.microsoft_app' doesn't exist

**Comment by Komal-sharma-2712** [comment]
@serjsv87 

You will be run the below command for the missing tables in your project:

`$ php bin/console d:s:u --force`

After that you will be clear cache of your project using the below command:

`$ php bin/console c:c`

Now check microsoft apps option working or not.

**Comment by serjsv87** [comment]
Yea, it worked for me, I searched for this info in readmy git and inside the articles on the site. but didn't find it. 
Already see that doctrine:schema:update is in help bin/console
But I think it would be nice to have it somewhere in readmy so I don't have to search for it. 
Thanks for your help!
