### ISSUE TITLE
Error in send mail

### ISSUE THREAD

**Issue by serjsv87** [uvdesk/community-skeleton#672]
# Bug report version 1.2.0

I wanted to expand the correct error occurred: Notice: Trying to access array offset on value of type null" and no email was sent. 
After much research I fixed the problem for me by adding a check into the
 vendor/uvdesk/core-framework/Services/EmailService.php
in the Configure email headers part

```PHP
            if ( is_array($value) ){
                continue;
            }
```

```PHP

        // Configure email headers
        $emailHeaders = $email->getHeaders();

        foreach ($headers as $name => $value) {
            if (is_array($value) && !empty($value['messageId'])) {
                $value = $value['messageId'];
            }
            if ( is_array($value) ){
                continue;
            }
            $emailHeaders->addTextHeader($name, $value);
        }

```

It didn't take away the warning, but the agent started getting emails

I could create a poolrequest, but unfortunately I don't know how to do it.

**Comment by Komal-sharma-2712** [comment]
@serjsv87 

We have noticed already this issue. Thanks for the reporting here.
If you want to create pull request so please check the below link:
https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

We will try to fix this error in v-1.2.0 uvdesk.

**Comment by piyushkalawatiyakdl** [comment]
Subject: Contribution Offer: Fixing Open Issue/Bug in Your Project

Hello! I'm experienced in this and interested in contributing to your open source project. I can address the open issue/bug by analyzing, developing a solution, and providing documentation. Let's collaborate and enhance your project together.

**Comment by papnoisanjeev** [comment]
@piyushkalawatiyakdl 

Glad to know that you want to contribute into uvdesk opensource.
It will be great to work together.

**Comment by papnoisanjeev** [comment]
@serjsv87

Added [here](https://github.com/uvdesk/core-framework/blob/v1.1.6_micro/Services/EmailService.php#L665-L674).
