### ISSUE TITLE
Swiftmailer stopped working suddenly

### ISSUE THREAD

**Issue by steveb85** [uvdesk/community-skeleton#673]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
Swiftmailer working fine until this week now error "Warning ! Swiftmailer not working. An error has occurred while sending emails!" after the reply is added

### Issue Description
No changes, which makes this odd

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1.v1.1.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. create ticket
    2. try to reply

**Comment by Komal-sharma-2712** [comment]
>> Swiftmailer working fine until this week now error "Warning ! Swiftmailer not working. An error has occurred while sending emails!" after the reply is added

Let us know, which email service you are using gmail, outlook (normal or office 365 modern auth), yahoo.
Also, we are suggested to you once setup again with the app password in your **swiftmailer, mailbox, and email settings** option.

After that **cleared cache** of project using the below command:

**$ php bin/console c:c**

If you have still facing the same issue, then let us know.

**Comment by steveb85** [comment]
@Komal-sharma-2712 thanks yes we have office 365, but i also tried with gmail and after both i cleared cache. A few months ago we lost support to check the office 365 but it was still sending through office until this week, even last week it was going fine. thank you.

**Comment by Komal-sharma-2712** [comment]
@steveb85 

Alright, once you can tried with the below solution for this error: _"Warning ! Swiftmailer not working. An error has occurred while sending emails!"_

Open the **swiftmailer.php** file under **config->packages** in your project.

Disable SSL verification on the server by using this option and make a try.

```
stream_options:
    ssl:
        verify_peer: false
        verify_peer_name: false
        allow_self_signed: true
```

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/4dc24e1a-c44c-4ef4-8d5d-79083863b4e1)


After that, you will clear the cache of your project run the below command in your project root directory:

`$ php bin/console c:c`

 
Now you can reply to tickets and check swift mailer is working or not.

**Comment by Komal-sharma-2712** [comment]
@steveb85 ,

Check once again your settings and add the correct app password of your Email id in the password field.

Locate the file **vendor->uvdesk->core-framework->Services->EmailService.php**.

Open the **EmailService.php** and reach to **sendMail() function**.

and **dump()** the exception as in the attached images.

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/fb8edb80-6c03-4dd5-904d-cbda94227c2b)
 
Once done then you just need to reply to the ticket accordingly the error will be reflected.

It will show the error you are facing while sending emails (if adding an agent, creating a ticket, etc).

 
**Another helpful link:**

https://forums.uvdesk.com/post/2083
