### ISSUE TITLE
What is the data retention policy

### ISSUE THREAD

**Issue by nomansafdar** [uvdesk/community-skeleton#676]
Hello everyone! I have a simple question. I would like to understand the default way data is stored in UVdesk. For example, if I have a 200GB hard disk, what happens when it becomes full? Also, I'm curious to know if there is an option to customize how long the data is retained. Thank you!

**Comment by Komal-sharma-2712** [comment]
@nomansafdar 

At this moment, we have not added like this data retention policy for the opensource uvdesk.
If you want more data storage so you will be increased your hard-disk space or delete old data.

If you have still any other query then let us know.


Thanks and Regards
Uvdesk Team

**Comment by Komal-sharma-2712** [comment]
@nomansafdar,

At this moment, we are closing this issue. If you have further any query or doubt then you can reply on the same issue thread.

Thanks and Regards
Uvdesk Team
