### ISSUE TITLE
How to view Agents Performance Report

### ISSUE THREAD

**Issue by nomansafdar** [uvdesk/community-skeleton#677]
Hello everyone,

Is there any way we can enable to see agents performance report in opensource uvdesk.

**Comment by Komal-sharma-2712** [comment]
@nomansafdar 

You can check it in the agent activity or performance in your **reports section -> agent activity** option on your admin panel:

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/80a88edf-cae5-4e30-b6f9-b62c0cdc8bdc)



You can check it from [here](https://docs.uvdesk.com/uvdemo/reports/agent-activity.html)

If you have any other query then let us know.

Thanks and Regards
Uvdesk Team

**Comment by Komal-sharma-2712** [comment]
@nomansafdar,

At this moment, we are closing this issue. If you have further any query or doubt then you can reply on the same issue thread.

Thanks and Regards
Uvdesk Team
