### ISSUE TITLE
Company logo is not showing on email which was set in email template

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#68]
Bug : 
Company logo missing from mail : 
![screenshot 40](https://user-images.githubusercontent.com/43210406/50279711-8a05e080-0470-11e9-97ed-c62bb0131096.png)

Description : 
This logo is setup in email template : 
![screenshot 38](https://user-images.githubusercontent.com/43210406/50279540-f6ccab00-046f-11e9-9c45-ecc2f9b6e5f1.png)

**Comment by papnoisanjeev** [comment]
Fixed.
