### ISSUE TITLE
[PHP] Warning: Trying to access array offset on value of type null ["exception" => ErrorException { …}]

### ISSUE THREAD

**Issue by Nitsz92** [uvdesk/community-skeleton#683]
# Bug report

### Title
Warning: Trying to access array offset on value of type null ["exception" => ErrorException { …}]

### Issue Description
After adding http to https redirection rule, Getting error in email cron jon

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. IIS 10

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

**Following rules are added in URL Rewrite : ** 

![image](https://github.com/uvdesk/community-skeleton/assets/139760970/ca8beeb8-b388-4d28-adb2-b06b5bf8a999)

### Actual result

Following error in cron job: 

![image](https://github.com/uvdesk/community-skeleton/assets/139760970/14ec2d5b-e42b-49bf-b720-0bf4c1bd1b62)

* [points....]
If I remove redirect to https rule, its working fine but url is not redirecting from http to https

**Comment by Nitsz92** [comment]
@Komal-sharma-2712 Issue has been resolved. Thanks for your support. 
I made the changes and after changes cron job was throwing following error. Which has been resolved by added cacert in php.ini

![image](https://github.com/uvdesk/community-skeleton/assets/139760970/92ba7404-99d4-40dc-a8f9-0969b92b1977)

**Comment by Komal-sharma-2712** [comment]
@Nitsz92 

Let us know, your issue has been resolve or not. If yes so we can closed this issue.
If you have further any query or doubt then let us know.

Thanks and Regards
Uvdesk Team

**Comment by Nitsz92** [comment]
@Komal-sharma-2712 issue has been resolved. I am closing this issue.
