### ISSUE TITLE
Apple / iCloud Mail Reply Causing New Ticket to Generate

### ISSUE THREAD

**Issue by kylebial0** [uvdesk/community-skeleton#688]
**Description**

I am receiving a very similar issue to #650, but it does not involve CC/BCC. This issue is caused when there is a reply from an end user who is using apple mail.

The end user had been using apple mail for their gmail account on an iPad. I was able to reproduce this issue on my end.

I had gone through the previously closed issues, but did not see anyone specifically mention the Apple mail application being the root cause of this issue, only the @mac.com domain (which was also likely using apple mail???)

**How to reproduce**

On apple iPad, open the mail app that is logged in with a gmail account
Reply to the email, and do not put anyone in CC / BCC
Send the reply
A new ticket will be created in UVdesk that shows the original email that they are responding to, image below (redacted)
![image](https://github.com/uvdesk/community-skeleton/assets/109872188/98563738-ac1d-4aa6-982f-c8404b23d210)

**Possible Solution**
I have not found a solution to this issue. From what I can tell, gmail, outlook, and outlook for web work as you would expect. I do not have other Apple devices, so I am unable to test on the mac version of mail.

**Comment by Komal-sharma-2712** [comment]
@kylebial0,

Can you please share a **.eml file** for your received emails (Ticket generated email) and also you have reply email from mail side. We need to check the both emails **.eml** file. 

Please share the both emails .eml file on our support panel from [here](https://support.uvdesk.com/en/customer/create-ticket/).

**Comment by Komal-sharma-2712** [comment]
At this moment, we are closing this issue. If you have further any query or doubt then you can reply on the same issue thread.
Also, you can create ticket on our support panel from [here](https://support.uvdesk.com/en/customer/create-ticket/).

Thanks and Regards
Uvdesk Team
