### ISSUE TITLE
UVDESK in windows XAMPP not receiving incoming emails.

### ISSUE THREAD

**Issue by marvelindxb** [uvdesk/community-skeleton#691]
### Discussed in https://github.com/uvdesk/community-skeleton/discussions/690

<div type='discussions-op-text'>

<sup>Originally posted by **marvelindxb** August 21, 2023</sup>
Dear Folks,
I installed a UVdesk in windows XAMPP for testing. I'm not receiving any incoming email, but SMTP is working fine. any fix?</div>

After the php syncing it started showing the below error message.
" - Establishing connection with mailbox
  - Fetching all emails since 21 August 2023
  - Found a total of 15 emails in mailbox since 21 August 2023

  # Processing all found emails iteratively:

    API http://10.108.0.150/uvdesk/public/mailbox/listener

    - Processing email 1 of 15:
  An unexpected error occurred: Warning: Trying to access array offset on value of type null"

**Comment by marvelindxb** [comment]
![image](https://github.com/uvdesk/community-skeleton/assets/142803880/8fabc016-c669-4d50-9be8-516390274a15)
This is the error I'm getting.

**Comment by marvelindxb** [comment]
![image](https://github.com/uvdesk/community-skeleton/assets/142803880/bfc39837-f653-4b3c-b07a-30f8929d1304)

Please look into it to put it in a test run.

**Comment by Komal-sharma-2712** [comment]
@marvelindxb,

Can you please share the project log files available in the **you-project-folder/var/log** directory relative to your project directory. 
![dev log-file](https://github.com/uvdesk/community-skeleton/assets/63539748/6db54645-23da-4382-a9c7-0ba5d6fed7a7)

In case these files are of large size, I would first suggest you to delete these files and try refreshing your mailbox again. 

In case of any issues, they should be logged into the newly generated log files accordingly. You can then share these log files with us which would help us look into what went wrong and where.

**Comment by marvelindxb** [comment]
This is the requested log file!
[dev1.log](https://github.com/uvdesk/community-skeleton/files/12418433/dev1.log)

**Comment by marvelindxb** [comment]
Any update on this issue @UVdesk Team???

**Comment by marvelindxb** [comment]
Waiting for the update!!!!

Regards,

*Allen Kenny Jones*

Administrator - Data Center, IT & Networks

[image: ***@***.***

Sheikh Amaar Road, Al Tallah 2,  P.O. Box 18484, Ajman, UAE

Tel:   +971 (0) 6 7110000 (Ext:1112) | Fax:  +971 (0) 6 7315111

[image: ***@***.***

[image: ***@***.***
<https://www.facebook.com/CityUniversityCollege>[image:
***@***.*** <https://twitter.com/CUCAjman> [image:
***@***.***
<https://www.instagram.com/cucajman/> [image:
***@***.*** <https://www.snapchat.com/add/cucajman/>
 [image: ***@***.***
<https://www.youtube.com/channel/UC0km336YbtDznOzrru98jdg>

[image: ***@***.***[image:
***@***.***

Get a glimpse of CU <https://youtu.be/HseRuQYdtqY>

[image: ***@***.***

**Comment by akshaywebkul** [comment]
Hello marvel,

Do you have access to postman that can be used debug the issue? If so, I'll share with you steps on how you can go about debugging this issue.

**Comment by marvelindxb** [comment]
Sure I can do that, if you guide me and update you the result.

**Comment by marvelindxb** [comment]
Good morning, waiting for the update?
Any luck!!!

**Comment by Komal-sharma-2712** [comment]
Hello marvel,

Please follow the below steps for postman debug:

Step 1: First you will fetch the mailbox command here you shown an error while fetching emails

Step 2: Now you will be some changes in your code in _RefreshMailboxCommand.php_ file follow the below path:

`vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php`

Add the below code in your code for download emails content in local. Also, attached a screenshot:

```
// Download emails
$timestamp = time();
file_put_contents(getcwd() . "/var/mail-$timestamp.eml", $message);
```

![Screenshot from 2023-08-29 18-45-16](https://github.com/uvdesk/community-skeleton/assets/63539748/907480ce-4e1d-40dd-bd98-c90fe5bb55fb)

Step 3: Now go to the _MailboxChannelXHR.php_ file follow the below path:

`vendor/uvdesk/mailbox-component/Controller/MailboxChannelXHR.php`

And add this line above of _try catch_ :

`$processedThread = $this->mailboxService->processMail($request->get('email'));`

Check the below screenshots add like this:

![Screenshot from 2023-08-29 18-44-55](https://github.com/uvdesk/community-skeleton/assets/63539748/4e150e7e-039e-4277-b9ff-c483dbc35129)

Step 4: Now refresh the mailbox command again and here shows your mails downloads with email contents. You can check the  downloaded email on **var/emails**

![Screenshot from 2023-08-29 19-22-23](https://github.com/uvdesk/community-skeleton/assets/63539748/f904e236-d696-48cf-ae13-25a2852ee68d)

Step 5: Now open your terminal when you have refreshed your mailbox command. Here you will be shown a api mailbox url copy this url: [http://localhost/uvdesk-latest/hd-1.1.3/public/mailbox/listener]

![Screenshot from 2023-08-29 19-24-14](https://github.com/uvdesk/community-skeleton/assets/63539748/9fb1c0da-ae94-4275-8d2a-7d7e04502cf0)

Step 6: Now open the postman and add this email content.

```
Action:: Post
Requested-url: http://your-helpdesk-url/public/mailbox/listener
Key:: email
Value:: email-raw-content
```

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/b0ba1619-f759-4739-a711-c8f17412820b)

After that click on send button and here you will be shown a email exception if any error and check it. 

Kind Respects,
Uvdesk Team

**Comment by marvelindxb** [comment]
it is still showing the same error

**Comment by marvelindxb** [comment]
![image](https://github.com/uvdesk/community-skeleton/assets/142803880/bda274ed-c6b7-4ae4-8852-0ff12119d623)
Additionsaly I checked with postman also and found this error.

**Comment by Komal-sharma-2712** [comment]
@marvelindxb ,

Let us know, you are still facing the same issue or not. At this moment, we are closing this issue. If you have still facing the same issue then you can reply on the same thread.

Thanks and Regards
Uvdesk Team
