### ISSUE TITLE
Unable to connect to postmark

### ISSUE THREAD

**Issue by asia-pixel** [uvdesk/community-skeleton#694]
# Bug report

### Title
I am trying to configure swiftmail configuration and connect to postmark.

### Issue Description
I was able to receive an email using the command: php bin/console swiftmailer📧send
But it is not working through the portal.

**Comment by Komal-sharma-2712** [comment]
@asia-pixel ,

Let us know, you are still facing the same issue or not.

**Comment by Komal-sharma-2712** [comment]
At this moment, we are closing this issue. If you have further any query or doubt then you can reply on the same issue thread.

Thanks and Regards
Uvdesk Team
