### ISSUE TITLE
Notice Template for option in predefined email templates which are need to be selected by default 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#70]
**Reason of Bug :** 
Some of the email template are automatically created for our project and their actions also defined in their template body but at **"Template for "** option no values get selected.

**Update :** 
**Template for** option should be get selected itself.
![screenshot 42](https://user-images.githubusercontent.com/43210406/50281264-eb2fb300-0474-11e9-9549-b16c98c434ca.png)

**Comment by papnoisanjeev** [comment]
It is not required to choose template for option. it can be null and by default template for option is set null when site is created.
