### ISSUE TITLE
can't view file upload in ticket after Add Attachment

### ISSUE THREAD

**Issue by chonnuchajo** [uvdesk/community-skeleton#700]
i have a problem with func.Add Attachment

- It's can be  add something and show detail from file upload
![image](https://github.com/uvdesk/community-skeleton/assets/62642745/907421ba-1c0c-4391-93d6-9490adc1b345)
![image](https://github.com/uvdesk/community-skeleton/assets/62642745/0856e444-502e-4ff2-80ec-51d141197f55)

- but sometime when i want to  view by click .It show error follow this
![image](https://github.com/uvdesk/community-skeleton/assets/62642745/14009e86-aa39-4879-b99f-175cfa9bb976)

i'm not sure miss someany config it

**Comment by Komal-sharma-2712** [comment]
@chonnuchajo ,

We have noticed this error in the latest release uvdesk. We have fixed this issue but changes wiil be reflect on the next release. At this moment you can change the some code in your project. Please follow the below steps:

Step 1: Go to your project, open and change the code in below mentioned file path:

`your-project-folder/vendor/uvdesk/core-framework/FileSystem/FileSystem.php`

Add a code like this as shown the below screenshot:

```
$scheme = $this->container->get('router')->getContext()->getScheme();
$host = $this->container->get('router')->getContext()->getHost();
$baseUrl = "$scheme://$host";
$assetDetails['downloadURL'] = $baseUrl.$assetDetails['downloadURL'];
```
![image](https://github.com/uvdesk/community-skeleton/assets/63539748/d682de94-0cb5-4db3-887a-39a1ea19efe1)

Reference from [here](https://github.com/uvdesk/core-framework/blob/ad4ab27f009426c635932a403983a2b04eb1302e/FileSystem/FileSystem.php#L143C13-L146C82).

Step 2: Now change some code in the mentioned below file path:

`your-project-folder/vendor/uvdesk/core-framework/Controller/Ticket.php`

$response->headers->set('Content-length', filesize($zipname));
Another line:

`readfile($path);`


![image](https://github.com/uvdesk/community-skeleton/assets/63539748/a8f7e95c-0829-410e-a27c-81d4483a17db)

**Reference from here:**

https://github.com/uvdesk/core-framework/pull/652/commits/ad4ab27f009426c635932a403983a2b04eb1302e

https://github.com/uvdesk/core-framework/pull/652/commits/dfd98fa3971df42ebdc7ab8265c502af8517b2cc

Step 3: After change the both files you will be **cleared cache of your project** using the below command in your project root directory:

`$ php bin/console c:c`

If you are facing the same issue then let us know.

Kind Respects,
Uvdesk team

**Comment by Komal-sharma-2712** [comment]
@chonnuchajo ,

Thanks for the update here. These changes wiil be reflect on the future release. For now we are closing this issue.
Thanks for your time and patience!!!


Kind Respects,
Uvdesk Team
