### ISSUE TITLE
It can be clone or create multi ticket in one time ?

### ISSUE THREAD

**Issue by chonnuchajo** [uvdesk/community-skeleton#703]
I have a question  
It can be clone or create multi ticket in one time ? 
Ex. i have a mulit customer with in the same problem and I need to clone or create multi ticket in one time . 
It able to be ? 

thank you for every your support

**Comment by Komal-sharma-2712** [comment]
@chonnuchajo ,

> It can be clone or create multi ticket in one time ?
Ex. i have a mulit customer with in the same problem and I need to clone or create multi ticket in one time .

We are informing to you, at this moment this clone or create multiple tickets at one time feature is not available in uvdesk.


Kind Respects,
Uvdesk Team

**Comment by Komal-sharma-2712** [comment]
As this moment this feature is not available in uvdesk. So we are closing this issue for now.

Thanks and Regards,
Uvdesk Team
