### ISSUE TITLE
FAIL TO REPLY TICKETS WITH EMAIL

### ISSUE THREAD

**Issue by cableriassupport** [uvdesk/community-skeleton#704]
# Bug report

### Title

FAIL TO REPLY TICKETS WITH EMAIL

### Issue Description

I INSTALL ALL GOOD AND CONFIGURATE EMAIL (GMAIL ACCOUNT). I CREATE A TICKET WITH ONE USER AND ASSIGN TICKET TO A ONE MEMBER. THE MEMBER REPLY THE TICKET IN THE WEBSITE. THE USER RECEIVED THE EMAIL WITH THE TICKETS WAS CREATED AND OTHER MAIL WITH THE REPLY OF THE MEMBER. 

THE PROBLEM IS NOW WHEN THE USER REPLY THE TICKET WITH THE EMAIL (NOT IN THE WEBSITE). THE REPLY DON'T APPEAR IN THE TICKET... NOT EXIST. I DON'T KNOW THE PROBLEM. 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    uvdesk-community-v1.1.3
    PHP 8.0   

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

 I CREATE A NEW TICKET AND ASSIGN TO A MEMBER AND USING THE WEBSITE THE MEMBER REPLY. 
THE USER THAT CREATED THE TICKET RECEIVED A EMAIL WHEN THE TICKED WAS CREATED AND WHEN THE MEMBER REPLY.
THE USER RESPONSE THE EMAIL (REPLY OF MEMBER) WITH GMAIL.. BUT THIS NOT APPEAR IN THE WEBSITE.. 

### Expected result

I NEED THAT WHEN USER RESPONSE THE EMAIL THE REPLY ADD AUTOMATIC TO A TICKET SYSTEM. 

*   [Screenshots, logs or description]

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/850cc3f6-8b2d-4aef-95e0-5ad8141a5eb4)
![image](https://github.com/uvdesk/community-skeleton/assets/148451214/2c3242aa-9493-472f-ad9e-d2aff9e4f14d)

HELP ME PLEASE..

**Comment by Komal-sharma-2712** [comment]
@cableriassupport ,


Let us know, you have configured mailbox setting or not. Also, you will be run the **refresh mailbox command** in your project root directory for fetching mail replies in the tickets.

`$ php bin/console uvdesk:refresh-mailbox your-configured-mailbox-email-address`

If you are not setup mailbox option then follow the below blog:

https://www.uvdesk.com/en/blog/setup-gmail-mailbox-uvdesk-open-source-helpdesk/



Kind Respects,
Uvdesk Team

**Comment by cableriassupport** [comment]
> @cableriassupport ,
> 
> Let us know, you have configured mailbox setting or not. Also, you will be run the **refresh mailbox command** in your project root directory for fetching mail replies in the tickets.
> 
> `$ php bin/console uvdesk:refresh-mailbox your-configured-mailbox-email-address`
> 
> If you are not setup mailbox option then follow the below blog:
> 
> https://www.uvdesk.com/en/blog/setup-gmail-mailbox-uvdesk-open-source-helpdesk/
> 
> Kind Respects, Uvdesk Team

Hello,

Thanks for you reply. I have configurated mailbox.

I try the command but i have a fail:
![image](https://github.com/uvdesk/community-skeleton/assets/148451214/c818a290-0b6a-4855-8a6e-2cf0a5254b3c)

I used sysnology system.. (distribution linux) but have a particular commands..
Regards

**Comment by Komal-sharma-2712** [comment]
Hii @cableriassupport ,


> I try the command but i have a fail:
![image](https://github.com/uvdesk/community-skeleton/assets/63539748/44af9ffc-eb38-4f25-b804-e8fb47d00329)

As per shared your screenshot, you have not running the command in your project root directory. Once you make a try with run the mailbox command in your project root directory. Please check the below screenshot:

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/6bc4fd96-e1f5-4c7a-b855-98959d3e9340)

Also, refresh mailbox command before clear cache of your project using the below command in your project root directory:

`$ php bin/console c:c`

Also, let us know which uvdesk version you are using.

Thanks and Regards,
Uvdesk Team

**Comment by cableriassupport** [comment]
HELLO,

LAST VERSION: 1.1.3

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/3c39d211-e663-4835-b163-e35c601838e0)

Now i have this fails...

**Comment by cableriassupport** [comment]
> Hii @cableriassupport ,
> 
> > I try the command but i have a fail:
> > ![image](https://github.com/uvdesk/community-skeleton/assets/63539748/44af9ffc-eb38-4f25-b804-e8fb47d00329)
> 
> As per shared your screenshot, you have not running the command in your project root directory. Once you make a try with run the mailbox command in your project root directory. Please check the below screenshot:
> 
> ![image](https://user-images.githubusercontent.com/63539748/276610750-6bc4fd96-e1f5-4c7a-b855-98959d3e9340.png)
> 
> Also, refresh mailbox command before clear cache of your project using the below command in your project root directory:
> 
> `$ php bin/console c:c`
> 
> Also, let us know which uvdesk version you are using.
> 
> Thanks and Regards, Uvdesk Team

HELLO,

LAST VERSION: 1.1.3

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/07f1cf38-5a3b-43a2-b939-6bdfbf868b46)


Now i have this fails...

**Comment by Komal-sharma-2712** [comment]
@cableriassupport ,

As per shared your screenshot, you will be check imap and mailparse extension is enabled or not in your php.ini file.
For checking extension is enabled or not, run the below command, and check imap and mailparse extension is enabled or not:

`$ php -m `

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/1c26c4dc-7a97-4643-9d17-a721018df5b3)

If **imap and mailparse extension is not enabled** then first you will be **installed imap and mailparse extension** in your php. Please follow the below steps:

**Please run the below command:**

```
$ sudo apt install php8.0-imap

$ sudo apt install php8.0-mailparse
```

**=> Note:**

>> If unable extensions package dependency after use the command then at this moment you will be update all apache packages using the below command:

`$ sudo add-apt-repository ppa:ondrej/php`

**or**

`$ sudo apt update`


Once make a try with this solution. 



Thanks and Regards,
Uvdesk Team

**Comment by cableriassupport** [comment]
If I do php -m not show this extension.. but here this extension are enabled and I check in .ini and imap.so and mailparse.so is in configuration file..

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/de8e7354-4d74-4f67-b6e5-81db708186d9)

Regards

**Comment by cableriassupport** [comment]
Can anyone help us?

**Comment by Komal-sharma-2712** [comment]
Let us know, you have after enabled these extentions **restart your apache server or not**. If not then once you restart your apache server.

Once you check your versions is same installed imap and mailparse according your php version. Also, should be shown the same extensions and version in **php info() file and cli command line**.

Also, let us know your are using windows (xamp or wampp) or ubuntu.

**Comment by cableriassupport** [comment]
Hello I restarted the server some many times.. all server not only apache.
I am using SYSNOLOGY (NAS). Use DSM S.O. https://www.synology.com/en-global/dsm
Is linux distribution but is a own operating system for SYSNOLOGY.

Regards

**Comment by cableriassupport** [comment]
> Let us know, you have after enabled these extentions **restart your apache server or not**. If not then once you restart your apache server.
> 
> Once you check your versions is same installed imap and mailparse according your php version. Also, should be shown the same extensions and version in **php info() file and cli command line**.
> 
> Also, let us know your are using windows (xamp or wampp) or ubuntu.

Hello,
I create a new virtual machine and install ubuntu for try..  i install all and try to forgot password in a one customer.. but not send email.. not works.. i don't known becasuse.. How can I check what the error is? because I don't get any error message. the account is set up correctly. 

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/c4f1c7d5-3e42-47bf-8768-d22e851e8f50)

**Comment by Komal-sharma-2712** [comment]
@cableriassupport ,

Let us know, which email service you are using? Also, please share a screenshots of the configured option: **swiftmailer, mailbox, and email settings**.

We are informing to you, in your password field, you will be use the **app password** of your configured email address.

**We are suggesting to you, once you can follow  the below blog:**

https://www.uvdesk.com/en/blog/setup-gmail-mailbox-uvdesk-open-source-helpdesk/


Thanks and Regards,
Uvdesk Team

**Comment by Komal-sharma-2712** [comment]
@cableriassupport ,

Let us know, after configuration your setup. You have cleared cache of your project. If not, once you make a try with clear cache of project using the below command in your project root directory:

`$ php bin/console c:c`

Now once you try with ticket created or ticket reply then check email received or not on customer email.

Thanks and Regards,
Uvdesk Team

**Comment by cableriassupport** [comment]
> @cableriassupport ,
> 
> Let us know, after configuration your setup. You have cleared cache of your project. If not, once you make a try with clear cache of project using the below command in your project root directory:
> 
> `$ php bin/console c:c`
> 
> Now once you try with ticket created or ticket reply then check email received or not on customer email.
> 
> Thanks and Regards, Uvdesk Team

I have tried to run that command but it still doesn't work...

**Comment by Komal-sharma-2712** [comment]
You can try with the once delete the channel and setup again with correct app password of gmail then clear cache of your project using the below command:

`$ php bin/console c:c`

Now try with the ticket created or reply in the ticket then check email received or not.

**Comment by cableriassupport** [comment]
ok... I do this and It's WORKS. Perfect now I have other problem.. I reply the email but not appear in ticket..

**Comment by Komal-sharma-2712** [comment]
Hello,

Thanks for the updated here. Let us know, you have refresh the mailbox command for fetching the mail replies or mail tickets.

If not, you will be **run the refresh mailbox command** in your project root directory for fetching mail replies in the tickets.

`$ php bin/console uvdesk:refresh-mailbox your-configured-mailbox-email-address`

Once you make a try with run the refresh mailbox command.

**Comment by cableriassupport** [comment]
> php bin/console uvdesk:refresh-mailbox your-configured-mailbox-email-address

Great.. If I run this command works.. I go to ticket and the reply are in... but I need to run the command.. If i don't run not works.. Shouldn't it be automatic?

**Comment by Komal-sharma-2712** [comment]
Hello,

> Great.. If I run this command works.. I go to ticket and the reply are in... but I need to run the command.. If i don't run not works.. Shouldn't it be automatic?

Please follow the below steps for crontab setup:

You have added your **crontab** with the following command:

`$ crontab -e `

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/01cecbbb-c72e-4e84-ac83-0bb46323910d)

After edit your **crontab** save and close the **crontab** for now (_CTRL + X, CTRL + Y_, then _ENTER_ if you selected nano).

2. Now check your view the contents of your **crontab**, but not edit it, you can use the following command:

`$ crontab -l`

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/7effc4ef-868c-457a-bece-1c6cf2c320b2)

3. Now check the setup is correct or not, so you will run the showing file path command till end in your crontab terminal check the below screenshot:

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/f6da3a48-ab04-4d71-b2fa-900c6e02fcfd)

If you are showing the successfully mailbox command running so it means setup is working now.

**Note:**

If you are not showing like this, so you will followed the below steps:

Go to the project root directory, and check the **current directory of your project folder**, run the below command:
 
`$ pwd`

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/1cc3bf97-02c8-40b0-81ee-ffa7404b7bdd)

 2. Now here showing your current directory project folder path, so copy and paste it in crontab file again like this:
 
![image](https://github.com/uvdesk/community-skeleton/assets/63539748/9ffe0b1e-f3a4-439a-a030-14e360cc4cde)

3. Once again check this is working or not, please follow the above 3 step again. You will run the showing file path command till end in your crontab terminal check the below screenshot:

![image](https://github.com/uvdesk/community-skeleton/assets/63539748/6f285056-c883-4a41-add2-0b0d514d1042)


Now your **crontab** is saved, and an email should fetch in every 5 minutes.


If you are still facing the same error then let us know.


Thanks and Regards,
Uvdesk Team

**Comment by cableriassupport** [comment]
THANKS for all. Now It's works very well. 

One last doubt. We have a corporate signature in the email... and it always attaches several photos when a person answers... is it possible that uvdesk uses plain text?

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/510c41f9-18d4-4acc-ab79-954d78cb7e2f)
 
One example:

![image](https://github.com/uvdesk/community-skeleton/assets/148451214/319f9f8f-6839-49a2-acab-50eece0c73ee)

**Comment by Komal-sharma-2712** [comment]
Hello, 

> THANKS for all. Now It's works very well

Thanks for the updated here. We are glad to know that your issue has been resolved now.

> We have a corporate signature in the email... and it always attaches several photos when a person answers... is it possible that uvdesk uses plain text?

Yes, you can check it. It should be send the same content on customer email whatever we have added in email signature. 

Thanks and Regards,
Uvdesk Team

**Comment by cableriassupport** [comment]
> Hello,
> 
> > THANKS for all. Now It's works very well
> 
> Thanks for the updated here. We are glad to know that your issue has been resolved now.
> 
> > We have a corporate signature in the email... and it always attaches several photos when a person answers... is it possible that uvdesk uses plain text?
> 
> Yes, you can check it. It should be send the same content on customer email whatever we have added in email signature.
> 
> Thanks and Regards, Uvdesk Team

Sorry, I think I explained myself wrong. We want that always that one person reply tickets by email it is always added in plain text to the tickets... currently when the people reply the system add images as attachments (these images are part of the email signature) no one has attached that...

**Comment by Komal-sharma-2712** [comment]
This is let you know that this is the current flow of UVdesk to add as a attachment of email signature images, system images or email replies images.

If you want to make any changes in the default flow of UVdesk helpdesk then it will be a part of paid customization and you need to discuss further on our [support panel](https://support.uvdesk.com/en/customer/create-ticket/) for the customization related requests.


Thanks and Regards,
Uvdesk Team

**Comment by cableriassupport** [comment]
Ok, I understand. Thanks for your support.
