### ISSUE TITLE
404 page does not work correctly

### ISSUE THREAD

**Issue by mgasche** [uvdesk/community-skeleton#705]
# Bug report

### Title
404 page does not work correctly

### Issue Description
I have installed UVdesk. Now I noticed during testing that if I enter a wrong URL the 404 error page does not work anymore. A Symfony Expection is displayed instead of the 404 page.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Version v1.1.3; Core Version v1.1.4
    2. Commit id: cbbb183
    3. Ubuntu 22.04.3 LTS
    4. PHP 8.0

### Steps to reproduce

I have installed UVdesk according to these instructions and after that the error of the wrong display of the 404 page occurred.

https://www.howtoforge.com/how-to-install-uvdesk-helpdesk-system-on-ubuntu-22-04/

### Expected result
The 404 page should be displayed like on the Colligso page.

![image](https://github.com/uvdesk/community-skeleton/assets/94894860/8ec64933-e859-47e8-b8e3-d16c77fdb4e4)

### Actual result

Instead, this page is displayed.

![image](https://github.com/uvdesk/community-skeleton/assets/94894860/24e619ee-1c72-4fe0-8f4f-0fd5772cff0d)

**Comment by Komal-sharma-2712** [comment]
@mgasche ,

> I have installed UVdesk according to these instructions and after that the error of the wrong display of the 404 page occurred.

We are informing to you, need to change your **.env** file in **prod** mode. If you have not changed your **env file dev to prod** mode. Then please follow the below steps:

Step 1: Open your project folder and open **.env file** and change **app_env** mode:

`APP_ENV=dev`

to 

`APP_ENV=prod`

Step 2: After change your env in prod mode then you will be **clear cache of your project** using the below command:

**$ php bin/console c:c**

Step 3: Now you can check your 404 page, now exception not display. 

Thanks and Regards,
Uvdesk Team

**Comment by mgasche** [comment]
Close

**Comment by mgasche** [comment]
Hello

This was the right hint. Now I also get the 4040 page.
Maybe it would be useful to have a hint on the web page when it is running in dev mode.
