### ISSUE TITLE
Code edit to fix fetching email issue

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#711]
# Bug report

### Title

An user on the forum reported he was not able to fetching email and was getting errors.
`An unexpected error occurred: Notice: Trying to access array offset on value of type null`

Finally the user found how to edit the core code to resolve this issue:
https://forums.uvdesk.com/post/4164

uvdeskprojectfolder/vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php

Changed this line:

$this->router->getContext()->setScheme((bool) $input->getOption('secure') ? 'https' : 'http');

To this:

$this->router->getContext()->setScheme('https');

**Comment by papnoisanjeev** [comment]
Issue not more exist.

**Comment by PeopleInside** [comment]
Hi @papnoisanjeev , a lot of time has been past.
Is always you? I hope you are well.
🤗

Is nice to see you back.
