### ISSUE TITLE
Installation : Something went wrong ! Please try again

### ISSUE THREAD

**Issue by bluexcii** [uvdesk/community-skeleton#716]
About to finish the installation but this error occurs. 

![image](https://github.com/uvdesk/community-skeleton/assets/129346284/2c092232-e867-494b-b120-c3bcd1d20a06)

![image](https://github.com/uvdesk/community-skeleton/assets/129346284/283ff994-b16c-41a1-af37-cedc0b431c06)

![image](https://github.com/uvdesk/community-skeleton/assets/129346284/e38ba521-2cc5-4af0-aac9-a075630955da)

**Comment by papnoisanjeev** [comment]
@bluexcii Need to enable read/write permission for some files and folders if not.
Hope below link will help you.
https://forums.uvdesk.com/topic/2002/file-permissions-in-the-case-you-have-throbles-installing-uvdesk/2
