### ISSUE TITLE
If there is a <base>

### ISSUE THREAD

**Issue by serjsv87** [uvdesk/community-skeleton#719]
If a client replied via email, and there is a <base ...> tag in the email, then in the end all links are taken starting from this tag and it is impossible to reply. I suggest a fix 

`uvdesk/core-framework/Services/TicketService.php`

```
            $dbTime = $threadDetails['createdAt'];
            $formattedTime = $this->fomatTimeByPreference($dbTime,$timeZone,$timeFormat,$agentTimeZone,$agentTimeFormat);

+++++            $threadDetails['message'] = preg_replace('/<base[^>]*>/', '', $threadDetails['message']);

            $threadResponse = [
                'id' => $threadDetails['id'],
                'user' => null,
```

**Comment by papnoisanjeev** [comment]
@serjsv87 please create a pull request for the same after review we will merge the update.
