### ISSUE TITLE
Agent/Customer Forget Password mail not received When user forget password

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#72]
**Workflow is setup :- for agent/customer forget password
Issue :- mail not received by users when they set to get new password.**
![screenshot 43](https://user-images.githubusercontent.com/43210406/50282782-e91c2300-0479-11e9-8e20-74d71f704b46.png)

**Comment by papnoisanjeev** [comment]
Agent and customer both are getting forget password mail. please check.
