### ISSUE TITLE
Prod mode not working

### ISSUE THREAD

**Issue by zer0ish** [uvdesk/community-skeleton#730]
# Bug report
Hello,

I though I already wrote about this issue before but can't find it anymore.

I started installing everything using Dev mode, everything seems fine.
When I change it to Prod mode, the docker starts, but I get this in the browser. 

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "security.context_listener.0" has a dependency on a non-existent service "Webkul\UVDesk\ApiBundle\Providers\ApiCredentials". in /var/www/html/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86 Stack trace: #0 /var/www/html/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false) #1 /var/www/html/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #2 /var/www/html/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(87): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Ar in /var/www/html/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86`

I'm using the latest docker from unraid apps. 

When in Dev I have no issues getting into the backend dashboard with my account that I created during install.
But when I'm ready to switch to Prod, I get the error above in my browser.

Not sure why I can't get this into production mode.

Any help would be appreciated.

**Comment by Niijimasama** [comment]
I had the same issue.
Run the command `composer dump-env prod` at your uvdesk root directory in your production server.
A file .**env.local.php** will be generated.
Try running your application in prod mode again.

**Comment by zer0ish** [comment]
> I had the same issue. Run the command `composer dump-env prod` at your uvdesk root directory in your production server. A file .**env.local.php** will be generated. Try running your application in prod mode again.

I deleted everything and rebuilt it in unraid. Once it was running in prod, I ran the command you provided and it said it was successful, but in the browser I get all this:
```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 351

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 385

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 394

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 408

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 416

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 451

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 529

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 559

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 637

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 638

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 640

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 678

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 679

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 681

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 835

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 835

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 839

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 839

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 843

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 843

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 847

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/uvdesk/core-framework/Utils/HTMLFilter.php on line 847

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "security.context_listener.0" has a dependency on a non-existent service "Webkul\UVDesk\ApiBundle\Providers\ApiCredentials". in /var/www/html/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86 Stack trace: #0 /var/www/html/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false) #1 /var/www/html/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false) #2 /var/www/html/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(87): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Ar in /var/www/html/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86
```

Nothing seems to have changed as far as the errors go from before and after running the command.

If I start from prod, it wont install uvdesk in the install location, and it wont add anything to the database.
I'd have to first install everything in Dev mode, which does allow me to get everything going, but still need Prod to work to use this.

**Comment by Niijimasama** [comment]
Was this file  **.env.local.php** generated?

This error **Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "security.context_listener.0" has a dependency on a non-existent service "Webkul\UVDesk\ApiBundle\Providers\ApiCredentials"**
shows a high chance that you have a security configuration error.

Go to <root_directory>/config/packages/security.yaml;

The default config should be:

providers:
        user_provider:
            id: user.provider

        api_user_provider:
            id: Webkul\UVDesk\ApiBundle\Providers\ApiCredentials

**Comment by zer0ish** [comment]
Yes the .env.local.php was generated, but it didn't resolve the original issue I had, so I did a clean fresh install of it in unraid. So maybe the docker container needs to be updated on unraid or docker hub?

If I install clean using Prod, it doesn't generate the database or any of the directories in the AppData share folder assigned to it.
![image](https://github.com/uvdesk/community-skeleton/assets/29928635/80c7cc98-d658-4cae-964b-b5ca470cb06e)


This is the docker repository being used to uvdesk: dietermartens/uvdesk:latest
Is there another one I should be using to install uvdesk in prod mode?

**Comment by Niijimasama** [comment]
You should install it in dev mode then switch to dev mode after completing installation.
I have not used that docker repo. I used https://hub.docker.com/r/webkul/uvdesk
