### ISSUE TITLE
Workflow :- When apply action as "mail to agent" then option to select agent are missing

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#74]
agent options are incorrect 
**Actual Result :** 
![screenshot 47](https://user-images.githubusercontent.com/43210406/50292164-72415300-0496-11e9-9794-da8064d3e061.png)

**Desired Result :** 
![screenshot 45](https://user-images.githubusercontent.com/43210406/50291994-052dbd80-0496-11e9-84ea-9b3356f53993.png)

**Comment by papnoisanjeev** [comment]
Added assigned agent.
