### ISSUE TITLE
For the document (.pdf, .doc, .xls) attach with ticket reply icon is missing

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#75]
![screenshot 49](https://user-images.githubusercontent.com/43210406/50326384-11566100-0510-11e9-95c6-12141c80c147.png)

**Comment by papnoisanjeev** [comment]
fixed.

**Comment by vaishaliwebkul** [comment]
Please specify the  files icon for the following supported extensions  (.docx, .ppt , .pptx,)

**Comment by shubhwebkul** [comment]
uvdesk/core-framework#32
