### ISSUE TITLE
Error: Mailbox for email not found.

### ISSUE THREAD

**Issue by beng016** [uvdesk/community-skeleton#756]
![error](https://github.com/uvdesk/community-skeleton/assets/170383376/7e9c8d4f-2e22-40bb-8ffd-c3784ecf8504)

anyone can help for this ?

- Ubuntu 22.04
- PHP 7.4
- Uvdesk Version v1.1.3; Core Version v1.1.4

**Comment by papnoisanjeev** [comment]
Please let us know the steps you have followed.
Most probably your mailbox not setup correctly.
