### ISSUE TITLE
Migrate away from imap extension

### ISSUE THREAD

**Issue by davispuh** [uvdesk/community-skeleton#765]
I'm trying to install UVdesk on openSUSE Leap 15.6 but I'm not able to because imap extension is not packaged anymore and I can't even build it there.

imap extension is unmaintained and that's why it was dropped from openSUSE.
When trying to build it I get error like this:
```
checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE... no
configure: error: utf8_mime2text() has new signature, but U8T_CANONICAL is missing. This should not happen. Check config.log for additional information.
```

Most likely this fails because it needs `libc-client` library but that isn't being packaged anymore either.

**Comment by papnoisanjeev** [comment]
Install Docker on your openSUSE system.
Use an existing PHP image with IMAP support and install UVdesk inside it.
Configure your container for UVdesk usage.


Hope it will help.
