### ISSUE TITLE
php bin/console uvdesk:configure-helpdesk Database is not connecting; error is "Unable to establish a connection with database server"

### ISSUE THREAD

**Issue by saultholath** [uvdesk/community-skeleton#775]
# Bug report

### Title
**Just a quick sentence to brief your trouble with UVDesk or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by lazyest** [comment]
it trying to connect redis
for me it was enough to disable php redis module to run
