### ISSUE TITLE
Admin name is missing when select forward a ticket to - > agent

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#78]
Missing admin name : 

![screenshot 51](https://user-images.githubusercontent.com/43210406/50331363-600df600-0524-11e9-98b0-663742e0aed4.png)

Profile of admin ;
![screenshot 52](https://user-images.githubusercontent.com/43210406/50331407-8764c300-0524-11e9-97f6-c3c5bff4e33b.png)

**Comment by shubhwebkul** [comment]
resolved
