### ISSUE TITLE
When save super admin credentials their must be a option of first name and last name field as mandatory

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#79]
Fields required : First and Last Name
Page need to Update : When save super admin credentials at web installer
Reason for enhancment : As at agent profile first name and last name both are mandatory
![screenshot 54](https://user-images.githubusercontent.com/43210406/50331625-4faa4b00-0525-11e9-9ea9-40a1a053f4f3.png)

**Comment by vaishaliwebkul** [comment]
if save admin by only given firstname and login to check profile where both agent fname and lname both are mandatory. so else don't make agent's lastname as required in profile of admin panel

**Comment by shubhwebkul** [comment]
User's last name is not required from now
