### ISSUE TITLE
Check Image Validation at agent/customer profile

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#8]
**What's the problem (or question)?**
When update profile of agent/customer by invalid File format(.tiff , .pdf , .html) rest all are mention,then no warning message shows for the invalid image and profile get updated successfully.
**Get Hint**
![download](https://user-images.githubusercontent.com/43210406/49222686-8697b000-f402-11e8-95d9-a08ec8feeab8.png)

**Comment by papnoisanjeev** [comment]
fixed. and will add after merging code.

**Comment by shubhwebkul** [comment]
please check
