### ISSUE TITLE
Customer reply to ticket by adding text effects like (Bold,Italic) then changes not get reflect 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#82]
**Customer reply to ticket by the following effects :** 
![screenshot 59](https://user-images.githubusercontent.com/43210406/50337120-29d97200-0536-11e9-9fa1-2026890a799e.png)

**When submit reply then no effects comes with text :** 
**Also check when text contains spaces then &nbsp tag shown :** 
![screenshot 61](https://user-images.githubusercontent.com/43210406/50337172-55f4f300-0536-11e9-9242-5e23c58fe904.png)

**Comment by papnoisanjeev** [comment]
fixed.
