### ISSUE TITLE
Unable to unassigned team/group from the ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#84]
1. Assign team to the particular ticket by selecting "Not Assigned" option then warning comes 
for which warning should not shown 

2. When assign ticket to team (eg, uvdesk) and again unassign that team than warning comes 
![screenshot from 2018-12-21 17-12-41](https://user-images.githubusercontent.com/43210406/50341316-62804800-0544-11e9-8075-7453ef15b18a.png)

**Comment by papnoisanjeev** [comment]
fixed.
