### ISSUE TITLE
Prepared Response section missing while applying to ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#9]
If in productivity section, prepared response is given 
![prepare](https://user-images.githubusercontent.com/43210406/49286467-44cd3f00-f4c0-11e8-868e-f584c5feef1d.png) then it must available in ticket detail for applying it into specific ticket. i.e; 
![preparedres](https://user-images.githubusercontent.com/43210406/49287160-76dfa080-f4c2-11e8-95a5-3828cf58aa7f.png)

**Comment by papnoisanjeev** [comment]
added prepared response
