### ISSUE TITLE
Agent unable to view ticket which are assigned to the group

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#94]
Steps to Reproduce Bug : 
1. Create group for (ex; uvdesk)
2. Assign agent to a specific group
3. Assign ticket to that same group 
4. Go to agent panel to check that ticket will shown or not

Actual Result : 
Ticket will not shown to agent

Excepted Result:
Ticket should be shown by agent.

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/core-framework/compare/uvdesk:0.1...papnoisanjeev:0.1

**Comment by vaishaliwebkul** [comment]
Hello @papnoisanjeev 
there is still one more issue, 

Please check when super admin assigns a ticket to the individual agent, then an assigned ticket will disable for the super admin itself.

**Comment by anmol107** [comment]
@vaishaliwebkul  This Issue has been fixed.
