### ISSUE TITLE
All the errors user get are in developer mode so please convert them in production mode

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#97]
![screenshot 84](https://user-images.githubusercontent.com/43210406/50520608-5d446f80-0ae7-11e9-88c5-6b2c2734a494.png)

This error should be shown as : 

![screenshot 85](https://user-images.githubusercontent.com/43210406/50520667-954bb280-0ae7-11e9-87ab-4f356e2204b4.png)

Errors page (for ex: page not found, session out , No route found ) should be shown by proper indentation 
in production mode like below as by showing in dev_mode all the files are showing to user whether customer or agent which is insecure.

**Comment by alessioluciano** [comment]
How can I go to the prod version?

**Comment by papnoisanjeev** [comment]
@alessioluciano.,
You can simply switch to production mode by changing **APP_ENV=prod** in **.env**  file which is in root directory of project.
After that run following command to clear the cache:
**php bin/console c:c**

**Comment by alessioluciano** [comment]
I did that but then I got this error by wanting to clear cache:
![archivo1](https://user-images.githubusercontent.com/50668488/65602004-87916380-df79-11e9-94ee-93147a4dbc6a.jpg)
![archivo2](https://user-images.githubusercontent.com/50668488/65602005-87916380-df79-11e9-87bd-4b323c302740.jpg)

do you have an idea?

**Comment by papnoisanjeev** [comment]
@alessioluciano 
We have already fixed this issue https://github.com/uvdesk/core-framework/issues/200  in prod mode(your code is not updated so you are facing this issue.)

so we recommend that create your project again as there are many new features and  changes done from our end.

**Comment by alessioluciano** [comment]
Where do I have to download it updated?
Because I downloaded it from https://s3-ap-southeast-1.amazonaws.com/cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk_community_01_development_php_72.zip and also with the command composer create-project uvdesk/community-skeleton helpdesk-project --stability dev but I get the same version as before. Can you help?

**Comment by papnoisanjeev** [comment]
@alessioluciano   
We have resolve this issue with same version. so run this command: 
composer create-project uvdesk/community-skeleton helpdesk-project --stability

and your issue will be resolve.

**Comment by alessioluciano** [comment]
Check this:
![imagen](https://user-images.githubusercontent.com/50668488/65607230-8e70a400-df82-11e9-95b5-f58310680cf8.png)

**Comment by papnoisanjeev** [comment]
@alessioluciano 
use this command  dev at end:
**composer create-project uvdesk/community-skeleton helpdesk-project --stability dev**

**Comment by alessioluciano** [comment]
Perfect, now i have the new version, but when i changed the version in the .env file, and when i want to run the server with:

php bin/console server:run

I have this error:

![imagen](https://user-images.githubusercontent.com/50668488/65610731-1f964980-df88-11e9-8e49-67643e69beaf.png)

**Comment by papnoisanjeev** [comment]
@alessioluciano 
**php bin/console server:run**  command is use only when you are using your project in dev mode.

If you want to run your project in production environment you have to access  public directory of your project.  i.e  **yourHost/yourProject/public**

**Comment by m4ary** [comment]
> @alessioluciano
> **php bin/console server:run** command is use only when you are using your project in dev mode.
> 
> If you want to run your project in production environment you have to access public directory of your project. i.e **yourHost/yourProject/public**

everything works for me in debug but in production `APP_ENV=prod` write the command
 `php bin/console server:run` in systemctl but show me:
`There are no commands defined in the "server" namespace.`

can you provide me how to deploy it to production? sorry can't find docs for that

**Comment by vaishaliwebkul** [comment]
@m4ary 

  to deploy project in production mode, just hit project's root directory path in the browser in the way
yourHost/Project_name/public.

**Comment by papnoisanjeev** [comment]
@m4ary 
**php bin/console server:run** works only when you are running your project in dev mode  i.e **APP_ENV=dev**  once you change it to **APP_ENV=prod** in **.env** file of your project you will see this message.
"There are no commands defined in the "server" namespace".

It means now your project in production mode, you will not able to run your project using command as it is only for development environment.

Now you need to run your project in this way (need to navigate to your project public path ):
**Your_Host/Project_Name/public**
